- package.json
Pulled from #8 
Has already been rebased with the result of merging #15
> fix: remove extraneous npm logs

- lib/cli/package-json.js
- package.json
- yarn.lock
With this PR if a component dependency version matches the version of the main module (or another package) dependency it gets installed into the `root/node_modules` folder instead of the component folder.
This removes duplicated dependencies living under each component folder, reducing time and space when doing an install.
Keep in mind that for this to work, dependency versions must match for those to be hoisted.
**The process works as follows:**
- Common dependencies will be installed only to the top-level node_modules, and omitted from individual package node_modules.
- Mostly-common dependencies are still hoisted, but outlier packages with different versions will get a normal, local node_modules installation of the necessary dependencies.
- In this instance, lerna bootstrap will always …
> chore: Introduces hoisting for dependencies of lerna packages (components)

- .github/CONTRIBUTING.md
- .gitignore
- lib/cli/cli.test.js
- lib/cli/package-json.js
- package.json
- packages/author/package.json
- yarn.lock
Mostly adds correct paths for `jest` configuration so it doesn't fail when it encounters other components under `node_modules`.
Also ignores `package-lock.json` files and updates some dependencies versions.
> Fixes for NPM scripts

- packages/card/__snapshots__/card.test.js.snap
- packages/image/__snapshots__/image.test.js.snap
- packages/image/image.js
- packages/image/image.stories.js
- packages/image/package.json
`Stylesheet` compiles the style and returns a number. To properly merge styles the style property should be set to an array of the styles to merge.
> fix: use style array to merge image styles

- package.json
- yarn.lock
Lerna 2.0.0 was released a couple of days ago - https://github.com/lerna/lerna/releases/tag/v2.0.0
> chore: bump lerna to 2.0.0

- .storybook/head.html
- ios/storybooknative.xcodeproj/project.pbxproj
- ios/storybooknative/Info.plist
- lib/fetch-fonts.js
- packages/article-summary/__snapshots__/article-summary.test.js.snap
- packages/article-summary/article-summary.js
- packages/card/__snapshots__/card.test.js.snap
For fonts to work in `react-native`, they need to be re-named in line with the generic `font family` we use in styles, so they work across native and web
> fix: name fonts

- packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
- packages/markup/__tests__/__snapshots__/markup.web.test.js.snap
- packages/markup/__tests__/markup.native.test.js
- packages/markup/__tests__/markup.web.test.js
- packages/markup/__tests__/test-helper.js
- packages/markup/markup-builder.js
- packages/markup/markup.js
- packages/markup/markup.stories.js
- packages/markup/markup.web.js
To allow `Flatlist` to use the markup output or fine grained styling of the child elements, expose builder so the consumer can act on the array of children
> feat: expose builder

- .eslintrc.json
~/times-components/packages/brightcove-video/brightcove.ios.fructose.js
4:29  error  Unable to resolve path to module './brightcove-video'
import/no-unresolved
✖ 1 problem (1 error, 0 warnings)
> fix: master eslint issues

- packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
- packages/card/__snapshots__/card.test.js.snap
- packages/card/card.js
- packages/card/card.stories.js
- packages/image/__snapshots__/image.test.js.snap
- packages/image/image.js
- packages/image/image.stories.js
- packages/image/image.test.js
This PR removes the aspect ratio property on an image and adds the resize mode.
One of the consequences of this change is that the width and height need to be specified, and there are two ways to do it. Set the dimension on the parent and the image will adapt or set the dimensions in the image.
> feat: replace aspect ratio for resize mode on image

- .travis.yml
As suggested on #89 we should run eslint for the full project on each CI job.
> fix: run lint on ci

- .eslintignore
- package.json
Run eslint on your changes only. This will pair well with #91 since the CI will be responsible for always linting the whole project.
> fix: run lint on staged changes only

- packages/caption/__snapshots__/caption.test.js.snap
- packages/caption/caption.js
- packages/caption/caption.stories.js
- packages/caption/caption.test.js
This PR is just to allow the already existent caption component to render credits only.
> fix: allow image caption to have credits only

- packages/link/package.json
Change the entry point for the `link` package from `link.js` to `link` in order to support proper multi platform import.
> fix: link package main entry point should be link

- lib/cli/package-json.js
Remove the `.js` extension from the main entry point in the cli tool. To avoid issues like #166
> fix: remove extension from main entry point in cli tool

- packages/article-byline/__snapshots__/article-byline.test.js.snap
- packages/article-byline/fixtures/authors.json
- packages/article-summary/__tests__/__snapshots__/article-summary.test.js.snap
- packages/article-summary/fixtures/article.json
- packages/author-head/author-head.js
- packages/author-head/fixtures/profile.json
- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/example.json
- packages/card/__tests__/__snapshots__/card.test.js.snap
- packages/card/fixtures/card-props.json
- packages/markup/__tests__/test-helper.js
- packages/markup/fixtures/anchor.json
- packages/markup/fixtures/bio.json
- packages/markup/fixtures/bold.json
- packages/markup/fixtures/image.json
- packages/markup/fixtures/italic.json
- packages/markup/fixtures/multi-paragraph.json
- packages/markup/fixtures/nested.json
- packages/markup/fixtures/script.json
- packages/markup/fixtures/single-paragraph.json
- packages/markup/fixtures/span.json
- packages/markup/fixtures/tag-mixture.json
- packages/markup/markup-builder.js
- packages/markup/markup.js
- packages/markup/markup.stories.js
- packages/markup/markup.web.js
- packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
- packages/provider/example.json
updated the markup tags and all the tests to reflect the changes on times-public-api.
> BREAKING CHANGE: conform markup component to new server side api

- packages/image/__snapshots__/image.test.js.snap
- packages/image/image.js
- packages/image/image.stories.js
- packages/image/image.test.js
- packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
- packages/provider/author-profile-provider.js
- packages/provider/example.json
- yarn.lock
On native, the URL resolver prepends the images path with `file`.
This PR ensures we fetch images from the image server using the https scheme.
> fix: fetch https images on native

- packages/article-headline/package.json
export the main entry point without the ext otherwise we can't use the specific android component
> export the main entry point without the ext

- .fructose/setup.js
- package.json
- packages/author-profile/author-profile.fructose.js
- packages/brightcove-video/brightcove-player.fructose.js
- yarn.lock
The latest version of fructose has introduced a number of breaking changes.
This PR allows the continuation of the Times components to e2e tested by fructose
> chore: update to latest version of fructose

- packages/ad/ad-composer.js
A simple fix to the `ad-composer` prop types.
> fix: ad-composer children prop-types

- packages/author-head/__tests__/author-head.test.js
- packages/author-head/author-head.js
- packages/author-head/author-head.stories.js
- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/author-profile-header.js
- packages/author-profile/author-profile.js
- packages/author-profile/author-profile.stories.js
- packages/author-profile/example.json
Adds a `onTwitterLinkPress` to author head and author profile.
It calls back with `(event, { url, handle })` so that native can handle the navigation.
PS
There's a bit of noise on the diff as I had to update the snapshots and fix all "missing proptype" warnings.
> Author profile links

- package.json
- yarn.lock
`pre-commit` is a bit nasty as it makes the .git/hooks dir all dirty. If this PR gets merged, people will not be able to commit without first doing a `rm .git/hooks/pre-commit`.
> Remove pre commit hooks

- packages/pagination/package.json
- packages/pagination/pagination-wrapper.js
- yarn.lock
Fixes "undefined" being used in displayName of pagination state hoc in cases where JSX doesn't set the displayName of wrapped component.
Before:
After:
> fix: prevent 'undefined' being used in pagination display name

- package.json
Rather than slacking devs to upgrade...yarn is supported in the `package.json` engines field
> chore: add yarn to engines

- packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
- packages/markup/package.json
Fix a bug introduced by #232. Bumping the `Ad` component to the correct version on the markup.
> fix: use the correct version of ad on markup

- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/author-profile-content.js
- packages/author-profile/author-profile-content.web.js
- packages/author-profile/author-profile-item.js
- packages/author-profile/author-profile.js
- packages/author-profile/author-profile.stories.js
- packages/author-profile/example.json
- packages/author-profile/package.json
- packages/link/__tests__/__snapshots__/link.native.test.js.snap
- packages/link/__tests__/__snapshots__/link.web.test.js.snap
- packages/link/__tests__/link-helper.js
- packages/link/__tests__/link.native.test.js
- packages/link/__tests__/link.web.test.js
- packages/link/link.web.js
- packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
Oooh, article links!
Now when you tap on a link, you get the `event` (duh) and an object with the `id` and `url` of the article.
1. Block links were adding underlines to text content, so I stopped that.
2. The article list now needs each articles `url`. Turns out that the provider was providing it anyway.
I hope you like snapshot diffs.
> Author profile article links

- packages/ad/package.json
- packages/article-flag/package.json
(`svgs` requires `react-native-svg` as a peer)
This was breaking on the native apps. The storybook didnt catch this as some other package was pulling it in as a dev dependency.
> fix: add missing dependency for ads

- packages/author-head/author-head.js
- packages/pagination/pagination.js
Adds font smoothing to correct the wrong shade of grey.
Job title:
Pagination:
IOS
> fix: web font smoothing

- packages/article/fixtures/no-ads.json
Updating the fixture for the article without ads. Fixing this issue:
> fix: update no-ads article fixture

- packages/markup/markup.stories.js
There was a change to the fixtures on the `d14cb15` commit that made the imports wrong.
Just a simple fix.
> fix markup fixtures imports

- packages/pagination/__tests__/test-wrapper-helper.js
- packages/pagination/pagination-wrapper.js
- packages/pagination/pagination.js
Makes synthetic event the first arg to the `onNext` and `onPrev` handlers to be consistent with  other components which use the same convention.
No visual changes.
> BREAKING CHANGE: change pagination event args order

- packages/brightcove-video/package.json
- packages/link/package.json
- packages/pagination/package.json
- yarn.lock
Coverage is currently running on every `js` file, narrow to only the link package in order to restore sanity to the build
Also - the svg version were out of date with the other packages
> fix: update coverage patterns

- .github/CONTRIBUTING.md
- lib/setup_device_connections.sh
- package.json
`yarn android:device` - Checks if a device is connected, sets up socket connections for live reloading, storybook and API, and runs the android task
> chore: yarn android:device task

- packages/article-headline/article-headline.android.js
> fix: style warning on android. Styles are not used in WebView

- packages/article-headline/WebView-auto-height.js
Reverts https://github.com/newsuk/times-components/pull/283/commits/a4662e47a304c9061329b34facd70149ef03f073#diff-e0bac437a16d31411da016800dee1cb4L60
And fixes headline:
> fix: article headline title

- packages/brightcove-video/README.md
Adds missing poster property to Brightcove video component readme.
> chore: adds missing poster property to readme

- README.md
Currently the fetch-fonts script runs before the storybook and storybook
native task. This means that fontforge is needed whether you're running
storybook web or native.
This PR updates the documentation to inform that fontforge must be
installed before running storybook to avoid error messages.
> docs: improve setup documentation

- .fructose/head.html
- .storybook/preview-head.html
- ios/storybooknative.xcodeproj/project.pbxproj
- ios/storybooknative/Info.plist
- lib/fetch-fonts.js
- packages/article-flag/__test__/__snapshots__/article-flag.android.native.test.js.snap
- packages/article-flag/__test__/__snapshots__/article-flag.test.js.snap
- packages/article-flag/article-flag.js
- packages/article/__tests__/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/__snapshots__/article.ios.test.js.snap
- packages/article/__tests__/__snapshots__/article.web.test.js.snap
- packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
- packages/author-head/author-head.js
- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
Changed the font metadata on the fetch-fonts script, as we had a typo on it. This fixes CPS-Content-Render for [TAP 135](https://nidigitalsolutions.jira.com/browse/TAP-135). I still need to investigate (and change?) the native android and iphone apps, as they have the old filename.
This shouldn't interfere with [TAP-186](https://nidigitalsolutions.jira.com/browse/TAP-186) or [TAP-159](https://nidigitalsolutions.jira.com/browse/TAP-159).
Screenshots:
> Fix: font-forge hack metadata for TimesDigitalW04-RegularSC font

- packages/ad/placeholder.js
- packages/article-byline/article-byline-proptypes.js
- packages/image/image-prop-types.js
- packages/watermark/package.json
View.propTypes has been deprecated - using ViewPropTypes instead.
> fix: replaces View.propTypes with ViewPropTypes

- .travis.yml
- lib/publish_storybook.sh
- packages/article/fixtures/full-article.json
Storybook will get published whenever any commits occur on master (including PR merges).
You can see the build log for a test deployment [here](https://travis-ci.org/newsuk/times-components/builds/295691376). The publishing appears under the _Deploying application_ section of the logs.
The `lib/publish_storybook.sh` script builds and deploys the storybook. This gets executed by Travis.
Tested it by:
* tracking a branch other than master
* changing fixtures and pushing to see if the storybook updated
* verifying that the gh-pages branch updated
* verified that the GH_TOKEN is not printed in the log
* disabled linting and testing to speed up builds
> chore: publish storybook using CI

- packages/tracking/__tests__/track-events.test.js
Setting default props to avoid errors causing noise in console when running tests
> tests: remove props warnings

- .storybook/preview-head.html
- yarn.lock
CNAME is in place now so this can be merged.
> TAP-226: Update font paths to load fonts from www.thetimes.co.uk

- packages/ad/ad.stories.native.js
Ad Placeholder positioned incorrectly due to inconsistent component context between iOS & Android.
This has been fixed by wrapping the Placeholder with a View.
> fix: mpu story (placeholder position)

- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/author-profile-author-head.js
- packages/author-profile/author-profile.js
- packages/provider/connect.js
On Android it became noticeable that the author head re-rendered on paging, on closer inspection it was fully unmounting and mounting again. This was because our GraphQL connect helper returned a new component every time it was rendered.
By refactoring the helper to dynamically calculate the GraphQL config options based on props, a new component didn't need to be returned each time.
In addition a SCU was added to `AuthorHead` to avoid a re-render and also keep consistency between web and Native, where Native has to have the head "within the content" to render in a recycler view, where traditionally in the web you would have it sitting outside the paged component.
> fix: stop unmounting and re-render

- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/author-profile.js
- packages/author-profile/fixtures/author-profile.json
- packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
- packages/provider/author-profile-provider.js
In order to keep the total number of articles between page changes we need to pull them to an "upper level". One way to do it (this PR) is to query the number of articles when getting the author information.
Another considered option was to create a new provider just to fetch the articles count that would wrap the articles list but this the complexity of having to manage one more loading state doesn't pay off.
> feat: query pagination count

- packages/ad/ad.js
- packages/ad/ad.web.js
- packages/ad/gpt.js
- packages/ad/package.json
- packages/article-headline/WebView-auto-height.js
- packages/article-headline/article-headline.js
- packages/article-headline/package.json
- packages/article-summary/package.json
- packages/author-profile/package.json
- packages/caption/caption.js
- packages/caption/package.json
- packages/card/package.json
- packages/date-publication/date-publication.js
- packages/date-publication/package.json
- packages/error-view/error-view.js
- packages/error-view/error-view.stories.js
- packages/error-view/package.json
- packages/gradient/gradient.js
- packages/gradient/gradient.web.js
- packages/gradient/package.json
- packages/image/package.json
- packages/image/placeholder/index.js
- packages/link/package.json
- packages/link/text-link.js
- yarn.lock
`react-style-proptype` doesn't take into account `StyleSheets` being numbers and tries to run `Object.keys` on them.
In retrospect depending on the third party which doesn't fully appreciate React Native to avoid slightly awkward syntax isn't that useful, use React Native propTypes instead
Hopefully this plays well with Babel `propType` stripping....
> chore: fix prop types

- packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/image.web.js
Web images should work without JS enabled which also makes SSR pages more elegant
n.b. still uses JS for placeholder
> fix: remove JS

- lib/cli/files/.npmrc
- packages/ad/.npmrc
- packages/article-byline/.npmrc
- packages/article-flag/.npmrc
- packages/article-headline/.npmrc
- packages/article-image/.npmrc
- packages/article-label/.npmrc
- packages/article-summary/.npmrc
- packages/article/.npmrc
- packages/author-head/.npmrc
- packages/author-profile/.npmrc
- packages/brightcove-video/.npmrc
- packages/caption/.npmrc
- packages/card/.npmrc
- packages/date-publication/.npmrc
- packages/error-view/.npmrc
- packages/gradient/.npmrc
- packages/image/.npmrc
- packages/jest-configurator/.npmrc
- packages/link/.npmrc
- packages/markup/.npmrc
- packages/pagination/.npmrc
- packages/provider/.npmrc
- packages/tracking/.npmrc
- packages/watermark/.npmrc
This should help developers avoid the situation where a package dependency is installed with a ^, which can cause the knock-on problem of a version of that dependency being installed which is newer than the version used in other packages and hoisted; if this occurs a package-lock.json will be generated in the package's folder which can cause the lint task to fail.
> Add an .npmrc to each package / scaffolding files to ensure exact NPM versions are used

- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/author-profile-item.js
- packages/author-profile/fixtures/article-list.json
- packages/provider/article-list-provider.js
- packages/provider/schema.json
- yarn.lock
At the moment if a client wants an article summary which is well within the teased limit, the API still needs to check with ACS because it queries article content.
Change to query `summary` which doesn't touch ACS and use `headline` instead of title which has SEO benefits
chore: update schema in provider for linting
> feat: use summary and headline for author profile

- packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/author-profile.js
* Pull page state up above author-profile so that correct page prop can be used for tracking
* Add `articlesCount` field to author profile tracking events
* Remove redundant test - can re-instate if it desired but didn't appear to be adding any value
> Author profiles tracking

- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/__tests__/author-profile-content.web.test.js
- packages/author-profile/author-profile-content.web.js
The current naïve implementation of lazy images does a lot of work on scroll which can cause jank on some machines/browsers. This effectively debounces any pending changes until the observations/scrolling stops before doing the JS work and reflowing to give better UX.
A small tweak to the threshold improved loading on mobile views where the cards are laid vertically and the image starts at the top.
Here are the profiles of scrolling fast down a list of 20 items
Before (lots of work and long frames): 
After (less work with one hit at the end):
> feat: add pending

- packages/article-flag/__test__/__snapshots__/article-flag.android.native.test.js.snap
- packages/article-flag/__test__/__snapshots__/article-flag.test.js.snap
- packages/article-flag/article-flag.js
- packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
Snapshot of **before** and **after** for flags
> REPLAT-922: Making flag font lowercase and changing height of diamond

- packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article/fixtures/full-article-typename.json
- packages/article/fixtures/full-article.json
- packages/article/fixtures/full-long-article.json
- packages/article/fixtures/no-ads.json
Addressing the comments in design review
- Fixture image ratio should be 16:9 or 3:2 (Inline primary image)
- Fixing fixture for provider data story, which was related to the iamge
> Chore: REPLAT-922: Change fixtures as per design review

- packages/article/styles/header/shared.js
fontWeight should be a string as per: https://facebook.github.io/react-native/docs/text.html
> fix: set font weight as a string

- packages/eslint-config-thetimes/package.json
- packages/tealium/package.json
If packages can't be published then the public storybook won't be updated/platforms can't take the latest versions
> fix: make packages public

- .github/CONTRIBUTING.md
- README.md
* The docs now point out that the build requires JDK 8 and won’t work
on more recent JDKs.
*  Removed old storybook run commands in .github/CONTRIBUTING.md now
superseded by instructions in README.md
> chore: update getting started docs

- packages/article-summary/__tests__/__snapshots__/article-summary.web.test.js.snap
- packages/article-summary/article-summary.js
- packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
- packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
Don't use antialiasing on article summary headline on web
> feat: remove font anti-aliasing of article headline on web

- packages/article-image/__tests__/android/__snapshots__/article-image.android.test.js.snap
- packages/article-image/__tests__/ios/__snapshots__/article-image.ios.test.js.snap
- packages/article-image/__tests__/shared.js
- packages/article-image/__tests__/web/__snapshots__/article-image.web.test.js.snap
- packages/article-image/__tests__/web/jest.config.js
- packages/article-image/article-image-proptypes.js
- packages/article-image/article-image.base.js
- packages/article-image/inset-caption.js
- packages/article-image/inset-caption.web.js
- packages/article-image/package.json
- packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article/article-lead-asset.web.js
- packages/article/package.json
As part of design review, fix the left padding for primary inline images for mob web and native. 
As part of this change we have introduced media queries for caption to add a 10px left padding for mobile web. We have used styled components for caption when it is associated with inline Primary image only.
The style change is applied to `article-image` package which is the consumer of Caption component. Inline images have three variations `inline`, `secondary`, `primary`. We have created a `caption-component` file in `article-image` package which handles the image variations for `secondary` and `inline` and a .web variation for a `primary` inline image where we had to apply the media query for web
**Before**
**After**
> feat: make inline image captions responsive

- packages/tracking/track-scroll-depth.web.js
For now if browsers don't support `IntersectionObserver` (safari), they won't get the advanced tracking
> fix: guard against no observer

- package.json
- packages/ad/package.json
- packages/article-byline/package.json
- packages/article-flag/package.json
- packages/article-image/package.json
- packages/article-label/package.json
- packages/article-summary/package.json
- packages/article/package.json
- packages/author-head/package.json
- packages/author-profile/package.json
- packages/brightcove-video/package.json
- packages/caption/package.json
- packages/card/package.json
- packages/date-publication/package.json
- packages/error-view/package.json
- packages/gradient/package.json
- packages/image/package.json
- packages/link/package.json
- packages/markup/package.json
- packages/pagination/package.json
- packages/provider/package.json
- packages/responsive-styles/package.json
- packages/storybook/package.json
- packages/tealium/package.json
- packages/tracking/package.json
- packages/watermark/package.json
- yarn.lock
3.2.18 includes a fix for a bug that broke storybook in IE11: https://github.com/storybooks/storybook/pull/2428
> Bump storybook version to 3.2.18

- packages/author-head/__tests__/author-head.test.js
- packages/author-head/package.json
- packages/card/__tests__/web/card.web.test.js
- packages/card/package.json
- packages/image/__tests__/placeholder.test.js
- packages/image/package.json
- packages/jest-configurator/jest-configurator.js
- packages/jest-configurator/package.json
- packages/jest-configurator/setup-jest.js
Move `Enzyme.configure` call to setup file in jest-configurator so it doesn't need to be repeated for every file that uses enzyme
> chore: use jest setup file to configure enzyme

- packages/author-profile/author-profile-content.js
The Next and Prev buttons should scroll to the top of the page when
clicked. Previously, they would scroll upwards, but either scroll too
far or not far enough. This was because the layout was recalculated
while the scroll was happening. This change delays the scroll until
after the layout so that it always scrolls to the top.
**iOS before fix after clicking "Next"**
**iOS after fix after clicking "Next"**
**android before fix after clicking "Next"**
**android after fix after clicking "Next"**
**web after fix after clicking "Next"**
(web never had an issue, but this shows it doesn't regress)
> fix: ensure consistent scrolling behaviour on author profile

- packages/provider/connect.js
- packages/provider/package.json
- packages/utils/graphql.js
- packages/utils/package.json
- yarn.lock
replace react-apollo with npmjs.com/package/react-apollo-temp which is
a fork that provides a workaround to this issue
https://github.com/apollographql/apollo-client/issues/2513
> Fix: clean up properly after a graphql error

- packages/tealium/package.json
Moved react-native to be a peer dependency inline with the other packages. This will mean it won't need to be installed on web
> chore: make Tealium a peer dependency so not installed on web

- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/android/modal-image.android.test.js
- packages/image/__tests__/image.native.test.js
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/__tests__/ios/modal-image.ios.test.js
- packages/image/__tests__/modal-image.native.test.js
- packages/image/__tests__/web/__snapshots__/modal-image.web.test.js.snap
- packages/image/__tests__/web/modal-image.web.test.js
- packages/image/modal-image.js
- packages/image/modal-image.stories.native.js
- packages/image/modal-image.web.js
- packages/image/package.json
- yarn.lock
Currently working on native only, this introduces `ModalImage` as a component, so that we can have an image open fullscreen.
`.web` implementation right now passes through to `Image`.
The :x: to close the modal is https://material.io/icons/#ic_close
| iOS | Android |
| --- | --- |
| ![iOS](https://user-images.githubusercontent.com/1263058/34679702-ae532cce-f48e-11e7-9969-707fa4e3edf3.gif) | ![android](https://user-images.githubusercontent.com/1263058/34679966-813a9c6c-f48f-11e7-85c2-b9b32c261b28.gif) |
> Modal image component

- packages/author-profile/author-profile.js
- packages/tracking/__tests__/tracking-context.test.js
- packages/tracking/tracking-context.js
Problem: 
The author name for the page view event on author profile was null. This is due to the page view being triggered on `componentDidMount`, but author name is only populated after the api request.
Solution:
Added a `isDataReady` callback on tracking context which only fires page view event when data is ready
> Added isDataReady check for pageView tracking

- packages/jest-configurator/setup.sh
Jest script was failing when the folder is already there, which is the case if you already have an
older version of the package installed.
> chore(Script fix): Removed set -e from jest script

- packages/jest-configurator/package.json
Setup script was being run on each install, but it should be running before tests only
> chore: Moved jest setup script to pretest instead of postinstall

- lib/start_android_emulator.sh
- package.json
Pre-android script launches an emulator but the app build doesn't wait for the emulator to be ready.
Added a wait script on start-emulator. Running yarn android should fire up an emulator and build the
app when the emulator has finished booting
> chore: Improve preandroid script to wait for emulator

- lib/start_android_emulator.sh
This PR makes sure not to spin an emulator up if there's already a device (real or emulator) connected.
Also:
1. Renamed the vars to be lowercase, as reserved vars will _always_ be uppercase, this way we don't risk name clashes.
2. Used correct path (with `$ANDROID_HOME`) as `emulator` might not be set as an alias.
> Do not spin up emulator if device connected

- .storybook/preview-head.html
@craigbilner this seems legit - have tested on gh-pages and fonts are back. I missed them.
> fix: fix fonts by removing local font definitions

- .babelrc
- package.json
- yarn.lock
Our codebase is not fully flowtyped. 
Flowtype makes PropTypes redundant as it shifts PropType checking from runtime to flow.
Unfortunately if you use a flowtyped component in a package that does not use flowtypes, you will have no proptype checks.
This PR installs https://github.com/brigand/babel-plugin-flow-react-proptypes
To create automatically proptypes from flowtypes.
You can verify that the plugin does it's job correctly by with the following component:
```js
import {Text} from "react-native";
import PropTypes from "prop-types";
class FlowTyped extends React.Component {
props : {foo:string}
render() {
return <Text>{
( FlowTyped.propTypes && FlowTyped.propTypes.foo == PropTypes.string )? "true" : "false"
}</Text>
}
}
```
> chore: installs babel-plugin-flow-react-proptype

- packages/card/package.json
- packages/gestures/package.json
- packages/image/package.json
`jest-configurator` was incorrectly added as a dependency in `gestures`, `card` and `image` packages. This PR moves to `devDependencies`.
> Chore: Move jest-configurator from dependencies to devDependencies

- packages/utils/graphql.js
`jest-configurator` doesn't work, if you have `@times-components/utils` as a transitive dependency.
This incompatibility was caused by mistakenly importing an untranspiled file from `react-apollo-temp`
This begs the question should we use `babel-jest` inside of jest-configurator?
> fix: utils/graphql.js now imports transpiled file

- .storybook.native/addons.js
Master is broken as it is looking for this addon that we dont use anymore. Simple fix.
> fix: Remove addon-links from native storybook

- .travis.yml
- lib/publish.sh
- lib/run_tests.sh
- package.json
By running the tests with the `since` flag everywhere has two issues:
* The coverage in coveralls is a little misleading for master
* Wider side effects a la babel scripts may break other packages but the PR tests won't fail
If we run all tests on the master branch this should resolve these two
> chore: only use since flag for PRs

- package.json
- packages/card/package.json
- yarn.lock
syncs up version number of the markup component and manually forces storybook components to v3.3.11.
Seems like some dependencies declare their dependencies with ^3.3.11 which installs a later version if available. Yesterday v3.3.13 has been released for some addons which breaks our setup
> fix: storybook versions

- packages/jest-configurator/__tests__/jest-configurator.test.js
- packages/jest-configurator/src/jest-configurator.js
- packages/utils/__tests__/jest.config.js
- packages/utils/package.json
- yarn.lock
Some packages do not require platform specific environments for testing. These currently have their own Jest files. In order to use Jest projects as the top level we would want to run a command like `jest --projects */**/jest.config.js`. This means if we have consistent Jest Configs in all packages using the Jest Configurator, we should be able to reach our goal.
Thoughts?
> feat: Allowing platform independence in Jest Configurator

- packages/ad/ad-init.js
This PR vertically aligns the ads. Unable to attach screenshot of native as storybook isn't working for native.
**Before on web**
**After on Web**
> Fix: vertically align the ads

- packages/article-byline/__tests__/android/__snapshots__/article-byline.android.test.js.snap
- packages/article-byline/__tests__/android/article-byline.android.test.js
- packages/article-byline/__tests__/android/jest.config.js
- packages/article-byline/__tests__/ios/__snapshots__/article-byline.ios.test.js.snap
- packages/article-byline/__tests__/ios/article-byline.ios.test.js
- packages/article-byline/__tests__/ios/jest.config.js
- packages/article-byline/__tests__/shared.js
- packages/article-byline/__tests__/web/__snapshots__/article-byline.web.test.js.snap
- packages/article-byline/__tests__/web/article-byline.web.test.js
- packages/article-byline/__tests__/web/jest.config.js
- packages/article-byline/package.json
Adds Jest Configurator to the Byline package.
N.B. The coverage is not 100%. This is because there is no implementation for onPress yet. This is waiting for a native routing solution.
> feat: Add Jest Configurator to the Article Byline package

- packages/gestures/package.json
- packages/slice/package.json
- packages/tealium/package.json
- packages/utils/package.json
- yarn.lock
syncs version numbers of several packages by following rules:
- if a dependency is times-component package take the latest version
- if there are multiple versions used in the codebase use what the majority uses.
- if it's a tie: use the latest version
> chore: sync version numbers

- packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/author-profile-content.native.js
- packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/web/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/author-profile-content.js
- packages/author-profile/author-profile-content.web.js
Now we have debounced paging it's possible to have new ids for the existing content because they're artificially based on the current page. We do have unique ids for articles though, so this PR uses them instead. Index has also been added for complete defence against any rogue duplicate articles....
> fix: make ids accurate

- packages/slice/package.json
- packages/slice/slice.stories.js
- yarn.lock
Adds the most basic story for the `Slice` component.
Fixes dextrose issue due to the component not having a story.
> feat: add story for slice component

- ios/storybooknative/AppDelegate.m
- ios/storybooknative/Info.plist
- package.json
- yarn.lock
Update the storybook-native ios with the latest changes related to react-native 0.50.1
> fix: storybook-native ios issue

- .travis.yml
- lib/publish.sh
The deploy script (making components.thetimes.co.uk) runs on every publish commit and every job. This moves the logic to the custom script where it will only publish for a single job when merged to master
> chore: publish once

- lib/publish.sh
Accidentally broke the coveralls report for master by not reporting the coverage for all jobs, only bail out on the other three jobs before publishing
> fix: publish coverage for all jobs

- packages/article/article-proptype.js
- packages/article/article-prototype.js
- packages/article/article.js
- packages/article/article.web.js
- yarn.lock
This PR exports article as an independent prop which can be used for validation in the consumers i.e. render
> Refactor: Change article as a standalone prop

- packages/utils/package.json
`@times-components/config` had `@times-components/jest-configurator` as a dependency, it should be a dev dependency. Moved it to the correct section 😄
> Moved dependency to dev dependency

- packages/ad/ad.stories.js
Moved the “Advertisement” story group into “Primitives” folder and added some documentation.
> fix: tidy up ads stories

- packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/author-profile-helper.js
- packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/web/__snapshots__/author-profile-content.web.test.js.snap
- packages/author-profile/author-profile-item.web.js
This is to fix REPLAT-1579 where on Author Profile pages with no images, we lose the summary text.
> fix: Put back the missing summary for Author Profiles with no images

- packages/author-profile/author-profile-content.js
The returned value from `keyExtractor` is expected to be a string. As a result a warning was being shown on Author Profile. This fixes this issue.
> fix: Fix the warning on Native devices when viewing Author Profile

- packages/article/article.js
- packages/article/article.web.js
This PR exposes article props which can be used for validation by the clients
> fix: export article default props

- lib/setup_device_connections.sh
`yarn android:device` was working only with real devices connected via usb. This PR changes the matching pattern to allow also for emulators.
> Add emulator to regex to match connected devices

- packages/brightcove-video/android/src/main/AndroidManifest.xml
- packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/BrightcovePlayerActivity.java
- packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/BrightcovePlayerJavaModule.java
- packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/BrightcovePlayerView.java
- packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveManager.java
- packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveView.java
- packages/brightcove-video/android/src/main/res/values/strings.xml
- packages/brightcove-video/android/src/main/res/values/styles.xml
The fullscreen button for `BrightcoveVideo` was disabled. This PR re-enables it.
Done also some code cleanup since I was at it, the main change is 21e49c0
| Before | After |
| --- | --- |
| ![brightcove_before](https://user-images.githubusercontent.com/1263058/37720561-7197e134-2d1f-11e8-95c6-b76e8678b5e0.png) | ![brightcove_after](https://user-images.githubusercontent.com/1263058/37720383-102c0006-2d1f-11e8-8a6e-d4b5decfa622.png) |
> REPLAT-1675 - Enable fullscreen button for BrightcoveVideo

- packages/article-byline/article-byline.js
- packages/article-byline/article-byline.stories.js
- packages/article-byline/package.json
- packages/article/__tests__/related-articles-shared.js
- packages/article/__tests__/shared.js
- packages/article/__tests__/web/article.web.test.js
- packages/article/article.js
- packages/article/article.stories.js
- packages/article/article.web.js
- packages/article/related-articles/related-article-item.js
- packages/article/related-articles/related-articles.js
Standardized onPress events for article-bylines and related articles and added addon-actions for
storybook to prevent default actions and log the event
> chore: Clean up press events for articles

- packages/depend/__tests__/__snapshots__/cli.test.js.snap
- packages/depend/__tests__/cli.test.js
- packages/depend/cli-parser.js
- packages/depend/depend.js
- packages/depend/main.js
- packages/depend/package.json
- yarn.lock
This PR adds an `--only` or `-on` (I went for `-on` instead of `-o` cause `-o` is usually used for output, could also just remove it) flag to restrict the packages on which `depends` act on.
The rationale behind that is that sometimes we're not interested in the whole deps graph, sometimes we are.
Talking to @nikhedonia it seems like in web implementations, for example, we want all the packages to be aligned because some CSS classes will be otherwise referring to different versions (so different styles), in native implementations, we're mostly interested in libraries that have a native library to be included on the project (e.g. `react-native-linear-gradient`), because there's only one entry point for these. The rest is ok because it'll simply be included with different versions in …
> Add filter to depend

- lib/cli/templates.js
- adds newlines to the ends of CLI-generated package.json and eslintrc files
> refactor: add appropriate newlines for CLI generated files

- packages/article/article.stories.js
- packages/article/src/__tests__/shared.js
- packages/article/src/__tests__/web/article.web.test.js
- packages/article/src/article-body/article-body-row.js
- packages/article/src/article-body/article-body-row.web.js
- packages/article/src/article-body/article-body.web.js
- packages/article/src/article-content.js
- packages/article/src/article.js
- packages/article/src/article.web.js
Added onLinkPress to article body and passed it to article row to enable link click callbacks for native. Native apps will expose a native module to utilize these callbacks.
Paired with: @colincclark
> feat: Inline article link callbacks for native

- packages/related-articles/fixtures/opinionandtwo/1-article.json
- packages/related-articles/fixtures/opinionandtwo/2-articles.json
- packages/related-articles/fixtures/opinionandtwo/3-articles.json
- packages/related-articles/src/__tests__/android/__snapshots__/related-articles.test.js.snap
- packages/related-articles/src/__tests__/ios/__snapshots__/related-articles.test.js.snap
- packages/related-articles/src/__tests__/web/__snapshots__/related-articles.test.js.snap
- yarn.lock
Fixes: https://nidigitalsolutions.jira.com/browse/REPLAT-1768 & https://github.com/newsuk/times-components/issues/791
Now hosting image on UAT image server which seems to fix the issue.
> Fix: Updated path to cutout image used in opinion slice

- packages/video-label/__tests__/android/__snapshots__/video-label.android.test.js.snap
- packages/video-label/__tests__/ios/__snapshots__/video-label.ios.test.js.snap
- packages/video-label/__tests__/shared.js
- packages/video-label/__tests__/web/__snapshots__/video-label.web.test.js.snap
- packages/video-label/src/video-label.js
Previously, the video label looked like this with no explicit label:
And like this with an explicit label:
Unless the label was "VIDEO" in which case it didn't show it, to avoid having the label "VIDEO | VIDEO".
Now the label only ever shows one bit of text, never 2 with a | character. If an explicit label is provided then it is used, otherwise "VIDEO" is shown:
iOS: 
Android:
> feat: only set video label to "video" if no explicit label is provided (REPLAT-1919)

- .storybook/config.js
Otherwise we extract info about the knobs HOC instead of our components
> fix: swap order of storybook decorators

- packages/storybook/src/knobs.js
#852 accidentally changed the API of showcaseToStoryBook, this fix restores it.
> fix: repair broken knobs argument to showcaseToStoryBook

- packages/slice/leadandtwo.stories.js
- packages/slice/opinionandtwo.stories.js
- packages/slice/standard.stories.js
- knobs were broken because the `selectV2` options do not accept an array
> fix: fix slice stories (knobs)

- packages/tealium-utils/package.json
- packages/tealium/package.json
BREAKING CHANGE: feat: bump version to 1.0.0 due to breaking changes not captured with conventional commits
> BREAKING CHANGE: bump version

- packages/tealium-utils/package.json
- packages/tealium-utils/src/storybook.js
fixed a bug around tealium-utils. It was lacking a cleanup-dist step in transpile, and this allowed a compilation bug to creep in that was hidden by stale files in the dist folder.
> fix: storybook native compilation error

- packages/styleguide/styleguide.stories.js
- packages/styleguide/styleguide.stories.styles.js
- fix warnings about invalid style and missing keys
> fix: warnings in font storybook

- .storybook/webpack.config.js
- README.md
Specifies a `devtool` option in our Webpack config, for web Storybook, to generate debuggable sourcemaps. Includes documentation.
> Fix/enhancement: debuggable source maps for web Storybook

- packages/article-summary/__tests__/android/__snapshots__/article-summary.android.test.js.snap
- packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
- packages/article-summary/__tests__/shared.js
- packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
- packages/article-summary/article-summary.showcase.js
- packages/article-summary/fixtures/with-links.js
- packages/article-summary/src/article-summary-renderer.js
- packages/markup/src/tree-prop-types.js
- packages/related-articles/__tests__/android/__snapshots__/related-articles.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/related-articles.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/related-articles.test.js.snap
We're not currently rendering links in the article summary. This renders their content as plain text.
There is a slight breaking change for sanity sake, the TV review data is so badly formatted that we may as well leave it even more broken so that we don't have to determine which text should be trimmed and which shouldn't. I'm still hopeful we can follow up initial work I started with the Methode team to create a known Review element which will resolve these issues.
> fix: implement link renderer

- .eslintignore
- .prettierignore
- lint and prettier need to ignore visual snapshots dir and fructose generated components file
> Chore: Add visual snapshots and generated components file to ignore

- packages/provider-test-tools/fixtures/topic.json
- packages/provider/__tests__/__snapshots__/topic-provider.test.js.snap
- packages/provider/src/topic-articles.js
The Topics provider was missing a headline in its request. This fixes this and the associated tests
> fix: Missing headline in topics provider

- packages/article/package.json
- packages/author-head/package.json
- packages/provider-test-tools/package.json
- packages/provider/package.json
- packages/responsive-styles/package.json
- packages/tracking/package.json
- yarn.lock
There's currently a handful of packages that have their own `node_modules` because their versions aren't compatible for hoisting to the root. Have bumped the versions of these packages (`styled-components` for `hoist-non-react-statics`)
> chore: fix unhoisted modules

- android/app/src/main/java/com/storybooknative/MainActivity.java
Haul does not support delta bundles, so it had to be turned off manually. Found a way to turn it off automatically for android
> Disable delta bundling on android for haul

- packages/topic/__tests__/android/__snapshots__/topic-functional.test.js.snap
- packages/topic/__tests__/ios/__snapshots__/topic-functional.test.js.snap
- packages/topic/__tests__/topic-functional.js
- packages/topic/__tests__/web/__snapshots__/topic-functional.test.js.snap
- packages/topic/package.json
- packages/topic/src/topic-tracking-context.js
REPLAT-2154
Analytics matches that of Author Profile other than:
1. Articles Count has been removed as it seemed unnecessary and wouldn't work correctly. If this is wanted, then I suggest we should put it back in when integrating the Name and Description provider as this will then closer mimic Author Profile. (Awkward in-between phase)
2. Passing in `isLoading: false` to get around the fact that we don't have the name and description provider yet,
> fix: Get Topic "Viewed" analytics working

- packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article/__tests__/shared-tracking.js
- packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article/package.json
- packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/author-profile.js
- packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
Following up from #954, this updates the analytics tests in our page components to follow the same pattern.
> chore: update analytics tests

- packages/eslint-config-thetimes/index.js
- packages/gradient/src/gradient.js
https://github.com/newsuk/times-components/issues/909
- Enforce the destruct of Component from React
- fix lint issue in gradient package as a result
> feat: enforce destruct of Component from React

- packages/article-list/src/article-list.js
- yarn.lock
React-native iOS has a bug, where onEndReached gets called right after load. Added a check to avoid this.
Bug: https://github.com/facebook/react-native/issues/16067
This workaround should be removed when the issue is resolved
> iOS infinite scroll bugfix for end reached calls before load

- packages/provider-test-tools/package.json
- packages/storybook/package.json
- packages/utils/package.json
- yarn.lock
Apollo-client has a fatal bug in android, crashing the app on network errors, so we needed to update to 2.3.2
> Apollo client bumped to 2.3.2

- packages/article-list/__tests__/android/__snapshots__/article-list.android.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list.ios.test.js.snap
- packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
- packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/src/image.js
- packages/topic/__tests__/android/__snapshots__/topic-styling.test.js.snap
- packages/topic/__tests__/ios/__snapshots__/topic-styling.test.js.snap
- fix the image component prop type warnings on native for empty `source.uri` props
- replace RegExp with `indexOf` for perf
> refactor: fix the image component prop type warnings

- package.json
- fix node version to less than 10, as t-c does not work on 10 yet.
Note: this will only throw a warning not an error if a node version greater than 10 is used
> chore: set or fix node version to less than 10

- packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
- packages/article-list/__tests__/web/__snapshots__/helper.web.test.js.snap
- packages/article-list/__tests__/web/helper.web.test.js
- packages/article-list/src/article-list.js
- packages/article-list/src/article-list.web.js
- packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
- fix lazy loading of `ArticleList` on safari. Safari does not use `IntersectionObserver`. The registration of images was happening _after_ the images were being fetched from the Component Class `images.map()`. Set the image width directly rather than going through the map as it was unnecessary
> fix: lazy loading on safari

- packages/article-list/__tests__/shared-web.js
- packages/article-list/article-list.showcase.js
- packages/article-list/src/article-list.web.js
- packages/article/article.showcase.js
- packages/author-profile/__tests__/mocks.js
- packages/author-profile/author-profile.showcase.js
- packages/author-profile/package.json
- packages/author-profile/src/author-profile.js
- packages/topic/__tests__/android/__snapshots__/topic-functional.test.js.snap
- packages/topic/__tests__/ios/__snapshots__/topic-functional.test.js.snap
- packages/topic/__tests__/topic-functional.js
- packages/topic/__tests__/topic-styling.js
- packages/topic/__tests__/web/__snapshots__/topic-functional.test.js.snap
- packages/topic/package.json
- packages/topic/src/topic.js
- packages/topic/topic.showcase.js
- fixes ArticleList ads by passing the adConfig down through the relevant consumer packages, and limiting ads to only showing when the loading of articles is completed
> fix: topic and author profile stories

- packages/ad/ad.showcase.js
- packages/ad/fixtures/topic-page-options.json
- Adds topic page ad config to `ad` storybook as per  https://docs.google.com/spreadsheets/d/1_btFh1lBtH2LoEVA0OGZIETLvBv0-ur1mHtJcK66dLE/edit#gid=0
> feat: Add Topic page ad config to ad stories

- .storybook/preview-head.html
> Fix: Missing font to fix storybook fonts in IE

- packages/article-list/__tests__/shared-native.js
- packages/article-list/src/article-list.js
React-native flatList has a bug, where certain devices trigger onEndReached multiple times, causing duplicate page loads. (see: https://github.com/facebook/react-native/issues/14015)
This PR aims to add a `loadingMore` state that blocks duplicate requests.
> Add loading state to article-list to avoid duplicate requests

- packages/author-profile/src/author-profile.js
`isLoading` was not been passed so was defaulting to `true` hence ads are not displaying.
> fix: ads in author-profile

- packages/topic/fixtures/topic-ad-config.json
`iuPartsSuffix` is a redundant field so removing from fixture. Confirmed with Dario from ad tech.
> fix: remove redundant slot targetting key-value pair

- packages/article-list/src/article-list-item.js
- packages/author-profile/__tests__/android/__snapshots__/author-profile-head.test.js.snap
- packages/author-profile/__tests__/author-profile-head.js
- packages/author-profile/__tests__/ios/__snapshots__/author-profile-head.test.js.snap
- packages/author-profile/__tests__/web/__snapshots__/author-profile-head.web.test.js.snap
- packages/author-profile/src/author-profile-head-base.js
- packages/author-profile/src/author-profile-head-image.js
- packages/author-profile/src/author-profile-head.js
- packages/author-profile/src/author-profile-head.web.js
Images are flickering on native apps while re-rendering because we are removing the view in loading state, instead of showing the placeholder. Removed the null checks for uri's as the image component itself has a placeholder state
> Show image loading state instead of hiding it

- packages/author-profile/__tests__/author-profile.js
- packages/author-profile/__tests__/shared-native.js
- packages/author-profile/author-profile.showcase.js
- packages/provider-test-tools/package.json
- packages/provider-test-tools/src/index.js
- packages/provider-test-tools/src/mocked-provider.js
- packages/provider/__tests__/article-provider.test.js
- packages/provider/__tests__/author-articles-no-images.test.js
- packages/provider/__tests__/author-articles-with-images.test.js
- packages/provider/__tests__/author-profile-provider.test.js
- packages/provider/__tests__/provider.test.js
- packages/provider/__tests__/topic-articles-provider.test.js
- packages/provider/__tests__/topic-provider.test.js
- packages/provider/provider.showcase.js
- packages/storybook/package.json
- packages/storybook/storybook-provider.js
- packages/topic/__tests__/topic-functional.js
- packages/topic/__tests__/topic-styling.js
- packages/topic/topic.showcase.js
- packages/utils/src/fragmentMatcher.js
- packages/utils/src/graphql.js
- packages/utils/src/index.js
As part of the provider refactor, we agreed to move the `MockedProvider` to the `provider-test-tools` package.
> chore: Move MockedProvider to provider-test-tools

- packages/article-topics/__tests__/android/__snapshots__/article-topics.test.js.snap
- packages/article-topics/__tests__/ios/__snapshots__/article-topics.test.js.snap
- packages/article-topics/__tests__/web/__snapshots__/article-topics.test.js.snap
- packages/article-topics/src/styles/index.js
- packages/video-label/src/style/index.web.js
as part of https://github.com/newsuk/times-components/issues/1069
> fix: video label and article topic design tweaks

- packages/provider-test-tools/package.json
- packages/provider-test-tools/src/mocked-provider.js
- packages/utils/package.json
As a result of a PR crossover, @tuncaulubilge code was accidentally removed from the Mocked Provider. This puts it back.
More information here: https://github.com/newsuk/times-components/commit/4ee2fbdc782bcd948f980003edec6b48da688c08#diff-f5bb9753b579b9d5c62e2b72f1b171bfR13
> chore: Put back the loading changes

- android-app/.prettierignore
- android-app/package.json
- ios-app/.prettierignore
- ios-app/package.json
CI is failing trying to publish android-app and ios-app packages. I've set them to private as they don't need to be published to npm.
Also added build and assets to prettierignore to exclude build artifacts from linting
> Set native packages as private and exclude assets from linting

- .babelrc
Applying the babel alias to the root level of the project for the fructose app to work (expo and dextrose etc)
> fix: replacing react apollo umd due to their issue

- packages/markup/README.md
- packages/markup/__tests__/android/__snapshots__/markup-ad.android.test.js.snap
- packages/markup/__tests__/android/__snapshots__/markup.android.test.js.snap
- packages/markup/__tests__/android/markup-ad.android.test.js
- packages/markup/__tests__/android/markup.android.test.js
- packages/markup/__tests__/ios/__snapshots__/markup-ad.ios.test.js.snap
- packages/markup/__tests__/ios/__snapshots__/markup.ios.test.js.snap
- packages/markup/__tests__/ios/markup-ad.ios.test.js
- packages/markup/__tests__/ios/markup.ios.test.js
- packages/markup/__tests__/shared-ad.base.js
- packages/markup/__tests__/shared.base.js
- packages/markup/__tests__/web/__snapshots__/markup-ad.web.test.js.snap
- packages/markup/__tests__/web/__snapshots__/markup.web.test.js.snap
- packages/markup/__tests__/web/markup-ad.web.test.js
- packages/markup/__tests__/web/markup.web.test.js
- packages/markup/fixtures/nested.json
- packages/markup/package.json
- packages/markup/src/markup.js
- packages/markup/src/markup.web.js
- packages/markup/src/render-tree-without-defaults.js
- extend the `markup` package to ignore child nodes of an AST with a `shouldIgnoreChildren` property - added `ignore children of nested tags` test for this
- add iterator to tests
- amend README
> refactor: markup renderer

- packages/article/fixtures/full-article.js
- packages/provider-test-tools/fixtures/article.json
- packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
- packages/provider/src/article.js
- packages/provider/src/article.web.js
- packages/related-articles/fixtures/standard/3-articles.js
- packages/related-articles/src/related-article-item.js
- packages/utils/src/schema.json
This PR fixes the issue mentioned in: https://nidigitalsolutions.jira.com/browse/REPLAT-2809
> fix: Allow poster image to show with lead asset videos

- packages/article/README.md
- packages/key-facts/README.md
- add a simple article package README
- adopt a standard when refering to ASTs in the docs
> docs: add article readme

- packages/depend/src/cli-parser.js
Without `<glob>` part commander interpret this option as boolean flag. Tests didn't catch this because commander is stubbed.
Without this change I get this:
```
$ npx @times-components/depend --only foo --list --lerna ./
TypeError: glob pattern string required
```
> fix(depend): add missing param for --only

- packages/storybook/__tests__/android/__snapshots__/storybook.android.test.js.snap
- packages/storybook/__tests__/ios/__snapshots__/storybook.ios.test.js.snap
- packages/storybook/__tests__/web/__snapshots__/storybook.web.test.js.snap
- packages/storybook/package.json
- packages/storybook/src/showcase-to-storybook.js
First step in moving away from deprecated features in React to ensure a painless migration to future versions. This helps devs know when developing a storybook that they are using a deprecated feature.
For the purposes of testing/debugging created a wrapper with a `displayName`
> feat: add strict wrapper

- ios/storybooknative.xcodeproj/project.pbxproj
ios storybook fix
Haul 1.0.0-rc5 has a breaking change on the scripts. Updated our ios build phases as per hauls documents: https://github.com/callstack/haul/releases/tag/v1.0.0-rc.5
> Update haul scripts

- lib/cli/files/.eslintignore
- lib/cli/files/.prettierignore
- packages/markup-forest/.eslintignore
- fix linting `rnw.js` ignores
- adds ignores to CLI for future packages
> fix: markup forest linting on master

- packages/caption/caption.showcase.js
- packages/caption/package.json
Circular deps in the repo can lead to confusing bugs and slows down setup time, this PR provides a simple image for the showcase instead
> chore: remove dep

- packages/provider-queries/package.json
- yarn.lock
When using webpack you need to install v4 at the package level to ensure `rnw.bundle` is built with v4 rather than the v3 root version for storybook
> fix: use webpack 4

- packages/article-byline/src/article-byline-prop-types.js
- packages/article-summary/src/article-summary-content.js
- packages/author-profile/src/author-profile-head-prop-types.base.js
- packages/related-articles/package.json
- packages/related-articles/src/related-article-item-prop-types.js
- packages/topic/src/topic-head-prop-types.js
This fixes the rest of the `treePropType` imports that broke in the move over to `markup-forest`
> fix: broken prop types

- packages/pages/src/article.js
Remove arguments from onCommentGuidelinesPress, as they are crashing the native app with unexpected arguments
> fix: Omit arguments in onCommentGuidelinesPress

- TimesReactIOS.podspec
- android-app/build.gradle
- android-app/package.json
- android-app/settings.gradle
- android-app/xnative/build.gradle
- android/app/build.gradle
- android/settings.gradle
- ios-app/package.json
- ios/storybooknative.xcodeproj/project.pbxproj
- yarn.lock
We are no longer using react-native-svg but native apps were still importing it. This pr aims to remove all dependencies to react-native-svg, as per https://github.com/newsuk/times-components/issues/1095
> Remove all references to react-native-svg

- packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
- packages/key-facts/__tests__/web/__snapshots__/key-facts-with-style.web.test.js.snap
- packages/key-facts/__tests__/web/__snapshots__/key-facts.web.test.js.snap
- packages/markup/README.md
- packages/markup/__tests__/android/__snapshots__/markup.android.test.js.snap
- packages/markup/__tests__/ios/__snapshots__/markup.ios.test.js.snap
- packages/markup/__tests__/shared.base.js
- packages/markup/__tests__/web/__snapshots__/markup.web.test.js.snap
- packages/markup/fixtures/emphasis.json
- packages/markup/fixtures/strong.json
- packages/markup/fixtures/tag-mixture.json
- packages/markup/src/markup.js
- packages/markup/src/markup.web.js
- packages/topic/__tests__/web/__snapshots__/topic-with-style.web.test.js.snap
- packages/topic/__tests__/web/__snapshots__/topic.web.test.js.snap
This feature is an update to the markup package so that is can support the content elements,
- `emphasis`,
- `strong`,
that will soon be returned by the Times Public API, once Methode Parser is updated ([#15](https://github.com/newsuk/times-methode-parser/pull/15)).
> feat: add markup support for `emphasis` and `strong`.

- android-app/pages/article.js
- packages/pages/src/article.js
Adds the ability to omit errors by introducing a new prop to pages package. 
With this prop, native apps can choose to do their own error handling, so react-native just ignores the errors and stays in a loading state
> Omit errors prop for android app

- lerna.json
- package.json
- packages/ssr/index.js
- packages/ssr/package.json
For a package to be ignored by the lerna npm publish step, it needs to be set to `private`. The `publish.ignoreChanges` glob is to simply ignore that package for the purposes of change detection.
fix: revert testing change
chore: update out of date script flags
> fix: ssr publish

- packages/article-summary/src/article-summary.js
- `Article-summary` label proptypes update to stop warnings in client.
> Fix: Label title should not be required field

- packages/provider-queries/src/article.js
- packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
SliceName was missing in the query. Added it in so related articles can be rendered when using the provider.
> Add slicename to relatedArticleSlice query

- packages/markup/fixtures/tag-mixture.json
I noticed that I forgot to put an emphasis tag in the storybook. This is to fix this oversight.
> chore: update markup > tag-mixture in storybook

- packages/article-label/__tests__/web/__snapshots__/article-label.web.test.js.snap
- packages/article-label/src/style/index.js
- packages/article-list/src/article-list-pagination.web.js
- packages/article-list/src/article-list-prop-types.web.js
- packages/article/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/pagination/__tests__/web/__snapshots__/pagination-with-styles.web.test.js.snap
- packages/pagination/__tests__/web/__snapshots__/pagination-wrapper.web.test.js.snap
- packages/pagination/__tests__/web/__snapshots__/pagination.web.test.js.snap
- packages/pagination/__tests__/web/pagination-with-styles.web.test.js
- packages/pagination/__tests__/web/pagination-wrapper.web.test.js
- packages/pagination/__tests__/web/pagination.web.test.js
- packages/pagination/src/pagination-wrapper.js
- packages/pagination/src/pagination.web.js
- packages/related-articles/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/std-with-style.web.test.js.snap
- packages/ssr/author-profile.client.js
- packages/ssr/author-profile.js
- packages/ssr/index.js
- packages/ssr/package.json
- packages/ssr/topic.client.js
- packages/ssr/topic.js
The current UX is a bit naff when you navigate to a list item and then hit back in the browser, we effectively broke the web experience :-(
This PR updates history state and provides a server-side implementation
chore: refactor prop-types and the way they were shared. We should always provide a no-js fallback for paging and sharing prop-types made this brittle
> feat: add server-side paging

- packages/author-profile/__tests__/android/__snapshots__/author-profile.android.test.js.snap
- packages/author-profile/__tests__/ios/__snapshots__/author-profile.ios.test.js.snap
- packages/author-profile/__tests__/shared.base.js
- packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
- packages/author-profile/src/author-profile-head-base.js
- packages/author-profile/src/author-profile-head.js
- packages/author-profile/src/author-profile-head.web.js
- packages/provider-test-tools/src/fixture-generator.js
- the new image render function matches the render functions for all of the other parts of the author profile head
> fix: dont display head image placeholder when no author image

- packages/ad/__tests__/utils/ad-init-gpt.js
- packages/ad/src/utils/ad-init.js
- packages/storybook/src/showcase-to-storybook.js
- fixes the broken ad stories which try to destroy slots when they are not there. The sympton was an empty page with ad blocker turned on, and a RN screen of death when traversing between stories with ads
- mock `<Fragment>` for storybook which does not recognise them, and gives prop type warnings from the [info add-on](https://github.com/storybooks/storybook/tree/master/addons/info). Seen in the `Ad Loading State` story
> fix: ad error, and mock fragment for storybook

- packages/article-list/src/article-list-pagination.web.js
- packages/pagination/package.json
- packages/pagination/pagination.showcase.web.js
- packages/pagination/pagination.stories.web.js
- packages/pagination/src/pagination.web.js
- fixed pagination storybook
- ensure no prop type warnings
- removed helper stories as this code is already called in the normal pagination stories
> fix: pagination storybook

- packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
- packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
- packages/article-list/src/article-list.web.js
- pass layout style (with keyline borders) to `Ad` so `Ad` can decide whether to show these keylines or not (when it fails due to ad blocker, in this example)
> fix: ad blocked layout in article list

- packages/article/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article/src/article-body/article-body-row.js
Interactive containers were not showing their padding. Turns out all the styling wasn't being applied natively.
> fix: Interactive container was not being applied

- packages/video/__tests__/android/__snapshots__/video-with-style.android.test.js.snap
- packages/video/__tests__/ios/__snapshots__/video-with-style.ios.test.js.snap
- packages/video/src/styles/shared.js
Lead asset image has a zIndex:1, so we need play icon to have a higher zIndex.
> fix: Add zindex on play icon overlay

- android-app/pages/article.js
- ios-app/pages/article.js
- Use mobile ad units on apps.
- Use networkId passed by the app, based on the build flavour
> fix: android ad id

- android-app/pages/article.js
- packages/article/src/article-meta/article-meta-base.js
- packages/provider-queries/src/article.js
- packages/provider-test-tools/fixtures/article.js
- packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
- packages/provider/__tests__/article-provider.test.js
- packages/related-articles/src/related-article-item-prop-types-base.js
Fixing a few prop-type warning inside the native app
- Added shortheadline to articles and related articles, and set optional in related articles
- Section name was passed to the wrong prop in android-app
- Byline prop-type definition fixed in article-meta
> fix: missing props article

- lib/start_android_emulator.sh
Adds a warning to emulator launch script for ANDROID_HOME env var
> chore: Update emulator script to provide a better warning

- TimesReactIOS.podspec
React as imported by the iOS project must have changed and fails to satisfy this dependency, so we cannot install any cocoa pods until we fix this podspec.
> fix: Remove unused dependency from TimesReactIOS podspec

- android-app/index.android.js
- android-app/package.json
- yarn.lock
React-native Android is overwriting URL class, which causes an error in our image component. 
Applied the following fix to polyfill URL using whatwg-url: https://github.com/facebook/react-native/issues/16434#issuecomment-392147974
> fix: Use whatwg-url for creating urls in android

- packages/pages/src/article.js
Article page was hanging in loading when `omitErrors` flag was set. This should only happen if there is an error.
> Fix omitErrors usage in pages

- packages/topic/__tests__/android/__snapshots__/topic-with-style.android.test.js.snap
- packages/topic/__tests__/ios/__snapshots__/topic-with-style.ios.test.js.snap
- packages/topic/src/styles/shared.js
Two line topic headlines were left aligned by default. Now forced them to center align always:
Before:
After:
> fix: Center align topic headline

- android-app/pages/article.js
Passes advertising testmode from the native app to the config. This allows us to put a custom debug field into the app for easier ad testing
> feat: Add test mode to ad configs for easier testing

- packages/ad/__tests__/web/__snapshots__/ad-with-style.web.test.js.snap
- packages/ad/src/dom-context-prop-types-base.js
- packages/ad/src/dom-context-prop-types.js
- packages/ad/src/dom-context-prop-types.web.js
- packages/ad/src/dom-context.web.js
https://nidigitalsolutions.jira.com/browse/REPLAT-3836
This should not adversely affect ads on any of the pages as the height is just set to be "auto", although this was difficult to test as ads seems to be very flakey. It shows intermittently and on some stories, not at all
> fix: variable ad height on articlie list pages

- .storybook.native/index.js
- android-app/index.android.js
- android-app/package.json
- package.json
- yarn.lock
The url polyfill we used for Android seem to only work when js debug is turned on, but crashing on release builds. Replaced with "url-polyfill" instead. Also added the same polyfill to storybook
> Use url-polyfill instead of whatwg-url

- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/src/image.js
- packages/related-articles/__tests__/android/__snapshots__/std-has-video.android.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-has-video.ios.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/std-has-video.web.test.js.snap
iOS doesn't seem to be happy with image sources with null uris. Use null source instead
> fix: iOS image loading error

- packages/article/fixtures/full-article.js
- packages/article/src/article-body/article-body-row.web.js
Object naming for Interactives in TC compared to TPA didn't match. This fixes the integration of Interactives.
> fix: Change object name so that it works

- android-app/pages/article.js
Part of the android analytics fix (REPLAT-1706). Splitted article page view event from track event so the native app can treat these events separately.
> fix: Split article view event from track event

- .storybook.native/webpack.haul.storybook.js
- packages/lazy-load/lazy-load.showcase.web.js
- packages/lazy-load/lazy-load.stories.web.js
Native storybooks are broken because of two issues, this PR fixes both:
- Graphql transpilation problems. Added mjs to list of extensions: (see https://github.com/graphql/graphql-js/issues/1272)
- Lazy load stories are converted to web only
> fix: storybooks

- packages/ad/__tests__/utils/webview-event-callback-setup.js
- packages/ad/src/utils/webview-event-callback-setup.js
window.postMessage doesn't work until the webView is loaded. Our previous fix for this was to add a timeout to postMessages, but that's not 100% reliable. Implemented a separate approach where the window enqueues messages until post message is ready:
Based on: https://github.com/facebook/react-native/issues/11594#issuecomment-274689549
> fix: Ads not loading - Enqueue window post messages until it's ready

- packages/article-flag/__tests__/android/__snapshots__/article-flag-with-style.android.test.js.snap
- packages/article-flag/__tests__/ios/__snapshots__/article-flag-with-style.ios.test.js.snap
- packages/article-flag/__tests__/web/__snapshots__/article-flag-with-style.web.test.js.snap
- packages/article-flag/src/style/index.android.js
- packages/article-flag/src/style/shared.js
Part of https://nidigitalsolutions.jira.com/browse/REPLAT-3472
NB: margins here are for layout _vis a vis_ font, rather than vertical rhythm, hence, did not use `spacing`
> fix: article flag layout

- .github/CONTRIBUTING.md
Building on Xcode 10 doesn't currently work. I figured out a work around that worked for me – thought it should be in the CONTRIBUTING.md so others do not have to stab in the dark.
> docs: provide instructions for building for iOS using Xcode 10

- .github/CONTRIBUTING.md
- .gitignore
This is because of https://nidigitalsolutions.jira.com/browse/REPLAT-4014. It should be reverted when the React Native issues with XCode 10 are fixed
> build: .gitignore the ios/Index folder

- packages/article/article.showcase.js
The article story now matches the ad one which also uses the `window.top.location` value as a link
> fix: ios article storybook has window and DOM references

- packages/eslint-config-thetimes/index.js
We do the same thing with `Component`
> chore: ensure PureComponent is destructed from React

- packages/tealium-utils/package.json
- packages/tealium-utils/src/storybook.js
- packages/tealium-utils/src/storybook.web.js
Call the action logger from the native storybook `tealium-util`. Looks like it was just an oversight that it wasn't added.
`if (!global.storiesOf)` has been removed which was a previous hack when `fructose` first started
> feat: expose tracking events to native storybook

- packages/card/card-wrapper.js
- packages/card/card-wrapper.web.js
- packages/card/card.showcase.js
Styled components doesn't support media queries on native platforms, but the error you get is very non-descriptive and without any kind of stack trace
```
node of type at rule not supported as an inline style
```
After investigating, this was tracked down to the use of media queries in two showcases that did not have native specific versions.
**You should avoid using media queries on native platforms as they will not work, and give you very confusing errors with no information to track them down**
> chore: stop using media queries on native platforms

- packages/image/image.showcase.js
- `image` package already handles case when `uri` prop is `null`
- Demonstrate image fallback to placeholder
> Feat: Add story to demonstrate image fallback

- app.json
- package.json
- yarn.lock
Update fructose and expo to fix expo.
Tested using the "delete_me_soon" workflow in bitrise on the following PR: https://github.com/newsuk/times-components/pull/1397
Will test against this one too.
Will need to add the expo steps back into the "PR" workflow in bitrise after this is merged.
> chore: update fructose to 3.11.4

- packages/article/src/article-prop-types.js
- remove `adConfig` prop type - Ad config is on the ArticlePage level, not Article anymore
> refactor: remove unrequired adConfig prop type

- packages/article/__tests__/comments.base.js
- packages/article/__tests__/comments.native.js
- packages/article/__tests__/images.base.js
- packages/article/__tests__/scaling.base.js
- packages/article/__tests__/shared-article-props.js
- packages/article/__tests__/shared-article-props.web.js
- packages/article/__tests__/shared-tracking.js
- packages/article/__tests__/shared-with-style.web.js
- packages/article/__tests__/shared.base.js
- packages/article/__tests__/shared.native.js
This prepares the ground for article prop types to be further separated out into web vs native. It removes the `refetch` required prop type warnings in native in the tests.
future pr: move more common prop types into the `shared-article-props` files in the `tests` directory
> test: remove prop type warnings in article

- packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/jest-configurator/__tests__/jest-configurator.test.js
- packages/jest-configurator/src/jest-configurator.js
Fixes #1102
Uses the `react-native` provided transformer for showing the filename of mocked image paths in native snapshots.
Unfortunately, we use an old version of `react-native`, and in this version the jest preset has the bug of not applying to scoped packages. Unfortunately, we're blocked on updating `react-native` by Expo. Therefore, I've temporarily copied the patch https://github.com/facebook/react-native/commit/216bce31632480ce70cc03b1b2a57ec12440afd7 into `jest-configurator`.
I've also whitelisted `@storybook/react-native` from the transform as it requires a png transform to work.
> chore: show filename of mocked image paths in native snapshots.

- packages/video-label/__tests__/android/__snapshots__/video-label.android.test.js.snap
- packages/video-label/__tests__/ios/__snapshots__/video-label.ios.test.js.snap
- packages/video-label/__tests__/video-label.native.js
- packages/video-label/__tests__/web/__snapshots__/video-label.web.test.js.snap
- packages/video-label/__tests__/web/video-label.web.test.js
- packages/video-label/src/video-label.js
Titles are optional in the `VideoLabel` component, but if you pass null the component breaks due to how it checks whether the title has been passed or not. This is a regression that was introduced when the "beautifier" was inlined in be5a458be5d3679f959edb1598c5397b4834d098, so I have added tests to prevent this occurring again.
> fix: Properly handle null titles in the video label component

- lib/cli/templates.js
The keys in our create component script are not sorted, this pr fixes it
> chore: Sort keys in template

- packages/article-paragraph/src/index.js
Not all markups have attributes in it so the previous code was crashing. Updated to fix native articles
> fix: Undefined value in para wrapper

- packages/article-error/package.json
- packages/article-error/webpack.config.js
Article error shouldn't be bundled for web as it's native only. Removed bundling as it was breaking releases
> chore: Remove bundling from article error since it's native only

- android/app/src/main/AndroidManifest.xml
@tuncaulubilge & I paired on this.
This should make Android builds of the storybook work again. 
Android was blocking connections to the bundle webpack server because it is being served over HTTP instead of HTTPS.
> fix: Allow android storybook to load bundle from insecure webpack server

- packages/gestures/__tests__/android/__snapshots__/gestures.android.test.js.snap
- packages/gestures/__tests__/ios/__snapshots__/gestures.ios.test.js.snap
- packages/gestures/__tests__/shared.native.js
- packages/gestures/src/gestures.js
- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
React Native doesn't support transform origin, so we have to use translations to emulate this. https://github.com/facebook/react-native/issues/1964
First we apply a translation to reset the origin of the transformation to the top left of the gesture view, and then we apply another translation to move the origin to the offset from that to the centre of the two touches. Then, we apply the zoom transformation, and then undo the translations. Then the rotation is applied.
> feat: Zoom at centre of the two touches during pinch to zoom

- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/__tests__/shared.native.js
- packages/image/src/image.js
- packages/image/src/utils.js
Image resize was broken on native apps since highResSize is not passed at the moment. This pr uses screenWidth if highResSize is not available
> fix: Use screen width if highRes is not provided in images

- package.json
- packages/related-articles/src/related-article-item.base.js
Also bumping `yarn` as that is now broken too
> chore: fix linter after master was broken

- packages/article-error/__tests__/android/__snapshots__/article-error-style.test.js.snap
- packages/button/__tests__/android/__snapshots__/button.android.test.js.snap
- packages/button/src/styles/index.android.js
Default style on android for buttons has the wrong lineHeight.
Before: 
After:
> fix: button android default style

- packages/provider-queries/src/article.web.js
The short headline isn't displaying in Related Articles slices on web, because its not included in the GraphQL query on web.
> fix: Use short headline in Related Articles on web

- packages/image/__tests__/shared.native.js
- packages/image/src/utils.js
Author profile head image has a resize in the url received from tpa, so this PR checks before appending another "resize" at the end of that url, otherwise the image is not loaded at all.
> fix: Check if resize already exists in url

- android/app/src/main/java/com/storybooknative/MainApplication.java
- android/app/src/main/java/com/storybooknative/stubs/ArticleEvents.kt
- android/app/src/main/java/com/storybooknative/stubs/AuthorProfileEvents.kt
- android/app/src/main/java/com/storybooknative/stubs/ReactAnalytics.kt
- android/app/src/main/java/com/storybooknative/stubs/ReactConfig.kt
- android/app/src/main/java/com/storybooknative/stubs/StorybookStubPackage.kt
- android/app/src/main/java/com/storybooknative/stubs/TopicEvents.kt
- packages/pages/pages.showcase.native.js
- packages/pages/src/apollo-client.js
Pages package is directly using the NativeModules now, so we had to stub those out on storybook android app. 
- Fixed the NativeFetch callback, which uses the default react-native fetch when not provided (storybook uses this fallback)
- Fixed showcases
- Added stub modules into storybooks, which just logs any native method calls.
> fix: pages stories

- packages/pages/src/article/article-base.js
There are few articles which has an empty newsdesk value, which causes the app to crash. Added default values for these scenarios
> fix: Add article section fallback on pages

- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/src/utils.js
Query param append util was broken on our fallback scenario. "URL" class is not defined in some android versions, so we had to fix our fallback scenario when URL is not defined.
> fix: native resize append util

- packages/provider-queries/src/author-articles-with-images.js
- packages/provider-queries/src/topic-articles.js
- packages/provider-test-tools/src/author-profile.js
- packages/provider/__tests__/__snapshots__/author-articles-with-images.test.js.snap
Apollo normalised cache has an issue which fails the network request if an object has an id in one query and doesn't have it in another. Added id to all image objects inside topic and author articles
Here is the error we are receiving at the moment: 
```
Store error: the application attempted to write an object with no provided id but the store already contains an id of Image:d3494166-0c9b-4971-86c0-602892d5b11c for this object. The selectionSet that was trying to be written is:
```
Here is the related github issue for more details: https://github.com/apollographql/apollo-client/issues/2510
> fix: Add id to images inside author and topic articles queries

- packages/article-main-standard/__tests__/android/__snapshots__/tracking.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/tracking.ios.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/tracking.web.test.js.snap
- packages/article/src/article-tracking-context.js
Right now we are sending the whole topic object, but the analytics team wants to see only the topic names. 
Part of Replat-4348
> fix: Comma join topic names for analytics

- packages/article-main-standard/__tests__/android/__snapshots__/tracking.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/tracking.ios.test.js.snap
- packages/article-main-standard/__tests__/shared-tracking.js
- packages/article-main-standard/__tests__/web/__snapshots__/tracking.web.test.js.snap
- packages/article-main-standard/src/article-main-standard.js
- packages/article/src/article-tracking-context.js
- packages/pages/__tests__/android/__snapshots__/pages.test.js.snap
- packages/pages/__tests__/ios/__snapshots__/pages.test.js.snap
- packages/pages/src/article/article-base.js
- packages/pages/src/article/article-prop-types.js
Analytics team wants to get the referralUrl whenever user launches an article through deeplinking, especially to see query params such as utm_tracking etc.
This "referralUrl" is passed through the native apps into our article component. 
Part of the Replat-4348 ticket
> feat: Add referral url to article analytics

- packages/provider-test-tools/src/author-profile.js
- packages/provider-test-tools/src/fixtures/article-list-with-images.json
Author profile showcases with images are broken due to a missing UUID resolver.
> chore: Add uuid resolver to author profile query

- packages/caption/__tests__/android/__snapshots__/caption-with-style.android.test.js.snap
- packages/caption/__tests__/android/__snapshots__/caption.android.test.js.snap
- packages/caption/__tests__/ios/__snapshots__/caption-with-style.ios.test.js.snap
- packages/caption/__tests__/ios/__snapshots__/caption.ios.test.js.snap
- packages/caption/__tests__/shared-with-style.base.js
- packages/caption/__tests__/shared.base.js
- packages/caption/__tests__/web/__snapshots__/caption-with-style.web.test.js.snap
- packages/caption/__tests__/web/__snapshots__/caption.web.test.js.snap
- packages/caption/caption.showcase.js
- packages/caption/src/caption.js
- packages/caption/src/centred-caption.js
- Create a new `<CenteredCaption />` component in the `caption` package 
- First use will be the `article-magazine-comment` template.
> feat: Add support for centred captions

- packages/provider-test-tools/fixtures/article.json
Fixes the problem with inconsistent results in #1512 
Required to go in first and separate from the breaking change.
> chore: To allow consistent results if template is queried

- packages/styleguide/src/theme/theme-factory.js
- Add support for secondary colour overrides for `magazine-comment` and `magazinestandard`
- Needed for https://nidigitalsolutions.jira.com/browse/REPLAT-4535
> Feat: theme article labels

- packages/article/__tests__/article.test.js
- packages/article/src/article.js
Native apps can use the article package with no data to show an error view, so the article package should work when article is undefined. Added a default value and a test
> fix: Support null article data on article package

- .snyk
Snyk security checks are failing due to a vulnerability in WS. We are only using ws for debugging purposes so we can safely ignore it.
> chore: Update snyk ignore config

- packages/article-magazine-comment/src/article-magazine-comment.web.js
- packages/article-main-comment/src/article-main-comment.web.js
- sets a default `author` object in article comment templates -  `main` and `magazine`
- Fixes 500 errors in render when view an article with this template as no author object is being currently returned.
> fix: Handle empty author object in article comment templates 

- packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-magazine-comment/src/styles/shared.js
- packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-magazine-standard/src/styles/shared.js
- packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-comment/src/styles/shared.js
Article bylines were misaligned on native, added a style to metaContainer on all templates
Before:
After:
> fix: Center alignment on native article meta

- packages/key-facts/key-facts.showcase.js
- packages/key-facts/key-facts.showcase.web.js
- packages/key-facts/showcase-helper.js
Split out the key facts stories so that scaling context and knob not seen on web
> fix: key facts stories

- packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-magazine-comment/__tests__/shared.base.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/src/article-magazine-comment.js
- packages/article-magazine-comment/src/article-magazine-comment.web.js
Magazine comment template is crashing when author image is null. This pr adds a null check for web and native
> fix: magazine comment empty author

- .storybook/preview-head.html
- lib/fetch-fonts.js
- packages/styleguide/src/fonts/fonts.js
- packages/styleguide/styleguide.showcase.js
Part one of font theming story
Added new fonts to the styleguide: https://nidigitalsolutions.jira.com/browse/REPLAT-4649
I opted for naming fonts per magazine sections as they are all specific to certain magazine sections we have (culture, style and ST)
Web:
Android:
> feat: Add new fonts to styleguide

- .storybook/preview-head.html
Quick fix for fonts in storybooks for componentes.thetimes.co.uk
> fix: Correct storybook fonts urls

- packages/article-comments/.jestlint
- packages/article-comments/__tests__/web/__snapshots__/shared-with-style.web.test.js.snap
- packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
- packages/article-comments/src/comments.web.js
- packages/article-comments/src/disabled-comments.web.js
- packages/article-comments/src/styles/index.web.js
- packages/article-in-depth/.jestlint
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/.jestlint
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/.jestlint
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/.jestlint
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/.jestlint
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-skeleton/.jestlint
- packages/article-skeleton/__tests__/mocks.web.js
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
Use `link` component in `article-comment` package instead of a "raw" `a` tag.
> chore: use link component in article-comment

- packages/fixture-generator/src/mock-article.ts
- packages/mock-tpa-server/src/create-mock-functions.js
- packages/ssr/__tests__/integration/article.js
This makes the cypress article tests use a better convention when generating data.
> refactor: article cypress tests

- .snyk
Snyk seems to be failing on the CI, so I've updated the expiries on some noncritical issues
> chore: Update Snyk ignore for non critical issues

- packages/author-profile/__tests__/shared.base.js
- packages/author-profile/author-profile.showcase.js
- packages/author-profile/src/author-profile.js
If authors have `noLeadAssets` enabled, we shouldn't be showing lead assets on their author page. This is a regression that needs fixing.
> fix: don't show images on author pages with no lead assets turned on

- packages/article-list/__tests__/android/__snapshots__/article-list-error-with-styles.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list-error.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list-states.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list-with-styles.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list.android.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-error-with-styles.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-error.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-states.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-with-styles.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list.ios.test.js.snap
- packages/article-list/src/article-list.js
- Keyline above loading spinner (shown when paginating on apps) was being displayed to the left on landscape tablets. This PR fixes this issue.
- Found as part of design review https://nidigitalsolutions.jira.com/browse/REPLAT-4865
> fix: Tablet layout of loading spinner keyline

- packages/article-in-depth/src/article-in-depth.js
- packages/article-in-depth/src/article-prop-types/article-prop-types.js
- packages/article-magazine-comment/src/article-magazine-comment.js
- packages/article-magazine-comment/src/article-prop-types/article-prop-types.js
- packages/article-magazine-standard/src/article-magazine-standard.js
- packages/article-magazine-standard/src/article-prop-types/article-prop-types.js
- packages/article-main-comment/src/article-main-comment.js
- packages/article-main-comment/src/article-prop-types/article-prop-types.js
- packages/article-main-standard/src/article-main-standard.js
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-content.js
- packages/article-skeleton/src/article-skeleton.js
- packages/interactive-wrapper/__tests__/android/__snapshots__/interactive-wrapper.test.js.snap
- packages/interactive-wrapper/__tests__/interactive-wrapper.native.js
- packages/interactive-wrapper/__tests__/ios/__snapshots__/interactive-wrapper.test.js.snap
- packages/interactive-wrapper/src/interactive-wrapper.js
- packages/pages/.jestlint
- packages/pages/__tests__/android/__snapshots__/pages.test.js.snap
- packages/pages/__tests__/ios/__snapshots__/pages.test.js.snap
- packages/pages/src/article/article-base.js
- packages/pages/src/article/article-prop-types.js
Introduced a couple of query params for interactive wrappers
dev: true / false   - Dictated by the native apps, and changed via the settings screen. This way, editorial can enable all the interactives and try new ones
environment: prod/qa  (more can be added as required) - This allows different whitelists for each environment
version     - Allows whitelisting depending on versions, ie we can enable puffs for versions above "4.7.1"
platform: ios/android  - Allows whitelisting per platform
> feat: interactive debug params android

- packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-standard/src/article-header/article-header.js
- packages/article-main-standard/src/article-main-standard.js
- packages/article-main-standard/src/article-meta/article-meta.js
- packages/article-main-standard/src/styles/article-header/shared.js
- packages/article-main-standard/src/styles/article-meta/shared.js
- packages/article-main-standard/src/styles/shared.js
- packages/styleguide/src/line-heights/mapping-base.js
This adds a max width for the article header on tablet, as well as increases the headline font size.
> feat: tablet layout for main standard article headers

- packages/article-in-depth/package.json
- packages/edition-slices/package.json
- packages/jest-configurator/package.json
- packages/lazy-load/package.json
- packages/markup-forest/package.json
- packages/provider-test-tools/package.json
- packages/provider/package.json
- packages/schema/package.json
- packages/svgs/package.json
- packages/tealium/package.json
- packages/watermark/package.json
Looks like we merged multiple PRs using the same dependencies, which caused a conflict with the version bump script. I did a quick `deps:fix` to tidy it up, this should fix master.
> chore: Fix versions due to multiple master merges

- packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-comment/__tests__/mocks.native.js
- packages/article-main-comment/__tests__/shared-with-style.native.js
- packages/article-main-comment/article-main-comment.showcase.js
- packages/article-main-comment/package.json
- packages/article-main-comment/src/article-header/article-header.js
- packages/article-main-comment/src/article-header/article-header.web.js
- packages/article-main-comment/src/styles/shared.js
Reduces the width of the header on tablets for main comment articles
> feat: main comment tablet header design

- packages/fixture-generator/.prettierignore
- packages/fixture-generator/README.md
- packages/fixture-generator/package.json
- packages/fixture-generator/tsconfig.json
Currently, fixture generator package can not be used inside Jest tests. This is due to the configuration of our jest, done by `jest-configurator` package. Jest configurator picks replaces source paths from "dist/.." to "src/.." in order to run the test code on non-transpiled code. 
The problem is, fixture generator is written in typescript, so it can't be run with the current jest-configurator. To avoid this and bypass jest-configurator logic, I've moved `dist` folder into a `build` folder for fixture generator.
> fix: Change ts build folder to build from dist

- packages/fixture-generator/src/__tests__/mock-markup.test.ts
- packages/fixture-generator/src/mock-article.ts
- packages/fixture-generator/src/mock-markup.ts
Added all the summaries (6 of them) to fixture generators.
Paired with: @nehasri89
> feat: Add all summaries to article fixtures

- packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list-states.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list.android.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-states.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list.ios.test.js.snap
- packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-magazine-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/__tests__/modal-shared.native.js
- packages/image/__tests__/shared.base.js
- packages/image/__tests__/shared.native.js
- packages/image/src/image.js
- packages/utils/__tests__/__snapshots__/screen.test.js.snap
- packages/utils/__tests__/screen.test.js
- packages/utils/src/screen.base.js
- packages/utils/src/screen.js
This PR uses `onLayout` on the image placeholder to decide which res image to request, meaning that we won't be requesting huge images in slices on tablet.
> feat: use image layout to decide which res image to request

- packages/article-in-depth/package.json
- packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-magazine-standard/src/article-header/article-header.js
- packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-comment/src/article-header/article-header.js
- packages/article-main-comment/src/styles/shared.js
In the internal sprint review, it showed that going to tablet width on `Article-Main-Comment` and `Article-Magazine-Standard` did not increase the headline font size.
This PR changes that.
> feat: Increase text size for tablet widths

- packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/shared-slices.base.js
- packages/edition-slices/__tests__/shared-tiles.base.js
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-slices.showcase.js
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/edition-slices.js
- packages/edition-slices/src/slices/index.js
- packages/edition-slices/src/slices/secondaryone/index.js
- packages/edition-slices/src/tiles/index.js
- packages/edition-slices/src/tiles/secondary/index.js
- packages/edition-slices/src/tiles/secondary/styles/index.js
- packages/fixture-generator/src/__tests__/mock-slice.test.ts
- packages/fixture-generator/src/index.ts
- packages/fixture-generator/src/mock-slice.ts
- Secondary One Slice | wireframe only | mobile only
- https://nidigitalsolutions.jira.com/browse/REPLAT-5139
- note summary is using `summary125` which should be `summary250` according to https://docs.google.com/spreadsheets/d/1NBC-dOAGcF1sgfrkfFH7uslKG7eEU4o3n3Og5T1WNC8/edit#gid=1321391883. All the summary text lengths will come in a forthcoming PR.
> feat: secondary one slice

- packages/article-in-depth/package.json
Aron realised utils are both a regular and a dev dependency in indepth package, which is causing a bug on lerna publish. Lerna is bumping only one of those dependencies, while leaving the other one. Removed dev dependency on utils from indepth to fix the issue.
> fix: Remove dev dependency on util

- packages/interactive-wrapper/__tests__/ios/__snapshots__/interactive-wrapper.test.js.snap
- packages/interactive-wrapper/src/interactive-wrapper.js
The interactive web wrapper was allowing scroll so if you tried to scroll the article from an interactive's position, it would bounce within its frame instead of allowing the whole article to scroll. Disabling the scroll in the web wrapper fixes the issue.
> fix: disable scroll in interactive web wrapper

- lib/fix-ios-storybook.sh
- package.json
The iOS Storybook app won't compile when running `yarn ios`. One of the reasons is that, if you open the project and try to compile, it is missing a config.h file.
This file gets properly created once running the configure script from the glog third party dependency. Created a script for going to the right directory and executing the configure script and added a call to that script in the `preios` step in the project's `package.json` file.
> fix: ios storybook app

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/shared-tiles.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/tiles/index.js
- packages/edition-slices/src/tiles/tile-i/index.js
- packages/edition-slices/src/tiles/tile-i/styles/index.js
- packages/edition-slices/src/tiles/tile-j/index.js
- packages/edition-slices/src/tiles/tile-j/styles/index.js
- packages/fixture-generator/src/__tests__/mock-slice.test.ts
- packages/fixture-generator/src/index.ts
- packages/fixture-generator/src/mock-slice.ts
- used as part of `LeadOneAndFourSlice`
> feat: Tile I and tile J

- ios/storybooknative.xcodeproj/project.pbxproj
Tiny one... This allows the iOS Storybook app to run on an iPad too.
> feat: enable ios storybook xcode project to be able to run on ipad too

- packages/image/README.md
- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/android/offline-image.android.test.js
- packages/image/__tests__/offline-image.android.js
- packages/image/__tests__/shared.native.js
- packages/image/src/image.js
- packages/image/src/lazy-loading-image.android.js
- packages/image/src/lazy-loading-image.js
New feature to support lazy loading from offline image bundle: (depends on native PR https://github.com/newsuk/nu-projectd-times-smartphone-android/pull/593)
- Added double Image views on top of each other (with a placeholder on the bottom)
- The bottom image has a "offline=true" query param, which is checked by the native app and uses the smapi tarball to fetch the image itself
- Top image does a network request and replaces the bottom one
This way, we can both preload with the low-res offline image and then get the high res from the network.
> feat: offline images lazy load

- packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/slices/secondarytwonopicandtwo/index.js
- packages/edition-slices/src/tiles/shared/tile-image.js
- packages/edition-slices/src/tiles/tile-g/index.js
- packages/edition-slices/src/tiles/tile-g/styles/index.js
- packages/edition-slices/src/tiles/tile-i/index.js
- packages/edition-slices/src/tiles/tile-j/index.js
- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/__tests__/shared.native.js
- packages/image/src/image-prop-types.js
- packages/image/src/image.js
- react native has a bug with border radius not being applied via style in Android API 24.
https://github.com/facebook/react-native/issues/8885
- This fixes by adding a `borderRadius` prop to the `Image`.
- Also adds missing `onPress` handler prop to `SecondaryTwoNoPicAndTwo` slice.
> fix: border radius bug and add onPress handler to SecondaryTwoNoPicAndTwo

- packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap
- packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap
- packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
- packages/article-topics/src/styles/index.android.js
- packages/article-topics/src/styles/index.js
- packages/article-topics/src/styles/index.web.js
- packages/article-topics/src/styles/shared.js
Because padding was used to correct the location of text within the article topic, it meant the topic ended up being significantly taller than it should be. This corrects for that by using relative positioning.
> fix: article topics size & layout

- packages/article-image/__tests__/android/__snapshots__/article-image-with-style.android.test.js.snap
- packages/article-image/__tests__/ios/__snapshots__/article-image-with-style.ios.test.js.snap
- packages/caption/__tests__/web/__snapshots__/caption.web.test.js.snap
- packages/caption/src/centred-caption.js
The centred caption didn't had any start/end paddings so when the text fitted well into one line, it would be to close to the edges. Added some horizontal padding to it.
> fix: add horizontal padding to the centred caption

- packages/utils/__tests__/__snapshots__/media-aspect-ratio.test.js.snap
- packages/utils/__tests__/add-missing-protocol.test.js
- packages/utils/__tests__/get-lead-asset.test.js
- packages/utils/__tests__/jest.config.js
- packages/utils/__tests__/media-aspect-ratio.test.js
- packages/utils/package.json
- packages/utils/src/get-lead-asset.js
Coverage for the utils package was ignored, however, it was being picked up in Coveralls and was dragging our score down. Rather than fix the coveralls issue, I thought I would just improve the coverage here.
> chore: Update utils coverage

- lib/.eslintrc.json
- lib/cli/cli.js
- lib/cli/cli.test.js
- lib/cli/edition-checker/README.md
- lib/cli/edition-checker/index.js
- lib/cli/edition-checker/src/EditionChecker.js
- lib/cli/edition-checker/src/EditionChecker.test.js
- lib/cli/edition-checker/src/Slack.js
- lib/cli/edition-checker/src/Slack.test.js
- lib/cli/edition-checker/src/SlackEditionIntegration.js
- lib/cli/edition-checker/src/SlackEditionIntegration.test.js
- lib/cli/edition-checker/src/api.js
- lib/cli/edition-checker/src/api.test.js
- lib/cli/edition-checker/src/main.js
- lib/cli/edition-checker/src/util.js
- lib/cli/edition-checker/src/util.test.js
- package.json
- yarn.lock
This adds a tool to the command line that allows you to crawl a specific edition or the past six days for issues in loading articles when using react. 
This requires being logged in to work, so you must set a `ACS_COOKIE` and `SACS_COOKIE` environment variable. We should probably set up credentials specifically for this tool in the long run.
This also requires the use of an internal Times API, and you must set the path to this with the `TIMES_API_ROOT` environment variable.
You can also configure the tool to post to Slack using a Slack incoming webhook with the `TIMES_SLACK_HOOK` and `TIMES_SLACK_USERNAME` environment variables. 
<s>I have not written tests for this tool, but it has been refactored and simplified significantly from its previous implementation to allow for this if deemed …
> feat: edition checker

- packages/test-utils/package.json
Two things:
1. This file uses Jest config in `package.json` rather than jest configurator. There is no platform specific code here so leaving this. This can be picked up again later.
2. I have ignored the file here from coverage as otherwise we would be really just testing jest mocking capability which seems unnecessary.
> chore: Test Utils Coverage

- packages/provider-queries/src/article-fragment.js
- packages/provider-queries/src/article.js
- packages/provider-queries/src/native-edition.js
- packages/provider-queries/src/provider-queries.js
- packages/provider-queries/src/section-fragment.js
- packages/provider-test-tools/src/index.js
- packages/provider-test-tools/src/native-edition.js
- packages/provider/.jestlint
- packages/provider/__tests__/__snapshots__/native-edition-provider.test.js.snap
- packages/provider/__tests__/native-edition-provider.test.js
- packages/utils/package.json
- packages/watermark/package.json
We were using the same fragment names within section fragment and article fragment, which causes an issue when we use both fragments within the same query. Prefixed section fragments with `section...` to avoid conflicts.
Addresses the pr comment by Christian: https://github.com/newsuk/times-components/pull/1685#discussion_r256454533
+ Also added a native-edition-query for test purposes only, to check how it'll work in the native app when we use both fragments
> fix: Fragment name conflicts

- packages/article-list/src/article-list.js
- packages/article-list/src/article-list.web.js
- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/styles/shared.js
- packages/image/src/image.js
- packages/utils/__tests__/screen.test.js
- packages/utils/src/screen.base.js
- packages/utils/src/screen.js
- packages/utils/src/screen.web.js
https://github.com/newsuk/times-components/pull/1704 introduced a regression where on devices smaller than 1180 pixels wide, the article would be wider than the screen width. This fixes that regression.
It also renames `normaliseWidth` to `normaliseWidthForAssetRequestCache`, and its arguments, to make its purpose more clear. 
It also removes the duplicated points-pixels conversation and normalisation as it is handled by TimesImage.
> fix: articles should not be larger than screen width

- packages/article-comments/__tests__/android/__snapshots__/shared-with-style.android.test.js.snap
- packages/article-comments/__tests__/ios/__snapshots__/shared-with-style.ios.test.js.snap
- packages/article-comments/src/styles/shared.js
- packages/related-articles/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/la2-with-style.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/oa2-with-style.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
- packages/related-articles/src/related-articles.js
- packages/slice-layout/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/la2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/oa2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/la2.base.js
- packages/slice-layout/slice-layout.showcase.js
- packages/slice-layout/src/templates/leadoneandtwo/index.js
- packages/slice-layout/src/templates/leadoneandtwo/index.web.js
- packages/slice-layout/src/templates/leadoneandtwo/proptypes.js
- packages/slice-layout/src/templates/opiniononeandtwo/index.js
- packages/slice-layout/src/templates/standard/index.js
Where there were no related articles, above comments would be missing a key line. To deal with optional topics and related articles, and keeping the complexity to a minimum, it made sense to remove the last keyline from related article slices and add this to the top of comments.
Additionally, within `leadoneandtwo`, there was a `withSeperators` prop that was never used. I removed this for simplicity.
===
> feat: Key line combinations for comments, related articles and topics

- packages/article-flag/src/article-flag.js
- packages/article-flag/src/style/shared.js
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-c/styles/index.js
- packages/edition-slices/src/tiles/tile-f/index.js
- packages/edition-slices/src/tiles/tile-f/styles/index.js
- packages/edition-slices/src/tiles/tile-j/styles/index.js
- packages/edition-slices/src/tiles/tile-l/styles/index.js
- Part 3 of 3 of https://nidigitalsolutions.jira.com/browse/REPLAT-5478
- minor tweaks and removal of marginRight when only 1 flag present, which was causing a layout issue on `Tile I` as it is centred.
> fix: Minor slice tweaks and article flags padding removal when only 1 flag

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/shared-tablet-slices.base.js
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/src/slices/secondaryfour/index.js
- packages/slice-layout/__tests__/android/__snapshots__/sd4-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/sd4.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/sd4-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/sd4.ios.test.js.snap
- packages/slice-layout/__tests__/sd4.base.js
- packages/slice-layout/__tests__/web/__snapshots__/sd4-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/sd4.web.test.js.snap
- packages/slice-layout/src/templates/secondaryfour/index.js
- packages/slice-layout/src/templates/secondaryfour/proptypes.js
- packages/slice-layout/src/templates/secondaryfour/styles.js
Secondary 4 tablet layout
- Reuses the same tile
- Passes breakpoint to slice-layout, and lays those slices in a col layout
> feat: secondary 4 tablet

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/shared-tiles.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/tiles/index.js
- packages/edition-slices/src/tiles/shared/tile-summary.js
- packages/edition-slices/src/tiles/tile-h/index.js
- packages/edition-slices/src/tiles/tile-h/styles/index.js
- packages/fixture-generator/src/mock-image.ts
- packages/fixture-generator/src/mock-markup.ts
- packages/provider/__tests__/__snapshots__/native-edition-provider.test.js.snap
Tile H to support `Supporting 1 and Columnist`. If the left-hand column exceeds the length of the image, the image will bottom align with no padding as in the designs.
https://nidigitalsolutions.jira.com/browse/REPLAT-5144
> feat: Edition Slice Tile - Tile H

- packages/utils/src/text-layout/styles/index.js
fixes ios dropcaps sometimes not rendering when swiping articles
> fix: drop caps not always rendering on ios

- packages/edition-slices/edition-slices.showcase.js
- minor update to slice showcase title
> fix: lead 1 and 1 slice title in storybook

- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-body/article-body.web.js
- packages/markup-forest/package.json
- packages/pull-quote/README.md
- packages/pull-quote/__tests__/android/__snapshots__/pull-quotes-with-style.android.test.js.snap
- packages/pull-quote/__tests__/ios/__snapshots__/pull-quotes-with-style.ios.test.js.snap
- packages/pull-quote/__tests__/shared-with-style.base.js
- packages/pull-quote/__tests__/web/__snapshots__/pull-quotes-with-style.test.js.snap
- packages/pull-quote/__tests__/web/__snapshots__/themes-with-style.web.test.js.snap
- packages/pull-quote/pull-quote.showcase.js
- packages/pull-quote/src/pull-quote-prop-types.js
- packages/pull-quote/src/pull-quote.base.js
- packages/pull-quote/src/styles/shared.js
- packages/slice-layout/package.json
- packages/svgs/package.json
- packages/tealium/package.json
- packages/tracking/package.json
- packages/utils/package.json
- packages/watermark/package.json
The caption on the pull quote (the author's name) should be a static grey colour, not depending on the section colour.
> fix: pull quotes captions should not change colour based on section

- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/src/styles/article-body/shared.js
With a `maxWidth`, the interactives were not displaying. This was down to the webview needing specific widths (I believe)
Please note: Poor screenshots!
> fix: Interactives now display on tablets

- packages/article-skeleton/src/article-tracking-context.js
Article page is crashing when topics are null. (which happens when there is an api error). Added a default value (lodash only defaults on `undefined`, not `null`)
https://nidigitalsolutions.jira.com/browse/REPLAT-5317
> fix: Add a default value on null for topics

- packages/article-list/__tests__/android/utils.android.test.js
- packages/article-list/__tests__/ios/utils.ios.test.js
- packages/article-list/__tests__/shared-utils.js
- packages/article-list/__tests__/web/utils.web.test.js
- packages/article-list/src/utils/index-base.js
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/android/shared-components.test.js
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/shared-components.test.js
- packages/edition-slices/__tests__/shared-components.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/shared-components.test.js
- packages/edition-slices/src/tiles/shared/tile-summary.js
https://nidigitalsolutions.jira.com/browse/REPLAT-5646
We were using the longer headline. This PR rectifies this.
It also adds a test for these as well as setting up testing for the shared components of `Tiles` and utils of `ArticleList`. These areas could use some more tests following this PR.
> feat: Short Headline to be the primary headline for List Pages and Slices

- packages/edition-slices/__tests__/android/__snapshots__/roundel-image-tiles.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/android/roundel-image-tiles.test.js
- packages/edition-slices/__tests__/ios/__snapshots__/roundel-image-tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/roundel-image-tiles.test.js
- packages/edition-slices/__tests__/shared-roundel-image-tiles.base.js
- packages/edition-slices/__tests__/shared-roundel-image-tiles.native.js
- packages/edition-slices/__tests__/shared-roundel-image-tiles.web.js
- packages/edition-slices/__tests__/web/__snapshots__/roundel-image-tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/roundel-image-tiles.test.js
- packages/edition-slices/src/tiles/tile-g/index.js
- packages/edition-slices/src/tiles/tile-p/index.js
https://nidigitalsolutions.jira.com/browse/REPLAT-5625
The issue was the tile was using the screen width to calculate the border-radius because the image was a percentage of the width, not a set value. There is no such thing as a proportional border-radius in React Native.
The Tile won't always fill the screen so this is wrong, so we now calculate the size of the container with which the image sits in. Additionally, the calculation was wrong as well assuming `25%` instead of `30%` so I have made this more explicit.
> fix: Roundel images working across ios and android

- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/src/modal-image.js
- packages/image/src/styles/shared.js
Using RN's `SafeAreaView`, we can ensure the modal exit button is in the correct place across all devices.
> fix: modal image close button should be in a safe area

- packages/styleguide/src/theme/theme-factory.js
https://nidigitalsolutions.jira.com/browse/REPLAT-5452.
Pull quotes, Dropcap and Key Facts on an In-Depth template require no change of colours. The feedback from design that the contrasting colours to the background colour of the header were too much. This, therefore, covers further components being added. As a result, its a simple change for in-depth templates to not have access to other section colours.
> feat: Removing section colours for indepth template

- packages/jest-configurator/package.json
- packages/lazy-load/package.json
- packages/markup-forest/package.json
- packages/provider-test-tools/package.json
- packages/provider/package.json
- packages/schema/package.json
- packages/slice-layout/package.json
- packages/slice-layout/slice-layout.showcase.js
- packages/svgs/package.json
- packages/tealium/package.json
- packages/utils/package.json
- packages/watermark/package.json
With the recent responsive slice work, there wasn't a way in storybook to test the slice layouts at different breakpoints.
> chore: Adding knobs to slice layout stories

- packages/ad/src/utils/sizes.js
Within the ad package, you can add more sizes to a particular slot. This has been done now to support billboard and leaderboard.
Please note: billboard seems to give inconsistent results and often shows a leaderboard. This might be due to ad inventory? I would ask that someone with better knowledge on ads can advise?
> feat: Additional ad sizes for larger widths

- packages/gestures/src/gestures.js
- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/modal-image.showcase.js
- packages/image/src/modal-image.js
- packages/image/src/styles/shared.js
I've noticed pinch to zoom for modal images is buggy on iOS – seems to be an issue with PanResponder support within Modals. There's a (closed) issue on react native discussing this which has a workaround. https://github.com/facebook/react-native/issues/14295
Also used absolute positioning for modal elements (caption, x button) in order to improve the vertical centring of the image. Sadly, due to SafeAreaView, we can't perfectly centre (as demonstrated with the below image)
> fix: pinch to zoom on iOS & alignment

- packages/edition-slices/edition-slices.showcase.js
- update tile name separators in storybook to be consistent
> chore: update tile name separators in storybook

- packages/utils/src/text-layout/styles/index.ios.js
In some cases, it seems there was an extra line being inserted during drop cap layout calculation on iOS, as seen below. 
I spent quite a long time thinking this was an issue in the layout engine, but eventually ruled that out when I noticed that the height of one of the words going into it was double what it needed to be. When I made the layout text elements appear, I noticed one of the words was wrapping inappropriately, which was throwing off the calculations in the layout engine. 
It seems that the defined width on the iOS container, which I believe was added to cancel an iOS optimisation from preventing `onLayout` from being called, was causing React Native to intermittently attempt to wrap certain words before it gave up. Removing this defined width prevents the inappropriate …
> fix: inappropriate text wrapping during layout calculation

- packages/article-image/__tests__/android/__snapshots__/article-image-with-style.android.test.js.snap
- packages/article-image/__tests__/ios/__snapshots__/article-image-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/styleguide/src/breakpoints/index.js
Before:
After:
Update the max width so that the tiny gutters currently present on the 11" iPad are no longer present.
> fix: update max width so that gutters do not show on landscape iPad Pro 11"

- packages/article-in-depth/__tests__/android/__snapshots__/article-internal-components.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article-internal-components.ios.test.js.snap
- packages/article-in-depth/__tests__/mocks.native.js
- packages/article-in-depth/__tests__/mocks.web.js
- packages/article-in-depth/__tests__/shared-internal-components.base.js
- packages/article-in-depth/__tests__/web/__snapshots__/article-internal-components.web.test.js.snap
- packages/article-in-depth/src/article-label/article-label-prop-types.js
- packages/article-in-depth/src/article-label/article-label.js
- packages/article-magazine-comment/__tests__/android/__snapshots__/article-internal-components.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article-internal-components.ios.test.js.snap
- packages/article-magazine-comment/__tests__/mocks.native.js
- packages/article-magazine-comment/__tests__/mocks.web.js
- packages/article-magazine-comment/__tests__/shared-internal-components.base.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-internal-components.web.test.js.snap
- packages/article-magazine-standard/__tests__/android/__snapshots__/article-internal-components.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article-internal-components.ios.test.js.snap
- packages/article-magazine-standard/__tests__/mocks.native.js
- packages/article-magazine-standard/__tests__/mocks.web.js
- packages/article-magazine-standard/__tests__/shared-internal-components.base.js
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-internal-components.web.test.js.snap
- packages/article-main-comment/__tests__/android/__snapshots__/article-internal-components.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-internal-components.ios.test.js.snap
- packages/article-main-comment/__tests__/mocks.native.js
- packages/article-main-comment/__tests__/mocks.web.js
- packages/article-main-comment/__tests__/shared-internal-components.base.js
- packages/article-main-comment/__tests__/web/__snapshots__/article-internal-components.web.test.js.snap
- packages/slice-layout/package.json
Non-default templates are not covering everything for their article labels.
Ideally with the Design Review PR this should increase the coverage by a fair bit.
> chore: Improve Article Label coverage in templates

- packages/pages/__tests__/shared.base.js
- packages/pages/src/article/article-base.js
- packages/pages/src/article/filter-interactives.js
Part of: https://nidigitalsolutions.jira.com/browse/REPLAT-5579
We no longer the feature flag to disable interactives, as we have the versioned whitelisting in place.
> feat: Remove showInteractives flag and delete logic to remove flag

- packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/slices/puzzle/index.js
- packages/edition-slices/src/slices/puzzle/styles.js
- packages/edition-slices/src/tiles/tile-ak/styles/index.js
Fixing and issue with puzzle tiles not being rendered correctly on mobile.
`Before:`
`After:`
> fix: puzzle tiles widths set correctly

- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-ag/index.js
- packages/edition-slices/src/tiles/tile-m/index.js
Article id and url was missing on leaders tiles, breaking the on press events.
> fix: leader tiles on press props

- packages/edition-slices/__tests__/shared-components.base.js
- packages/edition-slices/src/tiles/tile-a/index.js
- packages/edition-slices/src/tiles/tile-aa/index.js
- packages/edition-slices/src/tiles/tile-ab/index.js
- packages/edition-slices/src/tiles/tile-ac/index.js
- packages/edition-slices/src/tiles/tile-ad/index.js
- packages/edition-slices/src/tiles/tile-ah/index.js
- packages/edition-slices/src/tiles/tile-ai/index.js
- packages/edition-slices/src/tiles/tile-c/index.js
- packages/edition-slices/src/tiles/tile-d/index.js
- packages/edition-slices/src/tiles/tile-e/index.js
- packages/edition-slices/src/tiles/tile-g/index.js
- packages/edition-slices/src/tiles/tile-h/index.js
- packages/edition-slices/src/tiles/tile-i/index.js
- packages/edition-slices/src/tiles/tile-j/index.js
- packages/edition-slices/src/tiles/tile-n/index.js
- packages/edition-slices/src/tiles/tile-p/index.js
- packages/edition-slices/src/tiles/tile-q/index.js
- packages/edition-slices/src/tiles/tile-r/index.js
- packages/edition-slices/src/tiles/tile-t/index.js
- packages/edition-slices/src/tiles/tile-u/index.js
- packages/edition-slices/src/tiles/tile-v/index.js
- packages/edition-slices/src/tiles/tile-w/index.js
- packages/edition-slices/src/tiles/tile-z/index.js
- packages/fixture-generator/src/mock-article.ts
- packages/provider-queries/src/section-fragment.js
- packages/provider-test-tools/fixtures/article.json
- packages/provider/__tests__/__snapshots__/edition-provider.test.js.snap
- packages/provider/__tests__/__snapshots__/native-edition-provider.test.js.snap
The order or precedence as discussed with backed team is 
tile.leadAsset || tile.article.listingAsset || tile.article.leadAsset
> fix: Use listing asset override

- packages/edition-slices/src/slices/commentleadandcartoon/index.js
- packages/edition-slices/src/slices/dailyregisterleadfour/index.js
- packages/edition-slices/src/slices/leaders/index.js
- packages/edition-slices/src/slices/leadoneandfour/index.js
- packages/edition-slices/src/slices/leadoneandone/index.js
- packages/edition-slices/src/slices/leadonefullwidth/index.js
- packages/edition-slices/src/slices/leadtwonopicandtwo/index.js
- packages/edition-slices/src/slices/listtwoandsixnopic/index.js
- packages/edition-slices/src/slices/puzzle/index.js
- packages/edition-slices/src/slices/secondaryfour/index.js
- packages/edition-slices/src/slices/secondaryone/index.js
- packages/edition-slices/src/slices/secondaryoneandcolumnist/index.js
- packages/edition-slices/src/slices/secondaryoneandfour/index.js
- packages/edition-slices/src/slices/secondarytwoandtwo/index.js
- packages/edition-slices/src/slices/secondarytwonopicandtwo/index.js
- packages/edition-slices/src/tiles/shared/tile-summary.js
- packages/section/__tests__/android/__snapshots__/section.test.js.snap
- packages/section/__tests__/ios/__snapshots__/section.test.js.snap
- packages/section/src/section.js
Round 1 of section perf improvements (more coming soon, in a separate PR):
- Changed windowSize and initialNumToRender on section FlatList. Defaults are 20 items, which is huge for our use case.
- Got rid of inline function declarations in edition-slices and in tile-summary. However, we still got a million more to inline function declarations in slice-layout, but that'll be the next PR
> feat: section perf improvements

- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/__tests__/shared.base.js
- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/src/image.js
- packages/video/__tests__/android/__snapshots__/video.android.test.js.snap
- packages/video/__tests__/ios/__snapshots__/video.ios.test.js.snap
- packages/video/src/video.js
Native apps are crashing due to empty aspect ratio on certain images.
- Handled empty aspect ratio on images
- Added aspect ratio to video cover images
> fix: Handle null aspect ratio case in images

- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/src/styles/index.android.js
Very quick PR to remove the android specific margins around the x button in the modals. This should have been done in previous PRs.
> fix: remove android specific modal x margin

- android/app/src/main/java/com/storybooknative/stubs/SectionEvents.kt
- android/app/src/main/java/com/storybooknative/stubs/StorybookStubPackage.kt
- packages/pages/pages.showcase.native.js
- packages/pages/section-showcase-helper.js
- packages/pages/src/section/section.js
This PR will simplify save star development by adding stubs to storybook
- Added SectionEvents to android storybook app
- Fixed the storybook on pages.
- Changed the way we update saved article context. Now, we update save status in a synchronous manner, and undo it if native app rejects the promise. This removed the lag on status updates caused by the async nature of NativeModules
> feat: save star storybook

- packages/edition-slices/__tests__/shared-components.base.js
- packages/edition-slices/src/tiles/shared/tile-star.js
- packages/star-button/__tests__/android/__snapshots__/star-button.android.test.js.snap
- packages/star-button/__tests__/ios/__snapshots__/star-button.ios.test.js.snap
- packages/star-button/__tests__/shared.base.js
- packages/star-button/__tests__/web/__snapshots__/star-button.web.test.js.snap
- packages/star-button/src/star-button.js
- packages/star-button/src/styles/index.js
- packages/styleguide/src/colours/star.js
- packages/styleguide/src/styleguide.js
Small PR for fixing full with ripple effect of the star button on android:
> fix: ripple effect is not full width any more

- packages/jest-configurator/package.json
- packages/markup-forest/package.json
- packages/slice-layout/package.json
- packages/ssr/src/lib/run-server.js
- packages/svgs/package.json
- packages/watermark/package.json
SSR is broken because article queries are now too large to work over GET requests. There's no real benefit to using GET requests so lets remove that and use POST requests, which is the default for apollo.
> fix: use post requests for graphql queries

- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-lead-asset/__tests__/web/__snapshots__/article-lead-asset.test.js.snap
- packages/article-lead-asset/src/article-lead-asset.web.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/provider-test-tools/fixtures/article.json
- packages/provider-test-tools/src/fixtures/byline-with-link.json
- packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
- packages/schema/package.json
- packages/tealium/package.json
- packages/utils/package.json
The article showcase is currently completely broken due to incorrect byline fixtures. The lead asset was also missing as aspectRatio was not passed through. 
This PR fixes both.
> fix: article showcase & article lead assets on web

- packages/ssr/src/component/article.js
SSR wasn't using the theme factory to pass theme information into the context. This caused the confusing issue where articles would appear correctly themed in the storybook but not in SSR. This PR fixes that issue by using the same theme factory that the storybook uses.
> fix: setup theme correctly in SSR

- packages/pages/__tests__/android/section-update.test.js
- packages/pages/__tests__/ios/section-update.test.js
- packages/pages/__tests__/mocks.js
- packages/pages/__tests__/section-update.js
- packages/pages/src/section/section.js
This PR enables Section page data to be updated without a need to re-create the view. (https://nidigitalsolutions.jira.com/browse/REPLAT-6100)
To use this feature, native apps needs to implement `getSectionData` method in `SectionEvents` and resolve the promise with a section data (as a raw json string). 
```
fun getSectionData(sectionId: String, promise: Promise) {
...
}
```
Then, whenever the native app send an event named `updateSectionData`, components will use `getSectionData` bridge to ask for the updated section data and refresh its view. 
- Section prop is moved to state to enable reloads
- Subscribes and unsubscribes added to listen to `updateSectionData` events through DeviceEventEmitter
- Ask for section data when event is fired and update the state if it's successfully …
> feat: Update section data on native event

- packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
- packages/save-and-share-bar/src/bar-item.js
- packages/save-and-share-bar/src/save-and-share-bar.js
little fix for the share and save bar
> fix: save and share breaks mobile storybook

- packages/mock-tpa-server/src/default-mock-types.js
TPA added TinyUnit and UnitInterval as new types to their schema. Fixing our mocks so CI tests can pass again
> fix: Add TinyUnit and UnitInterval to mock types

- TimesComponents.podspec
This PR adds a new podspec TimesComponent.podspec to ease integration between react native components and native IOS app.
Please note the native app uses a copy of an existing `TimesReactIOS.podspec` present in this repo and this PR does not modify or delete that at the moment. A separate PR may be created in the future to delete old artifacts.
This PR is not complete set of changes for a better integration between RN and native app. Further changes would be required in bitrise build process to allow this podspec to access archived minified js bundle and assets (The same would be archived in this repo itself and later may move to a separate repo).
> Added new Podspec for integration with IOS native app

- packages/article-skeleton/__tests__/web/head.web.test.js
- packages/article-skeleton/src/head.web.js
- packages/article/showcase-helper.js
- packages/provider-test-tools/fixtures/article.json
Fixing the fixtures that render the article with template choice showcase. This is a bit of hack because I couldn't figure out how to make the mock provider understand the `descriptionMarkup` summary alias in the article web query.
> fix: temporary fix for article showcase

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-ah/styles/index.js
- packages/edition-slices/src/tiles/tile-w/index.js
- packages/fixture-generator/src/types.ts
- packages/slice-layout/__tests__/android/__snapshots__/l1and1-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l1and1-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l1and1-with-style.web.test.js.snap
- packages/slice-layout/src/templates/leadoneandone/styles.js
- Fixes various issue with lead asset / summary text sizes (https://nidigitalsolutions.jira.com/browse/REPLAT-6298)
- ~Updates types.ts as it was out of date~
- Other issues raised in the ticket should be solved once ios app has the latest queries updated (missing `bylines` and `strapline` field in some slices
> fix: Issues with lead asset size

- README.md
There is a `yarn` postinstall script that gets the requried fonts using `fontforge`, this means you need to have `fontforge` installed before running `yarn`.
I have updated the `README` to reflect this.
> chore: Update README to install fontforge before yarn installing

- README.md
- packages/ssr/src/client/topic.js
- packages/ssr/src/lib/run-client.js
- packages/ssr/src/server/topic.js
This PR adds support for passing a header to TPA when querying topics on SSR + client side. This header toggles the data source in TPA from Elastisearch to RDS, and is triggered by the presence of a URL query parameter `?useNewTopicDataSource=true` beiong provided on render.
The associated render PR is here: https://github.com/newsuk/cps-content-render/pull/2714
> feat: Topic list feature flag

- android-app/package.json
Babel 7 broke the android publish script, as it no longer generates a source map. Updated to scripts to fix this issue
> chore: Fix android publish script

- ios/storybooknative/AppDelegate.m
Fixed ios storybook entry file to `index.storybook.js`
> chore: Fix storybook entry file

- android-app/index.android.js
- ios-app/index.ios.js
- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/src/utils/appendToURL.js
We had a `hack` to fix react-native's URL, which seems to be broken after the babel 7 bump.
Removed the usage of URL on native until this issue is properly fixed on react-native: https://github.com/facebook/react-native/issues/16434
> fix: Image resize not being sent

- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
Fixes image display on phone, they were all showing as primary before.
> feat: fix image display on phone layout

- packages/article-image/__tests__/web/__snapshots__/article-image-with-style.web.test.js.snap
- packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
- packages/card/__tests__/web/__snapshots__/card-render-style.test.js.snap
- packages/card/__tests__/web/__snapshots__/card-reverse-style.test.js.snap
- packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-aj/index.js
- packages/edition-slices/src/tiles/tile-ak/index.js
- packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
- packages/image/__tests__/shared.native.js
- packages/image/__tests__/shared.web.js
- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/image.showcase.js
- packages/image/src/image-prop-types.js
- packages/image/src/image.js
- packages/image/src/image.web.js
This hides the placeholder during load on puzzle slices so that you don't need an oddly-sized placeholder (as the image is smaller than the slice)
> fix: hide placeholders for puzzle slices

- packages/tealium/src/tealium-send-scheduler.js
As part of the lighthouse report recommendation, just want to try out loading tealium script with defer instead of async
> feat: Changed tealium script tag from async to defer

- android-app/.eslintignore
- android-app/metro.config.js
- android-app/package.json
- ios-app/.eslintignore
- ios-app/metro.config.js
- ios-app/package.json
- storybook-native/.eslintignore
- storybook-native/metro.config.js
- storybook-native/package.json
This PR fixes android:app ios:app and storybook-native bundlers so they pick up dev changes instead of transpiled ones.
> chore: Fix dev bundlers via metro config

- packages/save-and-share-bar/save-and-share-bar.showcase.js
- packages/save-star-web/__tests__/shared.base.js
- packages/save-star-web/src/save-star-web.js
This PR fixes a bug in Save Star wherein the incorrect api methods were getting invoked on save, unsave
> fix: api calls for save unsave

- packages/image/src/image.js
- packages/section/src/section.js
- packages/styleguide/src/animations/index.js
Animated values use timers internally which can cause javascript objects to be kept in the heap when unmounting a react app.
> Stop animated values as well as timers onunmount as it can leak memory

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-paragraph/__tests__/web/__snapshots__/article-paragraph-with-style.web.test.js.snap
- packages/article-paragraph/__tests__/web/__snapshots__/themes-with-style.web.test.js.snap
- packages/article-paragraph/article-paragraph.showcase.web.js
- packages/article-paragraph/fixtures/drop-cap-short-text-showcase.json
- packages/article-paragraph/package.json
- packages/article-paragraph/src/article-paragraph.web.js
- packages/article-paragraph/src/drop-cap.web.js
- packages/article-paragraph/src/styles/responsive.web.js
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
This fixes drop cap positioning on web so that
- The drop cap is always the height of 3 regular sized lines across different fonts
- The drop cap position is consistent across browsers
- Two line paragraphs with a drop cap no longer break the position of the next paragraph
**TimesModern-Regular**
**Flama-Bold**
**Tiempos-Headline-Bold**
**CenturyGothic-Bold**
**Two line paragraphs**
> fix: make drop caps consistent across browsers + fix two line paras

- packages/message-bar/__tests__/android/__snapshots__/message-bar.test.js.snap
- packages/message-bar/__tests__/ios/__snapshots__/message-bar.test.js.snap
- packages/message-bar/__tests__/web/__snapshots__/message-bar.test.js.snap
- packages/message-bar/src/message-manager.js
The absolute positioning was not working on android when put inside a fragment. Replaced it with a View to fix flickering issue on cartoons
Before: 
After:
> fix: Change message bar layout to fix flicker issue

- TimesComponents.podspec
- lib/publish-ios-assets.sh
- package.json
Why is this needed?
-------------------
- Adds a new publish script for ios assets. The git repo is pointing to a temporary repo right now and will be updated to the right path once the new becomes available.
-  Adds the script to package.json
> REPLAT-6157: Added a new publish script for ios assets

- TimesComponents.podspec
Missed out resources path change in the previous PR.
> Updated times podsspec with path change for assets

- packages/depend/src/cli-parser.js
This PR adds the link to the help command output.
It looks like this
> docs: Add link to readme.md for depend help

- packages/markup/__tests__/android/__snapshots__/markup.android.test.js.snap
- packages/markup/__tests__/ios/__snapshots__/markup.ios.test.js.snap
- packages/markup/__tests__/shared.base.js
- packages/markup/__tests__/web/__snapshots__/markup.web.test.js.snap
- packages/markup/src/markup-flow.js
TextLayout implementation was causing a crash on subscript fallbacks (whenever the subscript markup is used with a character without an unicode subscript). Did a quick fix on this and added a test case
> Fix: Subscript/Superscript markup fallback scenario

- packages/interactive-wrapper/__tests__/android/__snapshots__/interactive-wrapper.test.js.snap
- packages/interactive-wrapper/__tests__/ios/__snapshots__/interactive-wrapper.test.js.snap
- packages/interactive-wrapper/src/interactive-wrapper.js
We've noticed an issue with the latest webview implementation, where some interactives were not being rendered. This is happening due to the initial height of the interactives being 0. I've changed the initial height to 1 to work around this problem
> Fix: Set initial interactives wrapper height to 1

- packages/article-skeleton/package.json
- packages/article-skeleton/src/article-skeleton.web.js
- packages/article/showcase-helper.js
- packages/article/src/article.js
- packages/message-bar/README.md
- packages/message-bar/__tests__/android/__snapshots__/message-bar.test.js.snap
- packages/message-bar/__tests__/ios/__snapshots__/message-bar.test.js.snap
- packages/message-bar/__tests__/message-bar.base.js
- packages/message-bar/__tests__/web/__snapshots__/message-bar.test.js.snap
- packages/message-bar/message-bar.showcase.js
- packages/message-bar/package.json
- packages/message-bar/src/message-bar.js
- packages/message-bar/src/message-manager.js
- packages/message-bar/src/styles/index.android.js
- packages/message-bar/src/styles/index.js
- packages/message-bar/src/styles/index.web.js
- packages/message-bar/src/styles/shared.js
- packages/save-and-share-bar/package.json
- packages/save-and-share-bar/save-and-share-bar.showcase.js
- packages/styleguide/src/colours/functional.js
[Jira link](https://nidigitalsolutions.jira.com/browse/REPLAT-6594)
Message bar consumed by save and share bar and trigger with click on copy link.
Fixed the component to unmount after 3 seconds.
Styling for all breakpoints applied.
Huge:
Wide:
Medium:
Small:
> fix: message bar consumed and styled in web

- packages/sticky/sticky.showcase.web.css
- packages/sticky/sticky.showcase.web.js
Prevents the save/share bar going blue when sticky in the storybook as it currently does as shown below.
> fix: prevent sticky story styles clashing with other stories

- packages/context/__tests__/android/__snapshots__/theme.test.js.snap
- packages/context/__tests__/ios/__snapshots__/theme.test.js.snap
- packages/context/__tests__/web/__snapshots__/theme.test.js.snap
- packages/context/src/defaults/index.js
- packages/ssr/src/component/article.js
**Currently**, only field 'isLoggedIn' is passed from SSR to packages consumers : 
```
user: {	   
isLoggedIn: userState.isLoggedIn	
}
```
**Fix**: Pass full user state data from SSR to consumers.
Format: 
```
userState : {
isLoggedIn: boolean
isMetered: boolean
isMeteredExpired: boolean
isShared: boolean
registrationTypes: string
}
```
> fix: pass whole userState object by SSR to the TC consumers

- packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-lead-asset/__tests__/android/__snapshots__/article-lead-asset.test.js.snap
- packages/article-lead-asset/__tests__/ios/__snapshots__/article-lead-asset.test.js.snap
- packages/article-lead-asset/src/article-lead-asset.js
- packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-magazine-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-magazine-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/src/modal-image/modal-image.js
Implement Article Perf - Lead Asset not waiting for onLayout.
Story: https://nidigitalsolutions.jira.com/browse/REPLAT-6648
In this PR we are passing the width from the `article-lead-asset` component down to the image as a `hightResSize` prop. This way the `image` component won't use the onLayout to calculate the size it's being rendered at, which will lead to faster request for the image.
> feat: implement lead asset to use the passed width

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-in-depth/src/article-in-depth.web.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/src/article-magazine-comment.web.js
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/src/article-magazine-standard.web.js
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/src/article-main-comment.web.js
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/src/article-main-standard.web.js
- packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
- packages/article-skeleton/__tests__/web/head.web.test.js
- packages/article-skeleton/src/article-skeleton.web.js
- packages/article-skeleton/src/head.web.js
- packages/article/src/article.js
- packages/ssr/src/component/article.js
- packages/ssr/src/lib/run-server.js
- packages/ssr/src/server/article.js
Json LD is removed from render and added to TC. This is done, because we need to add some data from TPA to json LD in order to improve the SEO.
Render PR: https://github.com/newsuk/cps-content-render/pull/2759
> Feat Add jsonLD to Helmet on article pages

- ios/storybooknative.xcodeproj/project.pbxproj
- ios/storybooknative/Info.plist
It seems Tunca's upgrade to and subsequent reversion of react native resulted in the loss of font references in the iOS storybook xcode project. This PR restores those references and in doing so fixes iOS storybook.
> fix: ios storybook fonts issue 

- packages/ad/__tests__/android/__snapshots__/ad-with-style.android.test.js.snap
- packages/ad/__tests__/ios/__snapshots__/ad-with-style.ios.test.js.snap
- packages/ad/src/dom-context.js
This updates the properties on the webview component has the new one has different defaults to the old one.
> fix: make unruly ads work correctly in the new webview component

- ios-app/README.md
Update ios-app readme with up to date information about running latest times-components on ios app. 
Tested and working
> chore: update ios-app readme

- packages/image/src/image.web.js
Sometimes an image has already loaded from isomorphic rendering before react starts rehydrating. This is a small fix that also checks the complete property on the image and calls the correct handler on component load.
> fix: handle the case where an image is already loaded

- packages/article-byline/__tests__/android/__snapshots__/article-byline-with-links-style.android.test.js.snap
- packages/article-byline/__tests__/ios/__snapshots__/article-byline-with-links-style.ios.test.js.snap
- packages/article-byline/__tests__/web/__snapshots__/article-byline-with-links-style.web.test.js.snap
- packages/article-byline/__tests__/web/__snapshots__/article-byline-with-links.web.test.js.snap
- packages/article-byline/src/styles/index.android.js
- packages/article-byline/src/styles/shared.js
- Have set the property `textDecorationLine` to `none` to remove the underline for author bylines
- https://nidigitalsolutions.jira.com/browse/REPLAT-6826
Before
After
> Fix: remove underline from byline

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/shared-tiles.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-w/index.js
https://nidigitalsolutions.jira.com/browse/REPLAT-6747
Remove the teaser text on Secondary 1 Slice on 768 tablet breakpoint
between 768px and 1024px:
wider than 1024px:
> fix: remove teaser text from secondary one slice on 768px breakpoint

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/shared-tiles.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-slices.showcase.js
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/slices/listtwoandsixnopic/index.js
- packages/edition-slices/src/tiles/index.js
- packages/edition-slices/src/tiles/tile-aq/index.js
- packages/edition-slices/src/tiles/tile-aq/styles/index.js
[Jira story](https://nidigitalsolutions.jira.com/browse/REPLAT-6745)
List 2 and 6 no pic
1. Teaser added for medium breakpoint
2. New tile created and [doc](https://docs.google.com/spreadsheets/d/1NBC-dOAGcF1sgfrkfFH7uslKG7eEU4o3n3Og5T1WNC8/edit#gid=255055858) updated.
3. Font size of list-2 headlines updated according to design.
More info [here](https://docs.google.com/spreadsheets/d/1NBC-dOAGcF1sgfrkfFH7uslKG7eEU4o3n3Og5T1WNC8/edit#gid=2068129030) - Samsung Tablet sheet - row 12
> fix: REPLAT-6745 list-2-and-6-no-pic tablet teaser

- package.json
- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
- packages/article-skeleton/src/head.web.js
jira: https://nidigitalsolutions.jira.com/browse/REPLAT-6693
- use smaller lead asset image for social media meta tag
> fix: replat 6693 twitter metadata

- packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/slices/dailyregisterleadfour/index.js
- packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
- packages/edition-slices/src/tiles/tile-w/styles/index.js
[Jira](https://nidigitalsolutions.jira.com/browse/REPLAT-6745). Fixes for tablet rows 9, 10, 11
1. Comment leader padding bottom added:
2. Comment Universal Register margin colour updated:
3. Comment Universal Register padding added - masthead and header:
> fix: REPLAT-6745 dailyRegisterLeadFour and secondaryOne styling updates

- packages/article-in-depth/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/src/article-in-depth.js
- packages/article-in-depth/src/styles/shared.js
- packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/src/article-meta/article-meta.js
- packages/article-main-comment/src/styles/shared.js
- packages/article-main-standard/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/src/article-meta/article-meta-base.js
JIRA Story : https://nidigitalsolutions.jira.com/browse/REPLAT-6102
- In depth template - remove padding below image if there is no caption and credit (this fixes the uneven spacing issue on cartoons) 
**Before**
**After**
- Main standard template - remove extra keyline between byline and pub info on article main standard template
**Before**
**After**
- Default, comment and In depth template (which have the pub/ byline between 2 keylines - padding looks wrong and we need to allow for a missing byline. 
If both byline and pub info:
-padding above and below 10px
-padding between 10px
If pub info only:
-padding above and below 10px
**Before**
**After**
- pub info only
- both byline and pub info
> feat: article design review amends REPLAT-6102 

- packages/provider-queries/src/section-fragment.js
[Jira story](https://nidigitalsolutions.jira.com/browse/REPLAT-6745)
Summary and teaser added lead1 and lead2 of TwoPicAndSixNoPicSlice section query.
By [design](https://app.zeplin.io/project/5c531dcd1dfb92353b64e7dc/screen/5c5dbb7ce0c3e72caed16ea4) the slice should show summary on tablet portrait (medium breakpoint).
Attaching screenshots of mobile and tablet landscape to show that summary is not visible.
> fix: REPLAT-6745 section fragment query updated

- packages/provider-queries/src/article-fragment.js
- packages/provider-queries/src/section-fragment.js
This is fixing the native edition query
Error:
```
{“errors”:[{“message”:“There can be only one fragment named \“cropProps\“.”,“locations”:[{“line”:132,“column”:12},{“line”:1655,“column”:12}],“extensions”:{“code”:“GRAPHQL_VALIDATION_FAILED”}}]}
```
Explanation: 
In the native-edition we are using both section and article query. Thats why these fragments needs to be with different names.
> fix: native edition query

- packages/article-extras/src/article-topics/styles/responsive.web.js
- packages/article-extras/src/styles/responsive.web.js
JIRA: https://nidigitalsolutions.jira.com/browse/REPLAT-6742
Changed width for topic links and share-save-bar.
Storybook: 
Render:
Tablet width:
> fix: change share-save-bar and topic-links width

- .storybook/config.js
Move storybook knobs on the right panel as expected. WEB
JIRA task : https://nidigitalsolutions.jira.com/browse/REPLAT-6879
> fix: move knobs in storybook web on the right side

- packages/article-in-depth/src/article-meta/article-meta.js
- packages/article-in-depth/src/article-meta/article-meta.web.js
- packages/article-magazine-comment/src/article-meta/article-meta.js
- packages/article-magazine-comment/src/article-meta/article-meta.web.js
- packages/article-magazine-standard/src/article-meta/article-meta.js
- packages/article-magazine-standard/src/article-meta/article-meta.web.js
- Currently getting broken layout when bylines are an empty array.
- https://nidigitalsolutions.jira.com/browse/REPLAT-6899
> fix: article meta layout when bylines are empty

- packages/article-main-standard/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/src/article-meta/article-meta-base.js
- packages/article-main-standard/src/styles/article-meta/index.android.js
- packages/article-main-standard/src/styles/article-meta/index.js
- packages/article-main-standard/src/styles/article-meta/index.web.js
- packages/article-main-standard/src/styles/article-meta/responsive.web.js
- packages/article-main-standard/src/styles/article-meta/shared.js
JIRA task : https://nidigitalsolutions.jira.com/browse/REPLAT-6900
**1. Web - mobile and tablet breakpoints remove the keyline between byline and pub info.**
- Tablet breakpoint:
- Mobile breakpoint:
**2. Android/IOS - the keyline should be removed and padding is correct spacing between elements (10px)**
IOS:
Android:
> feat: REPLAT-6900 article main standart design amends

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/sticky-save-share-bar.web.test.js.snap
- packages/sticky/__tests__/web/__snapshots__/sticky.test.js.snap
- packages/sticky/src/sticky.js
Firefox seems to be jumping when reaching the sticky element for the first time. This PR fixes that.
> fix: prevent a jump in firefox when scrolling to the sticky element

- packages/ad/src/dom-context.js
- fixes https://nidigitalsolutions.jira.com/browse/REPLAT-6914 which blocks beta release.
- it reverts a change made by @jmars here: https://github.com/newsuk/times-components/commit/e5272b5ee55f900cbdafb36fd63ba29f261f5a3a#diff-6bc333c08ceabd74f38d0d732289f9c2 but without the `androidHardwareAccelerationDisabled` change (https://nidigitalsolutions.jira.com/browse/REPLAT-6795)
> fix: issue with safari browser being launched when scroll to ad

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/src/slices/secondaryoneandcolumnist/index.js
- packages/edition-slices/src/tiles/tile-aa/index.js
- packages/edition-slices/src/tiles/tile-aa/styles/index.js
- packages/edition-slices/src/tiles/tile-ab/index.js
- packages/edition-slices/src/tiles/tile-ab/styles/index.js
Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-5492
Implement wide and huge tablet breakpoint for Secondary 1 and Columnist edition slice.
Wide/Huge:
Portrait tablet for ref:
> feat: implement wide and huge tablet Second1Column

- android-app/build.gradle
- android-app/gradle/wrapper/gradle-wrapper.properties
- android/build.gradle
- android/gradle/wrapper/gradle-wrapper.properties
This just updates gradle to the latest version supported by react-native 0.59.10. This makes the android-app teams life easier and doesn't affect much for us.
> chore: update gradle to latest version supported by RN

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/src/slices/leaders/index.js
- packages/edition-slices/src/tiles/tile-ag/index.js
- packages/edition-slices/src/tiles/tile-ag/styles/index.js
Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-5494
Implement Comment Leading Articles for wide and huge tablet breakpoints. Font size changed for huge breakpoint.
> feat: leading articles slice for wide huge tablet

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/edition-slices.showcase.js
- packages/edition-slices/src/slices/leadoneandone/index.js
- packages/edition-slices/src/tiles/tile-u/index.js
- packages/edition-slices/src/tiles/tile-u/styles/index.js
- packages/provider-queries/src/section-fragment.js
- packages/slice-layout/src/templates/leadoneandone/index.js
- packages/slice-layout/src/templates/leadoneandone/styles.js
Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-5483
- Wide breakpoint: 125 char teaser text on lead tile, headline font size on support tile remains 22 
- Huge breakpoint: 300 char teaser text on lead tile, 125 teaser text on support tile, increased headline font size on lead tile, content width - max 1180
Storybook - wide breakpoint:
Storybook - huge breakpoint:
App - wide breakpoint:
App - huge breakpoint:
> feat: REPLAT-5483 implement wide huge breakpoints on  lead 1 and 1 slice

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/edition-slices.showcase.js
- packages/edition-slices/src/slices/leadonefullwidth/index.js
- packages/edition-slices/src/tiles/tile-r/index.js
- packages/edition-slices/src/tiles/tile-r/styles/index.js
Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-5482
- Wide breakpoint - font size increased
- Huge breakpoint - same as wide, except the max width of 1180
Storybook - wide breakpoint:
Storybook - huge breakpoint:
*note:  the bordered box is of 1366px and it is to depict the gutter space for huge breakpoint
> feat: REPLAT 5482 implement wide huge breakpoints on lead 1 full width slice

- packages/article-flag/__tests__/android/__snapshots__/article-flag-with-style.android.test.js.snap
- packages/article-flag/__tests__/ios/__snapshots__/article-flag-with-style.ios.test.js.snap
- packages/article-flag/src/style/index.js
[REPLAT-6627](https://nidigitalsolutions.jira.com/browse/REPLAT-6627)
Flag was cut off on mobile android, because the line height was less than the font size.
Line height value updated.
Margin updated to center the circle.
Before:
After:
> fix: REPLAT-6627 article flag mobile styling fixes

- packages/fixture-generator/src/mock-slice.ts
- packages/section/__tests__/shared-tracking.js
- packages/video-label/__tests__/android/__snapshots__/video-label-with-style.android.test.js.snap
- packages/video-label/__tests__/ios/__snapshots__/video-label-with-style.ios.test.js.snap
- packages/video-label/__tests__/web/__snapshots__/video-label-with-style.web.test.js.snap
- packages/video-label/src/style/shared.js
Jira story: https://nidigitalsolutions.jira.com/browse/REPLAT-6946
A regression was created where the video label was not shown in some articles or slices. This happened when we tried to get the video label text not to overlap its container (which could have been observed for label text longer than a row) .`flex:1` was added to the video label styles that gives enough space for short labels, makes the longer labels wrap properly but when the layout is centred
the label text width is lost.
Video label disappears on:
- article templates like article-in-depth, article-main-comment 
- slices where we have tile with centred layout 
As per RN documentation: 
> When flex is -1, the component is normally sized according width and height. However, if there's not enough space, the component will …
> fix: REPLAT-6946 video label disappears when centred layout

- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-skeleton/__tests__/mocks.web.js
- packages/article-skeleton/__tests__/web/__snapshots__/article-link.web.test.js.snap
- packages/article-skeleton/__tests__/web/article-link.web.test.js
- packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
- packages/article-topics/__tests__/web/__snapshots__/article-topics.web.test.js.snap
- packages/link/__tests__/web/__snapshots__/link.web.test.js.snap
- packages/link/link.showcase.js
- packages/link/src/link.web.js
- packages/pagination/__tests__/web/__snapshots__/pagination-with-styles.web.test.js.snap
- packages/pagination/__tests__/web/__snapshots__/pagination.web.test.js.snap
- packages/save-star-web/__tests__/web/__snapshots__/save-star-web.test.js.snap
Currently, links re-create a styled-component on every single render, forcing both styled-components and react to do more work than necessary. I've updated the component to use `styled-components`'  prop interpalation feature instead.
In the long term, I think we should deprecate and/or remove `responsiveLinkStyles` as it doesn't seem like a useful abstraction and isn't great for performance, and is also not supported on native platforms, but I don't have a great view of how and why it is used. 
I also think we should add "cursor:pointer" as a default for all links, but didn't want to do that in this PR as it impacts more places. 
Todo:
> fix: links should not recreate a styled component on every render

- packages/video-label/__tests__/android/__snapshots__/video-label-with-style.android.test.js.snap
- packages/video-label/__tests__/ios/__snapshots__/video-label-with-style.ios.test.js.snap
- packages/video-label/__tests__/web/__snapshots__/video-label-with-style.web.test.js.snap
- packages/video-label/src/style/index.android.js
- packages/video-label/src/style/index.web.js
- packages/video-label/src/style/shared.js
Story: https://nidigitalsolutions.jira.com/secure/RapidBoard.jspa?rapidView=1116&modal=detail&selectedIssue=REPLAT-6787
Video icon and label text should be vertically aligned but currently they are not. This is observed mainly in Chrome on Windows, but actually it is an issue for all browsers despite the OS. 
Currently on all browsers once we put the items' borders:
The incorrect alignment is better noticed on Windows browsers because the used font `GillSansMTStd-Medium` behaves differently on Windows vs Mac/Linux and all the mobile simulators
*[Some fonts on apple devices has more padding than Windows font](https://stackoverflow.com/questions/25209060/some-fonts-on-apple-devices-has-more-padding-than-windows-font)
GillSansMTStd-Medium on macOS Mojave/Chrome 75
GillSansMTStd-Medium on …
> fix: (REPLAT-6787) article video label alignment

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
- packages/edition-slices/src/slices/shared/content-wrapper.js
- packages/edition-slices/src/slices/shared/index.js
- packages/edition-slices/src/slices/shared/responsive-slice.js
- packages/edition-slices/src/slices/shared/styles.js
- packages/edition-slices/src/tiles/tile-r/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/l2np2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/sd2and2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/sd2np2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l2np2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/sd2and2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/sd2np2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l2np2-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/sd2and2-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/sd2np2-with-style.web.test.js.snap
- packages/slice-layout/src/templates/leadoneandone/index.js
- packages/slice-layout/src/templates/leadoneandone/styles.js
- packages/slice-layout/src/templates/leadtwonopicandtwo/styles.js
- packages/slice-layout/src/templates/secondarytwoandtwo/styles.js
- packages/slice-layout/src/templates/secondarytwonopicandtwo/styles.js
- packages/styleguide/src/breakpoints/index.js
- packages/styleguide/src/styleguide.js
This PR is to implement a simple slice content wrapper used to restrict the content width to 1180px for huge breakpoints
This is by design:
**Before:**
**After:**
> fix: (REPLAT-6982) update slices width for huge breakpoint

- packages/ad/__tests__/web/__snapshots__/ad-with-style.web.test.js.snap
- packages/ad/__tests__/web/ad-with-style.web.test.js
- packages/ad/src/ad.js
- packages/article-skeleton/src/sticky-save-and-share-bar.js
- packages/user-state/src/client-user-state-consumer.js
- packages/utils/__tests__/__snapshots__/server-client-render.test.js.snap
- packages/utils/__tests__/server-client-render.test.js
- packages/utils/src/server-client-render.js
https://nidigitalsolutions.jira.com/browse/REPLAT-7031
In this PR, I've fixed article scroll tracking. I've done that by updating the two pass rendering mechanism to remove the "wrapper" Client and Server components. These were originally included to prevent React rendering both the Client and the Server "paths" whilst only one was needed. However, it turns out this breaks React's reconciling mechanism, and it leads to React unnecessarily destroying and recreating dom nodes on the second "pass" of rendering, even when this is unnecessary.
I thought for performance reasons it was necessary to continue to not render both "paths" whilst only using one, and so I have removed the "wrapper" components from `ClientUserStateConsumer`, and updated `ServerClientRender` to take render functions …
> fix: article scroll tracking

- packages/article-extras/__tests__/web/__snapshots__/article-extras.web.test.js.snap
- packages/article-extras/src/article-extras.web.js
- In order to make injecting Sponsored Articles easier for Nativo, commercial have asked for a wrapping div with id `sponsored-article`.
> Fix: Sponsored ads

- packages/article-image/__tests__/android/__snapshots__/article-image-inline.android.test.js.snap
- packages/article-image/__tests__/android/__snapshots__/article-image-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/styles/shared.js
- packages/caption/__tests__/android/__snapshots__/caption-with-style.android.test.js.snap
- packages/caption/src/styles/index.android.js
- packages/text-flow/__tests__/android/__snapshots__/text.test.js.snap
- packages/text-flow/src/Layout/TextFlow.js
- packages/text-flow/src/Text/Text.js
[Jira](https://nidigitalsolutions.jira.com/browse/REPLAT-6707).
What was done:
Spacing below paragraph with drop cap updated.
What's affected: 
iOS and Android app
Before:
After:
> fix: paragraph with dropcap margin bottom fixed

- packages/ad/__tests__/web/__snapshots__/ad-with-style.web.test.js.snap
- packages/ad/__tests__/web/ad-with-style.web.test.js
- packages/ad/src/ad.js
JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-7192
I have added detection for adblock in render:
https://github.com/newsuk/cps-content-render/pull/2860
Also there was a change in the flag and the way it is added to the project in this PR:
https://github.com/newsuk/cps-content-render/pull/2862
So if the user has been detected using adBlock, the Ad component will return nothing (null).
Also I have created a snapshot test for this case.
> fix: return nothing if adblock is detected

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-ar/index.js
- packages/edition-slices/src/tiles/tile-b/index.js
Dynamic teaser added to TileB and TileAR to reduce white space.
Slices affected: 
LeadOneAndOne
LeadTwoNoPicAndTwo
SecondaryFour
SecondaryTwoNoPicAndTwo
> feat: tileAR and TileB summary wrapper with without white space component 

- android-app/build.gradle
- android-app/package.json
- android-app/settings.gradle
- android-app/xnative/build.gradle
- android-app/xnative/src/main/java/uk/co/thetimes/xnative/XNative.java
- android/app/build.gradle
- android/app/src/main/java/com/storybooknative/MainApplication.java
- android/settings.gradle
- ios/storybooknative.xcodeproj/project.pbxproj
- package.json
- packages/ad/__tests__/android/__snapshots__/ad-with-style.android.test.js.snap
- packages/ad/__tests__/dom-context.native.js
- packages/ad/__tests__/ios/__snapshots__/ad-with-style.ios.test.js.snap
- packages/ad/package.json
- packages/ad/src/dom-context.js
- packages/ad/src/styles/index.js
- packages/article-skeleton/package.json
- packages/article-skeleton/src/article-skeleton.js
- packages/jest-configurator/__tests__/__snapshots__/jest-configurator.test.js.snap
- packages/jest-configurator/setup-jest.js
- packages/jest-configurator/src/jest-configurator.js
- yarn.lock
This ads viewport tracking for unruly so that they can know when they are in view before starting or stopping a video ad.
I am not sure of a good way to test this? Any suggestions?
Also currently waiting for an approved list of device data to pass to them without violating user data confidentiality.
> feat: (REPLAT-6797) add viewport tracking for unruly ads

- packages/article-flag/__tests__/shared.get-active-flags.js
- packages/article-flag/src/get-active-flags.js
This fixes issue of flags not showing up when the expiry time is null
> fix: respect null expiry for flags

- packages/link/src/link.android.js
Just delay the native android touch event slightly so that it doesn't trigger when swiping and scrolling.
> fix: REPLAT-7036 delay android animation when scrolling

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-ac/styles/index.js
- packages/edition-slices/src/tiles/tile-ad/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/l1and4-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l1and4-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l1and4-with-style.web.test.js.snap
- packages/slice-layout/src/templates/leadoneandfour/styles.js
[Jira story.](https://nidigitalsolutions.jira.com/browse/REPLAT-7421)
Lead one and four slice tablet styles updated according to [this design](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d2c84226b3c9a4d03e881bd).
This is how it's going to look with the stars on Android after [this PR](https://github.com/newsuk/times-components/pull/2171) is merged:
> feat: REPLAT-7421 lead1and4 styling tablet

- packages/article-summary/src/article-summary-content.js
- packages/edition-slices/src/tiles/shared/tile-summary.js
- packages/edition-slices/src/tiles/tile-ae/index.js
Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7498
Update SecondaryTwoNoPicAndTwo so it can have minimum 5 lines of teaser text for both upper Tiles (TileAE).
**Before:** 
**=============================================================**
**After:**
> feat: update secondary2NoPicAnd2 for 768px

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/src/slices/shared/content-wrapper.js
- packages/edition-slices/src/slices/shared/gutter.js
- packages/edition-slices/src/slices/shared/styles.js
- packages/section/__tests__/android/__snapshots__/section.test.js.snap
- packages/section/__tests__/ios/__snapshots__/section.test.js.snap
- packages/section/__tests__/shared.js
- packages/section/src/styles/index.js
Wide Before:
Wide After:
The item separator of the huge breakpoint is also updated
Before:
After:
> feat: Updating the gutter of the edition slices and the item separator

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/tiles/tile-ah/styles/index.js
- packages/edition-slices/src/tiles/tile-ai/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/clac-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/clac.android.test.js.snap
- packages/slice-layout/__tests__/clac.base.js
- packages/slice-layout/__tests__/ios/__snapshots__/clac-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/clac.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/clac-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/clac.web.test.js.snap
- packages/slice-layout/src/templates/commentleadandcartoon/styles.js
Styling fixes to align tile separator and image placeholder of lead 1 and cartoon.
Also the snapshot tests are fixed for small breakpoint.
Before:
After:
> fix: lead one and cartoon styling fixes 768

- package.json
- packages/ad/__tests__/android/utils.android.test.js
- packages/ad/__tests__/ios/utils.ios.test.js
- packages/ad/__tests__/web/utils.web.test.js
- packages/ad/package.json
- yarn.lock
Fix vulnerabilities alert and one of the test file for ad package wasn't invoke anywhere.
> chore: fix package vulnerabilites and add missing test file

- packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
- packages/article-skeleton/src/head.web.js
[JIRA](https://nidigitalsolutions.jira.com/browse/REPLAT-7366)
The "logo" field of the SEO data is in the wrong place – this PR fixes that.
> fix: seo logo

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/tiles/tile-ah/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/clac-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/clac.android.test.js.snap
- packages/slice-layout/__tests__/clac.base.js
- packages/slice-layout/__tests__/ios/__snapshots__/clac-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/clac.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/clac-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/clac.web.test.js.snap
- packages/slice-layout/src/templates/commentleadandcartoon/index.js
- packages/slice-layout/src/templates/commentleadandcartoon/styles.js
[Jira Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-7521)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d5189891ced2b350a8f0448)
Font size of the heading is updated to 40.
Snapshot test for wide breakpoint added.
Slice horizontal spacing updated to 50.
Left tile (TileAH) vertically center.
Result:
> feat: REPLAT-7521 lead and cartoon styled for wide breakpoint

- packages/edition-slices/src/tiles/tile-aa/styles/index.js
- packages/edition-slices/src/tiles/tile-u/index.js
- packages/edition-slices/src/tiles/tile-u/styles/index.js
Fixing the space below the headlines:
> fix: fix styles for lead 1 and 1 slice wide breakpoint

- packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
- packages/article-skeleton/src/article-skeleton.js
The in-app font size was working fine, but when the OS font scale was not 1.0 the scale was applied for layout and then again when rendering, resulting in defects. This is a small change that divides the font size by the scale factor when rendering (as the OS does the scaling and we can't control that without disabling accessible sizing).
> fix: replat-7475 Fix font scaling using native font scale

- packages/ad/__tests__/android/__snapshots__/ad-placeholder-with-style.android.test.js.snap
- packages/ad/__tests__/ios/__snapshots__/ad-placeholder-with-style.ios.test.js.snap
- packages/ad/__tests__/web/__snapshots__/ad-placeholder-with-style.web.test.js.snap
- packages/ad/__tests__/web/__snapshots__/ad-with-style.web.test.js.snap
- packages/ad/src/styles/index.js
[JIRA](https://nidigitalsolutions.jira.com/browse/REPLAT-7455)
There is a behaviour where the ad and the placeholder can be shown simultaneously after the ad has "loaded" but before it is "ready". This is likely to ensure there is no "gap" between the placeholder disappearing and the ad displaying.
However, the way the styles are done results in a container collapsing on firefox and not on Chrome. This fixes that.
> fix: Prevent ad from overlapping title

- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/edition-tiles.showcase.js
- packages/edition-slices/src/tiles/tile-r/styles/index.js
Mainly spacing updates for medium breakpoint of LeadOneFullWidthSlice.
The slice can be found in the edition from November 11 2018.
Edition id: 6c26f8dc-db1d-11e8-8b34-49942b38308d
Before:
After:
> Lead one will width slice styling updates for 768

- packages/article-flag/__tests__/android/__snapshots__/article-flag-with-style.android.test.js.snap
- packages/article-flag/__tests__/ios/__snapshots__/article-flag-with-style.ios.test.js.snap
- packages/article-flag/__tests__/web/__snapshots__/article-flag-with-style.web.test.js.snap
- packages/article-flag/src/style/index.js
- packages/article-flag/src/style/shared.js
- packages/article-summary/__tests__/android/__snapshots__/article-summary-with-style.android.test.js.snap
- packages/article-summary/__tests__/ios/__snapshots__/article-summary-with-style.ios.test.js.snap
- packages/article-summary/__tests__/web/__snapshots__/article-summary-with-style.web.test.js.snap
- packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
- packages/article-summary/src/styles/index.android.js
- packages/article-summary/src/styles/index.js
- packages/article-summary/src/styles/shared.js
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
- packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/la2-with-style.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/oa2-with-style.ios.test.js.snap
- packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
- packages/related-articles/__tests__/web/__snapshots__/std-with-style.web.test.js.snap
- Fixes issue with flags and article summary on web, which we supposed to be for edition slices only.
- I have retained the original code but made it for native only as edition slices are only for native for now.
> fix: broken flags and article summary

- package.json
Bundle the graphql files in the `TimesComponents` pod file so they can be reused by the iOS app
> feat[REPLAT-7371]: Pack graphql files in ios pod

- packages/edition-slices/src/tiles/tile-r/styles/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-7504)
LeadOneFullWidth slice styled for wide breakpoint.
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d5186ae32e23e3516c18fbd)
Result:
> feat: REPLAT-7504 lead 1 full width 1024 styling

- packages/article-list/__tests__/android/__snapshots__/article-list-states.android.test.js.snap
- packages/article-list/__tests__/android/__snapshots__/article-list.android.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list-states.ios.test.js.snap
- packages/article-list/__tests__/ios/__snapshots__/article-list.ios.test.js.snap
- packages/article-list/__tests__/shared.native.js
- packages/article-list/src/article-list-item.js
Article headlines were not rendering in article summary due to a missing function call.
> Fix: Replat-7828 fix article-list headlines

- packages/provider-queries/src/article-bookmarked.graphql
- packages/provider-queries/src/article-bookmarked.js
- packages/provider-queries/src/provider-queries.js
- packages/provider-test-tools/src/bookmarks.js
- packages/provider/src/article-bookmarked.js
- packages/provider/src/bookmarks.js
- packages/provider/src/provider.js
- packages/save-star-web/package.json
- packages/save-star-web/src/save-api.js
[JIRA](https://nidigitalsolutions.jira.com/browse/REPLAT-8223)
Currently, in order to determine the saved status of an article for a user, we request a list of the user's bookmarked articles and check whether the article is contained within it. However, it is not possible (or desirable) to get the full list of a user's bookmarked articles consistently, as the list is paged and the query must provide a page size (which defaults to 20).
This means that under the current approach, there will always be a maximum number of saved articles a user can have before they start to experience bugs. There are also undesirable side effects on increasing the page size, as it is essentially wasted network traffic for the client to compute this, and it requires both the server and the client to load into …
> fix: show correct saved status when user has more than 20 saved articles

- packages/provider-queries/src/section_fragment.graphql
Fix for LeadTwoNoPicAndTwoSlice and SecondaryOneAndColumnistSlice queries
For some reason updating those queries was missed during the development and merging to master the changes of 1024 slices.
In order to keep the lead 2 no pic and 2 small breakpoint unchanged. We need both 3:2 and 4:5 ratio of the pictures. To show you that the changes doesn't affect mobile I have provided screenshots.
Please check them below:
**LeadTwoNoPicAndTwoSlice Before:**
---
**LeadTwoNoPicAndTwoSlice After:**
---
**SecondaryOneAndColumnistSlice Before:**
---
**SecondaryOneAndColumnistSlice After:**
> fix: section fragment query updates

- packages/ad/src/dom-context.android.js
- packages/ad/src/dom-context.js
A small change, unruly have stated they expect an object with the same properties as when in-viewport for the out-of-viewport event.
> fix: REPLAT-7354 unruly expect an object always

- packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
- packages/article-skeleton/__tests__/web/head.web.test.js
- packages/article-skeleton/src/head.web.js
We need to ensure image metadata is correct when the lead asset is a video. This PR ensures that.
> fix: output correct metadata when lead asset is a video

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/slices/commentleadandcartoon/index.js
- packages/edition-slices/src/tiles/tile-ah/styles/index.js
- packages/edition-slices/src/tiles/tile-ai/index.js
- packages/edition-slices/src/tiles/tile-ai/styles/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-8279)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d5189891ced2b350a8f0448)
CommentLeadAndCartoon slice - Keyline spacing increased for wide breakpoint.
Result:
> feat: REPLAT-8279 comment lead and cartoon minor styling for wide breakpoint

- packages/provider-queries/src/section_fragment.graphql
- packages/provider/__tests__/edition-provider.test.js
There is no longer any usage of leadAsset45 and listingAsset45, so having the fragments there causes queries to fail with unused fragment errors. :(
Also, the test should spit out the error when it fails, instead of just failing with an undefined snapshot comparison.
> fix: broken querys

- CODEOWNERS
Nate removed.
Apostol and Georgi added as code owners.
> chore: codeowners updates

- packages/edition-slices/src/tiles/tile-w/styles/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-8278)
Secondary 1 slice headline font size updated to 40px for wide breakpoint.
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d51892c38345e9b5afbc471)
> feat: REPLAT-8278 Secondary 1 font size of headline increased for 1024

- packages/section/__tests__/android/__snapshots__/section.test.js.snap
- packages/section/__tests__/ios/__snapshots__/section.test.js.snap
- packages/section/src/section.js
- packages/section/src/styles/index.js
As discussed with the designers, we do not want to have additional space between every top most slice and the navigation on tablet.
> fix: remove top margin of section for tablet

- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/fixtures/full-article-content.js
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/markup-forest/src/markup-forest.js
Certain articles have nodes of type "unknown", we should at least try to render these without crashing. e.g https://www.thetimes.co.uk/past-six-days/2019-09-08/style/mrs-mills-answers-your-questions-dog-days-and-childcare-conundrums-jn8w0277s
> fix: REPLAT-8453 unknown nodes no longer crash

- packages/edition-slices/src/tiles/tile-r/styles/index.js
[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8552)
[Design](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d6e6999a4f1a31857f879bf)
Font size of headline increased to 45 on huge breakpoint.
Snapshot testing of the tile is expected when [this](https://nidigitalsolutions.jira.com/browse/REPLAT-8110) story is finished.
> feat: REPLAT-8552 Lead 1 Full width 1366 styling

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/src/slices/leadoneandone/index.js
- packages/edition-slices/src/tiles/tile-af/index.js
- packages/edition-slices/src/tiles/tile-af/styles/index.js
- packages/edition-slices/src/tiles/tile-z/index.js
- packages/edition-slices/src/tiles/tile-z/styles/index.js
- packages/slice-layout/__tests__/android/__snapshots__/l1and1-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l1and1-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l1and1-with-style.web.test.js.snap
- packages/slice-layout/src/templates/leadoneandone/styles.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-8550)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d6e698d1b6c9e18dbe0369f)
Font sizes of the headlines increased on 1366px.
Width of the tiles updated for both wide and huge in order to be more accurate to the design and be aligned with other slices (please check the seconds screenshot if it doesn't make sense)
Result:
slices alignment on wide breakpoint:
> feat: lead 1 and 1 slice - styling for 1366 and 1024

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
- packages/edition-slices/src/slices/leadoneandfour/index.js
- packages/edition-slices/src/tiles/tile-ac/styles/index.js
- packages/edition-slices/src/tiles/tile-ad/index.js
- packages/edition-slices/src/tiles/tile-ad/styles/index.js
- packages/provider-queries/src/section_fragment.graphql
[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8553)
As discussed with the designers, if there is no star or flags we should fill the left whitespace with teaser text for TileAD(right four slices in the slice)
Section fragment is updated by adding summary300 and teaser300 on LeadOneAndFourSlice.
With star:
> feat: leadOneAndFour for 1366px

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/slice-layout/src/templates/commentleadandcartoon/styles.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-8562)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d6e69997a7ba91b1aa58544)
Minor styling updates for huge breakpoint.
> feat: lead one and cartoon padding updates for 1366

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/sd2np2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/sd2np2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/sd2np2-with-style.web.test.js.snap
- packages/slice-layout/src/templates/secondarytwonopicandtwo/styles.js
Aligning the vertical lines between SecondaryTwoNoPicAndTwo and other slices.
Breakpoint affected: wide and huge.
Before:
After:
> fix: secondary 2 no pic and 2 slice minor styling

- packages/edition-slices/__tests__/android/__snapshots__/tile-m.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-m.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tile-m.test.js.snap
- packages/edition-slices/src/tiles/tile-m/styles/index.js
[Ticket](https://nidigitalsolutions.jira.com/browse/REPLAT-8564)
1. Headline's font size update from 20 to 24pt for wide breakpoint
2. Margin bottom between the headline and the strapline increased for huge breakpoint 
**Wide** breakpoint snapshot
**Huge** breakpoint snapshot
> feat: (REPLAT-8564) Leader slice redesigned for huge breakpoint

- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/tracking.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/tracking.ios.test.js.snap
- packages/article-skeleton/__tests__/shared-tracking.base.js
- packages/article-skeleton/__tests__/web/__snapshots__/tracking.web.test.js.snap
- packages/article-skeleton/fixtures/full-article.js
- packages/article-skeleton/src/tracking/article-tracking-context.js
The referral url was not being passed through to native in the same way as everything else and so they were sometimes getting null values.
https://nidigitalsolutions.jira.com/browse/REPLAT-7797
> fix: REPLAT-7797 fix referral url passing

- packages/provider-queries/src/article.graphql
- packages/provider-queries/src/article_page_props.graphql
For some reason 'articlepageprops' is mixed into the edition query so topics being there is breaking caching on TPA.
> fix: (REPLAT-9284) move topics query out of edition

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tile-u.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-u.test.js.snap
- packages/edition-slices/__tests__/tile-u/shared-tile-u.base.js
- packages/edition-slices/__tests__/web/__snapshots__/tile-u.test.js.snap
- packages/edition-slices/src/slices/leadoneandone/index.js
- packages/edition-slices/src/tiles/tile-u/index.js
- packages/edition-slices/src/tiles/tile-u/styles/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-9112)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d4040cec987b90d2eaeae9a)
Places of the Image and the content swapped in the right tile of the slice.
Teaser text removed.
Image ratio updated to 16:9 according to the design.
Breakpoint functionality for TileU removed.
Before:
After:
> feat: REPLAT-9112 lead 1 and 1 tile U updated for 768

- packages/edition-slices/__tests__/shared-slices.base.js
- packages/edition-slices/__tests__/shared-tablet-slices.base.js
- packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/package.json
- packages/responsive/__tests__/android/__snapshots__/responsive.test.js.snap
- packages/responsive/__tests__/android/responsive.test.js
- packages/responsive/__tests__/ios/__snapshots__/responsive.test.js.snap
- packages/responsive/__tests__/ios/responsive.test.js
- packages/responsive/__tests__/shared.base.js
- packages/responsive/__tests__/shared.native.js
- packages/responsive/__tests__/shared.web.js
- packages/responsive/__tests__/web/__snapshots__/responsive.web.test.js.snap
- packages/responsive/__tests__/web/responsive.web.test.js
- packages/responsive/package.json
- packages/responsive/src/responsive.js
- packages/responsive/src/responsive.web.js
- packages/utils/src/dimensions-util.js
- packages/utils/src/index.js
- packages/utils/src/index.web.js
Part of [this ticket](https://nidigitalsolutions.jira.com/browse/REPLAT-8113)
Background:
Breakpoint information is carried around through the `Responsive` component. This component takes the screen width from RN `Dimensions` API and saves it in context. For testing purposes react native's `Dimensions` is mocked but instead of this mock the real implementation is applied when performing web tests. (This is also valid for mocking other RN components and RN API for web, could be `react-native-web` issue or some configuration/transformation issue and needs further investigation for all TC packages) Thus we are unable to mock the different breakpoints we have and the web snapshots are faulty.
This PR suggest decoupling Dimensions and Responsive components and introducing helper functions that …
> fix: increase test coverage for slices on web

- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
[The latest tests](https://app.bitrise.io/build/5e83ae434d3d41a6#?tab=log) on master are failing. 
Updating the snapshots on master branch in order to unblock tests in all open the PRs.
Snaps updated in [this commit](https://github.com/newsuk/times-components/commit/d685fe69fee2a6b84ef579a8917a376c9399c8f3) were overridden by the [next commit.](https://github.com/newsuk/times-components/commit/4087b7f79eec707ea47158667c6d0a640153632c)
> chore: edition-slices web snapshots update

- packages/article-skeleton/src/head.web.js
- packages/context/package.json
- packages/mocks/package.json
- packages/watermark/package.json
Removing dateUpdated from jsonLD schema as we don't need it. Further details in JIRA comments
JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-8272
> fix: remove dateUpdated from schema REPLAT-8272

- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/l2np2-with-style.android.test.js.snap
- packages/slice-layout/__tests__/android/__snapshots__/l2np2.android.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l2np2-with-style.ios.test.js.snap
- packages/slice-layout/__tests__/ios/__snapshots__/l2np2.ios.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l2np2-with-style.web.test.js.snap
- packages/slice-layout/__tests__/web/__snapshots__/l2np2.web.test.js.snap
- packages/slice-layout/src/templates/leadtwonopicandtwo/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-9308)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d516aab9df85c9b3c22473b)
Lead 2 no pic 2 slice design changes:
Large image tile (support1) moved to right for wide and huge viewports.
Before:
After:
> feat: REPLAT-9308 lead 2 no pic 2 tiles swapped for 1024 and 1366

- packages/article-summary/src/article-summary-headline.js
We have limited space on tiles for article headlines and allowFontSizing with a large OS size causes clipping issues :(
edit: This appears to only be a bug on react-native android, iOS text containers are flexed correctly.
android: before
android:after
ios: before
ios:after - it scales fine
> fix: (REPLAT-9280) disable fontSizing on tile article headlines

- packages/edition-slices/__tests__/android/__snapshots__/tile-r.test.js.snap
- packages/edition-slices/__tests__/ios/__snapshots__/tile-r.test.js.snap
- packages/edition-slices/__tests__/web/__snapshots__/tile-r.test.js.snap
- packages/edition-slices/src/tiles/tile-r/index.js
- packages/edition-slices/src/tiles/tile-r/styles/index.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-9309)
[Design.](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d28524f9cb5a063a8a20ac2)
Tile rearranged and minor styling updates for all breakpoints.
Before:
After:
768:
1024:
1366:
> feat: REPLAT-9309 lead 1 full width structure updated 

- packages/article-paragraph/src/article-paragraph.js
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
A change in the previous PR that removed height from article-paragraph caused a regression. This restores it without adding undefined to the snapshots like it was before
BEFORE:
AFTER:
> fix: paragraph heights not correct

- packages/ssr/src/lib/run-client.js
[REPLAT-9907](https://nidigitalsolutions.jira.com/browse/REPLAT-9907)
Pagination broken for topics and journalist pages.
When making requests to the graphql endpoint client side, the requests were failing because we were sending `acs_tnl` and `sacs_tnl` cookies with the value of `null
`
Those cookies are only available when logged in but the topics and author pages are available when not logged in.
These cookies will only be added now if they have a `truthy` value
This has been tested by running a local version of TC in render
> fix: only add acs and sacs cookies if they exist

- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/shared.native.js
- packages/article-skeleton/fixtures/full-article.js
- packages/article-skeleton/package.json
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/body-utils.js
So this restores the max paragraph height to its original large value, this PR is targeted at an edge case where the jounalist generates a malformed paragraph containing almost all of the article (inserting their own line breaks to simulate the paragraph nodes) and turns on dropcaps. This does still work but it causes the entire article to be manually calculated for layout which is terrible for performance.
This is a more general solution to https://github.com/newsuk/times-components/pull/2348
> fix: edge case with huge paragraphs

- packages/article-in-depth/src/article-in-depth.web.js
- packages/article-magazine-comment/src/article-magazine-comment.web.js
- packages/article-magazine-standard/src/article-magazine-standard.web.js
- packages/article-main-comment/src/article-main-comment.web.js
- packages/article-main-standard/src/article-main-standard.web.js
- packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
- packages/article-skeleton/__tests__/web/head.web.test.js
- packages/article-skeleton/src/article-skeleton.web.js
- packages/article-skeleton/src/head.web.js
- packages/ssr/src/component/article.js
- packages/ssr/src/server/article.js
- in schema.org metadata the logo field needs to use the dual masthead image not the favicon as per https://nidigitalsolutions.jira.com/browse/REPLAT-8274
- Render PR to pass `logoUrl` with new image coming
> fix: Logo for seo

- packages/ssr/src/lib/run-client.js
Reverts PR-2351:
`sacsTnlCookie` will always be null as secure cookies cannot be accessed by the client. This breaks the Save and Share Bar
> fix: revert cookie pagination fix

- packages/article-comments/__tests__/web/__snapshots__/shared-with-style.web.test.js.snap
- packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
- packages/article-comments/src/comments.web.js
- In order to abstract from changing DOM structure in spot IM commenting 
- Currently visual tests are trying to hide/ignore/waitfor classnames in spot IM commenting but they often change.
> chore: add id comments container

- packages/related-articles/src/related-article-item.web.js
[Replat-9642](https://nidigitalsolutions.jira.com/browse/REPLAT-9642)
After having a look at the Related Article Item web it looks like a HOC was created to handle the analytics events but never implemented for the web version. 
After wrapping the component the events seem to be firing properly
> Fix: Replat-9642 no click tracking on related articles

- packages/ssr/src/client/author-profile.js
- packages/ssr/src/client/topic.js
- packages/ssr/src/lib/run-client.js
[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-9907)
Authorization skipped for topics and journalist pages.
Both of the pages are public and doesn't require authentication.
Sending the cookie `asc_tnl` no matter the value returns an authentication error.
Result:
The second bug - updating the component after the data is fetched will be covered in another PR. More information can be found in the comments in JIRA and in the video below:
> fix: REPLAT-9907 pagination fix on topic and author pages

- packages/article-list/src/article-list.web.js
- We had a [regression](https://github.com/newsuk/times-components/pull/2295/commits/ad0e781dac33864b4cf345f3f9a05356aa4252c7) in the `article-list` component. This fixes it.
> fix: article list not updating correctly

- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/shared.native.js
- packages/article-skeleton/fixtures/full-article.js
- packages/article-skeleton/src/body-utils.js
(╯°□°)╯︵ ┻━┻
This adds a function that lifts line breaks out of styling nodes so that paragraph chunking works properly. These things keep popping up, we should probably consider adding markup validation somewhere up the stack or we will end up implementing a full HTML renderer. :(
BEFORE:
AFTER:
> fix: (REPLAT-10284) nested and styled line-breaks

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/article-skeleton.web.js
- At some point during refactoring article templates the single pixel ads were mistakenly removed. 
- Here you can see where they were when they were in the `article` package: https://github.com/newsuk/times-components/blob/31c87a989bed5bb1242eab1ac2640f373f64dcf3/packages/article/src/article.web.js#L107
- This PR re-instates them to fix https://nidigitalsolutions.jira.com/browse/REPLAT-1407
> fix: missing single pixel ads

- packages/ad/ad.showcase.js
- packages/ad/src/utils/generate-config.js
- packages/ad/src/utils/sizes.js
Add a configuration for a new add slot named customMPU.
Request context: 
Current ad slots increase in width in relation to the overall device width. This request adds a new ad slot which displays at 300px on all device widths.
https://nidigitalsolutions.jira.com/browse/TCC-135?atlOrigin=eyJpIjoiYzljMzIzZmNiZGU5NDk3M2I1Mjc1MTAxNWJhNGYwMGEiLCJwIjoiaiJ9
> feat: add customMPU ad slot

- packages/styleguide/src/theme/theme-factory.js
- takeover pages were throwing an error in the `styleguide` package. This fixes it.
- https://nidigitalsolutions.jira.com/browse/REPLAT-7268
> fix: issue with takeover pages erroring

- packages/ad/README.md
Update the ad readme as previous squashed commit for ad stuff was not conventional.
This will force the repo to re-publish
> chore: update ad readme

- packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
- packages/save-and-share-bar/src/bar-item.js
- packages/save-and-share-bar/src/email-share.js
- packages/save-and-share-bar/src/save-and-share-bar.js
- `save-and-share-bar` component doesn't have any class names or id in order help UI testing such as Cypress
- As part of https://github.com/newsuk/cps-content-render/pull/3101 where we need to convert some Cypress tests which were using the non-react dom structure.
> chore: Add test ids to aid ui testing

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/src/styles/responsive.web.js
Removes the display none styling which was stopping the header ad from being displayed on mobile web.
Have tested locally and everything works.
Header Ad container is only used in web so shouldn't cause an issue in the Native world
> fix: remove display:none css styling

- packages/article-main-comment/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
- packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-comment/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-comment/src/article-header/article-header.js
Reverts the change to add bylines under author images in comment articles until we have the ability to detect the article position and only do this for the hero article.
> fix: revert comment article bylines

- packages/responsive-image/src/index.tsx
The cropping logic was adjusted to fix android but it turns out android was doing the wrong thing and ios was correct :(
> fix: ios crop urls are wrong

- packages/utils/__tests__/get-lead-asset.test.js
- packages/utils/src/get-lead-asset.js
- Fixes: https://nidigitalsolutions.jira.com/browse/REPLAT-11021
- For articles (generally old) which do not have any of the supported crops we currently show a 500 error  as the code is trying to get the `ratio` of null.
see thetimes.co.uk/article/should-the-world-be-run-on-fergie-time-vvgp8nmd6kz?react=1
- This PR handles that and results in showing no image in this case
> fix: do not show lead asset when no crop returned from tpa

- packages/save-star-web/src/save-api.js
Bookmarks on a draft article are currently causing error on the CI tests. 
Adding guard for the cases when article.isBookmarked is null or undefined...
> fix: bookmarks of null on a preview article

- packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
- packages/save-and-share-bar/src/save-and-share-bar.js
- packages/save-and-share-bar/src/styles/index.js
This PR fixes the following [issue](https://nidigitalsolutions.jira.com/secure/RapidBoard.jspa?rapidView=1117&view=planning&selectedIssue=REPLAT-10793).
> fix: fixed save-button position when share is disabled

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/src/article-body/article-body.web.js
- packages/article-skeleton/src/styles/article-body/responsive.web.js
- packages/context/package.json
- packages/mocks/package.json
- packages/responsive-image/package.json
- packages/watermark/package.json
This PR is for this [issue](https://nidigitalsolutions.jira.com/browse/REPLAT-11030).
Note the red line - the space there used to be non-existent.
> fix: fixed the margin below the fullstandard image

- packages/ad/src/ad.js
- packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article-images.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-images.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-skeleton.js
A state update for removing the loading spinner was causing the article content to rerender, this PR makes generous use of useMemo and useCallback to make sure that rerender only occurs when the data itself changes.
> fix: scroll to top on content load

- packages/article-skeleton/.eslintrc.json
- packages/article-skeleton/src/article-skeleton.js
Prettifier was adding deps that caused rerenders, we actually don't care about those props.
> fix: unnecessary rerender in article

- packages/article-skeleton/src/article-skeleton.js
We no longer rebuild article components after the first render, there is an arrow function callback somewhere up the tree causing a prop change of a callback that cannot be changed. Avoid changing the function as it is actually always the same just a different instance.
> fix: invalid callback change

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/src/styles/responsive.web.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/src/styles/responsive.web.js
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/src/styles/responsive.web.js
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/src/styles/responsive.web.js
- https://nidigitalsolutions.jira.com/browse/REPLAT-11399
- Fix bylines that were breaking out of container
> fix(REPLAT-11399): fix bylines that were breaking out of container

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/src/styles/article-body/index.web.js
Inline Ad was miss aligned.
Before:
After:
> fix: REPLAT-11287 inline ad web styling

- packages/image/package.json
- `responsive-image` has gone out again...
> chore: fix out of sync versions

- TimesComponents.podspec
- packages/image/package.json
- packages/responsive-image/package.json
See: https://nidigitalsolutions.jira.com/browse/REPLAT-11696
We were unable to update Times Components on the iOS app via the normal process (described [here](https://github.com/newsuk/nu-digital-projectd-times-smartphone-ios/blob/develop/README.md)) because this `podspec` file was incorrect.
We need to remove the dependencies from this podspec file (they are no longer required) so that the Times Components library can be installed successfully on iOS.
> Remove react dependencies from Podspec file (no longer required)

- packages/responsive-image/src/index.tsx
Attempt to get offline image as well as online from the react cache before trying the normal placeholder->tarball->online sequence.
> fix: REPLAT-8723 load offline images from react cache before tarball

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/article-skeleton.web.js
[Jira.](https://nidigitalsolutions.jira.com/browse/REPLAT-11059)
The sticky bar position wasn't calculated right when the article is shared.
The reason is that the marketing header above the article is outside the react context. 
Please check the screenshots to understand the issue.
After the PR is merged. [We should delete the container in render repo.](https://github.com/newsuk/cps-content-render/pull/3214)
**Before:**
**After:**
**This screenshot is a verification that the layout is unchanged:**
> fix: REPLAT-11059 adding article-marketing-header in article skeleton web

- packages/section/src/utils.js
Not all slices have an id property, resulting in slices having the key 'undefined.0', 'undefined.1' etc. This means that when the slices are rendered after an update while the app is open and they are in the same position but with different articles the update does not work properly. This commit just generates a key that is unique per index and child article content so that updates work properly.
> fix: section slice keys were entirely based on index

- android-app/package.json
- yarn.lock
The maintainer of react-native-v8 has published new versions that require a renamed lib for linking, he did not republish the v8 version so we need to roll forward or risk crashes on new builds.
> fix: update v8 for linking issues

- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
- packages/image/__tests__/modal-shared.native.js
- packages/image/src/modal-image/modal-image.js
- packages/image/src/styles/shared.js
Before, captions were over the top of the image, this moves them to the bottom of the modal as per the designs and turns on preloading as people complained about load time in image modals. It also enabled the swipe down to close gesture so that it works the same on iOS and Android.
https://nidigitalsolutions.jira.com/browse/REPLAT-11812
> fix: REPLAT-11812 caption appearing over images

- packages/save-and-share-bar/__tests__/shared-tracking.js
- packages/save-and-share-bar/__tests__/shared.base.js
- packages/save-and-share-bar/src/email-share.js
- packages/save-and-share-bar/src/save-and-share-bar.js
Add prevent default to copy and email buttons in save and share bar
TODO: I will create a PR in render with e2e tests for these scenarios
> fix: prevent default for copy and email buttons

- packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-isPreview.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/article-skeleton.web.js
- on legacy article pages it was easy to id the article template by viewing source.  This adds the template name to the article element as a data attribute.
> feat: add template name as data attr for debugging

- packages/key-facts/__tests__/web/__snapshots__/key-facts-with-style.web.test.js.snap
- packages/key-facts/fixtures/key-facts-showcase.json
- packages/key-facts/src/styles/responsive.web.js
- https://nidigitalsolutions.jira.com/browse/REPLAT-12165
- Zeplin design had more horizontal space then the implementation so I updated `key-facts` component.
> fix (REPLAT-12165): key facts layout issue

- packages/ssr/src/component/article.js
- packages/ssr/src/lib/section-from-tiles.js
- packages/utils/__tests__/get-section-from-tiles.test.js
- packages/utils/src/get-section-from-tiles.js
- packages/utils/src/index.js
- packages/utils/src/index.web.js
[Jira](https://nidigitalsolutions.jira.com/browse/REPLAT-12226)
Improvement on the get section name from tiles implementation. 
This is fixing the font issue on this article(https://www.thetimes.co.uk/article/johnny-flynn-interview-the-emma-star-on-playing-david-bowie-in-stardust-and-duncan-jones-reaction-to-the-biopic-mvt3x7x90) and probably a lot more fonts and theming related issues still currently uncaught.
Reason for the error: the current implementation is depending on the first tiles -> slices -> sections, which for this article is empty array.
> feat: get section name from tiles improvement

- packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-main-standard/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-main-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-main-standard/src/article-main-standard.js
- packages/article-main-standard/src/styles/article-body/shared.js
[REPLAT-12259](https://nidigitalsolutions.jira.com/browse/REPLAT-12259)
Before:
After:
> fix: REPLAT-12259 Show lead asset captions for mobile native apps 

- packages/edition-slices/src/edition-slices.js
- packages/responsive/src/responsive.js
- packages/styleguide/src/breakpoints/index.shared.js
- packages/styleguide/src/breakpoints/index.web.js
This is so that the native side on android can set all parts of the app into tablet mode when unfolding a folding phone, which is not quite big enough to trigger the tablet breakpoints but is too large for mobile layouts to look reasonable.
> feat: allow native to override breakpoints

- fonts.js
- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/header-with-style.native.js
- packages/article-skeleton/__tests__/images-with-style.native.js
- packages/article-skeleton/__tests__/images.native.js
- packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/scaling.native.js
- packages/article-skeleton/__tests__/shared-tracking.js
- packages/article-skeleton/__tests__/shared-with-style.native.js
- packages/article-skeleton/__tests__/shared.native.js
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-body/drop-cap.js
- packages/article-skeleton/src/article-body/inline-paragraph.js
- packages/article-skeleton/src/article-body/simple-paragraph.js
- packages/article-skeleton/src/body-utils.js
- packages/lazy-load/package.json
- packages/provider/package.json
- packages/tracking/package.json
- packages/typeset/__tests__/AttributedString.test.ts
- packages/typeset/__tests__/LayoutManager.test.ts
- packages/typeset/__tests__/__snapshots__/LayoutManager.test.ts.snap
- packages/typeset/src/AttributedString.ts
- packages/typeset/src/LayoutManager.ts
- storybook-native/package.json
- yarn.lock
This PR removes any and all hacks around multiple newlines and nested styling markup and handles it properly. Newlines and nesting work as they would on web.
https://nidigitalsolutions.jira.com/browse/REPLAT-12170
> feat: (REPLAT-12170) handle arbitrary newlines and nested styling

- packages/ssr/src/client/article.js
- packages/ssr/src/client/topic.js
- packages/ssr/src/server/topic.js
Topics had prematurely been updated to use v2. This was causing mismatches between the article and the topics pages. This PR reverts everything back to topics v1
> fix: issue with topics

- TimesComponents.podspec
In order to add the current TimesComponents version to the iOS app settings screen, we need to add the `version.meta` file from the js directory to the podspec's `resource_bundles` container
> TNLT-474: copy all contents from `assets/js` directory

- doc/running-ios-dev.md
- ios-app/README.md
- lib/publish.sh
Just updating the repository URL for the universal app as we had to rename it in order to match the new standard `newsuk` naming convention. I've also updated the git username/email for the publish step to use our service account.
> chore: Update README

- packages/image/__tests__/android/__snapshots__/modal-image-with-style.android.test.js.snap
- packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
- packages/image/src/styles/shared.js
[Jira](https://nidigitalsolutions.jira.com/browse/TNLT-652)
Before:
After:
> fix: close icon on modal images

- packages/interactive-wrapper/__tests__/web/interactive-wrapper.test.js
- packages/interactive-wrapper/src/interactive-wrapper.web.js
This returns a valid Promise from the default `fetchPolyfill` function
> fix: resolve default Webcomponent polyfill response

- packages/article-summary/package.json
- packages/lazy-load/package.json
- packages/provider/package.json
- packages/tracking/package.json
- storybook-native/package.json
TNL Checkout want to use article-summary package, but it's failing due to missing rnw dependency
> fix: move rnw dep to dependencies

- ios-app/package.json
Trying manually to sync ios-app version.
Because publish ios is failing.
> fix: manual ios bump

- android-app/package.json
- ios-app/package.json
- packages/pages/package.json
- packages/section/package.json
- packages/section/src/section-tracking-context.js
This is preventing the apps from crashing when there is puff slice in the edition. It also includes version bumps for ios, pages and section packages. 
Linked with: https://github.com/newsuk/times-components/pull/2593
> chore(TNLT-1941): prevent crash of puff slice

- packages/ad/__tests__/ios/__snapshots__/ad-with-style.ios.test.js.snap
- packages/ad/src/dom-context.js
Fix on Android flashing ads implemented [here](https://github.com/newsuk/times-components/pull/2572), broke the iOS ones.
The result after is loaded check is removed is:
> fix: remove loaded check for ads in iOS

- packages/article-paragraph/article-paragraph.showcase.web.js
- packages/styleguide/__tests__/shared.js
- packages/styleguide/src/theme/theme-factory.js
Sync fonts between mobile and web for dropcap and headline in the following case:
- When the article template is `indepth`, `magazinestandard` or `magazinestandard` in `The Sunday Times Magazine` section.
Font used: `Tiempos-Headline-Bold`
- Minor storybook knobs fixes
[TNLT-1964](https://nidigitalsolutions.jira.com/browse/TNLT-1964)
Before:
After:
> fix(FNLT-1964): update web font for ST magazine articles

- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/shared.base.js
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/fixtures/boldItalic-text-article-content.js
- packages/article-skeleton/fixtures/italic-link-article-content.js
- packages/article-skeleton/fixtures/link-text-article-content.js
- packages/article-skeleton/fixtures/mixed-link-article-content.js
- packages/article-skeleton/fixtures/text-bold-link-article-content.js
- packages/article-skeleton/src/article-body/simple-paragraph.js
- packages/typeset/__tests__/AttributedString.test.ts
- packages/typeset/src/AttributedString.ts
[TNLT-1826](https://nidigitalsolutions.jira.com/browse/TNLT-1826)
Handling flat article content structure like: 
`<p><b>For full TV listings for the week, see <a>thetimes.co.uk/tvplanner</a></b></p>`
In order to style hyperlinks as expected on native devices
Before:
Result:
> fix(TNLT-1826): support bold/italic links for native

- ios-app/package.json
Manual bump of ios app, because of failing publish.
> fix: manual version increment of ios app

- packages/pages/src/pages.js
- packages/pages/src/with-error-boundaries.js
Adding error boundaries for all the pages. We do this to catch the errors caused by pages and their child components at the top level. Instead of a crash the user will see this screen:
> feat: add error boundaries to pages

- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/src/styles/article-body/shared.js
[TNLT-1212](https://nidigitalsolutions.jira.com/browse/TNLT-1210)
Fix colour of the sub heading tags for android.
Before:
After:
> fix: TNLT-1210 heading colour updated for native

- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/shared.base.js
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/fixtures/inline-paragraph-content.js
- packages/article-skeleton/src/article-body/article-body-row.js
Renderer for inline markup added.
Before:
After:
> fix: TNLT-2236 handle inline paragraphs for native

- packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
- packages/article-skeleton/__tests__/shared.base.js
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/fixtures/dropcap-article-content.js
- packages/article-skeleton/src/article-body/drop-cap.js
[TNLT-1844](https://nidigitalsolutions.jira.com/browse/TNLT-1844)
Use [Font.getAdvanceWidth](https://github.com/opentypejs/opentype.js/tree/master#fontgetadvancewidthtext-fontsize-options) for dropcap width calculation, instead of [Glyph.getBoundingBox](Glyph.getBoundingBox()
) to fix dropcap text overlapping.
Before:
After:
> fix(TNLT-1844): dropcap width calculation updated for native

- packages/related-articles/fixtures/standard/3-draft-article.json
- packages/related-articles/related-articles.showcase.js
- packages/related-articles/src/related-articles.js
Fix rendering of related articles with sliceName: `DraftStandardSlice`.
Used on Preview environments.
The bug was introduced [here](https://github.com/newsuk/times-components/pull/2585).
> fix: render related articles on preview env

- packages/interactive-wrapper/src/interactive-wrapper.android.js
Split native interactive wrapper to ios and android
Revert [#2611](https://github.com/newsuk/times-components/pull/2611) changes for ios
> fix: revert ios interactive wrapper

- packages/article-skeleton/__tests__/android/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-button.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-button.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/newsletter-puff-button.test.js.snap
- packages/article-skeleton/src/article-body/article-body-row.js
- packages/article-skeleton/src/article-body/article-body.web.js
- packages/article-skeleton/src/article-body/newsletter-puff-button.js
This PR:
* Decode the imageUri that comes encoded from the component builder before we pass it as a prop to `inline-newsletter-puff`
* Change the copy of NewsletterPuffButton from `Sign up to newsletter` to `Sign up now` 
[TNLT-2519](https://nidigitalsolutions.jira.com/browse/TNLT-2519)
> feat(TNLT-2519): Decode imageUri and change NewsletterPuffButton copy

- packages/provider/src/connect.js
This PR:
* Add `ssr` prop in QueryProvider so we can use the `false` value when we don't want to call the GraphQL query from the server and call it only form the client. We set this prop as optional with the default value equal to `undefined` as the `Query` only checks if the value is false (See screenshot). From the documentation of the `Query` component
```
ssr: boolean
Pass in false to skip your query during server-side rendering.
```
We need it for the `GetNewsletter` query but it will be useful if we need it in another query in the future.
[TNLT-2993](https://nidigitalsolutions.jira.com/browse/TNLT-2993)
> feat(TNLT-2993): Add ssr prop in QueryProvider

- packages/article-extras/__tests__/shared.web.js
- packages/article-extras/__tests__/web/__snapshots__/article-extras.web.test.js.snap
- packages/article-extras/src/article-extras.web.js
At the moment we do not pass the `isReadOnly` flag into the `<ArticleComments />` component on web. This is fine for the most part, as the wrapping `<UserState>` component ensure it isn't visible to logged out readers. Unfortunately, there is an edge case where it _can_ be shown for readers who are logged out, but are using a share token (to see the full article). This wraps the comment component with an additional user state check, and falls back to pass in the `isReadOnly` flag.
> fix(TNLT-2359): make Spot read only for share token users

- packages/article-comments/src/comments.web.js
This PR adds the once option to the comments event listener as it was firing multiple times.
After investigating, the event listener was only registered once, so multiple firing must be to do with slightly dodgy event listener firing. Once option should limit the event listener to firing just once
https://nidigitalsolutions.jira.com/browse/TNLT-3719
> feat(TNLT-3719): add once to spot IM comment call

- packages/article-skeleton/__tests__/android/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-link.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-link.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/inline-newsletter-puff.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/newsletter-puff-link.test.js.snap
- packages/article-skeleton/src/article-body/inline-newsletter-puff.js
- packages/article-skeleton/src/styles/inline-newsletter-puff.js
In this PR we change the copy that is displayed when a user sign up successfully to a newsletter
[TNLT-5506](https://nidigitalsolutions.jira.com/browse/TNLT-5506)
PR [#179](https://github.com/newsuk/times-components-native/pull/179) in `times-components-native`
> feat(TNLT-5506): Change confirmation copy in newsletter puff

- packages/article-skeleton/src/article-body/inline-newsletter-puff.js
- packages/article-skeleton/src/article-body/newsletter-puff-button.js
- packages/article-skeleton/src/article-body/newsletter-puff-link.js
- packages/tracking/src/tracking-context.js
In this PR we fix the `onPress` and `oneView` tracking by adding the `trackingName` to the NewsletterPuff components.
[TNLT-4872](https://nidigitalsolutions.jira.com/browse/TNLT-4872)
PR [#244](https://github.com/newsuk/times-components-native/pull/244) in `times-components-native`
> feat(TNLT-4872): Update newsletter puff tracking

- packages/article-extras/__tests__/shared.web.js
- packages/article-extras/src/article-extras.web.js
- packages/user-state/src/matchers.js
- packages/user-state/src/user-state.js
When we render comments as read only, or read/write, we used to check the `UserState.loggedIn` state. This check effectively looks at whether the request came in through a non-`_tp_` or non-`_fp_/open_anonymous` route  in Render.
The downside to thios approach, is that for readers that come as logged out with a `?shareToken=` param,  they also get routed through the full article path in Render. This ultimately means that despite being logged out, they are actually treated as 'logged in'.
This means the check we make on comments isn't valid, as it's trying to make them writable for readers that should only get read-only access.
Instead, I have introduced a new state checker, with the catchy name: `isLoggedInOrLoggedInAndNotShared`. This effectively does the following:
* If the reader is …
> fix(TNLT-2359): add new user state check for comments readOnly state

- packages/article-skeleton/src/article-body/article-body.web.js
- packages/article-skeleton/src/article-body/inline-newsletter-puff.js
- packages/article-skeleton/src/article-body/newsletter-puff-button.js
- packages/article-skeleton/src/article-skeleton.web.js
- packages/provider-test-tools/fixtures/article.json
This PR creates a dummy newsletter puff component and adds logic to the ArticleBody component to show the dummy puff when in Preview.
The dummy puff component in Storybook:
> Fix(TNLT-6934): Made newsletter puff visible in preview

- packages/article-skeleton/__tests__/web/__snapshots__/auto-place-newsletter-puff.web.test.js.snap
- packages/article-skeleton/src/newsletter-puff.web.js
The Images in the automated Newsletter Puff were not rendering. [TE-34](https://nidigitalsolutions.jira.com/jira/software/c/projects/TE/issues/TE-34)
- The component expects to receive an encoded string and then decodes it, however the encoded url works and the decoded url doesn't. To fix the issue I encoded the string the url receives twice.
- Encoded: https://www.thetimes.co.uk/imageserver/image/methode%2Ftimes%2Fprod%2Fweb%2Fbin%2F728c3e68-5311-4533-809a-b313a6503789.jpg?resize=800
- Decoded: https://www.thetimes.co.uk/imageserver/image/methode/times/prod/web/bin/728c3e68-5311-4533-809a-b313a6503789.jpg?resize=800
> Encode image urls again so they render correctly in the component

- packages/article-extras/article-extras.showcase.web.js
- packages/article-extras/src/article-extras-content.js
- packages/article-extras/src/article-extras.web.js
- packages/article-in-depth/src/article-in-depth.web.js
- packages/article-magazine-comment/src/article-magazine-comment.web.js
- packages/article-magazine-standard/src/article-magazine-standard.web.js
- packages/article-main-comment/src/article-main-comment.web.js
- packages/article-main-standard/src/article-main-standard.web.js
- packages/article-skeleton/src/article-skeleton.web.js
- packages/article/showcase-helper.js
- packages/related-articles/related-articles.showcase.js
- packages/related-articles/src/related-articles-heading.js
- packages/related-articles/src/related-articles.js
- packages/ssr/src/client/article.js
- packages/ssr/src/component/article.js
- packages/ssr/src/server/article.js
Additional Related Articles rail functionality added. Enabled using the `additionalRelatedArticlesFlag` flag which should be passed in through render as a feature flag
> feat(TE-33): Additional Related Articles rail

- packages/context/package.json
- packages/mocks/package.json
- packages/pages/src/apollo-client.js
- packages/ssr/src/lib/run-client.js
- packages/ssr/src/lib/run-server.js
- packages/ssr/src/server/article.js
- packages/ssr/src/server/author-profile.js
- packages/ssr/src/server/topic.js
- packages/utils/src/make-client-util.js
This PR adds the "name" config to all TPA Apollo clients - to improve request attribution in Apollo Studio.
> chore: name apollo clients

- packages/article-skeleton/src/article-body/article-body.web.js
- packages/ts-components/src/__tests__/InArticlePuff.test.tsx
- packages/ts-components/src/__tests__/__snapshots__/InArticlePuff.test.tsx.snap
- packages/ts-components/src/in-article-puff/index.stories.tsx
- packages/ts-components/src/in-article-puff/index.tsx
- packages/ts-components/src/in-article-puff/styles.ts
- Added section colour to the style of label and byline of InArticlePuff component. This logic is already used in other components in the repo so have followed the application in those examples.
> feat(TE-90): add section colour to label and byline in article puff

- .storybook/config.js
- .storybook/webpack.config.js
- package.json
ts-components typescript files will render in storybook without having to do a 'yarn build'. This is still required if a typescript component is used by a module that is not typescript
> added storybook for ts-components

- packages/ts-components/src/components/in-article-puff/InArticlePuff.tsx
- packages/ts-components/src/components/in-article-puff/__tests__/InArticlePuff.test.tsx
- packages/ts-components/src/components/in-article-puff/__tests__/__snapshots__/InArticlePuff.test.tsx.snap
- packages/ts-components/src/components/in-article-puff/styles.ts
This PR updates how the `InArticlePuff` uses `sectionColour`
* Remove inline styles
* Pass `sectionColour` to component styles
This approach does mean we are unable to unit test the `sectionColour` is rendering correctly? Is this a problem?
> feat(TE-43): InArticlePuff - cleaner section colour implementation

- packages/ts-components/src/components/olympics/__tests__/OlympicsMedalTable.test.tsx
- packages/ts-components/src/components/olympics/__tests__/OlympicsSchedule.test.tsx
- packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsMedalTable.test.tsx.snap
- packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsSchedule.test.tsx.snap
- packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.stories.tsx
- packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx
- packages/ts-components/src/components/olympics/medal-table/styles.ts
- packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.stories.tsx
- packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.tsx
- packages/ts-components/src/components/olympics/schedule/styles.ts
Enable scroll on the olympics schedule widget. -- Remove show all button as is no longer required, and adjust footer height.
> fix(te-000): update olympic schedule scroll

- packages/ts-components/src/components/olympics/__tests__/OlympicsMedalTable.test.tsx
- packages/ts-components/src/components/olympics/__tests__/OlympicsSchedule.test.tsx
- packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsMedalTable.test.tsx.snap
- packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsSchedule.test.tsx.snap
- packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx
- packages/ts-components/src/components/olympics/medal-table/styles.ts
- packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.stories.tsx
- packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.tsx
- packages/ts-components/src/components/olympics/schedule/styles.ts
- packages/ts-components/src/components/olympics/shared-styles.ts
Styling updates: 
1: Heading - Add a larger heading and separate from the label
2: Centralise spacing of items in the schedule list.
3: Change colour of border, label and time on schedule to the olympic purple as requested by Anthony.
> Update styles of heading in olympic widgets

- packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsSchedule.test.tsx.snap
- packages/ts-components/src/components/olympics/schedule/styles.ts
Now we can see live data on the Olympics schedule, can see that the medal in the right hand side overlaps both 'Live' status and 'finished' status so have to move it back to the original left position. 
Also the text in the 'Live' status was very high up so have centralised it. -- More styling issues in my opinion with 'Live' and 'Finished' but that can be added later.
> fix(te-000): Revert medal position change 

- packages/ts-components/src/components/article-flag/LiveArticleFlag.tsx
- packages/ts-components/src/components/article-flag/__tests__/__snapshots__/LiveArticleFlag.test.tsx.snap
- packages/ts-components/src/components/article-flag/styles.ts
This PR fixes the alignment of the diamond and the text in the LIVE flag.
The flag looks like this in Storybook:
> feat(TDP-478): Fix LIVE flag alignment

- packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
- packages/article-comments/__tests__/web/shared.web.test.js
- packages/article-comments/src/comments.js
Based on this, I think we were listening on the wrong event
https://developers.openweb.com/docs/event-listener-reference
> TDP-1024 - update im posted event name and added new tests for it

- packages/key-facts/__tests__/web/__snapshots__/key-facts.web.test.js.snap
- packages/key-facts/src/key-facts-text.js
- packages/key-facts/src/styles.js
The links in the Key Facts component was not working after converting Key Facts away from React Native. This change fixes that.
> fix(TDP-759): Fix links in key-facts

- packages/user-state/__tests__/matchers.test.js
- packages/user-state/src/matchers.js
- packages/user-state/src/user-state.js
In this PR we add `hasAccess` to `userState` and we check it to `matchers` when we see if we `shouldShowFullArticle`
[TDP-1329](https://nidigitalsolutions.jira.com/browse/TDP-1329)
> feat(TDP-1329): Unlock related articles to users with access to full articles 

- packages/ts-components/src/components/article-header/ArticleHeader.stories.tsx
- packages/ts-components/src/components/article-header/__tests__/__snapshots__/ArticleHeader.test.tsx.snap
- packages/ts-components/src/components/article-header/styles.ts
The spacing below the article divider component was previously being handled by the bottom of the headline - However given the headline is an optional property in the case of no headline the component squished against the top of the following paragraph/component. This change passes the spacing to the component container instead.
Also added a story without a headline.
[Storybook](https://26857-93151110-gh.circle-artifacts.com/0/Storybook/index.html?path=/story/typescript-component-article-header--article-header-without-headline)
> fix(TDP-760): Fix article heading divider spacing

- packages/button/package.json
- packages/button/src/button-prop-types.js
Removed react-native components Text & ViewPropTypes and replaced with PropTypes as only used for style props
> feat(TDP-1417): remove react-native prop types from button

- packages/article-skeleton/src/tracking/article-tracking-context.js
- packages/context/package.json
- packages/key-facts/src/key-facts.js
The value for article_flag if a live or breaking article was coming through as uppercase. This PR changes it to lower case.
[TDP-1777](https://nidigitalsolutions.jira.com/browse/TDP-1777)
> fix(TDP-1777): Make analytics article_flag data lower case

- packages/article-magazine-standard/fixtures/full-article.js
- packages/article-skeleton/__tests__/web/__snapshots__/tracking.web.test.js.snap
- packages/article-skeleton/__tests__/web/data-helper.test.js
- packages/article-skeleton/__tests__/web/tracking.web.test.js
- packages/article-skeleton/src/data-helper.js
- packages/article-skeleton/src/tracking/article-tracking-context.js
- packages/responsive/package.json
- packages/utils/package.json
- yarn.lock
[TDP-1829](https://nidigitalsolutions.jira.com/browse/TDP-1829)
Remove reference to the deprecated "flags" data - we don't query for it, so no longer need to code against it. 
Update article_flag tracking to check for ACTIVE flags, if they are active the value will be the lower case of the flag name, if they don't exist or are expired it will be "no flag".
> fix(tdp-1829): update flag tracking

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/src/article-meta/article-meta.js
- packages/article-in-depth/src/styles/responsive.js
Fixed small UI issue for DatePublication line for in-depth articles [TDP-1690](https://nidigitalsolutions.jira.com/browse/TDP-1690) 
was showing:
now showing 
[](url)
> feat(TDP-1690): fixed small UI issue on date publication line

- packages/article-skeleton/src/head.js
This PR adds the `articleSection` property to the JSON LD of live articles (`articleSection` was previously added to the JSON LD of articles but not of live articles)
[TDP-1520](https://nidigitalsolutions.jira.com/browse/TDP-1520)
> fix(TDP-1520): add articleSection to live articles

- packages/ad/__tests__/web/__snapshots__/ad-container.web.test.js.snap
- packages/ad/src/ad-container.js
This PR removes the id from the ad-container, which is causing issues with ads appearing correctly.
> fix(TDP-2238): remove id from ad container

- packages/article-skeleton/__tests__/web/data-helper.test.js
- packages/article-skeleton/src/data-helper.js
[TDP-2179](https://nidigitalsolutions.jira.com/browse/TDP-2179)
@DMackintosh-TNL has written some good documentation on the problem we were having [here](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/4013850689?atlOrigin=eyJpIjoiNjU5ZGNjMmFiN2E3NGMxMGE0ZWU5MzA2N2ZmZTA5OTkiLCJwIjoiY29uZmx1ZW5jZS1jaGF0cy1pbnQifQ).
But to summarise this PR - Editorial want to be able to set an active flag either by using an expiry time, but also for cases where they don't know how long the piece will run for ahead of time they also want to not set an expiry and later manually expire the flag. This means that the data we receive could be either a date/time or a null value for when the flag is meant to be live.  - For this reason I have added a check for a null value in the function …
> fix(TDP-2179): Fix article_flag bug

- packages/article/src/article.js
- packages/message-bar/__tests__/message-bar.base.js
- packages/message-bar/__tests__/message-manager.base.js
- packages/message-bar/__tests__/shared.base.js
- packages/message-bar/__tests__/web/__snapshots__/message-bar.test.js.snap
- packages/message-bar/message-bar.showcase.js
- packages/message-bar/package.json
- packages/message-bar/src/message-bar.js
- packages/message-bar/src/message-manager.js
- packages/message-bar/src/styles/index.js
- packages/message-bar/src/styles/shared.js
- packages/save-and-share-bar/save-and-share-bar.showcase.js
- yarn.lock
Remove React Native from message-bar package
[TDP-1419](https://nidigitalsolutions.jira.com/browse/TDP-1419)
Due to the message bar using TouchableOpacity and Animate particularly from react-native we had to refactor the MessageBar component quite a bit to recreate the animation. 
To test the behaviour locally best component is the save-share-bar if you click the icon to copy the link you should see the message bar, and it will automatically close after 3000ms or you can click the close button and it will close. - Compare against the built component [here](https://components.thetimes.co.uk/?path=/story/composed-save-and-share-bar--save-and-share-bar)
Big thank you to @adamosborne-tnl and @DMackintosh-TNL for the assist on this one!
> feat(TDP-1419): Remove react-native from message-bar package

- packages/fixture-generator/package.json
Seems a bit much to make a whole PR from this, but in the spirit of one package one PR - removed the react native references from fixture-generator.
> feat(TDP-1712): fixture generator

- babel.config.js
- package.json
- yarn.lock
removing all React Native created a storybook error, and this babel plugin fixes it
> feat(TDP-1712): fixed storybook error

- packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
- packages/article-comments/__tests__/web/utils.test.js
- packages/article-comments/src/comments.js
- packages/article-comments/src/utils.js
When a user initially logs into an article page, dummy user details are used which means an incorrect display name is passed which will not trigger the functionality of the smart banner.
The issue of the dummy data is initially resolved and the correct values are stored into local storage. This pr simply reads the local storage data as a source of truth rather than data we get back from spotim which is dummy data.
https://nidigitalsolutions.jira.com/jira/software/c/projects/TDP/boards/1491?modal=detail&selectedIssue=TDP-2233
> fix (TDP-2233): get user details from local storage instead of openweb

- packages/article-byline/src/article-byline-with-links.js
This PR fixes the analytics for author bylines with links by changing the `onClick ` prop to `onPress`.
[TDP-2097](https://nidigitalsolutions.jira.com/browse/TDP-2097)
> fix(TDP-2097): Fix analytics for bylines with links

- lib/publish.sh
Simple fix for string comparison in bash which was causing error in the pipeline.
```
$ sh ./lib/publish.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
CircleCI commit: 92a0d600b183105d33f8c15780922bd630048793, Head commit: 92a0d600b183105d33f8c15780922bd630048793
./lib/publish.sh: 11: ./lib/publish.sh: [[: not found
```
> chore(TLP-00): Fix string comparasion.

- lib/publish.sh
- packages/message-bar/src/styles/shared.js
Attempting to fix broken pipeline as seen here https://app.circleci.com/pipelines/github/newsuk/times-components/6296/workflows/206dfa4d-9465-443b-a39a-df947fe2ad1b/jobs/43835
Simple fix for string comparison in bash which was causing error in the pipeline.
```
$ sh ./lib/publish.sh
Already on 'master'
Your branch is up to date with 'origin/master'.
CircleCI commit: 92a0d600b183105d33f8c15780922bd630048793, Head commit: 92a0d600b183105d33f8c15780922bd630048793
./lib/publish.sh: 11: ./lib/publish.sh: [[: not found
```
> Chore/tlp 00/fix/publish

- packages/article-comments/src/comments.js
This PR removes the feature flag from the real name commenting smart banner. There will be another ticket in Render for the timer function to show the smart banner on 29 December, which is during the code freeze.
[TDP-2429](https://nidigitalsolutions.jira.com/browse/TDP-2429)
> feat(TDP-2429): Remove feature flag from real name commenting smart banner

- packages/article-main-comment/src/article-main-comment.js
- packages/article-main-comment/src/article-prop-types/article-prop-types.base.js
- packages/article-main-standard/src/article-main-standard.js
- packages/article-main-standard/src/article-prop-types/article-prop-types.js
- packages/article-skeleton/__tests__/shared.base.js
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/article-body/article-body.js
- packages/article-skeleton/src/article-skeleton-prop-types.js
- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/static-content.js
- packages/ssr/src/client/article.js
- packages/ssr/src/component/article.js
- packages/ssr/src/server/article.js
This PR adds a static component to test if we can use it to allow Zephr to make changes to the page without React overwriting those things on the client side. This is behind a feature flag so won't display unless the flag is set.
If the flag is set, it just adds a div with no content with an id that we can use in Zephr to target and add content. If this is successful then we could markup the content with such divs and use Zephr to target them for transformations.
> chore: add an ssr only component to the article body for zephr

- packages/ts-newskit/src/components/navigation/Navigation.tsx
When we import newskit it doubles the bundle size in render for times-components 
This is a test to see if we import the components independently rather than `import { TextBlock } from 'newskit'` we hope that it will significantly reduce it.
> feat(TDP-000) POC - Import independent newskit components into ts-newskit package

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/src/styles/responsive.js
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/src/styles/responsive.js
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/src/newStyles/responsive.js
- packages/article-magazine-standard/src/styles/responsive.js
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/src/styles/responsive.js
On article pages, the headline and the standfirst are displaying bold, but they don’t need to be.
[JIRA-1148](https://nidigitalsolutions.jira.com/browse/TMRX-1148)
From the image above, you can see the fonts on the left, without bold applied, and on the right as they currently are, but are incorrect.
Both the H1 and the H2 on the template are using the browser default stylesheet formatting of using bold for Hx tags, bold doesn’t need to be applied as it is already bold in the fonts and a font weight of normal(400) should be used.
We need to apply font-weight: 400 to both of them so they display as on the left.
The font-weight is applied so that the fonts are displayed correctly.
Check all article templates and apply same if needed.
> fix(TMRX-1148): fonts displaying bold when they dont need tobe

- packages/article-skeleton/src/article-body/article-body.js
Related to previous change https://github.com/newsuk/times-components/pull/3314 
We don't want to render the Native Ad slot in articles on live/breaking.
> feat(TMRX-11172): Remove native ad again from live articles

- packages/article-skeleton/src/article-body/article-body.js
Reverts newsuk/times-components#3314
So a decision is yet to be made on whether editorial & product want this change. So we will probably revert this revert of a revert next week. But so we don't block times-components putting this in now until we get a concrete answer
> Revert "feat(TMRX-1172): Remove logic disabling ads on live/breaking articles"

- packages/ts-newskit/src/components/puzzles/flag/Flag.stories.mdx
[TMST-632](https://nidigitalsolutions.jira.com/browse/TMST-632)
**Description**
- Updated the component to use new 'puzzle-web-light' theme instead of 'times-web-light'.
[TMST-632]: https://nidigitalsolutions.jira.com/browse/TMST-632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMST-632): Flag component

- packages/article-image/__tests__/web/__snapshots__/article-image.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-list/__tests__/web/__snapshots__/article-list-error.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
- packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
- packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
- packages/image/src/image.js
- packages/related-articles/fixtures/standard/1-article-no-byline.json
- packages/related-articles/fixtures/standard/1-article-no-label.json
- packages/related-articles/fixtures/standard/1-article-video-lead.json
- packages/related-articles/fixtures/standard/1-article.js
- packages/related-articles/fixtures/standard/2-articles.js
- packages/related-articles/fixtures/standard/3-articles.js
- packages/ts-components/src/components/latest-from-section/__tests__/__snapshots__/LatestFromSection.test.tsx.snap
Updated the IMG that is used for **Related Images**, **More News...** and secondary and subsequent images in articles so that it uses the HTML property `loading="lazy"`
[TMRX-1181](https://nidigitalsolutions.jira.com/browse/TMRX-1181)
[TMRX-1181]: https://nidigitalsolutions.jira.com/browse/TMRX-1181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1181): added lazy loading to tc_images

- packages/ts-newskit/src/components/slices/lead-story/LeadStory.stories.mdx
- packages/ts-newskit/src/components/slices/lead-story/__tests__/index.test.tsx
- packages/ts-newskit/src/components/slices/lead-story/index.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/fixtures/data.json
- Allow for content to be placed below image
- Allow for different Headline sizes
[TMRX-1225](https://nidigitalsolutions.jira.com/browse/TMRX-1225)
[TMRX-1225]: https://nidigitalsolutions.jira.com/browse/TMRX-1225?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1225): update leadStory component to accommodate slice

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/head.test.js.snap
- packages/article-skeleton/__tests__/web/head.test.js
- packages/article-skeleton/src/head.js
- packages/provider-queries/src/article_web.graphql
[TMRX-1266](https://nidigitalsolutions.jira.com/browse/TMRX-1266)
Have updated query to return 5 latest tiles
have updated schema to output keywords value populated by sections 
[TMRX-1266]: https://nidigitalsolutions.jira.com/browse/TMRX-1266?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1266): update schema to have sections listed under keywords

- packages/ts-newskit/src/components/puzzles/cards-container/ScrollControls.tsx
- packages/ts-newskit/src/components/puzzles/cards-container/index.tsx
[TMST-695](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMST/boards/1608?modal=detail&selectedIssue=TMST-695)
- Made the 'See All' link optional in the cards container component.
[TMST-695]: https://nidigitalsolutions.jira.com/browse/TMST-695?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMST-695): Hide the 'See all' links from view

- packages/ts-newskit/src/components/slices/article/index.tsx
- packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/lead-article/index.tsx
- packages/ts-newskit/src/components/slices/lead-article/unorderedList.tsx
- packages/ts-newskit/src/components/slices/shared/grouped-article.tsx
- packages/ts-newskit/src/components/slices/shared/tag-and-flag.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-1/index.tsx
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/index.tsx
- packages/ts-newskit/src/slices/fixtures/data.json
- packages/ts-newskit/src/slices/fixtures/lead-story.json
- packages/ts-newskit/src/slices/fixtures/lead-story3.json
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/index.tsx
- packages/ts-newskit/src/slices/lead-story-1/lead-story-1.stories.mdx
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/article-stacks.tsx
- packages/ts-newskit/src/slices/lead-story-2/index.tsx
- packages/ts-newskit/src/slices/lead-story-2/lead-story-2.stories.mdx
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/article-stack.tsx
- packages/ts-newskit/src/slices/lead-story-3/index.tsx
- packages/ts-newskit/src/slices/shared-styles/index.ts
- packages/ts-newskit/src/slices/shared/article-stacks.tsx
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/stacked-module-1/index.tsx
This PR addresses an issue with the height of the divider component on the Safari browser. Previously, the divider had a fixed height of 100% as the default, which caused rendering issues specifically on Safari. To resolve this issue, I have made a modification by adding height: auto to the divider component.
> fix(TMRX-0000): apply design feedback

- packages/ts-newskit/src/components/puzzles/cards-container/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/__snapshots__/PuzzleCard.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
- packages/ts-newskit/src/components/puzzles/puzzle-card/styles.ts
- packages/ts-newskit/src/components/puzzles/story-card-listing/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/storyCard/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/storyCard/index.tsx
- packages/ts-newskit/src/components/puzzles/storyCard/styles.ts
Release-1 feedback: Text on puzzle cards jumps when image loads [TMST-726](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMST/boards/1608?modal=detail&selectedIssue=TMST-726)
- added limit for aspect ration on puzzle card and story card images
- if images is different aspect ration then 3/2, it will be readjusted to 3/2 ratio
- added lazy loading for images
[TMST-726]: https://nidigitalsolutions.jira.com/browse/TMST-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
>  feat(TMST-722): limited puzzle and story images sizes

- packages/ts-newskit/src/components/puzzles/cards-container/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/PuzzleCard.test.tsx
- packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/__snapshots__/PuzzleCard.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/styles.ts
Release-1 feedback: Text on puzzle cards jumps when image loads [TMST-726](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMST/boards/1608?modal=detail&selectedIssue=TMST-726)
- Added minimum height for puzzle card image wrapper so that it occupies the same space before the image loads.
- Added test case for puzzle card placeholder coverage
[TMST-726]: https://nidigitalsolutions.jira.com/browse/TMST-726?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMST-726): Text on puzzle cards jumps when image loads

- packages/ts-newskit/src/components/puzzles/puzzle-card/PuzzleCard.stories.mdx
- packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/__snapshots__/PuzzleCard.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/fixtures/data.json
Puzzle card - controls not working in story book [TMST-751](https://nidigitalsolutions.jira.com/browse/TMST-751)
- removed controls for date and status because these parameters are now passed trough data object
[TMST-751]: https://nidigitalsolutions.jira.com/browse/TMST-751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMST-751): removed puzzle card unecesary components

- packages/ts-newskit/src/index.ts
Just added the export for the Times themes for newskit 7
> chore(TMRX-0000): added export for newskit themes

- packages/ts-newskit/src/components/slices/lead-article/LeadArticle.stories.mdx
- packages/ts-newskit/src/components/slices/lead-article/__tests__/index.test.tsx
- packages/ts-newskit/src/components/slices/lead-article/index.tsx
- packages/ts-newskit/src/components/slices/shared/GroupedArticle.stories.mdx
- packages/ts-newskit/src/slices/fixtures/data.json
- packages/ts-newskit/src/slices/fixtures/lead-story.json
- packages/ts-newskit/src/slices/fixtures/lead-story3.json
Noticed that by formatting the summary in render to check for standfirst and then truncate the summary if not available, it added that summary to existing slices that shouldn't have a summary. We are able to avoid this by renaming the prop standfirst so that other slices don't pick it up. 
> fix(TMRX-1314): Replace props so that current slices not affected by summary formatting

- packages/ts-newskit/src/components/slices/slice-header/__tests__/index.test.tsx
- packages/ts-newskit/src/components/slices/slice-header/index.tsx
We need to pass the object name to the tracking event to map with the allow list. 
[TMRX-1312](https://nidigitalsolutions.jira.com/browse/TMRX-1312)
[TMRX-1312]: https://nidigitalsolutions.jira.com/browse/TMRX-1312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1312): Add object name to SliceHeader for tracking

- packages/jest-serializer/package.json
- packages/ts-newskit/package.json
- packages/ts-newskit/src/slices/fixtures/lead-story.json
- packages/ts-newskit/src/slices/fixtures/lead-story3.json
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/index.tsx
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/article-stack.tsx
- packages/ts-newskit/src/slices/lead-story-3/index.tsx
- yarn.lock
Himesh has requested that we show the image in mobile web for the first article in the lead 1 & 3 2 ices. 
Designs here: 
Lead 1 https://www.figma.com/file/C1K0ePqSX0irobX6lAMq7h/Sport-section?type=design&node-id=274%3A129455&mode=design&t=o5auQUx6vwJntLTS-1 - Connect your Figma account
Lead 3 https://www.figma.com/file/C1K0ePqSX0irobX6lAMq7h/Sport-section?type=design&node-id=274%3A178284&mode=design&t=o5auQUx6vwJntLTS-1 - Connect your Figma account 
Lead 1
Lead 3
> feat(TMRX-1444): Update image on mobile web for Lead 1 and Lead 3

- packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/create-menu.test.tsx.snap
- packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/navitems.test.tsx.snap
- packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-desktop.test.tsx.snap
- packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-desktop.test.tsx.snap
- packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-mobile.test.tsx.snap
- packages/ts-newskit/src/components/navigation/secondary-menu/desktop/create-menu.tsx
- packages/ts-newskit/src/components/navigation/secondary-menu/desktop/navItems.tsx
Padding on secondary nav should match the padding in place for top level nav as this is correct
Increase right margin on Menu item from 12px to 16px
[TMRX-1386](https://nidigitalsolutions.jira.com/browse/TMRX-1386)
[TMRX-1386]: https://nidigitalsolutions.jira.com/browse/TMRX-1386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1386): Fixed inconsistent padding between elements in L2 Nav

- README.md
- packages/ts-components/src/components/welcome-banner/WelcomeBanner.tsx
- packages/ts-components/src/components/welcome-banner/styles.ts
- packages/ts-styleguide/src/styleguide/colours/functional.tsx
This PR updates the design of the Welcome banner to make the title font bigger, make the background blue and change the alignment and line breaks at different breakpoints.
[TMG-914](https://nidigitalsolutions.jira.com/browse/TMG-914)
Old welcome banner:
Updated mobile design:
Updated design at larger breakpoints:
[TMG-914]: https://nidigitalsolutions.jira.com/browse/TMG-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMG-914): Update welcome banner design

- packages/ts-newskit/src/components/slices/slice-header/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/slice-header/index.tsx
- packages/ts-newskit/src/components/slices/slice-header/styles.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/index.tsx
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/index.tsx
- packages/ts-newskit/src/slices/shared/layouts.tsx
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
Add `min-height` style to Slice Header, to maintain minimum height when icon for link is not included.
Also, added spacing to slices through `CustomStackLayout`
[TMRX-1477](https://nidigitalsolutions.jira.com/browse/TMRX-1477)
[TMRX-1477]: https://nidigitalsolutions.jira.com/browse/TMRX-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1477): add min-height to slice header

- packages/article-skeleton/src/article-body/article-body.js
- packages/ts-components/src/components/article-header/ArticleBylineBlock.stories.tsx
- packages/ts-components/src/components/article-header/ArticleBylineBlock.tsx
- packages/ts-components/src/components/article-header/ArticleHeader.stories.tsx
- packages/ts-components/src/components/article-header/ArticleHeader.tsx
- packages/ts-components/src/components/article-header/__tests__/ArticleBylineBlock.test.tsx
- packages/ts-components/src/components/article-header/__tests__/ArticleHeader.test.tsx
- packages/ts-components/src/components/article-header/styles.ts
- packages/ts-components/src/types/related-article-slice.ts
Context
An update to the current live file separating block with the rule and fine and date to include a byline name and pic.
Purpose
We need this as the current way of using datawrapper byline pics get very heavy from a page load point of view so we are hoping this way would be much lighter
Requirements
It’d be great if this was really easy to update - so if we had some analysis from William Hague for example (!), we could quickly add his byline embed.
It would be great if the second line had enough space for us to be able to include a sentence of description with the author byline, thus helping google discover authors who are experts in their fields. 
Technical implementation: 
You can expect two new fields in the parameters data for the live dividers. One will be the slug name of the …
> feat(TMRX-1300): create article byline block

- packages/ts-newskit/src/theme/puzzles-web-light/index.ts
- packages/ts-newskit/src/theme/times-web-light-sport/index.tsx
- packages/ts-newskit/src/theme/times-web-light/index.tsx
- packages/ts-newskit/src/utils/__tests__/theme-formatting.test.tsx
- packages/ts-newskit/src/utils/theme-formatting.ts
Addition of function to support the addition of theme overrides using the `formatThemeOverrides` function
[TMRX-1495](https://nidigitalsolutions.jira.com/browse/TMRX-1495)
[TMRX-1495]: https://nidigitalsolutions.jira.com/browse/TMRX-1495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1495): update function to support addition of theme overrides

- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/content-bucket-1/index.tsx
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/content-bucket-2/index.tsx
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/content-bucket-3/index.tsx
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/lead-story-1/index.tsx
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/lead-story-2/index.tsx
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/section-bucket/index.tsx
Initialise the components with a breakpoint value so they don't render as empty components before client side breakpoint is found. 
This doesn't entirely fix the loading issue as we use breakpointKey to manipulate data etc. But is an improvement in the meantime before we introduce our refactor. 
[TMRX-1529](https://nidigitalsolutions.jira.com/browse/TMRX-1529)
[TMRX-1529]: https://nidigitalsolutions.jira.com/browse/TMRX-1529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(TMRX-000): Add initial breakpoint state to resolve empty loading stat

- packages/ts-components/src/components/article-header/ArticleHeader.tsx
We are calling the fetch to /api/author-profile even if we don't have an author. This adds a check so that we don't call the route with undefined
[TMRX-1577](https://nidigitalsolutions.jira.com/browse/TMRX-1577)
[TMRX-1577]: https://nidigitalsolutions.jira.com/browse/TMRX-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1577): Dont call fetch if authorSlug is undefined

- packages/ts-newskit/src/components/slices/article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/article/index.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
Add lazy loading to images that aren't lead images
[TMRX-1580](https://nidigitalsolutions.jira.com/browse/TMRX-1580)
[TMRX-1580]: https://nidigitalsolutions.jira.com/browse/TMRX-1580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1580): Add lazy loading to images that aren't lead images

- packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/shared-styles/index.ts
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
Some of the styles weren't being applied because they were wrapped in quotes. Oops. This was causing the image to overlap the caption.
> fix(TMRX-000): Remove quotes around styles

- packages/ts-newskit/src/components/slices/shared/articleTileInfo.tsx
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
The video icon isn't working in render because it points to an image which we don't have. For now I have removed the icon, and will ask design to provide a full SVG for the icon. 
Small change to styling as in the design the video label does not have a brand colour applied to it. 
[Design](https://www.figma.com/file/zYjnqWXVY0cFFaJgcSqM5M/Section-Slices?type=design&node-id=3019-241814&mode=design&t=E27GNkj82g43QA9Y-0)
-- Current behaviour in staging
-- Now in storybook
> fix(TMRX-1594): Remove video icon for now as the iamge doesnt work in render

- packages/ts-newskit/src/components/slices/slice-header/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/slice-header/index.tsx
- packages/ts-newskit/src/components/slices/slice-header/styles.tsx
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
The slice header has a hover state and the cursor changes when you hover over it as default. It needs to only do this if there is a link on the block title. See - https://www.thetimes.co.uk/sport/all-sport
- Slice header behaves as clickable if there is a link
- Slice header behaves as text if no link.
[JIRA-1617](https://nidigitalsolutions.jira.com/browse/TMRX-1617)
> fix(TMRX-1617): only render slice header as link if href is provided

- packages/ts-newskit/src/assets/VideoIcon.tsx
- packages/ts-newskit/src/assets/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/shared/articleTileInfo.tsx
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
Design sent us a new SVG for the video Icon so have included that again.
> fix(TMRX-000): Add new video Icon SVG

- packages/ts-components/src/components/recommended-articles/RecommendedFetch.tsx
- packages/ts-components/src/components/recommended-articles/__tests__/RecommendedFetch.test.tsx
- packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedFetch.test.tsx.snap
When I visit an article and scroll towards the end of the article
I want to be presented with recommended articles
So that I can discover content of interest to me (and continue reading)
The today’s section rail is titled: Read more (need final decision on heading from @Tim Arbabzadah ) - :white_check_mark:  Agreed 2/11
This is presented across all articles (from all sections)
Description
Given I’m a web user
And I visit an article page
When I scroll to the end of an article
And I’m presented with the today’s section rail
Then the title of the rail reads: Read more
Reason for change
To avoid a recurring issue whereby the title is presented as Today’s unknown section
[JIRA-1634](https://nidigitalsolutions.jira.com/browse/TMRX-1634)
> fix(TMRX-1634): change today's rail title

- packages/ts-newskit/src/components/puzzles/article-sidebar/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/article-sidebar/index.tsx
- packages/ts-newskit/src/components/puzzles/article-sidebar/styles.ts
- packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts
Fixed below feedback on the article sidebar.
"Please darken the circle on hover, but the chevron should stay orange."
[TMPZ-249](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMPZ/boards/1656?selectedIssue=TMPZ-249)
[TMPZ-249]: https://nidigitalsolutions.jira.com/browse/TMPZ-249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMPZ-249): update puzzle sidebar

- .circleci/config.yml
Lerna [version 8](https://github.com/lerna/lerna/releases) expects Node 18+
This PR keeps Lerna below version 8 so we do not have to update Node (yet!).
> fix(TM-000): Add specific Lerna version

- packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/shared-styles/index.ts
- packages/ts-newskit/src/components/slices/shared/articleTileInfo.tsx
- packages/ts-newskit/src/components/slices/shared/customTextBlock.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-4/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
Reverts changes to article tile info to unblock other PRs.
> fix(TMRX-1578): revert article tile info line break changes

- packages/article-skeleton/src/contentModifiers/newsletter-puff.js
Automated newsletter puff is not showing the article under Irish Sport section.
[JIRA-1550](https://nidigitalsolutions.jira.com/browse/TMRX-1550)
> fix(TMRX-1550): newsletter puff not appearing in irish sport section

- packages/ts-newskit/src/slices/lead-story-4/mobile.tsx
This PR is an initial change for Lead Story 5. Given the similarity between Lead Story 5 and Lead Story 4, this pull request is focused on disabling scrollable article summaries in Lead Story 4 for mobile devices
before 
after
> feat(TMRX-0000): disable summary for mobile

- packages/ad/src/ad-container.js
- packages/ssr/__tests__/helpers/author-profile-helper.js
- packages/ssr/__tests__/helpers/topic-helper.js
The commercial team are expecting `ad-article-inline` as the id of the ad container on topic and author pages that use the articleList component. 
[TMRX-1745](https://nidigitalsolutions.jira.com/browse/TMRX-1745)
[TMRX-1745]: https://nidigitalsolutions.jira.com/browse/TMRX-1745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1745): Fix ads on list view slice

- packages/article-main-comment/src/article-header/article-header.js
This is a fix for `comment` template articles not having a byline [TMRX-1768](https://nidigitalsolutions.jira.com/browse/TMRX-1768)
[TMRX-1768]: https://nidigitalsolutions.jira.com/browse/TMRX-1768?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1768): Check a byline exists

- packages/ts-newskit/src/components/slices/lead-article/index.tsx
- packages/ts-newskit/src/components/slices/shared/tag-and-flag.tsx
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/mobile.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/index.tsx
- packages/ts-newskit/src/slices/types.ts
the byline is currently appearing in the Tag and Flag section below the summary or short summary. The byline should be removed specifically from these sections, excluding the List View slice.
Byline should not be displayed in the Tag and Flag section(below the summary , short summary or headline) in slices other than the List View.
[JIRA-1806](https://nidigitalsolutions.jira.com/browse/TMRX-1806)
> fix(TMRX-1806): remove byline from tag and flag

- .circleci/config.yml
```
The version of Java (11.0.11) used to run this analysis is deprecated, and SonarCloud no longer supports it. Please upgrade to Java 17 or later.
As a temporary measure, you can set the property 'sonar.scanner.force-deprecated-java-version' to 'true' to continue using Java 11.0.11
This workaround will only be effective until January 28, 2024. After this date, all scans using the deprecated Java 11 will fail.
ERROR: 
ERROR: Re-run SonarScanner using the -X switch to enable full debug logging.
https://app.circleci.com/pipelines/github/newsuk/cps-content-render/74737/workflows/4631d25f-a097-4e58-b9b7-f478fd9d37d9/jobs/444196
````
<b>Acceptance Criteria</b>
<div>
Update SonarCloud Orbs version
</div>
[TMP-663](https://nidigitalsolutions.jira.com/browse/TMP-663)
Include screenshots if …
> chore(TMP-663): Bump sonarcloud orb version to the latest one.

- packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/lead-article/index.tsx
- packages/ts-newskit/src/components/slices/shared/tag-and-flag.tsx
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-4/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/mobile.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/desktop.test.tsx
- packages/ts-newskit/src/slices/list-view-slice/data.json
- packages/ts-newskit/src/slices/list-view-slice/pagination.tsx
- packages/ts-newskit/src/slices/types.ts
TMRX-1822: Conditionally render a link for the byline, which will bring viewer to  journalists profile page when clicked
TMRX-1828: Increase spacing between label and headline from 8px to 12px in LeadArticle component
TMRX-1829: Update pagination to remove first/last and truncated navigation buttons to mitigate performance related issues in Render with current paginated data from TPA. This will be reintroduced once CP team has updated data response and query to utilise de-duped cursor based paginated data.
[TMRX-1826](https://nidigitalsolutions.jira.com/browse/TMRX-1826)
[TMRX-1826]: https://nidigitalsolutions.jira.com/browse/TMRX-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1826): update pagination, spacing and make byline clickable

- packages/responsive/package.json
- packages/ts-newskit/src/components/slices/slice-header/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/slice-header/styles.tsx
- packages/ts-newskit/src/slices/list-view-slice/__tests__/desktop.test.tsx
- packages/ts-newskit/src/slices/list-view-slice/__tests__/index.test.tsx
- packages/ts-newskit/src/slices/list-view-slice/__tests__/mobile.test.tsx
- packages/ts-newskit/src/slices/list-view-slice/index.tsx
- packages/ts-newskit/src/slices/list-view-slice/list-view-slice.stories.mdx
- packages/ts-newskit/src/slices/list-view-slice/mobile.tsx
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/utils/package.json
Add `useBreakpointKey` hook to conditionally render mobile/desktop views
* Updated to add new slot (`SectionAdMob`) for mobile, instead of using `usebreakpointKey` hook
[TMRX-1879](https://nidigitalsolutions.jira.com/browse/TMRX-1879)
[TMRX-1879]: https://nidigitalsolutions.jira.com/browse/TMRX-1879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRX-1879): list view ads not loading

- packages/ts-newskit/src/components/slices/article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/article/index.tsx
- packages/ts-newskit/src/components/slices/comment-card/__tests__/__snapshots__/comment-card.test.tsx.snap
- packages/ts-newskit/src/components/slices/comment-card/index.tsx
- packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/slices/lead-article/index.tsx
- packages/ts-newskit/src/slices/comment-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/lead-story-4/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/mobile.test.tsx.snap
- packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
- fixed slightly narrowed External content images
**Before:**
**After:**
[TNLBT-1219](https://nidigitalsolutions.jira.com/browse/TNLBT-1219?atlOrigin=eyJpIjoiM2IxMjNiMTdhMzI5NGNjMTkxN2M2ZjU2N2E0Yjc0YTAiLCJwIjoiaiJ9)
[TNLBT-1219]: https://nidigitalsolutions.jira.com/browse/TNLBT-1219?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TNLBT-1219): slightly narrowed images on channel pages

- packages/ts-newskit/src/components/navigation/breadcrumb/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/theme/times-web-light/style-presets/breadcrumb.ts
Updates active breadcrumb styling to appear as a link (uses the base styling tokens). 
[JIRA-1902](https://nidigitalsolutions.jira.com/browse/TMRX-1902)
**The below screenshots show the item being hovered**
**Before**
**After**
> feat(TMRX-1902): update active breadcrumb styling

- packages/ad/src/ad.js
- packages/article-skeleton/__tests__/web/inline-ad.test.js
- packages/article-skeleton/fixtures/inline-ad.js
- packages/article-skeleton/src/contentModifiers/inline-ad.js
- packages/article-skeleton/src/contentModifiers/native-ad.js
We have been asked to update our ad placements in articles to display after 5, 10, 15, 20 & 25 paragraphs instead of the current 5, 9, 13, 20, 27. 
[TMRX-1962](https://nidigitalsolutions.jira.com/browse/TMRX-1962)
Have made a [comparison document](https://nidigitalsolutions.jira.com/wiki/spaces/TNLDigital/pages/4751425645/Ad+placement+change+-+5+10+15+20+25) to show the difference across a few different articles.
[TMRX-1962]: https://nidigitalsolutions.jira.com/browse/TMRX-1962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRX-1962): Update ad placement in articles

- packages/ts-newskit/src/components/puzzles/article-sidebar/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/article-sidebar/index.tsx
- packages/ts-newskit/src/components/puzzles/article-sidebar/styles.ts
Implemented a fix for the Article sidebar jumping issue that occurs when the placeholder is loading.
> feat(TMPZ-000) : Article Sidebar placeholder changes

- packages/ts-newskit/src/components/puzzles/cards-container/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/PuzzleCard.stories.mdx
- packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/__snapshots__/PuzzleCard.test.tsx.snap
- packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
- packages/ts-newskit/src/components/puzzles/puzzle-card/styles.ts
To add the background color for the puzzle tiles.
[TMPZ-368](https://nidigitalsolutions.jira.com/browse/TMPZ-368)
[TMPZ-368]: https://nidigitalsolutions.jira.com/browse/TMPZ-368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMPZ-368): Use transparent icons for puzzle tiles and add a background color, enabling same images to be used on sidebar

- packages/video/src/inline-video-player.js
Fixes the following bugs with the video play button:
1. Double video icon on older chrome versions
2. On Safari the icon appears to jump when hovering over the player
[JIRA-1734](https://nidigitalsolutions.jira.com/browse/TMRX-1734)
**Before**
https://github.com/newsuk/times-components/assets/142982056/3bc26af6-c19f-4756-b08d-c537e6c7b661
**After**
https://github.com/newsuk/times-components/assets/142982056/ec16459c-7ca5-49de-b891-f079ec3ac669
> fix(TMRX-1734): video play button bugs

- packages/article-skeleton/src/styles/responsive.js
- packages/ts-newskit/src/components/misc/banner/__tests__/__snapshots__/banner.test.tsx.snap
- packages/ts-newskit/src/components/misc/banner/styles.ts
Implemented banner using the Newskit Design system for verify-email reminder 
[TMG-1344](https://nidigitalsolutions.jira.com/browse/TMG-1344)
[TMG-1344]: https://nidigitalsolutions.jira.com/browse/TMG-1344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Feat(TMD-000): Added banner stylings

- packages/image/src/image.js
After further investigation, it seems react sends the requests through with a null value to start, then replaces it with the highRes value when it knows what dimensions are on board, this means for some images it's asking for the full size before the restricted one, which can be MB's in size, so have put a default small value to restrict this.
[TMD-177](https://nidigitalsolutions.jira.com/browse/TMD-177)
[TMD-177]: https://nidigitalsolutions.jira.com/browse/TMD-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMD-177): remove low res and set a small default

- .circleci/config.yml
- .storybook/vendor.webpack.config.js
- .storybook/webpack.config.js
- package.json
- packages/ssr/src/standalone-renderer/webpack.config.js
- packages/ssr/webpack.config.js
- packages/webpack-configurator/src/configurator.js
Upgrade to Node `18.19.1` https://nidigitalsolutions.jira.com/browse/TMRX-1881
Webpack and certain Webpack plugins use MD4 hashing algorithm which is no longer available in OpenSSL 3.0+ which ships with Node 17+. In order to continue using the legacy algorithm this PR creates a proxy function which swaps `md4` for `sha256`.
_**This is the current workaround but the full solution should be to upgrade Webpack and other dependancies to work correctly without falling back to insecure functions.**_
> chore(TMW-000): Node 18 upgrade

- packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.tsx
- packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/OptaFootballFixturesTicker.test.tsx
- packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
- packages/ts-components/src/components/opta/football/fixtures/__tests__/__snapshots__/OptaFootballFixtures.test.tsx.snap
- packages/ts-components/src/components/opta/football/match-stats/__tests__/__snapshots__/OptaFootballMatchStats.test.tsx.snap
- packages/ts-components/src/components/opta/football/shared-styles.ts
- packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.stories.tsx
- packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.tsx
- packages/ts-components/src/components/opta/football/standings/__tests__/OptaFootballStandings.test.tsx
- packages/ts-components/src/components/opta/football/standings/__tests__/__snapshots__/OptaFootballStandings.test.tsx.snap
- packages/ts-components/src/components/opta/football/standings/styles.ts
- packages/ts-components/src/components/opta/football/summary/__tests__/__snapshots__/OptaFootballSummary.test.tsx.snap
- packages/ts-components/src/components/opta/utils/__tests__/replaceNationalTeamDetails.test.tsx
- packages/ts-components/src/components/opta/utils/replaceNationalTeamDetails.ts
- packages/ts-components/src/components/opta/utils/useUpdateNationalTeamDetails.tsx
Updates `Standings` football widget from OPTA, to replace flags for Euros
- update function that replaced flags to use CSS background image, to prevent images being removed in re-render on Standings
[TMRS-211](https://nidigitalsolutions.jira.com/browse/TMRS-211)
[TMRS-211]: https://nidigitalsolutions.jira.com/browse/TMRS-211?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRS-211): update standings widget and replace flags function

- packages/article-list/__tests__/web/__snapshots__/article-list-error-with-styles.web.test.js.snap
- packages/image/__tests__/web/__snapshots__/image-with-style.web.test.js.snap
- packages/image/src/image.js
- packages/ts-components/src/components/latest-from-section/__tests__/__snapshots__/LatestFromSection.test.tsx.snap
so that image spaces where images are loading are defined and don't look like washed out white areas of the page
By removing the placeholder it removed the definition or outline of the page where images are loaded into, so by putting the background colour in it returns the definition, without the complication of the placeholder removed with [TMD-329](https://nidigitalsolutions.jira.com/browse/TMD-329)
[TMD-000](https://nidigitalsolutions.jira.com/browse/TMD-000)
[TMD-329]: https://nidigitalsolutions.jira.com/browse/TMD-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMD-529): add background colour to image container

- packages/article-skeleton/fixtures/inline-ad.js
- packages/article-skeleton/src/contentModifiers/inline-ad.js
Update article ad positions from BEFORE paragraph (10 for example) to AFTER paragraph (9)
> feat(TMW-000): Update article ad positions

- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/ts-components/src/components/article-sidebar/ArticleSidebar.tsx
- packages/ts-components/src/components/article-sidebar/__tests__/__snapshots__/index.test.tsx.snap
- packages/ts-components/src/components/article-sidebar/styles.ts
Header color to match the brand color
[TMPZ-546](https://nidigitalsolutions.jira.com/browse/TMPZ-546)
[TMPZ-546]: https://nidigitalsolutions.jira.com/browse/TMPZ-546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMPZ-546): Puzzle sidebar headline Color should be updated

- packages/ts-components/src/components/features-carousel/FeaturesCarousel.tsx
- packages/ts-components/src/components/features-carousel/__tests__/index.test.tsx
- packages/ts-components/src/components/features-carousel/features-carousel.stories.mdx
- packages/ts-components/src/components/features-carousel/fixtureData.json
Conditionally hide the `Header` of the `FeaturesCarousel` to enable us to conditionally use the container slice header for edition pages
[TMRS-593](https://nidigitalsolutions.jira.com/browse/TMRS-593)
[TMRS-593]: https://nidigitalsolutions.jira.com/browse/TMRS-593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRS-593): update benefits rail

- packages/article-skeleton/fixtures/newsletter.js
- packages/article-skeleton/src/contentModifiers/newsletter-puff.js
- packages/ts-components/src/components/newsletter-puff/NewsletterPuff.stories.tsx
- packages/ts-components/src/components/newsletter-puff/__tests__/AutoNewsletterPuff.test.tsx
What
Update to the title of the Best of Times newsletter to Daily Briefing 
Why
The Best of Times newsletter has been rebranded to become the Daily Briefing
Scope
Automated on-click newsletter sign up component presented within articles
Technical Notes
Relevant notes that would be useful for any dev picking this story up
Design + QA Notes for handoff (To be filled in while on the board)
Any relevant design notes of what to test, build numbers, etc. as well as QA notes that should be called out before the story is move across the board
Component currently:
The title now renders as Daily Briefing when the automated on-click newsletter sign up component is presented within articles 
[JIRA-1082](https://nidigitalsolutions.jira.com/browse/TMD-1082)
> feat(TMD-1082): update to newsletter title within on click sign up com

- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/src/styles/shared.js
Margin was mistakenly added in this PR [#3984](https://github.com/newsuk/times-components/pull/3984)
> fix(TMW-000): Broken header style

- packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.stories.tsx
- packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.tsx
- packages/ts-components/src/components/opta/cricket/scorecard/__tests__/__snapshots__/OptaCricketScorecard.test.tsx.snap
- packages/ts-components/src/components/opta/cricket/shared-styles.ts
- packages/ts-components/src/components/opta/football/fixtures-tournament/__tests__/__snapshots__/OptaFootballFixturesTournament.test.tsx.snap
- packages/ts-components/src/components/opta/football/fixtures/__tests__/__snapshots__/OptaFootballFixtures.test.tsx.snap
- packages/ts-components/src/components/opta/football/match-stats/OptaFootballMatchStats.tsx
- packages/ts-components/src/components/opta/football/match-stats/__tests__/__snapshots__/OptaFootballMatchStats.test.tsx.snap
- packages/ts-components/src/components/opta/football/player-stats/OptaFootballPlayerStats.tsx
- packages/ts-components/src/components/opta/football/player-stats/__tests__/__snapshots__/OptaFootballPlayerStats.test.tsx.snap
- packages/ts-components/src/components/opta/football/shared-styles.ts
- packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.stories.tsx
- packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.tsx
- packages/ts-components/src/components/opta/football/standings/__tests__/__snapshots__/OptaFootballStandings.test.tsx.snap
- packages/ts-components/src/components/opta/football/summary/__tests__/__snapshots__/OptaFootballSummary.test.tsx.snap
- Height attribute added to OPTA widgets. Where this is fixed, as with the `OptaFootballFixturesTicker` the height has been entered as the default value.
- Support for breakpoint specific `height` attributes have been added to our iframe component;
e.g. 
```
attributes: {
...
height: {
xs: number;
sm: number;
md: number;
lg: number;
}
}
```
NB: These height values will need to be configured in NewsPress for use in articles.
[TMRS-586](https://nidigitalsolutions.jira.com/browse/TMRS-586)
[TMRS-586]: https://nidigitalsolutions.jira.com/browse/TMRS-586?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRS-586): add heights to opta widgets

- packages/ts-components/src/components/newsletter-puff/InlineNewsletterPuff.tsx
- packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/AutoNewsletterPuff.test.tsx.snap
- packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/InlineNewsletterPuff.test.tsx.snap
- packages/ts-components/src/components/newsletter-puff/preview-newsletter-puff/__tests__/__snapshots__/PreviewNewsletterPuff.test.tsx.snap
- packages/ts-components/src/components/newsletter-puff/styles.ts
We have been investigating CLS on the website and the automated newsletter puff has been flagged. See video below - the loading state doesn’t match the component and is causing layout shift. 
Would be good to get a lighthouse test on it (WebPageTest won’t work as won’t meet the user criteria for rendering it) before and after to note whether it has improved the CLS score. 
Check the manually placed Newsletter as well as I believe it’s the same component but could have different loading states, this video is the automated one. Example article: Signs of insider dealing detected in a third of UK takeover bids 
[JIRA-1221](https://nidigitalsolutions.jira.com/browse/TMD-1221)
> fix(TMD-1221): update newsletter puff loading

- packages/ts-components/src/components/cta-button/CtaButton.tsx
- packages/ts-components/src/components/cta-button/__tests__/CtaButton.test.tsx
The CTA button should not appear if there are no text or url entered.
[TMC-319](https://nidigitalsolutions.jira.com/browse/TMC-319)
[TMC-319]: https://nidigitalsolutions.jira.com/browse/TMC-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tmc-319): Button not visible if text is empty

- packages/ts-components/src/components/article-cards/Card/Card.tsx
- packages/ts-components/src/components/article-cards/Card/styles.ts
- packages/ts-components/src/components/article-cards/__tests__/Card.test.tsx
Fix article cards images
[TMC-328](https://nidigitalsolutions.jira.com/browse/TMC-328)
[TMC-328]: https://nidigitalsolutions.jira.com/browse/TMC-328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tmc-328): Fix article cards images

- packages/article-skeleton/src/article-skeleton.js
- packages/article-skeleton/src/contentModifiers/reorder-interactive-before-ad.js
Added logic that tracks elements in article and on every occurrence of ad dividing cta button from paragraph, we reorder and put cta button above advertisment.
[TMC-339](https://nidigitalsolutions.jira.com/browse/TMC-339)
BEFORE:
AFTER:
[TMC-339]: https://nidigitalsolutions.jira.com/browse/TMC-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feature(TMC-339): Added logic which reorders interactive and ad elements in article

- packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
- packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
- packages/article-skeleton/src/styles/article-body/responsive.js
Advertisement label - H2 tag is changed to <span> on Article template.
[TMC-362](https://nidigitalsolutions.jira.com/browse/TMC-362)
[TMC-362]: https://nidigitalsolutions.jira.com/browse/TMC-362?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(tmc-362): change ad label from h2 to span

- packages/article-skeleton/src/contentModifiers/map-list-elements.js
Fixes indentation issue with unordered lists rendering within paywalled content as they were not mapped correctly.
[TMRP-193](https://nidigitalsolutions.jira.com/browse/TMRP-193)
**BEFORE**
**AFTER**
[TMRP-193]: https://nidigitalsolutions.jira.com/browse/TMRP-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRP-193): indents on unordered lists

- packages/article-skeleton/src/contentModifiers/map-list-elements.js
Fixes indentation issue with unordered lists rendering within paywalled content as they were not mapped correctly.
**This change makes sure we swap the paywalled content for the mapped content.**
[TMRP-193](https://nidigitalsolutions.jira.com/browse/TMRP-193)
**BEFORE**
**AFTER**
[TMRP-193]: https://nidigitalsolutions.jira.com/browse/TMRP-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMRP-193): fix indents on unordered lists

- .circleci/config.yml
- packages/article-extras/src/article-extras.js
- packages/article-skeleton/src/article-skeleton.js
- packages/save-and-share-bar/__tests__/shared.base.js
- packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
- packages/save-and-share-bar/src/save-and-share-bar.js
- packages/save-and-share-bar/src/styled.js
- packages/user-state/src/matchers.js
- packages/utils/__tests__/check-for-symphony-experiment.test.js
- packages/utils/__tests__/get-base64-cookie-value.test.js
- packages/utils/__tests__/get-cookie-value.test.js
- packages/utils/src/check-for-symphony-experiment.js
- packages/utils/src/get-base64-cookie-value.js
- packages/utils/src/get-cookie-value.js
- packages/utils/src/index.js
During Project Symphony, when all articles will be open to all users, we would like to emphasise the "share" feature on articles. This PR adds a flashing blue dot to the share button and logic to only show it during Project Symphony (as determined by the `nuk_zephr_decisions` cookie) and only before the button is clicked. Once the share button has been clicked the blue dot should no longer be visible.
[TMG-3003](https://nidigitalsolutions.jira.com/browse/TMG-3003)
Without the blue dot:
With the blue dot:
[TMG-3003]: https://nidigitalsolutions.jira.com/browse/TMG-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(TMG-3003): Add blue dot to share button

- packages/article-extras/src/article-extras.js
- packages/article-skeleton/src/article-skeleton.js
It has been decided that we want all users to see the share button.
This PR removes the `<UserState>` wrapper around the `<SaveAndShareBar>`.
> feat(TMG-000): Remove SaveAndShareBar UserState logic

- packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/InlineNewsletterPuff.test.tsx.snap
- packages/ts-components/src/components/newsletter-puff/newsletter/Newsletter.tsx
[TMRA-193](https://nidigitalsolutions.jira.com/browse/TMRA-193)
This one fixes a typo (`succesfully`) and adds `the` on signup to newsletter.
`You've succesfully signed up to` is now `You've successfully signed up to the`
[TMRA-193]: https://nidigitalsolutions.jira.com/browse/TMRA-193?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRA-193): fix newsletter signup typo

- packages/article-skeleton/src/article-skeleton.js
If the `removeTeaserContent` feature flag is active - remove all content from the teaser article page.
> chore(TMW-000): Remove teaser article extras

- packages/article-in-depth/src/article-in-depth.js
add `paidContentClassName` parameter to resolve value for `cssSelector` in article-in-depth template.
[TMRA-264](https://nidigitalsolutions.jira.com/browse/TMRA-264)
[TMRA-264]: https://nidigitalsolutions.jira.com/browse/TMRA-264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(TMRA-264): resolve cssSelector value on in-depth template

- packages/article-skeleton/src/head.js
The Live blogs are seeing less traffic than usual and Google Search Console is reporting Crawl issues which could be the cause of the issue.
We need to ensure that all articles crawled have no issues. In particular the Live Blog articles which are critical for converting traffic into paid subscribers.
The videos posts within the live blogs articles should all have the Missing or recommended fields.
Currently, the description field is missing from video posts within Live Blog articles. This ticket is to add that field to resolve the following warning:
Missing field 'description' (optional)
Live Blogs need to have all missing attributes
Missing field 'uploadDate'
Missing field 'name'
Missing field 'thumbnailUrl'
Missing field 'description' (optional)
Either 'contentUrl' …
> fix(TMPR-520): add missing description to live blog articles
