newsuk/times-components

LICENSE
package.json

Updates the Author in both package.json and LICENSE file

chore: updates author name

---

package.json
yarn.lock

Corrects the hoisting flag that was being passed improperly to `lerna bootstrap`

fix: correct hoisting flag

---

lib/cli/cli.js
lib/cli/package-json.js
package.json
yarn.lock

Runs `prettier --write` on the staged .js files using [lint-staged](https://github.com/okonet/lint-staged).
Also moved the `pre-commit` dep to dev deps.

Run prettier --write on pre-commit hook

---

.travis.yml

chore: add yml file

---

.travis.yml
README.md
package.json

Now when you run `yarn test` in root as a precommit hook, your commit doesnt fail.

Coverage only in ci

---

package.json

fix: ignore node_modules

---

lib/cli/cli.js
lib/cli/cli.test.js
lib/cli/package-json.js
lib/cli/templates.js

chore: lint output and change command

---

.storybook/config.js

Restricts stories to the ones found on each component folder

fix: update storybook path regex

---

.bithoundrc
.storybook.native/addons.js

bug: fixes native action logger

---

package.json
yarn.lock

upgrades eslint to 4.2

---

package.json
yarn.lock

Reverts newsuk/times-components#51

Revert "upgrades eslint to 4.2"

---

package.json

chore: remove fructose from precommit

---

packages/markup/LICENSE
packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
packages/markup/__tests__/__snapshots__/markup.web.test.js.snap
packages/markup/__tests__/markup.native.test.js
packages/markup/__tests__/markup.web.test.js
packages/markup/__tests__/test-helper.js
packages/markup/fixtures/anchor.json
packages/markup/fixtures/bio.json
packages/markup/fixtures/bold.json
packages/markup/fixtures/image.json
packages/markup/fixtures/italic.json
packages/markup/fixtures/multi-paragraph.json
packages/markup/fixtures/nested.json
packages/markup/fixtures/script.json
packages/markup/fixtures/single-paragraph.json
packages/markup/fixtures/span.json
packages/markup/fixtures/tag-mixture.json
packages/markup/markup-builder.js
packages/markup/markup-proptype.js
packages/markup/markup.js
packages/markup/markup.stories.js
packages/markup/markup.web.js
packages/markup/package.json

feat: add markup component with tests

---

packages/card/yarn.lock

fix: update yarn.lock file on card component

---

.storybook/head.html
packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
packages/author-head/author-head.js

fix: use correct fonts

---

packages/brightcove-video/__tests__/__snapshots__/brightcove-video.test.js.snap
packages/brightcove-video/__tests__/brightcove-video.test.js
packages/brightcove-video/__tests__/brightcove-video.web.test.js
packages/brightcove-video/android/rntbrightcovevideo/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveManager.java
packages/brightcove-video/android/rntbrightcovevideo/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveView.java
packages/brightcove-video/brightcove-video.defaults.js
packages/brightcove-video/brightcove-video.js
packages/brightcove-video/brightcove-video.proptypes.js
packages/brightcove-video/brightcove-video.stories.js
packages/brightcove-video/brightcove-video.web.js
packages/brightcove-video/fixtures/video-adder.js
packages/brightcove-video/fixtures/video-with-external-controls.js
packages/brightcove-video/ios/RNTBrightcove.h
packages/brightcove-video/ios/RNTBrightcove.m
packages/brightcove-video/ios/RNTBrightcoveManager.m
yarn.lock

https://nidigitalsolutions.jira.com/browse/REPLAT-280

feat: Add support of brightcovePolicyKey and brightcovePlayerId

---

packages/brightcove-video/brightcove.ios.fructose.js
packages/brightcove-video/ios/RNTBrightcove.m

`yarn test:fructose` to test
you need to `yarn ios` first if you don't have the storybook app built
you may also need to follow the instructions in the contributing under testing if you've never run fructose before.

test: brightcove fructose tests

---

.eslintrc.json

fix: invalid eslintrc.json because missing comma

---

packages/brightcove-video/ios/RNTBrightcove.h
packages/brightcove-video/ios/RNTBrightcove.m

improves ios code for brightcove player

---

packages/brightcove-video/.npmignore

chore: add ignore file

---

packages/pagination/LICENSE
packages/pagination/__snapshots__/pagination.test.js.snap
packages/pagination/package.json
packages/pagination/pagination.js
packages/pagination/pagination.stories.js
packages/pagination/pagination.test.js

feat: pagination component

---

packages/card/__tests__/__snapshots__/card.test.js.snap
packages/card/card.js
packages/pagination/package.json

Remove padding from a card, this is a responsibility of the container.
Also rewrote the styles to avoid calling a function and creating a stylesheet on the render method.

feat: remove padding from card and adjust other styles

---

ios/storybooknative/AppDelegate.m
packages/article-summary/article-summary.js
packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
packages/author-head/author-head.js
packages/author-head/fixtures/profile.json
packages/author-profile/LICENSE
packages/author-profile/__snapshots__/author-profile.test.js.snap
packages/author-profile/author-profile-footer.js
packages/author-profile/author-profile-header.js
packages/author-profile/author-profile-item-separator.js
packages/author-profile/author-profile-item.js
packages/author-profile/author-profile.js
packages/author-profile/author-profile.stories.js
packages/author-profile/author-profile.test.js
packages/author-profile/author-profile.web.js
packages/author-profile/example.json
packages/author-profile/package.json
packages/card/__tests__/__snapshots__/card.test.js.snap
packages/card/card.js
packages/image/image.js
packages/pagination/__snapshots__/pagination.test.js.snap
packages/pagination/pagination.js
yarn.lock

feat: author profile page

---

packages/article/__snapshots__/article.test.js.snap
packages/article/article-content.js
packages/article/package.json

feat: add article flag to article

---

packages/article-flag/__snapshots__/article-flag.test.js.snap
packages/article-flag/article-flag.js
packages/article/__snapshots__/article.test.js.snap

feat: beautify title

---

packages/article-flag/article-flag.js

fix: article flag typo

---

lib/cli/package-json.js

Can we add this to CLI? every package has it and every time we create a new one using the CLI, we need to add the prop-types.

Proposal: add prop-types in cli package.json

---

packages/article-label/.npmignore
packages/article-label/LICENSE
packages/article-label/__snapshots__/article-label.test.js.snap
packages/article-label/article-label.js
packages/article-label/article-label.stories.js
packages/article-label/article-label.test.js
packages/article-label/package.json

https://nidigitalsolutions.jira.com/browse/REPLAT-356
Discussed and approved with Jake and Claire.

Feat: article label

---

packages/article/__snapshots__/article.test.js.snap
packages/article/article-content.js
packages/article/package.json

feat: add article label to article

---

lib/cli/package-json.js
packages/article-flag/package.json
packages/article-label/package.json
packages/article/package.json

chore: bump webpack

---

ios/storybooknative.xcodeproj/project.pbxproj

fix: native ios storybook app

---

.fructose/setup.js
package.json
packages/brightcove-video/brightcove-video.fructose.js
yarn.lock

chore: update fructose

---

packages/article-flag/article-flag.js
packages/article-headline/article-headline.js
packages/article-label/article-label.js

chore: fix lint warnings

---

packages/brightcove-video/__tests__/__snapshots__/brightcove-video.web.test.js.snap
packages/brightcove-video/brightcove-video.web.js

fix:Brightcove player autoplay prop

---

packages/article-headline/WebView-auto-height.js
packages/article-headline/article-headline.android.js
packages/article-headline/article-headline.stories.js

feat: headline on a webview for android

---

packages/caption/.npmignore
packages/caption/LICENSE
packages/caption/__snapshots__/caption.test.js.snap
packages/caption/caption.js
packages/caption/caption.stories.js
packages/caption/caption.test.js
packages/caption/package.json

Adds a new package `Caption` component.

feat: add caption component

---

packages/brightcove-video/__tests__/brightcove-video.native.test.js
packages/brightcove-video/brightcove-video.native.js
packages/brightcove-video/brightcove-video.stories.js

This PR causes the video to pause if the app goes into the background & play from where it was if you resume the app. Fixes issue discovered while integrating this component back into the native tablet apps.

feat: pause/play video based on appstate

---

packages/link/link.proptypes.js
packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
packages/markup/__tests__/__snapshots__/markup.web.test.js.snap
packages/markup/jest.config.json
packages/markup/jest.config.web.json
packages/markup/markup.js
packages/markup/markup.web.js
packages/markup/package.json
yarn.lock

Use the `Link` component in the markup builder. This was part of the work on #138.
__Dependent on #150__

feat: add link component to markup builder

---

packages/article-summary/__tests__/__snapshots__/article-summary.test.js.snap
packages/article-summary/fixtures/article.json
packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/card/__tests__/__snapshots__/card.test.js.snap
packages/card/fixtures/card-props.json
packages/date-publication/__snapshots__/date-publication.test.js.snap
packages/date-publication/date-publication.js
packages/date-publication/date-publication.stories.js
packages/date-publication/date-publication.test.js

Fixes [#153](https://github.com/newsuk/times-components/issues/153)

fix: date-publication add enum for publication values

---

packages/link/__tests__/__snapshots__/link.native.test.js.snap
packages/link/__tests__/__snapshots__/link.web.test.js.snap
packages/link/link.js
packages/link/link.web.js
packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
packages/markup/__tests__/__snapshots__/markup.web.test.js.snap

fix: link - add underline to links

---

packages/author-profile/author-profile-item.js
packages/author-profile/package.json
packages/card/__tests__/__snapshots__/card.test.js.snap
packages/card/__tests__/card.test.js
packages/card/card.js
packages/card/card.stories.js
packages/provider/author-profile-provider.js
yarn.lock

fix: ensure no exception is thrown no asset

---

package.json
yarn.lock

chore: use the same version on storybook dependencies

---

packages/brightcove-video/ios/RNTBrightcove/RNTBrightcove.m

revised conditional as per @RussellToon & @mabidakun suggestion

review: make conditional more consistent

---

packages/provider/author-profile-provider.js

fix: change provider query

---

packages/brightcove-video/android/build.gradle

fix: use 4.x version of brightcove android SDK

---

packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveManager.java
packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/RNTBrightcoveView.java

brightcove review: android code improvements

---

packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/author-profile-loading.js
packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
yarn.lock

On the web, the parent tag needs to expand to every available space in order for the loading indicator to be centered.

fix: replace loading text by an activity indicator

---

.github/PULL_REQUEST_TEMPLATE.md

chore: add pull request instructions on gif demos

---

packages/article-byline/package.json
packages/article-flag/package.json
packages/article-headline/package.json
packages/article-label/package.json
packages/article-summary/package.json
packages/article/package.json
packages/author-head/package.json
packages/author-profile/package.json
packages/brightcove-video/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/image/package.json
packages/link/package.json
packages/markup/package.json
packages/pagination/package.json
packages/provider/package.json

Add prettier to each component to allow each package to handle their own linting

Add prettier to each component

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
packages/brightcove-video/android/build.gradle
yarn.lock

We would like to move to android studio 3 and we need to update the gradle files in the project. Also we have done some clean up on those files as some dependencies were using .+ which is dangerous.

Gradle clean up and studio 3 changes

---

packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
packages/author-head/__tests__/author-head.test.js
packages/author-head/author-head.js
packages/author-head/author-head.stories.js
packages/author-head/fixtures/profile.json
packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap
packages/provider/example.json
yarn.lock

fix: ensure author-head doesn't crash without image

---

package.json

Bumping the yarn version used to latest.

chore: bump the version of yarn used in the repo

---

.storybook/webpack.config.js
package.json
yarn.lock

There are quite a few PRs that have come up which for a variety of reasons don't have a working storybook.
This PR is a simple first step to ensure that builds fail if the storybook can't build

chore: test storybook build

---

packages/article-byline/package.json
packages/article-flag/package.json
packages/article-label/package.json
packages/article-summary/package.json
packages/article/package.json
packages/author-head/package.json
packages/author-profile/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/image/package.json
packages/pagination/package.json
packages/provider/package.json

fix: package.json main

---

packages/article-image/__tests__/__snapshots__/article-image.test.js.snap
packages/article-image/__tests__/__snapshots__/article-image.web.test.js.snap
packages/article-image/article-image.js
packages/article/__tests__/__snapshots__/article.android.test.js.snap
packages/article/__tests__/__snapshots__/article.ios.test.js.snap
packages/article/__tests__/__snapshots__/article.web.test.js.snap
packages/article/article.js
packages/article/fixtures/full-article.json
packages/article/package.json

Styles were discussed with Jake

feat: add images to article

---

lib/cli/package-json.js

add prettier to package.json template

---

.travis.yml

update yarn to 1.1.0 (travis)

---

packages/pagination/__tests__/__snapshots__/pagination.native.test.js.snap
packages/pagination/__tests__/__snapshots__/pagination.web.test.js.snap
packages/pagination/__tests__/test-helper.js
packages/pagination/pagination.stories.js
yarn.lock

The storybook for the pagination controls was using `compact` instead of `hideResults`.

chore: fix storybook using wrong prop

---

packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/author-profile-content.js
packages/author-profile/author-profile-content.web.js
packages/author-profile/author-profile-footer.js
packages/pagination/__tests__/__snapshots__/pagination.native.test.js.snap
packages/pagination/__tests__/__snapshots__/pagination.web.test.js.snap
packages/pagination/pagination.js
packages/provider/__tests__/__snapshots__/author-profile-provider.test.js.snap

Its not the prettiest, but its something we can improve.
I've also removed "page" from the controls, just to make it a little bit closer to the mockups (https://app.zeplin.io/project/59a6a2c092fb8c2b6944c504/screen/59a6a3120f46b28066f67eca).

Add basic pagination footer to author profile

---

packages/brightcove-video/ios/RNTBrightcove/RNTBrightcove.m

A fix for fullscreen issue with iOS brightcove player.

feat: set presenting view controller to fix fullscreen

---

packages/error-view/package.json

Fix the path for error-view tests

---

packages/caption/caption.js

fix: caption was not considering empty string

---

packages/article/article.js

fix: article condition missing

---

packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/author-profile-content.web.js
packages/author-profile/author-profile-footer.js
packages/author-profile/author-profile-header.js

fixes #270 - author profile now renders correctly in IE11 and all other supported platforms
IE11
Web
iOS
android

fix: author profile ie

---

.travis.yml
bitrise.yml
package.json
yarn.lock

[Changelog](https://github.com/yarnpkg/yarn/releases)
Ran locally, looks like it works fine.

chore: upgraded yarn to 1.2.0

---

.prettierignore
packages/ad/.prettierignore
packages/article-byline/.prettierignore
packages/article-flag/.prettierignore
packages/article-headline/.prettierignore
packages/article-image/.prettierignore
packages/article-label/.prettierignore
packages/article-summary/.prettierignore
packages/article/.prettierignore
packages/author-head/.prettierignore
packages/author-profile/.prettierignore
packages/brightcove-video/.prettierignore
packages/caption/.prettierignore
packages/card/.prettierignore
packages/date-publication/.prettierignore
packages/error-view/.prettierignore
packages/image/.prettierignore
packages/link/.prettierignore
packages/markup/.prettierignore
packages/pagination/.prettierignore
packages/provider/.prettierignore
packages/tracking/.prettierignore

fix: ignore package.json

---

.prettierignore
packages/ad/.prettierignore
packages/article-byline/.prettierignore
packages/article-flag/.prettierignore
packages/article-headline/.prettierignore
packages/article-image/.prettierignore
packages/article-label/.prettierignore
packages/article-summary/.prettierignore
packages/article/.prettierignore
packages/author-head/.prettierignore
packages/author-profile/.prettierignore
packages/brightcove-video/.prettierignore
packages/caption/.prettierignore
packages/card/.prettierignore
packages/date-publication/.prettierignore
packages/error-view/.prettierignore
packages/image/.prettierignore
packages/link/.prettierignore
packages/markup/.prettierignore
packages/pagination/.prettierignore
packages/provider/.prettierignore
packages/tracking/.prettierignore

fix: prettier to ignore native code

---

packages/tracking/__tests__/__snapshots__/track-events.test.js.snap
packages/tracking/__tests__/__snapshots__/tracking-context.test.js.snap
packages/tracking/__tests__/test-tracking-context.js
packages/tracking/__tests__/track-events.test.js
packages/tracking/__tests__/track-render.test.js
packages/tracking/__tests__/tracking-context.test.js
packages/tracking/track-events.js
packages/tracking/tracking-context.js
packages/tracking/tracking.js
packages/tracking/tracking.stories.js
yarn.lock

Component to track the events exposed by other components via their props. Existing handlers for these events will be wrapped so they will still work.

Track component events

---

README.md

chore: added travis status badge

---

packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/markup/__tests__/__snapshots__/markup.native.test.js.snap
packages/markup/__tests__/__snapshots__/markup.web.test.js.snap
packages/markup/__tests__/test-helper.js
packages/markup/fixtures/line-break.json
packages/markup/fixtures/ratings.json
packages/markup/markup.js
packages/markup/markup.stories.js
packages/markup/markup.web.js

feat: Line breaks

---

packages/brightcove-video/ios/RNTBrightcove.xcodeproj/project.pbxproj

Updates xCode project file references to fix `react-native link`

fix: react-native link

---

.prettierignore

Stop generated file causing linting to fail

Don't lint generated story-loader.js

---

packages/brightcove-video/android/src/main/java/uk/co/news/rntbrightcovevideo/BrightcovePlayerActivity.java
packages/brightcove-video/android/src/main/res/layout/brightcove_player_activity.xml
packages/brightcove-video/android/src/main/res/values/styles.xml

fix: simple brightcove activity with fullscreen icon hidden

---

.fructose/setup.ios.js
bitrise.yml
packages/article/article.fructose.ios.js
packages/author-profile/author-profile.fructose.ios.js
packages/brightcove-video/brightcove-player.fructose.ios.js

we are relaunching the app between tests to make sure previously failing tests don't prevent subsequent tests from running

chore: make tests more reliable

---

packages/brightcove-video/brightcove-player.fructose.ios.js

fix: change player on brightcove fructose tests

---

packages/gradient/.eslintignore
packages/gradient/.eslintrc.json
packages/gradient/.npmignore
packages/gradient/.prettierignore
packages/gradient/LICENSE
packages/gradient/__mocks__/react-native-linear-gradient.js
packages/gradient/__tests__/__snapshots__/gradient.test.js.snap
packages/gradient/__tests__/gradient.test.js
packages/gradient/gradient.js
packages/gradient/gradient.stories.js
packages/gradient/gradient.web.js
packages/gradient/package.json
yarn.lock

Like the name says it creates a gradient 👍 
This is built on top of [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) to add a property to define the degrees of the gradient.

feat: gradient package

---

packages/author-profile/__tests__/author-profile-content.web.test.js
packages/author-profile/__tests__/author-profile-helper.js
packages/author-profile/author-profile-item.js
packages/author-profile/author-profile.js
packages/author-profile/author-profile.stories.js
packages/author-profile/package.json
yarn.lock

Adds tracking to author profile item (to track twitter link) and applies author profile fields to all tracking events raised for author profile components.
No visual changes.

Author profile tracking

---

.github/CONTRIBUTING.md

Just a little addition to the docs for a problem I encountered when trying to run the project. This isn't specific to the project but React Native in general. Quite an obscure one, but anyone who has used older version of React Native may easily fall into this.

Documentation update for iOS issue

---

android/build.gradle

Tested (manually) storybook native android in android studio 3.0

update to latest stable gradle plugin 3.0

---

.github/CONTRIBUTING.md

Updating contributing with fonts findings

---

packages/watermark/.prettierignore
yarn.lock

Edit: Fixing failing build in master.

chore: update prettierignore

---

packages/brightcove-video/package.json

remove (unused) enzyme from brightcove

---

packages/brightcove-video/README.md

Add gradle update step to README

---

yarn.lock

fix an issue with the yarn lock file

restore yarn.lock

---

packages/brightcove-video/android/build.gradle

Fix android build on RN0.49.5

---

packages/pagination/__tests__/__snapshots__/pagination-icons.native.test.js.snap
packages/pagination/__tests__/__snapshots__/pagination-icons.web.test.js.snap
packages/pagination/__tests__/__snapshots__/pagination.native.test.js.snap
packages/pagination/__tests__/__snapshots__/pagination.web.test.js.snap

fix: update snapshots for pagination

---

.github/CONTRIBUTING.md

Updating font readme on Contributing

---

yarn.lock

chore: bump yarn

---

.editorconfig
packages/article/styles/james.js

I compared the default options set out the prettier config which can be seen here: https://prettier.io/docs/en/options.html. I then implemented those in the editor config file. To test this I created a test file and ran `yarn fmt` against it. I tweaked the settings until I saw no change.

TAP-203: Editor Config File

---

packages/tracking/tracking.stories.js

Update tracking stories to remove track render and remove hocs from `storiesOf`. Solves https://github.com/newsuk/times-components/issues/298

Tracking stories

---

packages/article-image/__tests__/__snapshots__/article-image.test.js.snap
packages/article-image/__tests__/__snapshots__/article-image.web.test.js.snap
packages/article-image/fixtures/primary-image.json
packages/article-image/fixtures/secondary-image.json
packages/article/__tests__/__snapshots__/article.android.test.js.snap
packages/article/__tests__/__snapshots__/article.ios.test.js.snap
packages/article/__tests__/__snapshots__/article.web.test.js.snap
packages/article/fixtures/full-article.json
packages/article/fixtures/no-ads.json

primary image could be any ratio

update ratio for primary image

---

packages/brightcove-video/brightcove-video.stories.js

fix: storybook brightcove-video poster image uri

---

packages/ad/package.json
packages/article-headline/package.json
packages/article-summary/package.json
packages/author-profile/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/gradient/package.json
packages/image/package.json
packages/link/package.json
packages/link/text-link.js
yarn.lock

Fixes proptype warning that manifested itself in react-native storybook (byline component).

fix: upgrades react-style-proptype & fixes text link proptypes

---

.github/CONTRIBUTING.md
packages/article/__tests__/shared.js
packages/article/article.fructose.ios.js
packages/article/article.js
packages/article/package.json
packages/author-profile/__tests__/author-profile-helper.js

https://nidigitalsolutions.jira.com/browse/TAP-87
Track page views only, initially

Tracking article

---

lib/publish_storybook.sh

chore: write the cname on publish

---

packages/article/fixtures/article-no-flags-no-standfirst.json
packages/article/fixtures/article-no-flags.json
packages/article/fixtures/full-article-typename.json
packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/fixture-generator.js
packages/author-profile/fixtures/article-list.json
packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
packages/provider/fixtures/article.json
packages/provider/fixtures/author-profile.json

This story pointed at dev image server which has a bad https cert & is not available outside office network.

fix: don't point at dev imageserver

---

packages/jest-configurator/.eslintignore
packages/jest-configurator/.eslintrc.json
packages/jest-configurator/.npmignore
packages/jest-configurator/.prettierignore
packages/jest-configurator/__tests__/index.js
packages/jest-configurator/package.json

Make package consistent with the rest of the repo and don't prettier `package.json`

fix: add ignore files

---

packages/article/article.stories.js

At the moment all Article stories are broken - this fixes them.

fix: add missing required property of article

---

android/app/build.gradle

Update react-native implementation for (android) storybook

Update react-native implementation for (android) storybook

---

packages/article-summary/article-summary.js
packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/__tests__/author-profile-helper.js
packages/card/__tests__/__snapshots__/card.test.js.snap
packages/card/__tests__/card.test.js
packages/card/card-loading.js
packages/card/card.js
packages/date-publication/date-publication.js
packages/link/link.js
packages/link/link.proptypes.js
packages/link/link.web.js
yarn.lock

We are getting several prop warnings within the author profile tests:
* Be stricter on publication `propType`
* Fix erroneous loading snapshot
* Follow render and default to `TIMES` when no prop is provided
* Split web and native `Link` `propTypes`

chore: refactor props and fix tests

---

.storybook.native/index.js
storybook/decorators/white-bg-color.js

remove the grey background color visible in android storybook

Fix/remove grey color in storybook android 

---

packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
packages/image/__tests__/web/__snapshots__/image.web.test.js.snap
packages/image/image.web.js

From left to right: chrome, FF, safari
From left to right: android, ios

fix: browser issue

---

packages/author-head/__tests__/__snapshots__/author-head.test.js.snap
packages/author-head/author-head.js
packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap
packages/author-profile/author-profile-content.web.js

When using in SSR for example, we shouldn't be relying on window being in the environment
chore: increase resolution for author head which looks bad on IE11

fix: test for window

---

.travis.yml

chore: update install command

---

packages/tracking/__tests__/tealium-send-scheduler.web.test.js
packages/tracking/__tests__/track-scroll-depth.web.test.js
packages/tracking/tealium/tealium-send-scheduler.js
storybook/storybook-tealium-reporter.js

* use new Tealium profile
* use `tealiumTrack` instead of `utag.view` and `utag.link`
* fix typo

Tracking updates

---

.travis.yml
package.json

This is the behaviour on travis:

enable yarn cache on travis

---

packages/responsive-styles/.eslintignore
packages/responsive-styles/.eslintrc.json
packages/responsive-styles/.npmignore
packages/responsive-styles/.npmrc
packages/responsive-styles/.prettierignore
packages/responsive-styles/LICENSE
packages/responsive-styles/__tests__/web/__snapshots__/responsive-styles.test.js.snap
packages/responsive-styles/__tests__/web/jest.config.js
packages/responsive-styles/__tests__/web/responsive-styles.test.js
packages/responsive-styles/package.json
packages/responsive-styles/responsive-styles.js
packages/responsive-styles/responsive-styles.stories.web.js

Extracts responsive-styles to be a separate package and updates author-head to consume it. Will be used next by author-profile.

Responsive styles component

---

packages/storybook/package.json

chore: publish

---

dextrose/dextrose.android.js
lib/functional_tests/run-ios.sh
lib/visual_snapshots/run-android-dextrose.sh
lib/visual_snapshots/run-ios-dextrose.sh

fix: native packager issues for fructose/dextrose

---

packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/author-profile-content.native.test.js
packages/author-profile/__tests__/author-profile-content.web.test.js
packages/author-profile/author-profile-content.js
packages/author-profile/author-profile-content.web.js

[REPLAT-1097](https://nidigitalsolutions.jira.com/browse/REPLAT-1097)

Scroll to top of page when paging

---

dextrose/dextrose.ios.js
fructose/webpack.config.js

Feature: Dextrose ci

---

packages/author-profile/author-profile.stories.js

Help out dextrose and people alike with a working story. On the whole stories should use the component of the package rather than a specific potion of it

chore: use component for story

---

packages/provider/__tests__/__snapshots__/provider.test.js.snap
packages/provider/__tests__/provider.test.js
packages/provider/connect.js

- Add tests for refetch
- Change `Wrapper` back to a functional component as the use of `retry` means that the wrapped component will now be rendered on refetch so this is no longer requried

Add refetch tests and refactor

---

packages/article-summary/__tests__/__snapshots__/article-summary.native.test.js.snap
packages/article-summary/__tests__/__snapshots__/article-summary.web.test.js.snap
packages/article-summary/article-summary.js
packages/author-profile/__tests__/__snapshots__/author-profile-content.native.test.js.snap
packages/author-profile/__tests__/__snapshots__/author-profile-content.web.test.js.snap

Adjust margin under publication date as per design review and as part of https://nidigitalsolutions.jira.com/browse/REPLAT-1208

fix: replat 1208 Article Summary margins

---

packages/tealium/__tests__/__snapshots__/tealium-send-scheduler.web.test.js.snap
packages/tealium/__tests__/tealium-send-scheduler.web.test.js
packages/tealium/package.json
packages/tealium/tealium-send-scheduler.js

Refactor the tests to test behaviour rather than implementation and increase coverage

chore: fix coverage and add tests

---

packages/tracking/__tests__/__snapshots__/tracking.test.js.snap
packages/tracking/__tests__/__snapshots__/tracking.web.test.js.snap
packages/tracking/__tests__/tracking.test.js
packages/tracking/__tests__/tracking.web.test.js
packages/tracking/jest.config.web.json
packages/tracking/package.json
packages/tracking/track-scroll-depth.web.js

Tracking was a little out of date in terms of test config so updated and added tests to increase coverage.
Fixed a bug where the child id wasn't being checked correctly.

chore: increase tracking coverage

---

packages/pagination/pagination.stories.js

Add missing stories for `hideTopKeyline` and `hideBottomKeyline` props in pagination component.

add stories for pagination keyline new props

---

lib/publish_storybook.sh

fix: folder name publish storybook task

---

packages/article/article-tracking-context.js
packages/article/article.stories.js
packages/article/package.json
packages/author-head/author-head.stories.js
packages/author-head/package.json
yarn.lock

Added an article tracking story so stakeholders can see what events are raised

feat: adds tealium reporting to article stories

---

packages/ad/package.json
packages/article-byline/package.json
packages/article-flag/package.json
packages/article-image/package.json
packages/article-label/package.json
packages/article-summary/package.json
packages/article/package.json
packages/author-head/package.json
packages/author-profile/package.json
packages/brightcove-video/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/gradient/package.json
packages/icons/package.json
packages/image/package.json
packages/jest-configurator/package.json
packages/link/package.json
packages/markup/package.json
packages/pagination/package.json
packages/provider/package.json
packages/pull-quote/package.json
packages/responsive-styles/package.json
packages/tealium/package.json
packages/tracking/package.json
packages/utils/package.json
packages/watermark/package.json

Babel was causing issues on Android (and possible other platforms) without babel preset env and stage-2 installed. Added those as peer dependency on all packages

chore: Added babel presets as peer dependency to all packages

---

.storybook/preview-head.html

@craigbilner 
This is for testing purposes. Will need a fuller and better fix

fix: fix https font error

---

packages/author-profile/__tests__/author-profile-helper.js
packages/author-profile/author-profile.js
packages/card/card.stories.js
packages/card/card.stories.web.js

fix: props validation warnings on date

---

package.json
yarn.lock

Added babel-preset-env and babel-preset-stage-2 to root project as a dev dependency, to suppress warnings

chore: Added babel-preset to root dev deps

---

packages/article/article-body/article-body-row.web.js

Fixes the missing keys warning in article pages with pull quotes

fix: handle keys properly in the article rows renderers

---

.babelrc
package.json
yarn.lock

Reverts newsuk/times-components#571

Revert "chore: installs babel-plugin-flow-react-proptype"

---

packages/article/article-body/article-link.web.js
packages/link/__tests__/web/__snapshots__/link.web.test.js.snap
packages/link/__tests__/web/link.web.test.js
packages/link/link.web.js
packages/link/package.json

Simple snapshot test to demonstrate correct composition when responsive styles are passed

chore: add tests

---

packages/article-summary/package.json
packages/slice/__tests__/android/__snapshots__/slice.test.js.snap
packages/slice/__tests__/ios/__snapshots__/slice.test.js.snap
packages/slice/__tests__/web/__snapshots__/slice.test.js.snap
packages/slice/fixtures/single-related-article.json
packages/slice/package.json
yarn.lock

1. Update fixture for related article
2. Update to latest `article-summary` package

fix: update to latest article summary and update fixture

---

packages/gestures/__tests__/gestures.native.test.js

chore: use fake timers in gesture tests

---

package.json

fix coverage report

---

packages/tealium/__tests__/__snapshots__/tealium-send-scheduler.web.test.js.snap
packages/tealium/__tests__/shared.js
packages/tealium/__tests__/web/__snapshots__/tealium.web.test.js.snap
packages/tealium/__tests__/web/jest.config.js
packages/tealium/__tests__/web/tealium.web.test.js
packages/tealium/package.json

As this only is used on web, I have only added the web config.
Also there was no coverage for `tealium.js` and `storybook.js`. Does this need to be added?

feat: add Jest Configurator to the Tealium package

---

README.md

We are introducing testing summary tables to READMEs

add test coverage table to readme

---

packages/article/__tests__/web/__snapshots__/related-articles.web.test.js.snap
packages/article/related-articles/heading.web.js
packages/article/related-articles/related-article-item.web.js
packages/article/related-articles/related-articles.web.js

@craigbilner any idea how to add other elements? https://github.com/necolas/react-native-web/blob/master/website/guides/accessibility.md#accessibilityrole does not seem to support `p`, `time` or other special tags we are using on prod

feat: add semantic elements to related articles

---

packages/article/__tests__/web/__snapshots__/related-articles.web.test.js.snap
packages/article/related-articles/related-articles.web.js
yarn.lock

- removing `map` mutation and replace with nicer functional `reduce`
@craigbilner

refactor: refactor related articles loop

---

packages/slice/package.json
yarn.lock

Slice is using the wrong version of article which seems to have broken the build. #659 should remove this pain

chore: fix article version

---

package.json

chore: always bump the depend package version

---

packages/slice/__tests__/shared.js
packages/slice/styles/role-map.js
yarn.lock

Lets increase coverage for slice!

chore: adds tests and for roleMap in slice

---

packages/author-profile/author-profile.stories.js
packages/author-profile/package.json
yarn.lock

Unfortunately it's not straight forward for us to remove the preflight requests from author profile paging. Will update render to do the same as this, updating to align the technical implementation/experience.

chore: align with render

---

packages/author-head/__tests__/android/__snapshots__/author-head.android.test.js.snap
packages/author-head/__tests__/ios/__snapshots__/author-head.ios.test.js.snap
packages/author-head/__tests__/web/__snapshots__/author-head.web.test.js.snap
packages/author-head/author-bio.base.js
packages/author-head/author-head-container.web.js
packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/web/__snapshots__/author-profile-content.web.test.js.snap
packages/pagination/__tests__/android/__snapshots__/pagination-icons.native.test.js.snap
packages/pagination/__tests__/android/__snapshots__/pagination.native.test.js.snap
packages/pagination/__tests__/ios/__snapshots__/pagination-icons.native.test.js.snap
packages/pagination/__tests__/ios/__snapshots__/pagination.native.test.js.snap
packages/pagination/__tests__/web/__snapshots__/pagination-icons.web.test.js.snap
packages/pagination/__tests__/web/__snapshots__/pagination.web.test.js.snap
packages/pagination/pagination-icons.js
packages/pagination/results-message.js

Test ids added:
author-bio
author-head
pagination-button-next
pagination-button-previous
results-message (Showing page X of Y)

feat: add test ids to components in author profile to support e2e tests

---

packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
packages/article-summary/styles/index.js
packages/article-summary/styles/index.web.js
packages/article/__tests__/ios/__snapshots__/related-article.ios.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap

updated font weight for article summary headline - ios platform specific

---

.travis.yml
bitrise.yml
package.json

chore: bump yarn to 1.5.1

---

packages/article/fixtures/article-no-flags-no-standfirst.json
packages/article/fixtures/article-no-flags.json
packages/article/fixtures/full-article-typename.json
packages/article/fixtures/full-article.json
packages/article/fixtures/full-long-article.json
packages/article/fixtures/no-ads.json
packages/article/fixtures/no-flags.json
packages/article/fixtures/no-label-no-flags-no-standfirst.json
packages/article/fixtures/no-label-no-flags.json
packages/article/fixtures/no-label.json
packages/article/fixtures/no-lead-asset.json
packages/article/fixtures/no-standfirst-no-flags.json
packages/article/fixtures/no-standfirst-no-label.json
packages/article/fixtures/no-standfirst.json
packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
packages/provider/article.js
packages/provider/fixtures/article.json

Update to provider and fixtures to support work on https://nidigitalsolutions.jira.com/browse/REPLAT-1315
This updates the different summary length we need for all 3 related article templates.
As per 
https://docs.google.com/spreadsheets/u/1/d/1CbsUSIbeSHnnsG_z_xnCYhwSN5D0Z9_xqXZJxBnyyqs/edit#gid=0

Feat: Update summary fields with new character counts

---

packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article/article-body/article-body.web.js
packages/article/article.web.js
packages/article/data-helper.js
packages/article/fixtures/article-no-flags-no-standfirst.json
packages/article/fixtures/article-no-flags.json
packages/article/fixtures/full-article-typename.json
packages/article/fixtures/full-article.json
packages/article/fixtures/full-long-article.json
packages/article/fixtures/no-ads.json
packages/article/fixtures/no-flags.json
packages/article/fixtures/no-label-no-flags-no-standfirst.json
packages/article/fixtures/no-label-no-flags.json
packages/article/fixtures/no-label.json
packages/article/fixtures/no-lead-asset.json
packages/article/fixtures/no-standfirst-no-flags.json
packages/article/fixtures/no-standfirst-no-label.json
packages/article/fixtures/no-standfirst.json
packages/markup/__tests__/android/__snapshots__/markup.android.test.js.snap
packages/markup/__tests__/ios/__snapshots__/markup.ios.test.js.snap
packages/markup/markup.js
packages/markup/markup.web.js
packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
packages/provider/article.js
packages/provider/fixtures/article.json

feat: add support for article section

---

packages/article/__tests__/android/__snapshots__/related-article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/related-article.ios.test.js.snap
packages/article/__tests__/related-articles-shared.js
packages/article/__tests__/web/__snapshots__/related-articles.web.test.js.snap
packages/article/related-articles/related-articles-heading.js
packages/article/related-articles/related-articles-heading.web.js

- change "Related links" to "Related articles"
- fix Animation test issue

feat: change related links to articles and fix Animation test issues

---

packages/ad/__tests__/ad-init-mocks.js
packages/ad/__tests__/ad-init.test.js
packages/ad/ad-init.js

Add support for responsive ads (different ads size for different breakpoint), no different bidding.

feat: responsive ads

---

packages/article/related-articles/related-articles.js
packages/slice/__tests__/android/__snapshots__/slice.android.test.js.snap
packages/slice/__tests__/ios/__snapshots__/slice.ios.test.js.snap
packages/slice/__tests__/shared.js
packages/slice/__tests__/web/__snapshots__/slice.web.test.js.snap
packages/slice/slice.stories.js
packages/slice/templates/leadandtwo/index.js
packages/slice/templates/leadandtwo/index.web.js
packages/slice/templates/standard/index.js
packages/slice/templates/standard/index.web.js

https://nidigitalsolutions.jira.com/browse/REPLAT-1585
https://nidigitalsolutions.jira.com/browse/REPLAT-1590
- rewrite how Related Articles handles articles and passes them to Slice
- rewrite how Slice handles keys, and ensure tests and stories match

refactor: rewrite related articles handling of Slice children

---

packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article/article-body/article-body.web.js
packages/article/article.web.js
packages/article/data-helper.js
packages/article/fixtures/article-no-flags-no-standfirst.json
packages/article/fixtures/article-no-flags.json
packages/article/fixtures/article-with-video-asset.json
packages/article/fixtures/full-article-typename.json
packages/article/fixtures/full-article.json
packages/article/fixtures/full-long-article.json
packages/article/fixtures/no-ads.json
packages/article/fixtures/no-flags.json
packages/article/fixtures/no-label-no-flags-no-standfirst.json
packages/article/fixtures/no-label-no-flags.json
packages/article/fixtures/no-label.json
packages/article/fixtures/no-lead-asset.json
packages/article/fixtures/no-standfirst-no-flags.json
packages/article/fixtures/no-standfirst-no-label.json
packages/article/fixtures/no-standfirst.json
packages/provider/__tests__/__snapshots__/article-provider.test.js.snap
packages/provider/article.js
packages/provider/fixtures/article.json

Enable grapeshot on ads via Article component

enable grapeshot on Ad inside Article

---

packages/article/package.json
packages/author-head/package.json
packages/icons/package.json
packages/link/package.json
packages/pagination/package.json
packages/responsive-styles/package.json
yarn.lock

updates styled components as the old version is not compatible with newer versions of react-native-web in a ssr context

fix: updates styled-compoents

---

package.json
packages/ad/package.json
packages/article-byline/package.json
packages/article-flag/package.json
packages/article-image/package.json
packages/article-label/package.json
packages/article-summary/package.json
packages/article/package.json
packages/author-head/package.json
packages/author-profile/package.json
packages/brightcove-video/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/gestures/package.json
packages/gradient/package.json
packages/icons/package.json
packages/image/package.json
packages/link/package.json
packages/markup/package.json
packages/pagination/package.json
packages/provider/package.json
packages/slice/package.json
packages/tracking/package.json
packages/video-label/package.json
packages/watermark/package.json
yarn.lock

chore: bump dextrose

---

packages/article/fixtures/full-article-typename.json
packages/provider/article.web.js

fix: Fix the errors that appear in the Provider story for Article.

---

packages/article/article-body/article-body.web.js

fix: use mutable object as apollo uses immutables

---

dextrose/dextrose.web.js
package.json
packages/ad/package.json
packages/article-byline/package.json
packages/article-flag/package.json
packages/article-image/package.json
packages/article-label/package.json
packages/article-summary/package.json
packages/article/package.json
packages/author-head/package.json
packages/author-profile/package.json
packages/brightcove-video/package.json
packages/caption/package.json
packages/card/package.json
packages/date-publication/package.json
packages/error-view/package.json
packages/gestures/package.json
packages/gradient/package.json
packages/icons/package.json
packages/image/package.json
packages/link/package.json
packages/markup/package.json
packages/pagination/package.json
packages/provider/package.json
packages/slice/package.json
packages/tracking/package.json
packages/video-label/package.json
packages/watermark/package.json
yarn.lock

chore: bump dextrose, remove extra web breakpoints

---

packages/article/article.web.js
packages/article/related-articles/fixtures/leadandtwo/lead-and-support-related-articles.json
packages/article/related-articles/fixtures/leadandtwo/lead-and-two-supports-related-articles.json
packages/article/related-articles/fixtures/leadandtwo/lead-related-article.json
packages/article/related-articles/fixtures/standard/single-related-article-no-byline.json
packages/article/related-articles/fixtures/standard/single-related-article-no-label.json
packages/article/related-articles/fixtures/standard/single-related-article.json
packages/article/related-articles/fixtures/standard/three-related-articles.json
packages/article/related-articles/fixtures/standard/two-related-articles.json
packages/article/related-articles/related-article-item.js
packages/article/topics/index.js
packages/article/topics/index.web.js

Related Articles component hadn't been added to the Web version. This now adds it and clears up errors regarding the Image on the component as well as some warnings from the Topics package.

feat: Add related articles to the Web.

---

packages/article/__tests__/android/__snapshots__/related-article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/related-article.ios.test.js.snap
packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/card/__tests__/android/__snapshots__/card.android.test.js.snap
packages/card/__tests__/card.native.test.js
packages/card/__tests__/ios/__snapshots__/card.ios.test.js.snap
packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
packages/card/__tests__/web/card.web.test.js
packages/card/card-loading.js
packages/card/card-shared-proptypes.js
packages/card/card.js
packages/card/card.stories.js
packages/card/package.json
packages/card/styles/index.js
packages/topics/.prettierignore

https://nidigitalsolutions.jira.com/browse/REPLAT-1614
- Card now takes a prop to reverse it's flex direction in order for it to work with the new Opinion slice

feat: add reversal flag for Card layout

---

packages/ad/__tests__/ad-init.test.js
packages/ad/__tests__/check-self-contained-function.js
packages/ad/__tests__/check-self-contained-function.test.js
packages/ad/__tests__/check-serialisable-function.js
packages/ad/__tests__/dom-context.stories.test.js
packages/ad/__tests__/webview-event-callback-setup.test.js
packages/ad/ad-init.js
packages/ad/ad.js
packages/ad/ad.stories-domcontext-init.js
packages/ad/ad.stories.js
packages/ad/webview-event-callback-setup.js

Minor bugfix to get ads stories working on native

fix: fix logic bug and compile errors on native ads

---

packages/article-byline/article-byline.js
packages/article/article-content.js
packages/article/article-meta/article-meta-base.js
packages/article/article.js
packages/article/related-articles/related-articles.js

Added onAuthorPress callback to article byline links for author names. This callback will be implemented in native to navigate to author profiles.

feat: Author link press on article byline

---

packages/article/article.stories.js

This PR changes the storybook page for article to use a components that sets defaults.

Simplify article storybook page

---

packages/provider/article.js
packages/provider/article.web.js
packages/utils/schema.json

Use a common field name to denote the main article in a related article layout.
Related TPA PR : https://github.com/newsuk/times-public-api/pull/332

feat: Update related article field denoting the main article

---

packages/article/related-articles/related-article-item-proptypes.js

- native only has the summary125
@tuncaulubilge

fix: proptypes for related articles proptypes for native

---

packages/article/src/related-articles/related-articles.js

- these defaults are not required as they should never be needed... if there are strong opinions to keep them, please advise how you would test the defaults (for coverage purposes)...

test: increase related articles code coverage

---

packages/article/src/article-meta/article-meta-base.js

refactor: Refactor meta row list creation in a more functional approach

---

lib/cli/package-json.js

Fixes transpile script name in CLI to mirror existing packages

Fixes transpile script name in CLI

---

packages/storybook/package.json

fix: fix storybook tests

---

packages/related-articles/__tests__/shared.js
packages/topics/__tests__/shared.js
yarn.lock

chore: bump lock file

---

packages/utils/src/__tests__/add-missing-protocol.test.js

chore: lint

---

packages/article-flag/__tests__/web/jest.config.js
packages/article-summary/__tests__/android/__snapshots__/article-summary.android.test.js.snap
packages/article-summary/__tests__/android/article-summary.android.test.js
packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
packages/article-summary/__tests__/ios/article-summary.ios.test.js
packages/article-summary/__tests__/shared.js
packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
packages/article-summary/__tests__/web/article-summary.web.test.js
packages/article-summary/src/article-summary-renderer.js
packages/article-summary/src/article-summary.js

- added test coverage around article-summary

test: increase code coverage for article-summary

---

packages/tealium-utils/package.json
yarn.lock

fix: update dep

---

app.json
packages/jest-configurator/src/jest-configurator.js
packages/jest-serializer/__tests__/serializer.test.js
packages/utils/src/schema.json

fix: linting

---

packages/tealium-utils/src/storybook.web.js

fix for native - tealium refactor broke the native storybook
@tuncaulubilge

fix: fixed tealium storybook for android / native

---

packages/related-articles/package.json

remove wrong tealium-utils ref

---

README.md

Adds Haul info and React Native debugging instructions to README

---

README.md

Add info about setting up android script.

Updated readme for android sdk path

---

lib/cli/templates.js

- change test name to reflect multiple tests
- change storybook file path (to created component) because it is broken

refactor: change file path and test name to tests

---

lib/cli/cli.test.js
lib/cli/templates.js

CLI needs to create the showcase file abstraction.
Fixes https://github.com/newsuk/times-components/issues/917

Chore: Add showcase abstraction to CLI

---

README.md

feat: adding expo qr code to readme

---

README.md
lib/cli/package-json.js
lib/cli/templates.js

- Add storybook to devDependencies
- Remove extraneous colon in test template

Fix: Add storybook to devDependencies in CLI

---

packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/shared.js
packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
packages/author-profile/src/author-profile.js

This fixes the missing article loading state that was removed in the recent refactor
https://nidigitalsolutions.jira.com/browse/REPLAT-2427
NOTE: this is a fix, the snapshots are being tidied up on a separate PR

fix: articles list loading state

---

packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap

Responding to broken master build. Not sure how this happened as the PR that was merged passed the CI build....

fix: a temp fix for author profile snapshots as master is broken

---

android/app/build.gradle
yarn.lock

fix: android dependency due to facebook's version bump

---

package.json
yarn.lock

Giving fructose some nice error handling capabilities

chore: bumping fructose

---

package.json

chore: bump yarn version

---

packages/ad/src/placeholder.js
packages/author-head/__tests__/android/__snapshots__/author-head.android.test.js.snap
packages/author-head/__tests__/ios/__snapshots__/author-head.ios.test.js.snap
packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/author-profile/src/styles/index.js
packages/gradient/src/gradient.js
packages/gradient/src/gradient.web.js
packages/link/link.showcase.js
packages/styleguide/src/colours/functional.js
packages/topic/__tests__/android/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-styling.test.js.snap
packages/topic/src/styles/index.js
packages/watermark/src/watermark.android.js

As per https://nidigitalsolutions.jira.com/browse/REPLAT-2392

Feat: Update author profile and topic head background

---

packages/article-list/__tests__/android/__snapshots__/article-list.android.test.js.snap
packages/article-list/__tests__/ios/__snapshots__/article-list.ios.test.js.snap
packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/image/__tests__/android/__snapshots__/image.android.test.js.snap
packages/image/__tests__/ios/__snapshots__/image.ios.test.js.snap
packages/image/__tests__/shared-native.js
packages/image/src/image.js
packages/topic/__tests__/android/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-styling.test.js.snap
packages/video/__tests__/android/__snapshots__/video.android.test.js.snap
packages/video/__tests__/ios/__snapshots__/video.ios.test.js.snap

https://github.com/newsuk/times-components/issues/912
- fix query string formatting for images
- fix data url images - should not have query strings

fix: image component resize query string params

---

packages/provider-test-tools/package.json
yarn.lock

To align with other consumers (render)

feat: updates apollo-link

---

packages/article-list/article-list.showcase.js
packages/author-profile/src/author-profile.js
packages/topic/__tests__/android/__snapshots__/topic-functional.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-functional.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-functional.test.js.snap
packages/topic/src/topic.js

Fixes fetchMore crash on article-list loading stories

Fix article list loading state

---

packages/article-list/__tests__/shared.js
packages/author-profile/__tests__/android/__snapshots__/author-profile.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile.test.js.snap
packages/button/__tests__/android/__snapshots__/button.test.js.snap
packages/button/__tests__/ios/__snapshots__/button.test.js.snap
packages/button/__tests__/web/__snapshots__/button.web.test.js.snap
packages/button/src/button.js
packages/styleguide/src/colours/functional.js

- changed button to `TouchableHighlight` to allow press state color change

feat: add button onPress styles

---

README.md
packages/utils/README.md

chore: Update readme to include schema fetching

---

packages/button/package.json
packages/button/webpack.config.js

Package created before cli was updated to include bundling

fix: Add bundle step to button package

---

packages/button/.eslintignore
packages/button/.prettierignore

(Hopefully) fixes master build failures

Fix: Add rnw.js to prettier and lint ignore files

---

ios/storybooknative.xcodeproj/xcshareddata/xcschemes/storybooknative.xcscheme

chore: amend ios build scheme to run in dev

---

packages/button/__tests__/shared.js
packages/button/src/button-prop-types.js

- Button onPress event is required

refactor: code coverage for button package to 100%

---

packages/provider-test-tools/fixtures/topic.json
packages/provider-test-tools/src/fixture-generator.js
packages/provider/__tests__/__snapshots__/topic-provider.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-functional.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-functional.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/topic-functional.js
packages/topic/__tests__/topic-styling.js
packages/topic/__tests__/web/__snapshots__/responsive.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-functional.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-head-functional.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-styling.test.js.snap
packages/topic/src/styles/responsive.web.js
packages/topic/src/topic-head.web.js

Fix: Topic head in IE

---

packages/ad/__tests__/web/__snapshots__/placeholder.test.js.snap
packages/ad/src/placeholder.js
packages/article/__tests__/web/__snapshots__/article.web.test.js.snap

Fix: Ad placeholder layout in IE

---

packages/article-list/__tests__/shared-web.js
packages/article-list/__tests__/shared.js
packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
packages/article-list/__tests__/web/helper.web.test.js
packages/article-list/article-list.showcase.js
packages/article-list/package.json
packages/article-list/src/article-list-prop-types.web.js
packages/article-list/src/article-list.web.js
yarn.lock

- add an ad to article list, every fifth article. Added storybook and test

feat: article list ads

---

packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap

Fix: update article-list snapshot

---

packages/svgs/.eslintignore
packages/svgs/.prettierignore
packages/svgs/package.json
packages/svgs/webpack.config.js

- Added missing bundling steps

Fix: Bundling in svgs package

---

packages/article-summary/package.json

chore: bumps deps

---

packages/ad/ad.showcase.js

fix: ad storybook has the wrong props

---

packages/article-list/src/article-list.web.js

- Fixes `article-list` on the server.

Fix: Defensive check for window object

---

packages/article-list/src/article-list.js

No longer creating fetchMoreOnEndReached function inside render, instead moved to a class function

Move fetchMoreOnEndReached to a class function

---

packages/topic/__tests__/android/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-styling.test.js.snap
packages/topic/__tests__/web/__snapshots__/responsive.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-head-functional.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-head-styling.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-styling.test.js.snap
packages/topic/src/styles/index.js
packages/topic/src/styles/responsive.web.js

Topic head part of https://github.com/newsuk/times-components/issues/1069

fix: minor topic head padding tweaks

---

packages/jest-serializer/README.md

docs: add README for jest-serializer

---

packages/ad/__tests__/web/dom-context.web.test.js
packages/ad/src/ad-init.js
packages/ad/src/ad.js
packages/ad/src/dom-context-prop-types.js
packages/ad/src/dom-context.web.js

https://nidigitalsolutions.jira.com/browse/REPLAT-2861
Note: ad component testing is limited atm, I believe it should be done with the `jest-serializer` package on a separate PR

fix: handle ad blocker

---

lib/cli/cli.test.js
lib/cli/files/.babelrc
lib/cli/files/.npmignore
lib/cli/templates.js

chore: fix up CLI generation code

---

lib/cli/cli.test.js
lib/cli/templates.js

- added README template (_a la_ Slice) to CLI with tests

feat: added README and tests to CLI

---

packages/test-utils/package.json

Fix for master CI as I was missing the webpack-config in the package.json file

fix: test-utils webpack config for master CI

---

lib/cli/package-json.js
packages/test-utils/package.json

fix: test-utils and cli bundle scripts

---

packages/styleguide/__tests__/android/__snapshots__/styleguide.android.test.js.snap
packages/styleguide/__tests__/android/styleguide.android.test.js
packages/styleguide/__tests__/ios/__snapshots__/styleguide.ios.test.js.snap
packages/styleguide/__tests__/ios/styleguide.ios.test.js
packages/styleguide/__tests__/shared.js
packages/styleguide/__tests__/web/__snapshots__/styleguide.web.test.js.snap
packages/styleguide/__tests__/web/serializers.js
packages/styleguide/__tests__/web/styleguide.web.test.js
packages/styleguide/package.json

* Follow naming conventions
* Print `styled-component` styles for web

test: refactor styleguide snaps

---

android-app/pages/article.js
packages/pages/__tests__/shared.base.js
packages/pages/src/client/ad-targeting-config.js

- Populate ad config for Android.
- Corresponding Android Smartphone PR: https://github.com/newsuk/nu-projectd-times-smartphone-android/pull/420

Feat: Android ad config

---

packages/article/fixtures/full-article.js

To enable a design review as requested by Jake Cox

refactor: add key facts to default article storybook

---

packages/related-articles/related-articles.showcase.js

Related article stories are giving errors in storybook. This will fix it.

fix: Fix errors with related article stories

---

packages/watermark/.jestlint

test: improve watermark snapshots

---

packages/brightcove-video/README.md

Q: what else should we do to deprecate this package? Do we need to unpublish, etc?

docs: deprecation message for brightcove

---

packages/article/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article/src/styles/article-meta/index.android.js

Android specific fix for byline issue.

chore: Android Byline styling fix

---

packages/article-topics/__tests__/android/__snapshots__/article-topics.test.js.snap
packages/article-topics/__tests__/ios/__snapshots__/article-topics.test.js.snap
packages/article-topics/__tests__/web/__snapshots__/article-topics.test.js.snap
packages/article-topics/src/article-topic.js
packages/article-topics/src/styles/index.android.js
packages/article-topics/src/styles/index.js
packages/article-topics/src/styles/shared.js
packages/related-articles/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/la2-with-style.ios.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/oa2-with-style.ios.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-with-style.web.test.js.snap
packages/related-articles/src/related-articles.js

Fixes for these issues: https://nidigitalsolutions.jira.com/browse/REPLAT-3226

chore: Styling fixes for Article Topics

---

package.json

Bitrise bumped yarn to 1.9.2, updated package.json to fix failing builds

Bump yarn to 1.9.2

---

packages/ad/README.md
yarn.lock

taken from an internal Google Docs ads doc

docs: add ads README

---

packages/article-label/README.md
packages/article-label/src/article-label.js

docs: add article label readme

---

packages/article-image/README.md
packages/article-image/__tests__/android/__snapshots__/article-image.android.test.js.snap
packages/article-image/__tests__/ios/__snapshots__/article-image.ios.test.js.snap
packages/article-image/__tests__/shared.base.js
packages/article-image/__tests__/shared.web.js
packages/article-image/__tests__/web/__snapshots__/article-image-with-style.web.test.js.snap
packages/article-image/__tests__/web/__snapshots__/article-image.web.test.js.snap
packages/article-image/src/article-image-prop-types.js
packages/article-image/src/article-image.base.js
packages/article-image/src/article-image.js
packages/article-image/src/inline-image.js
packages/article-image/src/inline-image.web.js
packages/article-image/src/inset-caption.js
packages/article-image/src/inset-caption.web.js
packages/article-image/styles/index.js
packages/article-image/styles/responsive.web.js

- refactor article image
- increase coverage to 100%
- add readme

refactor: article image

---

packages/article-list/README.md

docs: add article list readme

---

packages/article-summary/README.md
packages/article-summary/src/styles/index.android.js
packages/article-summary/src/styles/index.js
packages/article-summary/src/styles/index.web.js
packages/article-summary/src/styles/shared.js

refactor: article-summary: make styles iOS first, and add readme

---

packages/caption/README.md
packages/caption/src/caption-prop-types.js
packages/caption/src/caption.js
packages/caption/src/styles/index.android.js
packages/caption/src/styles/index.js
packages/caption/src/styles/index.web.js
packages/caption/src/styles/shared.js

refactor: caption and add readme

---

packages/article-topics/README.md
packages/article-topics/article-topics.showcase.js
packages/article-topics/src/article-topic-prop-types.js
packages/article-topics/src/article-topic.js
packages/article-topics/src/article-topics.js

- add readme
- refactor for consistency
- fix test to make coverage 100%
- test ordering
- fix storybook

refactor: article topics readme, tests and small refactor

---

packages/date-publication/README.md
packages/date-publication/__tests__/android/__snapshots__/date-publication-gmt.android.test.js.snap
packages/date-publication/__tests__/android/__snapshots__/date-publication.android.test.js.snap
packages/date-publication/__tests__/android/date-publication-gmt.android.test.js
packages/date-publication/__tests__/ios/__snapshots__/date-publication-gmt.ios.test.js.snap
packages/date-publication/__tests__/ios/__snapshots__/date-publication.ios.test.js.snap
packages/date-publication/__tests__/ios/date-publication-gmt.ios.test.js
packages/date-publication/__tests__/ios/date-publication.ios.test.js
packages/date-publication/__tests__/shared.js
packages/date-publication/__tests__/web/__snapshots__/date-publication-gmt.web.test.js.snap
packages/date-publication/__tests__/web/__snapshots__/date-publication.web.test.js.snap
packages/date-publication/__tests__/web/date-publication-gmt.web.test.js
packages/date-publication/date-publication.showcase.js
packages/date-publication/package.json
packages/date-publication/src/date-publication.js

- added readme
- improved coverage and tests in general (iterator, better tests)
- ensure non-publication strings do not show as `undefined`

refactor: date publication tests and readme

---

packages/card/README.md
packages/card/src/card-loading.js

docs: add card readme

---

packages/provider-test-tools/src/fixture-generator.js

Fixes bug in master where storybook is totally broken

fix: article fixture code

---

package.json

chore: unfix yarn version

---

packages/article/article.showcase.js
packages/article/package.json

fix: article fixtures

---

packages/error-view/README.md
packages/error-view/__tests__/android/__snapshots__/error-view.android.test.js.snap
packages/error-view/__tests__/android/error-view.android.test.js
packages/error-view/__tests__/ios/__snapshots__/error-view.ios.test.js.snap
packages/error-view/__tests__/ios/error-view.ios.test.js
packages/error-view/__tests__/shared.js
packages/error-view/__tests__/web/__snapshots__/error-view.web.test.js.snap
packages/error-view/__tests__/web/error-view.web.test.js
packages/error-view/__tests__/web/jest.config.js
packages/error-view/__tests__/web/serializers.js
packages/error-view/error-view.showcase.js
packages/error-view/package.json
packages/error-view/src/error-view.js

- add readme
- improve snapshots

refactor: error view tests and readme

---

packages/article/src/article.js
packages/brightcove-video/src/brightcove-player.web.js
packages/pagination/src/pagination-wrapper.js
packages/provider/__tests__/inner.js
packages/tracking/src/tracking-context.js
packages/video/src/inline-video-player.web.js

refactor: remove unsafe React lifecycle events

---

packages/icons/README.md
packages/icons/icons.showcase.js
packages/icons/src/icons/diamond.js
packages/icons/src/icons/email.js
packages/icons/src/icons/facebook.js
packages/icons/src/icons/prop-types.js
packages/icons/src/icons/star.js
packages/icons/src/icons/twitter.js
packages/icons/src/icons/video.js

- the refactor is simply ordering or renaming

docs: icons small refactor and add readme

---

packages/pull-quote/README.md
packages/pull-quote/__tests__/android/__snapshots__/pull-quotes-with-style.test.js.snap
packages/pull-quote/__tests__/ios/__snapshots__/pull-quotes-with-style.test.js.snap
packages/pull-quote/__tests__/web/__snapshots__/pull-quotes-with-style.test.js.snap
packages/pull-quote/pull-quote.showcase.js
packages/pull-quote/src/styles/index.js
packages/pull-quote/src/styles/shared.js
packages/topic/package.json

- add knobs to showcase
- amend colour and layouts as per Jake C

refactor: amend some styles and add readme for pull quotes

---

packages/provider-test-tools/fixtures/topic.json
packages/provider-test-tools/src/fixture-generator.js
packages/provider/__tests__/__snapshots__/topic-provider.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-loading.android.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic-with-style.android.test.js.snap
packages/topic/__tests__/android/__snapshots__/topic.android.test.js.snap
packages/topic/__tests__/fixtures.js
packages/topic/__tests__/ios/__snapshots__/topic-loading.ios.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic-with-style.ios.test.js.snap
packages/topic/__tests__/ios/__snapshots__/topic.ios.test.js.snap
packages/topic/__tests__/shared.base.js
packages/topic/__tests__/web/__snapshots__/topic-loading.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic-with-style.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic.web.test.js.snap
packages/topic/package.json
packages/topic/src/topic-head-prop-types.js
packages/topic/src/topic-head.js
packages/topic/src/topic-head.web.js
packages/topic/src/topic.js
packages/utils/src/schema.json

- Alongside https://github.com/newsuk/times-public-api/pull/584
- update Topic `description` to allow editorial to add basic style

Feat: Topic description type update

---

packages/date-publication/src/date-time.js

refactor: amend prop type to work with article summary

---

packages/article/.jestlint

PRs  merged to make a broken lint limit

fix: lint params

---

android-app/xnative/proguard-rules.pro
android/app/src/main/java/com/storybooknative/MainApplication.java

Remove svg dependency from android storybooks

Remove svg from native storybooks

---

packages/topic/package.json
yarn.lock

Top has an erroneous double entry of `@times-components/utils`

fix: remove topic dep

---

packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap
packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap
packages/article-topics/__tests__/shared-with-style.base.js
packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
packages/article-topics/article-topics.showcase.js
packages/article-topics/package.json
packages/article-topics/src/article-topic.js
packages/article-topics/src/article-topics.js
packages/article/__tests__/android/__snapshots__/article-comments-with-style.android.test.js.snap
packages/article/src/article-comments/comments.js
packages/button/src/button.js
packages/styleguide/src/fonts/font-sizes.android.js
packages/styleguide/src/fonts/font-sizes.js
packages/styleguide/src/line-heights/mapping.android.js
packages/styleguide/src/line-heights/mapping.js

Scaling updates specifically to Comments Button and Article Topics
https://nidigitalsolutions.jira.com/browse/REPLAT-3322

Feat: UX scaling updates

---

packages/schema/.prettierignore
yarn.lock

fix: ignore changelog

---

package.json
yarn.lock

fix: add lerna

---

packages/slice/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
packages/slice/src/templates/leadoneandtwo/config.web.js

Bug raised by @colincclark in the standup.

fix: Padding on image on wide

---

lib/cli/package-json.js

Adding depcheck to fix `yarn lint` on new packages.

fix: Update CLI for depcheck

---

packages/video/src/inline-video-player.web.js

- Fixes issue with hidden video player controls on web

Fix: Brightcove video controls

---

packages/key-facts/src/key-facts-text.js

fix: key facts ast prop warning

---

packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article/fixtures/full-article.js

fix: related article prop type warnings in article story

---

packages/article-list/src/article-list-page-error.web.js
packages/article-list/src/article-list.web.js
packages/article-list/src/styles/index.web.js
packages/article/__tests__/android/__snapshots__/article-comments-with-style.android.test.js.snap
packages/article/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-comments-with-style.ios.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/button/__tests__/android/__snapshots__/button.android.test.js.snap
packages/button/__tests__/ios/__snapshots__/button.ios.test.js.snap
packages/button/__tests__/shared.base.js
packages/button/__tests__/shared.native.js
packages/button/__tests__/shared.web.js
packages/button/__tests__/web/__snapshots__/button-accessible.web.test.js.snap
packages/button/__tests__/web/__snapshots__/button.web.test.js.snap
packages/button/src/button-prop-types.js
packages/button/src/button.web.js
packages/button/src/styles/index.web.js
packages/button/src/styles/shared.js

- replace Touchable component which is broken in RNW since the RN version bump. We decided to do this instead of a RNW version bump (will be done later)
- fixed missing prop types and related code coverage

fix: replace RN touchable component with web button

---

packages/ad/__tests__/android/__snapshots__/ad-placeholder-with-style.android.test.js.snap
packages/ad/__tests__/android/__snapshots__/ad-placeholder.android.test.js.snap
packages/ad/__tests__/ios/__snapshots__/ad-placeholder-with-style.ios.test.js.snap
packages/ad/__tests__/ios/__snapshots__/ad-placeholder.ios.test.js.snap
packages/ad/__tests__/web/__snapshots__/ad-placeholder-with-style.web.test.js.snap
packages/ad/__tests__/web/__snapshots__/ad-placeholder.web.test.js.snap
packages/ad/__tests__/web/__snapshots__/ad-with-style.web.test.js.snap
packages/ad/src/ad-placeholder.js

- Add test id to ad placeholder to aid e2e testing

chore: add test id to ad placeholder

---

packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
packages/article-list/src/article-list.web.js
packages/article-list/src/styles/index.web.js

- Fixes Article list inline ad with adblocker keyline bug

fix: article list inline ad with adblocker keyline bug

---

dextrose/dextrose.web.js

chore: large breakpoint for dextrose web

---

package.json
yarn.lock

Bitrise updated to yarn 1.10.0

Update yarn to 1.10.0

---

package.json
yarn.lock

chore: Bump fructose to 3.9.4

---

package.json

build: upgrade yarn

---

packages/article/__tests__/android/__snapshots__/article-comments-with-style.android.test.js.snap
packages/article/__tests__/android/__snapshots__/article-comments.android.test.js.snap
packages/article/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-comments-with-style.ios.test.js.snap
packages/article/__tests__/mocks.native.js
packages/article/src/article-comments/styles/shared.js
packages/button/src/styles/index.android.js

Request from Jake.
Bizarrely the margin was also creating a shadow, so it had to go.

fix: Removing shadow from buttons

---

packages/article/__tests__/ios/__snapshots__/article-comments-with-style.ios.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-comments.ios.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/button/__tests__/android/__snapshots__/button.android.test.js.snap

Merge was too quick on the last branch. This fixes `master`

chore: update snapshots

---

packages/article/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article/src/styles/article-body/shared.js

Fixes the ad padding across all three platforms

fix: Ad padding

---

packages/article-summary/__tests__/android/__snapshots__/article-summary-with-style.android.test.js.snap
packages/article-summary/src/styles/index.android.js
packages/article/__tests__/android/__snapshots__/article-comments.android.test.js.snap
packages/button/__tests__/android/__snapshots__/button-accessible.android.test.js.snap
packages/button/__tests__/android/__snapshots__/button.android.test.js.snap
packages/button/src/button.js
packages/button/src/button.web.js
packages/button/src/styles/index.android.js
packages/button/src/utils/index.android.js
packages/button/src/utils/index.js
packages/related-articles/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
packages/styleguide/src/fonts/font-sizes.android.js

These include:
* removing capitalisation from the button
* Increasing the button font size
* Label to Headline bottom margin removed
* Button border radius reduced to 2

fix: Minor Android styling adjustments

---

packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
packages/article-list/src/article-list.web.js

- Fix for production issue: https://nidigitalsolutions.jira.com/browse/REPLAT-4087
- All articles are now shown in `article-list`

Fix: Missing item in article list

---

packages/article-paragraph/__tests__/web/__snapshots__/article-paragraph-with-style.web.test.js.snap
packages/article-paragraph/__tests__/web/__snapshots__/article-paragraph.web.test.js.snap
packages/article-paragraph/src/article-paragraph.web.js
packages/article-paragraph/src/styles/responsive.web.js
packages/article/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article/__tests__/web/__snapshots__/article.web.test.js.snap

fix: remove surrounding divs from p tags in article

---

package.json

chore: upgrade yarn

---

packages/ssr/README.md

- update ssr readme to include article endpoint

fix: update ssr readme to include article endpoint

---

packages/provider-test-tools/package.json
yarn.lock

fix: error in master

---

packages/mock-tpa-server/package.json

fix: publish mock tpa server

---

packages/article-byline/__tests__/android/__snapshots__/article-byline-style.android.test.js.snap
packages/article-byline/__tests__/android/__snapshots__/article-byline-with-links-style.android.test.js.snap
packages/article-byline/__tests__/android/__snapshots__/article-byline-with-links.android.test.js.snap
packages/article-byline/__tests__/android/__snapshots__/article-byline.android.test.js.snap
packages/article-byline/__tests__/ios/__snapshots__/article-byline-style.ios.test.js.snap
packages/article-byline/__tests__/ios/__snapshots__/article-byline-with-links-style.ios.test.js.snap
packages/article-byline/__tests__/ios/__snapshots__/article-byline-with-links.ios.test.js.snap
packages/article-byline/__tests__/ios/__snapshots__/article-byline.ios.test.js.snap
packages/article-byline/__tests__/shared.base.js
packages/article-byline/__tests__/web/__snapshots__/article-byline-style.web.test.js.snap
packages/article-byline/__tests__/web/__snapshots__/article-byline-with-links-style.web.test.js.snap
packages/article-byline/__tests__/web/__snapshots__/article-byline-with-links.web.test.js.snap
packages/article-byline/__tests__/web/__snapshots__/article-byline.web.test.js.snap
packages/article-byline/fixtures/authors.json
packages/article-byline/shared-showcase.js

- Update byline showcase stories to use byline formatting more inline with current editorial usage

fix: Update byline showcase fixtures

---

packages/provider-test-tools/fixtures/article.json

- add missing `paywalledContent` field in fixture data

fix: missing paywalledContent field in fixture data

---

packages/ssr/src/server/topic.js

fix: add adconfig stuff to ssr server topic

---

ios/storybooknative.xcodeproj/project.pbxproj
ios/storybooknative/ArticleEvents.m
ios/storybooknative/AuthorProfileEvents.m
ios/storybooknative/ReactAnalytics.m
ios/storybooknative/ReactConfig.m
ios/storybooknative/TopicEvents.m

Added stub NativeModules for ios storybooks to get it working again

chore: Add native module stubs for ios storybooks

---

packages/utils/__tests__/get-headline.test.js

Adding a test that was missing.

test: getHeadline test added to utils package

---

ios-app/package.json
package.json

Added a script to bitrise to bundle ios assets (js bundle and images) and deploy them to bitrise. Deploy script is added to bitrise workflow

chore: automate ios builds

---

package.json
packages/ssr/__tests__/integration/article.js
packages/ssr/cypress.json
packages/ssr/package.json

fix: script to run from bitrise

---

packages/article-magazine-comment/__tests__/ad-mock.js
packages/article-magazine-comment/__tests__/shared.base.js
packages/article-magazine-comment/__tests__/web/semantic.web.test.js
packages/article-magazine-comment/article-magazine-comment.showcase.js
packages/article-magazine-comment/src/article-prop-types/article-prop-types.base.js
packages/article-main-comment/__tests__/android/jest.config.js
packages/article-main-comment/__tests__/ios/jest.config.js
packages/article-main-comment/__tests__/mocks.web.js
packages/article-main-comment/__tests__/shared-internal-components.base.js
packages/article-main-comment/__tests__/shared-props.js
packages/article-main-comment/__tests__/shared-with-style.native.js
packages/article-main-comment/__tests__/shared-with-style.web.js
packages/article-main-comment/__tests__/shared.base.js
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/jest.config.js
packages/article-main-comment/__tests__/web/semantic.web.test.js
packages/article-main-comment/src/article-flags/article-flags.js
packages/article-main-comment/src/article-prop-types/article-prop-types.base.js
packages/article/article.showcase.js
packages/article/package.json
packages/article/src/article.js

Main comment had a couple of changes that were made after magazine comment was created, and magazine comment improved a couple of things that can and should be copied back to main comment. That's what this PR does.

chore: update main comment with improvements from magazine comment

---

packages/article/article.showcase.js
packages/article/package.json

- Fix section list in article storybook

fix: Section list in article storybook

---

packages/storybook/__tests__/android/__snapshots__/storybook.android.test.js.snap
packages/storybook/__tests__/ios/__snapshots__/storybook.ios.test.js.snap
packages/storybook/__tests__/shared-showcase.js
packages/storybook/__tests__/web/__snapshots__/storybook.web.test.js.snap
packages/storybook/src/showcase-to-storybook.js

Ability to turn off strict mode for your storybook stories. This is to aid debugging for the things we are unable to fix for the time being.

feat: Toggle React Strict Mode

---

README.md
android/app/src/main/java/com/storybooknative/stubs/ReactConfig.kt
ios/storybooknative/ReactConfig.m
package.json
packages/ad/__tests__/dom-context.native.js
packages/ad/__tests__/utils/ad-init-prebid.js
packages/ad/__tests__/utils/ad-init-utils.js
packages/ad/__tests__/utils/ad-init.js
packages/ad/__tests__/web/dom-context.web.test.js
packages/ad/fixtures/ad-init-mocks.js
packages/ad/fixtures/check-self-contained-function.js
packages/ad/src/ad.js
packages/ad/src/dom-context.js
packages/ad/src/dom-context.web.js
packages/ad/src/utils/ad-init.js
packages/ad/src/utils/generate-config.js
packages/ad/src/utils/logger.js
packages/ad/src/utils/prebid-config.js
packages/article-skeleton/__tests__/ad-mock.js
packages/ssr/package.json
packages/ssr/src/lib/ads/base-ad-config.js

Previously headerbidding was not working on any react pages see https://www.thetimes.co.uk/edition/news/mays-brexit-backstop-is-barrier-to-new-trade-deals-says-leaked-legal-notes-tdbxtjx5h?react=1
this pr fixes the header bidding process by effectively passing the correct slot sizes

fix: prebid headerbidding on react pages

---

packages/related-articles/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
packages/slice/.jestlint
packages/slice/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
packages/slice/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
packages/slice/slice.showcase.js
packages/slice/src/templates/leadoneandtwo/index.web.js
packages/slice/src/templates/leadoneandtwo/responsive.web.js
packages/slice/src/templates/opiniononeandtwo/index.web.js
packages/slice/src/templates/opiniononeandtwo/responsive.web.js

Styles were screwed up in the last refactor 4 months ago. Also, keys were not being passed into to components which were iterated so fixed that too

fix: related articles styling

---

packages/article-list/src/article-list.web.js
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/src/article-meta/article-meta.web.js
packages/article-magazine-comment/src/styles/responsive.web.js
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/src/article-meta/article-meta.web.js
packages/article-magazine-standard/src/styles/responsive.web.js
packages/article-main-comment/src/article-meta/article-meta.web.js
packages/article-main-comment/src/styles/responsive.web.js

- Fixes broken server side rendering of separators on both magazine templates

fix: broken ssr of seperators

---

package.json

chore: new commands build:local and prepublish

---

packages/article-paragraph/src/index.js
packages/article-skeleton/__tests__/android/__snapshots__/article-header-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-header-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/src/article-body/article-body-row.js

Drop cap was not getting coloured on native. Fixed the prop name on article-paragraph so it's more clear and passed the dropCapColour from context

fix: drop cap section colouring

---

packages/ssr/__tests__/cypress/support/index.js
packages/ssr/package.json
yarn.lock

chore: upgrade cypress to 3.1.3

---

packages/article-skeleton/article-skeleton.showcase.js
packages/article-skeleton/article-skeleton.showcase.web.js
packages/article-skeleton/showcase-helper.js
packages/eslint-config-thetimes/index.js

Separate stories in order to not show scaling on web

fix: article skeleton story

---

packages/article/article.showcase.web.js
packages/article/showcase-helper.js

https://nidigitalsolutions.jira.com/browse/REPLAT-4706
Removes scaling from the article storybook by separating the stories

fix: article stories - remove web scaling

---

packages/article-comments/README.md

It's a one line addition to the README.MD file of the package `article-comments` to include the command to run tests for the web.

chore: update README of article-comments to include web test command

---

.storybook/config.js

https://nidigitalsolutions.jira.com/browse/REPLAT-4700
Move add on panel to the right in config for web as requested

refactor: put knobs and action logger panel on the right

---

packages/ad/fixtures/article-ad-config.json
packages/article-list/fixtures/article-ad-config.json

fix: correct storybook adslot config

---

packages/ad/src/utils/generate-config.js
packages/ad/src/utils/index.js
packages/ad/src/utils/prebid-config.js
packages/article-in-depth/package.json

- Passes position and section keywords to appnexus bid parameters http://prebid.org/dev-docs/bidders.html#appnexus-bid-params
- index exchange prebid adaptor does not support this 
- rubicon prebid adaptor only supports section keywords

feat: adding section and position to prebid vendors

---

packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-standard/__tests__/mocks.native.js
packages/article-main-standard/__tests__/responsive-mock.js
packages/article-main-standard/__tests__/shared-with-style.native.js
packages/article-main-standard/package.json
packages/article-main-standard/src/article-main-standard.js
packages/article-main-standard/src/styles/article-body/shared.js

feat: move lead asset on tablet on article main standard

---

packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap

We broke some snapshots while merging multiple PRs. Updated the snaps with the ArticleFlags mock

chore: Update snaps

---

packages/article-in-depth/package.json
packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-standard/__tests__/mocks.native.js
packages/article-magazine-standard/__tests__/shared-with-style.native.js
packages/article-magazine-standard/package.json
packages/article-magazine-standard/src/article-header/article-header.js
packages/article-magazine-standard/src/article-magazine-standard.js
packages/article-magazine-standard/src/styles/shared.js
packages/edition-slices/package.json
packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/provider-test-tools/package.json
packages/provider/package.json
packages/schema/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/watermark/package.json

feat: magazine standard tablet layout header

---

packages/article-in-depth/package.json

fix: Versions

---

packages/article-flag/article-flag.showcase.js

- Remove default flag from storybook

chore: remove default flag from storybook

---

packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-standard/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-comment/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/src/article-skeleton.js
packages/article-skeleton/src/styles/shared.js

https://nidigitalsolutions.jira.com/browse/REPLAT-5267
Feedback from the internal sprint review was to put in a placeholder width while we deal with a native tablet version of related articles. This PR is designed to do that.

feat: Allow related articles to be smaller on a native tablet breakpoint

---

packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-in-depth/__tests__/shared-with-style.native.js
packages/article-in-depth/package.json
packages/article-in-depth/src/article-header/article-header.js
packages/article-in-depth/src/article-in-depth.js
packages/article-in-depth/src/article-meta/article-meta.js
packages/article-in-depth/src/styles/shared.js
packages/styleguide/src/breakpoints/index.js
packages/styleguide/src/styleguide.js

https://nidigitalsolutions.jira.com/browse/REPLAT-5155
* Sets a max width of 1180px for items that are considered "100%" width.
* Increases in font size for Headline
* Meta information changes display layout and introduces a seperator

Feat: REPLAT-5155 In depth header width

---

packages/article-image/__tests__/android/__snapshots__/article-image-with-style.android.test.js.snap
packages/article-image/__tests__/android/__snapshots__/article-image.android.test.js.snap
packages/article-image/__tests__/ios/__snapshots__/article-image-with-style.ios.test.js.snap
packages/article-image/__tests__/ios/__snapshots__/article-image.ios.test.js.snap
packages/article-image/src/article-image.js
packages/article-image/src/inset-caption.js
packages/article-image/src/styles/index.js

https://nidigitalsolutions.jira.com/browse/REPLAT-5156
With Bonus:
- Inline image padding changes
- Dependency fixes

feat: Left align caption and credits on tablet body images

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/fixtures/leadoneandone.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-d/index.js
packages/edition-slices/src/tiles/tile-d/styles/index.js
packages/edition-slices/src/tiles/tile-e/index.js
packages/edition-slices/src/tiles/tile-e/styles/index.js
packages/fixture-generator/src/mock-image.ts
packages/styleguide/src/line-heights/mapping-base.js

Based on the spreadsheet here: https://docs.google.com/spreadsheets/d/1kmhTKkxRk_FlS3S0tqEKZxJrWp741hs3EQJEw2r-eNg/edit?ts=5c4852a4#gid=0
These are two required slices.

feat: Tile D and E

---

packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/provider-test-tools/package.json
packages/provider/package.json
packages/schema/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/watermark/package.json

chore: Update dependencies

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/tile-b/index.js
packages/edition-slices/src/tiles/tile-g/index.js

- remove unused style
- add a `View` as we can't add padding to the `<TileLink>`

fix: padding on tiles

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-slices.base.js
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/tile-c/index.js

Current in master:
Fixed in PR

Chore: fixing style for Tile C

---

packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/provider-test-tools/package.json
packages/provider/package.json
packages/schema/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/watermark/package.json

chore: Fix master dependencies

---

android-app/index.android.js
ios-app/index.ios.js
packages/pages/__tests__/section.native.js
packages/pages/pages.showcase.native.js
packages/pages/src/pages.js
packages/pages/src/section/index.js
packages/pages/src/section/section.js

This PR enables native apps to consume section pages with the section data, passed in as a json string.

feat: Add section page entry point for apps

---

packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/src/article-header/article-header.js
packages/article-main-comment/src/styles/shared.js
packages/article-main-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
packages/article-skeleton/src/article-topics/index.js
packages/article-skeleton/src/styles/article-topics/shared.js

One of the tasks from: https://nidigitalsolutions.jira.com/browse/REPLAT-5405

feat: Updating keyline width for tablet articles

---

packages/article-summary/__tests__/android/__snapshots__/article-summary.android.test.js.snap
packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
packages/article-summary/__tests__/shared.base.js
packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
packages/article-summary/fixtures/no-byline.js

Again in the effort to improve our overall coverage, some additional tests for `ArticleSummary`.

chore: Improve article summary coverage

---

packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-in-depth/src/article-header/article-header.js
packages/article-in-depth/src/styles/shared.js

Number 4 of the design review task: https://nidigitalsolutions.jira.com/browse/REPLAT-5405

feat: Restricting the width of the header text for indepth tablet

---

packages/provider/__tests__/__snapshots__/native-edition-provider.test.js.snap

Edition snapshot is breaking master, fixed.

fix: Update edition snap

---

packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/src/article-header/article-header.js
packages/article-main-comment/src/article-meta/article-meta.js
packages/article-main-comment/src/styles/shared.js

6a on this ticket: https://nidigitalsolutions.jira.com/browse/REPLAT-5405

feat: Update the main comment byline design

---

packages/watermark/package.json

- versions are out again on `master`

fix: deps on master

---

packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/shared/tile-summary.js
packages/edition-slices/src/tiles/tile-n/index.js
packages/edition-slices/src/tiles/tile-n/styles/index.js
packages/edition-slices/src/tiles/tile-o/index.js
packages/edition-slices/src/tiles/tile-o/styles/index.js

- fixes issue with article labels

fix: broken article label

---

packages/article-paragraph/__tests__/android/__snapshots__/article-paragraph-with-style.android.test.js.snap
packages/article-paragraph/__tests__/android/__snapshots__/themes-with-style.android.test.js.snap
packages/article-paragraph/src/drop-cap.js
packages/article-paragraph/src/styles/drop-cap-sizes.android.js
packages/article-paragraph/src/styles/drop-cap-sizes.js
packages/utils/src/screen.js
packages/utils/src/text-layout/index.js
packages/utils/src/text-layout/styles/index.android.js
packages/utils/src/text-layout/styles/index.js
packages/utils/src/text-layout/styles/shared.js

Fixes a bunch of issues with drop-caps on iOS

Fix: ios drop caps

---

CODEOWNERS

chore: add myself to CODEOWNERS

---

packages/storybook/__tests__/android/__snapshots__/storybook.android.test.js.snap
packages/storybook/__tests__/ios/__snapshots__/storybook.ios.test.js.snap
packages/storybook/__tests__/shared.js
packages/storybook/__tests__/web/__snapshots__/storybook.web.test.js.snap
packages/storybook/src/select-shim.js
packages/storybook/src/showcase-to-storybook.js

Small test improvements to help improve coverage.

chore: Improve the coverage on the storybook package slightly

---

packages/article-in-depth/src/article-meta/article-meta.js
packages/article-in-depth/src/styles/shared.js
packages/article-magazine-comment/src/article-header/article-header.js
packages/article-magazine-comment/src/article-meta/article-meta.js
packages/article-magazine-comment/src/styles/index.android.js
packages/article-magazine-comment/src/styles/index.js
packages/article-magazine-comment/src/styles/native.js
packages/article-magazine-comment/src/styles/shared.js
packages/article-main-comment/src/article-meta/article-meta.js
packages/article-main-comment/src/styles/shared.js

This one is the same as the Comment Template. This needs to feature in Magazine Comment: https://nidigitalsolutions.jira.com/browse/REPLAT-5405

feat: Article Magazine Comment - Tablet Byline

---

packages/article-magazine-standard/src/article-header/article-header.js
packages/article-magazine-standard/src/article-meta/article-meta.js
packages/article-magazine-standard/src/styles/index.android.js
packages/article-magazine-standard/src/styles/index.js
packages/article-magazine-standard/src/styles/native.js
packages/article-magazine-standard/src/styles/shared.js
packages/article-main-comment/src/styles/shared.js
packages/fixture-generator/package.json
packages/markup-forest/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/tracking/package.json
packages/utils/package.json
packages/watermark/package.json

Another Byline and Datepub on the same line.

feat: Article Magazine Standard tablet byline

---

packages/article-paragraph/src/styles/drop-cap-sizes.android.js
packages/article-paragraph/src/styles/drop-cap-sizes.js

Some more offsets, this time for ios magazine templates.

fix: ios magazine drop cap numbers

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-t/index.js
packages/edition-slices/src/tiles/tile-t/styles/index.js

Tile T is like Tile D, but with a different ratio image.

feat: Edition slice tile - Tile T

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/tiles/tile-f/styles/index.js

- fixed text wrap issue in web only

fix: tile f text wrap bug on web

---

packages/article-byline/article-byline-opinion.showcase.js
packages/article-byline/shared-showcase.js
packages/article-byline/src/article-byline-opinion.js
packages/article-byline/src/article-byline.js
packages/article-byline/src/render-byline.js
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/shared/tile-summary.js
packages/edition-slices/src/tiles/tile-p/styles/index.js
packages/related-articles/src/related-article-item.base.js

This PR places byline to the bottom of Tile H, also centre aligns the strapline.

fix: tile p style and byline

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/slices/secondaryone/index.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-w/index.js
packages/edition-slices/src/tiles/tile-w/styles/index.js

- as per https://nidigitalsolutions.jira.com/browse/REPLAT-5305

feat: secondary 1 - 768 breakpoint

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/slices/leaders/styles.js
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/edition-slices/src/tiles/tile-d/styles/index.js
packages/edition-slices/src/tiles/tile-e/styles/index.js
packages/edition-slices/src/tiles/tile-i/styles/index.js
packages/edition-slices/src/tiles/tile-j/styles/index.js
packages/edition-slices/src/tiles/tile-m/styles/index.js
packages/edition-slices/src/tiles/tile-n/index.js
packages/edition-slices/src/tiles/tile-n/styles/index.js
packages/fixture-generator/src/__tests__/mock-tile.test.ts
packages/fixture-generator/src/index.ts
packages/fixture-generator/src/mock-article.ts
packages/fixture-generator/src/mock-slice.ts
packages/fixture-generator/src/mock-tile.ts
packages/fixture-generator/src/types.ts

- as per https://nidigitalsolutions.jira.com/browse/REPLAT-5586

fix: design review changes

---

packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/fixture-generator/src/mock-image.ts

Images were not showing in the native storybook. This change fixes that.

fix: Missing images in storybook

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-x/index.js
packages/edition-slices/src/tiles/tile-x/styles/index.js
packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/schema/package.json
packages/slice-layout/package.json
packages/styleguide/src/line-heights/mapping-base.js
packages/svgs/package.json
packages/tealium/package.json
packages/utils/package.json
packages/watermark/package.json

feat: Tile X required for Lead 2 No Pic and 2

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-y/index.js
packages/edition-slices/src/tiles/tile-y/styles/index.js

feat: Tile Y for Lead 2 no pic and 2

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-z/index.js
packages/edition-slices/src/tiles/tile-z/styles/index.js
packages/slice-layout/package.json

feat: Tile Z for Lead no pic and 2

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/slices/leadoneandone/index.js
packages/edition-slices/src/tiles/tile-i/styles/index.js
packages/edition-slices/src/tiles/tile-j/styles/index.js
packages/edition-slices/src/tiles/tile-u/styles/index.js
packages/edition-slices/src/tiles/tile-w/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/l1and1-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/sd2and2-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/l1and1-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd2and2-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/l1and1-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd2and2-with-style.web.test.js.snap
packages/slice-layout/src/templates/leadoneandone/styles.js
packages/slice-layout/src/templates/secondarytwoandtwo/styles.js

- as per https://nidigitalsolutions.jira.com/browse/REPLAT-5617

fix: design review updates

---

packages/article-comments/__tests__/android/__snapshots__/shared-with-style.android.test.js.snap
packages/article-comments/__tests__/android/__snapshots__/shared.android.test.js.snap
packages/article-comments/__tests__/ios/__snapshots__/shared-with-style.ios.test.js.snap
packages/article-comments/__tests__/ios/__snapshots__/shared.ios.test.js.snap
packages/article-comments/src/comment-error.js

https://nidigitalsolutions.jira.com/browse/REPLAT-5581

fix: Update offline message for comments

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/shared-tablet-slices.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/slices/leadtwonopicandtwo/index.js
packages/slice-layout/__tests__/android/__snapshots__/l2np2-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/l2np2.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/l2np2-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/l2np2.ios.test.js.snap
packages/slice-layout/__tests__/l2np2.base.js
packages/slice-layout/__tests__/web/__snapshots__/l2np2-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/l2np2.web.test.js.snap
packages/slice-layout/src/templates/leadtwonopicandtwo/index.js
packages/slice-layout/src/templates/leadtwonopicandtwo/proptypes.js
packages/slice-layout/src/templates/leadtwonopicandtwo/styles.js

feat: Portrait Tablet (768px) for Lead Two No Pic And Two slice

---

packages/edition-slices/__tests__/android/__snapshots__/roundel-image-tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/roundel-image-tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/roundel-image-tiles.test.js.snap

A small PR for updating failing snapshots.

fix: update failing snapshots

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/slices/listtwoandsixnopic/index.js
packages/edition-slices/src/tiles/tile-l/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/list2and6nopic-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/list2and6nopic.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/list2and6nopic-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/list2and6nopic.ios.test.js.snap
packages/slice-layout/__tests__/list2and6nopic.base.js
packages/slice-layout/__tests__/web/__snapshots__/list2and6nopic-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/list2and6nopic.web.test.js.snap
packages/slice-layout/src/templates/listtwoandsixnopic/index.js
packages/slice-layout/src/templates/listtwoandsixnopic/styles.js

- as per https://nidigitalsolutions.jira.com/browse/REPLAT-5245

feat: List 2 no pic 6 tablet

---

packages/provider-test-tools/src/edition.js

Attempt to fix the errors in master.

fix: Attempt to fix Edition Provider Test Tools

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/tile-ae/index.js
packages/edition-slices/src/tiles/tile-ae/styles/index.js

Needed for Secondary 2 no pic and 2 tablet portrait

feat: Tile AE

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/shared-tablet-slices.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/slices/secondarytwonopicandtwo/index.js
packages/slice-layout/__tests__/android/__snapshots__/sd2np2-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/sd2np2.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd2np2-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd2np2.ios.test.js.snap
packages/slice-layout/__tests__/sd2np2.base.js
packages/slice-layout/__tests__/web/__snapshots__/sd2np2-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd2np2.web.test.js.snap
packages/slice-layout/src/templates/secondarytwonopicandtwo/index.js
packages/slice-layout/src/templates/secondarytwonopicandtwo/proptypes.js
packages/slice-layout/src/templates/secondarytwonopicandtwo/styles.js

This is the slice for the 768px breakpoint

feat: Secondary 2 no pic and 2 tablet

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/shared-components.base.js
packages/edition-slices/__tests__/shared-tablet-slices.base.js
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap

feat: Better test coverage on shared tile components

---

packages/section/src/section.js
packages/slice-layout/src/templates/column/index.js

Added keys to FlatList items and column layout for better performance.

fix: Add keys to flatlists

---

packages/video/src/inline-video-player.web.js

- fix bug whereby pause and fullscreen buttons were hidden for 360 videos

fix: bug whereby pause and fullscreen buttons were hidden for 360 videos

---

packages/edition-slices/src/slices/puzzle/index.js
packages/edition-slices/src/slices/puzzle/puzzle-tracking-events.js
packages/edition-slices/src/tiles/shared/tile-tracking-events.js
packages/fixture-generator/src/mock-section.ts
packages/fixture-generator/src/mock-slice.ts
packages/pages/src/section/index.js
packages/section/__tests__/android/__snapshots__/section-tracking.test.js.snap
packages/section/__tests__/ios/__snapshots__/section-tracking.test.js.snap
packages/section/__tests__/shared-tracking.js
packages/section/__tests__/shared.js
packages/section/section.showcase.js
packages/section/src/section.js

Article press and puzzle press events on sections.
+ Also fixed puzzle click analytics

feat: section press events

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/shared-tablet-slices.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/slices/dailyregisterleadfour/index.js
packages/edition-slices/src/slices/dailyregisterleadfour/styles.js

Implement Daily Universal Register for Tablet
Portrait 
Landscape:

feat: Implement Daily Register for Tablet

---

packages/article-summary/__tests__/android/__snapshots__/article-summary-shared-supporting-components-with-style.android.test.js.snap
packages/article-summary/__tests__/android/__snapshots__/article-summary-supporting-components.android.test.js.snap
packages/article-summary/__tests__/android/article-summary-shared-supporting-components-with-style.android.test.js
packages/article-summary/__tests__/android/article-summary-supporting-components.android.test.js
packages/article-summary/__tests__/ios/__snapshots__/article-summary-shared-supporting-components-with-style.ios.test.js.snap
packages/article-summary/__tests__/ios/__snapshots__/article-summary-supporting-components.ios.test.js.snap
packages/article-summary/__tests__/ios/article-summary-shared-supporting-components-with-style.ios.test.js
packages/article-summary/__tests__/ios/article-summary-supporting-components.ios.test.js
packages/article-summary/__tests__/shared-supporting-components-with-style.native.js
packages/article-summary/__tests__/shared-supporting-components-with-style.web.js
packages/article-summary/__tests__/shared-supporting-components.base.js
packages/article-summary/__tests__/shared-supporting-components.native.js
packages/article-summary/__tests__/shared-supporting-components.web.js
packages/article-summary/__tests__/web/__snapshots__/article-summary-shared-supporting-components-with-style.web.test.js.snap
packages/article-summary/__tests__/web/__snapshots__/article-summary-supporting-components.web.test.js.snap
packages/article-summary/__tests__/web/article-summary-shared-supporting-components-with-style.web.test.js
packages/article-summary/__tests__/web/article-summary-supporting-components.web.test.js
packages/slice-layout/package.json

Trying to bring our coverage back up

chore: Improve code coverage in Article Summary

---

packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/provider-test-tools/package.json
packages/provider/package.json
packages/schema/package.json
packages/slice-layout/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/utils/package.json
packages/watermark/package.json

chore: Fix versions

---

packages/jest-configurator/package.json
packages/lazy-load/package.json
packages/markup-forest/package.json
packages/provider-test-tools/package.json
packages/provider/package.json
packages/schema/package.json
packages/slice-layout/package.json
packages/svgs/package.json
packages/tealium/package.json
packages/utils/package.json
packages/watermark/package.json

chore: deps

---

packages/edition-slices/edition-slices.showcase.js
packages/edition-slices/src/tiles/shared/tile-link.js
packages/pages/src/section/index.js
packages/section/section.showcase.js

Fix broken snapshot click event

fix: Fix broken snapshot click event

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/src/tiles/tile-ah/styles/index.js
packages/edition-slices/src/tiles/tile-ai/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/clac-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/clac-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/clac-with-style.web.test.js.snap
packages/slice-layout/src/templates/commentleadandcartoon/styles.js

The PR updates ratio split as per zeplin
Also corrects top padding on the left tile as per zeplin

feat: updated design and snapshots

---

packages/icons/__tests__/android/__snapshots__/icons-colour.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons-dim.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons.android.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons-colour.ios.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons-dim.ios.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons.ios.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons-colour.web.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons-dim.web.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons.web.test.js.snap
packages/icons/src/icons.js
packages/icons/src/icons/forward-arrow.js
packages/section/__tests__/android/__snapshots__/section.test.js.snap
packages/section/__tests__/ios/__snapshots__/section.test.js.snap
packages/section/__tests__/shared-tracking.js
packages/section/__tests__/shared.js
packages/section/package.json
packages/section/section.showcase.js
packages/section/src/puzzle-bar.js
packages/section/src/puzzle-notification-bar.js
packages/section/src/section.js
packages/section/src/styles/index.js

- as per https://nidigitalsolutions.jira.com/browse/REPLAT-5406

feat: Puzzle notification bar

---

packages/edition-slices/.jestlint
packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/src/slices/leaders/styles.js

add grey bg to the leaders slice

fix: add grey background to the leaders slice

---

packages/article-in-depth/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/styles/shared.js

- fix byline alignment
- https://nidigitalsolutions.jira.com/browse/REPLAT-5870

fix: Byline alignment on indepth template

---

packages/article-label/__tests__/android/__snapshots__/article-label.android.test.js.snap
packages/article-label/__tests__/ios/__snapshots__/article-label.ios.test.js.snap
packages/article-label/src/style/index.js
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/la2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/oa2-with-style.android.test.js.snap
packages/related-articles/__tests__/android/__snapshots__/std-with-style.android.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/la2-with-style.ios.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/oa2-with-style.ios.test.js.snap
packages/related-articles/__tests__/ios/__snapshots__/std-with-style.ios.test.js.snap

fix: decrease letter spacing on article label text

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
packages/edition-slices/src/tiles/tile-m/styles/index.js
packages/edition-slices/src/tiles/tile-s/styles/index.js

☐ DUR body copy should be Times Digital line-height needs increasing
☐ Leaders - strapline colour should be #696969
☐ DUR title needs to match Leaders title padding

fix: DUR and Leaders slice issues

---

android-app/build.gradle
android-app/package.json
android-app/settings.gradle
android-app/xnative/build.gradle
android/app/build.gradle
android/app/src/main/java/com/storybooknative/MainApplication.java
android/settings.gradle
package.json
packages/icons/.jestlint
packages/icons/__tests__/android/__snapshots__/icons-colour.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons-dim.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons.android.test.js.snap
packages/icons/__tests__/shared-dim.native.js
packages/icons/icons.showcase.js
packages/jest-configurator/__tests__/__snapshots__/jest-configurator.test.js.snap
packages/jest-configurator/__tests__/jest-configurator.test.js
packages/jest-configurator/src/jest-configurator.js
packages/svgs/.jestlint
packages/svgs/__tests__/android/__snapshots__/svgs.test.js.snap
packages/svgs/__tests__/android/svgs.test.js
packages/svgs/package.json
packages/svgs/src/index.android.js
packages/video/.jestlint
packages/video/__tests__/android/__snapshots__/video.android.test.js.snap
packages/video/__tests__/ios/__snapshots__/video.ios.test.js.snap
packages/video/src/play-icon.native.js
yarn.lock

React-native-art has some serious bugs on android concerning performance and issues on re-rendering. This PR replaces our react-native-art based svg implementation with react-native-svg library.

feat: react native svg on android

---

packages/edition-slices/src/tiles/tile-ag/index.js
packages/edition-slices/src/tiles/tile-m/index.js
packages/jest-configurator/package.json
packages/markup-forest/package.json
packages/slice-layout/package.json
packages/svgs/package.json
packages/watermark/package.json

Noticed two tiles where strapline override was missing

fix: strapline

---

packages/article-list/__tests__/web/__snapshots__/article-list-error-with-styles.web.test.js.snap
packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-render-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-reverse-style.test.js.snap
packages/image/__tests__/web/__snapshots__/image-with-style.web.test.js.snap
packages/image/src/styles/index.web.js
packages/jest-configurator/package.json
packages/markup-forest/package.json
packages/svgs/package.json
packages/watermark/package.json

fix: images on safari

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article/showcase-helper.js
packages/provider-test-tools/src/fixtures/inline-video.json
packages/provider-test-tools/src/fixtures/key-facts.json
packages/provider-test-tools/src/fixtures/pull-quote.json
packages/provider-test-tools/src/index.js
packages/pull-quote/__tests__/android/__snapshots__/pull-quotes-with-style.android.test.js.snap
packages/pull-quote/__tests__/android/__snapshots__/pull-quotes.android.test.js.snap
packages/pull-quote/__tests__/ios/__snapshots__/pull-quotes-with-style.ios.test.js.snap
packages/pull-quote/__tests__/ios/__snapshots__/pull-quotes.ios.test.js.snap
packages/pull-quote/__tests__/web/__snapshots__/pull-quotes-with-style.test.js.snap
packages/pull-quote/__tests__/web/__snapshots__/pull-quotes.test.js.snap
packages/pull-quote/__tests__/web/__snapshots__/themes-with-style.web.test.js.snap
packages/pull-quote/pull-quote.showcase.js
packages/pull-quote/src/pull-quote-twitter-link.js
packages/pull-quote/src/styles/responsive.web.js
packages/pull-quote/src/styles/shared.js

Fix the design of pull quotes on web. Also add some new elements to the article showcase

fix: pull quotes design

---

packages/icons/__tests__/android/__snapshots__/icons-colour.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons-dim.android.test.js.snap
packages/icons/__tests__/android/__snapshots__/icons.android.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons-colour.ios.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons-dim.ios.test.js.snap
packages/icons/__tests__/ios/__snapshots__/icons.ios.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons-colour.web.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons-dim.web.test.js.snap
packages/icons/__tests__/web/__snapshots__/icons.web.test.js.snap
packages/save-and-share-bar/README.md
packages/save-and-share-bar/__tests__/shared.base.js
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/constants/index.js
packages/save-and-share-bar/src/save-and-share-bar.js

feat: implement fb and tw sharing

---

android/app/build.gradle
android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties

-  this fixes the build issue that I was having to get the storybook native working locally

fix: upgrade android dependancies for storybook native

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/tiles/tile-ac/styles/index.js
packages/edition-slices/src/tiles/tile-ad/styles/index.js
packages/edition-slices/src/tiles/tile-ae/styles/index.js
packages/edition-slices/src/tiles/tile-aj/styles/index.js
packages/edition-slices/src/tiles/tile-c/styles/index.js
packages/edition-slices/src/tiles/tile-r/styles/index.js
packages/edition-slices/src/tiles/tile-u/styles/index.js
packages/edition-slices/src/tiles/tile-v/styles/index.js
packages/edition-slices/src/tiles/tile-x/styles/index.js
packages/edition-slices/src/tiles/tile-y/styles/index.js
packages/edition-slices/src/tiles/tile-z/styles/index.js

- https://nidigitalsolutions.jira.com/browse/REPLAT-6297

fix: Font size issues on slices

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/shared/styles/index.js
packages/edition-slices/src/tiles/tile-c/index.js

This reverts commit 2a3735b0d29f65421dc3c285d594c97ea56c5373.

fix: android tile star styling

---

package.json

More info : https://github.com/meteor/meteor/issues/9824#issuecomment-386115424

chore: fix storybook

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/tile-aj/index.js
packages/edition-slices/src/tiles/tile-aj/styles/index.js
packages/edition-slices/src/tiles/tile-ak/index.js
packages/edition-slices/src/tiles/tile-ak/styles/index.js

- Puzzle background styling fixed for both mobile and tablet puzzle tiles

fix: puzzle tile bgs

---

packages/article-paragraph/__tests__/web/__snapshots__/article-paragraph-with-style.web.test.js.snap
packages/article-paragraph/__tests__/web/__snapshots__/themes-with-style.web.test.js.snap
packages/article-paragraph/src/article-paragraph.web.js

**Issue: article page is broken in storybook web locally - shows blank page with js errors.**
This PR is fixing it.
- more info : https://github.com/facebook/react/issues/15375#issuecomment-490701560

fix: fix article page on storybook web

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/slices/secondaryoneandfour/index.js
packages/edition-slices/src/slices/secondaryoneandfour/styles.js
packages/edition-slices/src/tiles/tile-n/index.js
packages/edition-slices/src/tiles/tile-n/styles/index.js

Implement supplement secondary 1 and 4 for huge tablet breakpoint.

feat: Implement edition slice supplement secondary 1 and 4

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/src/slices/secondaryone/index.js
packages/edition-slices/src/tiles/tile-w/index.js
packages/edition-slices/src/tiles/tile-w/styles/index.js

Implement secondary-one slice for huge breakpoint.

feat: Implement secondary-one slice for huge breakpoint.

---

packages/ad/src/ad.js

feat: make ads 100% width on native platforms

---

packages/utils/__tests__/user-state.test.js
packages/utils/src/index.js
packages/utils/src/user-state.js

Chore: Add user state util functions in util package

Chore: Add user state util functions

---

package.json
yarn.lock

Added react-scripts as a dev dependency to fix issues on our published storybook

chore: Add react-scripts to fix storybook issues

---

packages/utils/src/index.web.js
yarn.lock

We are exporting HoverIcon on utils for all platforms, which is breaking native apps due to styledComponents not being available on native

fix: Native crash due to HoverIcon

---

packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
packages/article-skeleton/__tests__/web/article-with-user-state.web.test.js
packages/article-skeleton/src/article-skeleton.web.js
packages/article/article.showcase.web.js
packages/article/showcase-helper.js

This PR is about display metered expired page, to users that have red all of their free articles.
This page is similar to teaser page. The difference is that metered expired pages displays also:
1. Save and share bar
2. Topics links

Feat: Display metered expired page for metered expired users

---

packages/article-list/__tests__/mocks.js
packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
packages/article-list/src/article-list-item.web.js
packages/article-summary/fixtures/article-empty-paragraph.js
packages/article-summary/fixtures/article-multi.js
packages/article-summary/fixtures/blank.js
packages/article-summary/fixtures/default.js
packages/article-summary/fixtures/no-byline.js
packages/article-summary/fixtures/no-datepublication.js
packages/article-summary/fixtures/no-headline.js
packages/article-summary/fixtures/no-label.js
packages/article-summary/fixtures/opinion-byline.js
packages/article-summary/fixtures/review.js
packages/article-summary/fixtures/strapline.js
packages/article-summary/fixtures/video-label.js
packages/article-summary/fixtures/with-summary-links.js
packages/article-summary/src/article-summary.js
packages/edition-slices/src/tiles/shared/tile-summary.js
packages/image/src/close-button/close-button.js
packages/image/src/logo/t.js
packages/pages/__tests__/saved-star-sync.js
packages/pages/src/section/section.js
packages/related-articles/src/related-article-item.base.js

Improve section performance by:
- Preventing multiple simultaneous saved article syncing (triggering multiple re-renders)
- Improve performance of image placeholder component
- Improve performance of articule summary component

chore: improve section performance

---

packages/article/article.showcase.web.js
packages/article/showcase-helper.js

workaround to show less data for logged out / RA expired users

fix: show less content for teaser page and metered expired page

---

packages/article-in-depth/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/article-header/article-header.js
packages/article-in-depth/src/article-in-depth.js
packages/article-in-depth/src/styles/shared.js
packages/article-magazine-comment/src/article-magazine-comment.js
packages/article-magazine-standard/src/article-magazine-standard.js
packages/article-main-comment/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/src/article-main-comment.js
packages/article-main-comment/src/styles/shared.js
packages/article-main-standard/src/article-main-standard.js
packages/article-paragraph/src/styles/drop-cap-sizes.android.js
packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/src/article-body/article-body-row.js
packages/article-skeleton/src/article-skeleton.js
yarn.lock

feat: (Replat 6378) Fix article regressions

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/save-and-share-bar.js
packages/save-star-web/__tests__/shared-tracking.js
packages/save-star-web/__tests__/shared.base.js
packages/save-star-web/__tests__/web/__snapshots__/save-star-web-tracking.test.js.snap
packages/save-star-web/__tests__/web/__snapshots__/save-star-web.test.js.snap
packages/save-star-web/__tests__/web/save-star-web-tracking.test.js
packages/save-star-web/package.json
packages/save-star-web/src/save-star-web.js
packages/save-star-web/src/tracking/with-track-events.js

Add tracking to save star press event. Only articleId is going to be tracked. Save star tests are refactored.

Feat Add tracking to save star press event

---

lib/publish-ios-assets.sh
package.json

Fixes github url with the token for ios publish scripts

fix: ios publish script

---

android-app/README.md
packages/save-and-share-bar/__tests__/shared-tracking.js
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/save-and-share-bar.js
packages/save-star-web/__tests__/shared-tracking.js
packages/save-star-web/__tests__/shared.base.js
packages/save-star-web/src/save-star-web.js

Update save star web tests. Add two more test scenarios to test if the correct method is invoked. 
Add some changes to the android-app readme

fix: save-star-web tests

---

README.md
packages/text-flow/lib/process-fonts.sh

Slight update to the Readme and an install script based on the process I had to go through to get the app running. 
I'm not that familiar with `python`'s `pip` so if this doesn't look right I'm happy to revert

Update readme and install script for fonts

---

TimesComponents.podspec

Updated times components podspec with react native webview dependency

REPLAT-6654 Upgrade Web View Library within Native App

---

lib/cli/package-json.js
packages/user-state/package.json

fix cli watch command and add user-state watch

chore: fix cli watch command and add user-state watch

---

packages/save-and-share-bar/__tests__/shared.base.js
packages/save-and-share-bar/package.json
packages/save-and-share-bar/src/email-share.js
packages/save-and-share-bar/src/save-and-share-bar.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-6792

fix: email sharing publication name

---

packages/schema/__tests__/__snapshots__/fetch-gql-schema.test.js.snap
packages/schema/fetch-gql-schema.js

fix: legacy iOS

---

packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/tile-ah/styles/index.js
packages/edition-slices/src/tiles/tile-g/styles/index.js
packages/edition-slices/src/tiles/tile-l/styles/index.js

fix: save star positioning

---

packages/text-flow/text-flow.showcase.js

Remove text flow from web storybook

fix: remove text flow from web storybook

---

packages/ad/__tests__/utils/ad-init.js
packages/ad/src/utils/ad-init.js
packages/ssr/__tests__/helpers/article-helper.js

jira: https://nidigitalsolutions.jira.com/browse/REPLAT-1407
This separates googletag page and slot targeting, due to the way ad components are set up in react pages

fix: correct ad loading behaviour

---

packages/ad/src/dom-context.js

fix: restore fix for android unruly ads
