newsuk/times-components

packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/article-header/article-header.js
packages/article-in-depth/src/article-header/article-header.web.js
packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/src/article-header/article-header.js
packages/article-magazine-comment/src/article-header/article-header.web.js
packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/src/article-header/article-header.js
packages/article-magazine-standard/src/article-header/article-header.web.js
packages/styleguide/src/theme/theme-factory.js

https://nidigitalsolutions.jira.com/browse/REPLAT-7122

fix: uppercase font on style magazine templates

---

packages/article-paragraph/src/drop-cap.js
packages/article-skeleton/src/article-body/article-body-row.js
packages/article-skeleton/src/article-skeleton.js
packages/article-skeleton/src/dropcap-util-common.js
packages/text-flow/src/Layout/TextFlow.js
packages/text-flow/src/Text/Linebreak.js
packages/text-flow/src/Text/Text.js

Fixes a bunch of issues causing high cpu usage in some articles, depending on template.

fix: REPLAT-7145, REPLAT-7130

---

packages/styleguide/src/theme/theme-factory.js

- default values don't handle `null` values well so need the extra check for section.
- Fix Render 500 errors in CI with latest TC.

fix: theme factory handling of null sections

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/shared-tiles.base.js
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/edition-tiles.showcase.js
packages/edition-slices/src/slices/secondaryfour/index.js
packages/edition-slices/src/tiles/index.js
packages/edition-slices/src/tiles/shared/styles/index.js
packages/edition-slices/src/tiles/tile-ar/index.js
packages/edition-slices/src/tiles/tile-ar/styles/index.js
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/provider-queries/src/section-fragment.js
packages/slice-layout/__tests__/android/__snapshots__/sd4-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/sd4.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd4-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd4.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd4-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd4.web.test.js.snap
packages/slice-layout/src/templates/secondaryfour/index.js
packages/slice-layout/src/templates/secondaryfour/styles.js

Story: https://nidigitalsolutions.jira.com/browse/REPLAT-7059
Android:
iOS:

feat: (REPLAT-7059) Redesign secondary 4 slice for medium breakpoint

---

packages/provider-queries/src/section-fragment.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7170
Teaser800 and Summary800 added to the following slices:
LeadTwoNoPicAndTwo
SecondaryTwoNoPicAndTwoSlice
Secondary One Slice
LeadOneAndOne
ListTwoAndSixNoPicSlice
Secondary One and Columnist
Secondary Two and Two

feat: add teaser800 and summary800

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/slices/leadtwonopicandtwo/index.js
packages/edition-slices/src/tiles/tile-d/index.js
packages/edition-slices/src/tiles/tile-d/styles/index.js
packages/edition-slices/src/tiles/tile-e/index.js
packages/edition-slices/src/tiles/tile-e/styles/index.js
packages/edition-slices/src/tiles/tile-x/index.js
packages/edition-slices/src/tiles/tile-x/styles/index.js
packages/edition-slices/src/tiles/tile-y/index.js
packages/edition-slices/src/tiles/tile-y/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/l2np2-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/l2np2-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/l2np2-with-style.web.test.js.snap
packages/slice-layout/src/templates/leadtwonopicandtwo/index.js
packages/slice-layout/src/templates/leadtwonopicandtwo/styles.js

Story: https://nidigitalsolutions.jira.com/browse/REPLAT-7055

feat: (REPLAT-7055) Redesign lead 2no pic and 2 slice for medium breakpoint

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/slices/secondarytwonopicandtwo/index.js
packages/edition-slices/src/tiles/tile-ae/index.js
packages/edition-slices/src/tiles/tile-ae/styles/index.js
packages/edition-slices/src/tiles/tile-g/index.js
packages/edition-slices/src/tiles/tile-g/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/sd2np2-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/sd2np2.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd2np2-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd2np2.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd2np2-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd2np2.web.test.js.snap
packages/slice-layout/src/templates/secondarytwonopicandtwo/index.js
packages/slice-layout/src/templates/secondarytwonopicandtwo/styles.js

Story: https://nidigitalsolutions.jira.com/browse/REPLAT-7062
Screenshots:

feat: (REPLAT-7062) Redesign Secondary 2 no pic and 2 slice for medium breakpoint

---

lib/cli/edition-checker/src/api.test.js
packages/styleguide/__tests__/shared.js

Add test for theme-factory.js and increase the test coverage

fix: add tests for theme factory

---

package.json
yarn.lock

- the package is not used...
see https://www.npmjs.com/package/react-scripts

chore: remove react-script package

---

package.json
packages/webpack-configurator/__tests__/configurator.test.js
packages/webpack-configurator/src/configurator.js
yarn.lock

chore: remove proptypes

---

package.json
yarn.lock

This is reverting the commit that broke storybook static builds which power components.thetimes.co.uk

fix: fix storybook static builds

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/tiles/tile-x/index.js
packages/edition-slices/src/tiles/tile-x/styles/index.js
packages/edition-slices/src/tiles/tile-y/index.js
packages/edition-slices/src/tiles/tile-y/styles/index.js
packages/provider-queries/src/section-fragment.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7390

feat: update LeadTwoNoPicAndTwoSlice

---

packages/edition-slices/__tests__/android/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/src/slices/leaders/index.js
packages/edition-slices/src/slices/leaders/masthead.js
packages/edition-slices/src/slices/leaders/masthead.web.js
packages/edition-slices/src/slices/leaders/styles.js
packages/edition-slices/src/tiles/tile-m/index.js
packages/edition-slices/src/tiles/tile-m/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/leaders-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/leaders.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/leaders-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/leaders.ios.test.js.snap
packages/slice-layout/__tests__/leaders.base.js
packages/slice-layout/__tests__/web/__snapshots__/leaders-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/leaders.web.test.js.snap
packages/slice-layout/src/templates/leaders/index.js
packages/slice-layout/src/templates/leaders/proptypes.js
packages/slice-layout/src/templates/leaders/styles.js

[Jira story.](https://nidigitalsolutions.jira.com/browse/REPLAT-7068)
Before:
After:

feat: REPLAT-7068 Leaders slice redesigned for medium breakpoint

---

packages/edition-slices/__tests__/android/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/slices/secondaryoneandfour/index.js
packages/edition-slices/src/slices/secondaryoneandfour/styles.js
packages/edition-slices/src/tiles/tile-n/index.js
packages/edition-slices/src/tiles/tile-n/styles/index.js
packages/edition-slices/src/tiles/tile-o/styles/index.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7385

feat: update SecondaryOneAndFourSlice for 768px

---

README.md

Update README with more info on how to debug the tests.

docs: update readme (how to debug tests)

---

.storybook/preview-head.html
packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/__tests__/shared-with-style.web.js
packages/article-skeleton/__tests__/shared.base.js
packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-body/article-body-row.js
packages/article-skeleton/src/article-body/article-body.web.js
packages/article-skeleton/src/styles/article-body/responsive.web.js
packages/article-skeleton/src/styles/article-body/shared.js
packages/ssr/src/standalone-renderer/app.js

[JIRA](https://nidigitalsolutions.jira.com/browse/REPLAT-7225)
I believe the alignment issues on native are an issue with the interactive (as its inside a webview)

feat: full width interactives

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/src/keylines.js

768px width breakpoint:
Before:
After:

fix: keylines margin

---

packages/article-comments/__tests__/web/__snapshots__/tracking.web.test.js.snap
packages/article-comments/__tests__/web/tracking.web.test.js
packages/article-comments/package.json
packages/article-comments/src/comments.web.js
packages/article-comments/src/tracking/with-track-events.js
packages/article-skeleton/__tests__/web/__snapshots__/tracking.web.test.js.snap
packages/article-skeleton/__tests__/web/tracking.web.test.js
packages/article-skeleton/src/article-body/article-link-tracking-events.web.js

Added tracking for comment start and comment post events in article-comments.
Also added link text into tracking of article-link component.
JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-7189

Feat: add tracking to comments and article-link text to tracking REPLAT-7189

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/slices/secondaryoneandcolumnist/index.js
packages/edition-slices/src/slices/secondaryoneandfour/styles.js
packages/edition-slices/src/tiles/tile-ab/index.js
packages/edition-slices/src/tiles/tile-ab/styles/index.js
packages/edition-slices/src/tiles/tile-b/index.js
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/provider-queries/src/section-fragment.js
packages/slice-layout/__tests__/android/__snapshots__/s1andc-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/s1andc-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/s1andc-with-style.web.test.js.snap
packages/slice-layout/src/templates/secondaryoneandcolumnist/styles.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7518

feat: secondary1andColumnist for 1024px

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/src/slices/dailyregisterleadfour/index.js
packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
packages/edition-slices/src/tiles/tile-s/styles/index.js

https://nidigitalsolutions.jira.com/browse/REPLAT-7555

feat: (REPLAT-7555) redesign daily register slice for wide breakpoint

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles.test.js.snap
packages/edition-slices/src/slices/secondaryone/index.js
packages/edition-slices/src/tiles/tile-w/index.js
packages/edition-slices/src/tiles/tile-w/styles/index.js

https://nidigitalsolutions.jira.com/browse/REPLAT-7508

feat:  (REPLAT-7508) secondary 1 slice for wide breakpoint

---

ios-app/metro.config.js

[Related PR.](https://github.com/newsuk/times-components/pull/2194)
Fixing imports of graphql files for ios-app

fix: metro config updated for ios-app

---

packages/edition-slices/__tests__/android/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tiles-with-style.test.js.snap
packages/edition-slices/src/slices/listtwoandsixnopic/index.js
packages/edition-slices/src/tiles/tile-as/index.js
packages/edition-slices/src/tiles/tile-as/styles/index.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-7517)

feat: list2and6nopic for 1024px

---

packages/article-in-depth/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-in-depth/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-in-depth/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-in-depth/src/styles/index.js
packages/article-magazine-comment/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-comment/src/styles/native.js
packages/article-magazine-standard/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-magazine-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-standard/src/styles/native.js
packages/article-main-comment/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-main-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-main-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-comment/src/styles/index.android.js
packages/article-main-comment/src/styles/index.js
packages/article-main-standard/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-main-standard/src/styles/article-header/index.android.js
packages/article-main-standard/src/styles/article-header/index.js
packages/article-main-standard/src/styles/article-meta/index.android.js
packages/author-profile/__tests__/android/__snapshots__/author-profile-with-style.android.test.js.snap
packages/author-profile/__tests__/ios/__snapshots__/author-profile-with-style.ios.test.js.snap
packages/styleguide/src/line-heights/mapping.android.js
packages/styleguide/src/line-heights/mapping.js

https://nidigitalsolutions.jira.com/browse/REPLAT-7822

fix: REPLAT-7822 changes requested by editorial for native articles

---

packages/topic/__tests__/web/__snapshots__/topic-loading.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic.web.test.js.snap
packages/topic/src/head.web.js

Adding optimizely MVT script to topic head for POC.

feat/PPEC-23: Add optimizely script to topic head

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/s1andc-with-style.android.test.js.snap
packages/slice-layout/__tests__/android/__snapshots__/sd4-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/s1andc-with-style.ios.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/sd4-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/s1andc-with-style.web.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/sd4-with-style.web.test.js.snap
packages/slice-layout/src/templates/secondaryfour/styles.js
packages/slice-layout/src/templates/secondaryoneandcolumnist/styles.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8027)
Changes:
Secondary 4 - Tile B - 15 padding instead of 10
DailyRegisterLeadFour: 768 and 1024 font size

fix: style updates for slices-1024px

---

packages/slice-layout/src/templates/secondaryoneandfour/index.js

fix: lint in slice-layout

---

packages/section/__tests__/android/__snapshots__/section.test.js.snap
packages/section/__tests__/ios/__snapshots__/section.test.js.snap
packages/section/src/styles/index.js

**IOS:**
**===========================================================**
**Android:** 
**======================================================**

fix: cutting of the last slice on tablet

---

CODEOWNERS

- I'm getting told off for working on tnl...

chore: remove myself

---

packages/article-summary/__tests__/android/__snapshots__/article-summary-with-style.android.test.js.snap
packages/article-summary/__tests__/android/__snapshots__/article-summary.android.test.js.snap
packages/article-summary/__tests__/ios/__snapshots__/article-summary-with-style.ios.test.js.snap
packages/article-summary/__tests__/ios/__snapshots__/article-summary.ios.test.js.snap
packages/article-summary/__tests__/shared-with-style.base.js
packages/article-summary/__tests__/shared.base.js
packages/article-summary/__tests__/web/__snapshots__/article-summary-with-style.web.test.js.snap
packages/article-summary/__tests__/web/__snapshots__/article-summary.web.test.js.snap
packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap
packages/article-topics/__tests__/android/__snapshots__/article-topics.android.test.js.snap
packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap
packages/article-topics/__tests__/ios/__snapshots__/article-topics.ios.test.js.snap
packages/article-topics/__tests__/shared-with-style.base.js
packages/article-topics/__tests__/shared.base.js
packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
packages/article-topics/__tests__/web/__snapshots__/article-topics.web.test.js.snap

Improve test coverage in article-summary and article-topics to 100%

chore: improve test coverage in article-summary and article-topics

---

packages/provider-queries/src/author_articles_with_images.graphql
packages/provider-queries/src/topic_articles.graphql
packages/provider/__tests__/__snapshots__/author-articles-with-images.test.js.snap
packages/provider/__tests__/__snapshots__/topic-articles-provider.test.js.snap

Adding caption field to lead images query in topics and author profile pages.
JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-8247

feat: REPLAT-8247 add caption to lead images query

---

CODEOWNERS

chore: remove neha

---

packages/context/__tests__/android/__snapshots__/theme.test.js.snap
packages/context/__tests__/ios/__snapshots__/theme.test.js.snap
packages/context/__tests__/web/__snapshots__/theme.test.js.snap
packages/context/src/defaults/index.js
packages/ssr/src/component/article.js
packages/ssr/src/server/article.js

feat: ppdsc 180 init newskit feature flag

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/src/slices/secondaryfour/index.js
packages/edition-slices/src/slices/secondaryfour/styles.js
packages/edition-slices/src/tiles/tile-ar/index.js
packages/edition-slices/src/tiles/tile-ar/styles/index.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8557)
Font size changes for tiles: TileAR, TileB

feat: secondary4 for 1366px

---

packages/article-list/__tests__/shared-pagination.web.js
packages/article-list/src/article-list-prop-types.js
packages/article-list/src/article-list.web.js

Add a small flag for usages on web that don't involve autoscroll

feat: REPLAT-8755 add a switch to disable autoscroll on web articlelist

---

packages/edition-slices/__tests__/android/__snapshots__/tile-w.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-w.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-w.test.js.snap
packages/edition-slices/src/tiles/tile-w/styles/index.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8566)
[Design](https://app.zeplin.io/project/5d2849a2b4a4605645afb4be/screen/5d6e6996c07a876257e7b082)

feat: secondary1 for 1366px

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices.test.js.snap
packages/edition-slices/__tests__/shared-components.base.js
packages/edition-slices/__tests__/shared-tablet-slices.base.js
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices.test.js.snap

Mobile test coverage:
In order for the web to have 100% coverage, we will need to fix the `Dimension` mock first so we can set different breakpoints in the web tests

feat: increase test coverage for slices (Mobile only !) 

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-ab.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-b.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-ab.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-b.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-ab.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-b.test.js.snap
packages/edition-slices/src/tiles/tile-ab/index.js
packages/edition-slices/src/tiles/tile-ab/styles/index.js
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/slice-layout/__tests__/android/__snapshots__/s1andc-with-style.android.test.js.snap
packages/slice-layout/__tests__/ios/__snapshots__/s1andc-with-style.ios.test.js.snap
packages/slice-layout/__tests__/web/__snapshots__/s1andc-with-style.web.test.js.snap
packages/slice-layout/src/templates/secondaryoneandcolumnist/styles.js

[Ticket](https://nidigitalsolutions.jira.com/browse/REPLAT-8560)
Medium breakpoint
Wide breakpoint
Huge breakpoint

fix: (REPLAT-8560) secondary 1 and columnist rearrange

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-s.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-s.test.js.snap
packages/edition-slices/__tests__/tile-s/shared-tile-s.base.js
packages/edition-slices/__tests__/web/__snapshots__/slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-s.test.js.snap
packages/edition-slices/src/slices/dailyregisterleadfour/styles.js
packages/edition-slices/src/tiles/tile-s/index.js
packages/edition-slices/src/tiles/tile-s/styles/index.js

Updating styles for the headline icons that affect all breakpoints except small screens
**Medium**
**Wide**
**Huge**

feat: daily register for 1366px

---

packages/ssr/src/client/article.js

feat: newskit client side feature flag

---

packages/edition-slices/__tests__/android/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-ak.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tablet-slices-with-style.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-ak.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-ak.test.js.snap
packages/edition-slices/src/slices/puzzle/styles.js
packages/edition-slices/src/tiles/tile-ak/styles/index.js
packages/section/src/section.js
packages/section/src/styles/index.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-8563)
Font size change and fix for the whitespace that was cut at the bottom of the section.

feat: puzzles for 1366px

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/src/head.web.js

Adding time to datePublished metadata as requested in JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-8272

feat: add time to date published metadata REPLAT-8272

---

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/src/article-skeleton.js
packages/text-flow/lib/convert-font.js

We were losing some text due to a weird issue with nested Text views, an easy fix is to just set the height from our own layout stuff.
**BEFORE**
**AFTER**

fix: (REPLAT-9274) fix missing text

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/src/head.web.js
packages/provider-queries/src/article_web.graphql

This PR is to add dateModified to jsonLD schema in the head of react article pages in order to improve SEO.
JIRA:
https://nidigitalsolutions.jira.com/browse/REPLAT-7845

feat: add dateModified to schema REPLAT-7845

---

packages/edition-slices/package.json
packages/edition-slices/src/edition-slices.js
packages/fixture-generator/src/mock-edition.ts
packages/fixture-generator/src/mock-section.ts
packages/section/__tests__/android/__snapshots__/section-tracking.test.js.snap
packages/section/__tests__/android/__snapshots__/section.test.js.snap
packages/section/__tests__/ios/__snapshots__/section-tracking.test.js.snap
packages/section/__tests__/ios/__snapshots__/section.test.js.snap
packages/section/__tests__/shared.js

[Story.
](https://nidigitalsolutions.jira.com/browse/REPLAT-7556)
Expected result on tablet:
Before:
After:

feat: REPLAT-7556 tablet slices mapping modified

---

packages/topic/__tests__/web/__snapshots__/topic-loading.web.test.js.snap
packages/topic/__tests__/web/__snapshots__/topic.web.test.js.snap
packages/topic/src/head.web.js

Remove Optimizely script from the topic head
[PPEC-55](https://nidigitalsolutions.jira.com/browse/PPEC-55)

chore (PPEC-55): Remove Optimizely from topic head

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/src/head.web.js

Jira: https://nidigitalsolutions.jira.com/browse/REPLAT-7841

feat: author name in schema

---

ios-app/package.json

These dependencies were missing

fix: ios: add missing dependency

---

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-scaling.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/src/article-body/article-body-row.js

Need to pass in the OS font setting when rendering articles.

fix: OS font scaling

---

packages/provider-queries/src/section_fragment.graphql

Problem: edition query is huge and has a lot of repeating parts
Solution: extract same queries in fragments

fix[PPDSC-535]: Simplify query

---

packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-skeleton.web.js

- Add the article id in an attribute ~`article-id`~ `data-article-identifier` to aid testing, debugging and INCA.

feat: add article id to aid debugging and testing

---

packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/__tests__/shared.native.js
packages/article-skeleton/fixtures/full-article.js
packages/article-skeleton/src/article-body/article-body-row.js

fix: article link should scale with os font size

---

packages/ssr/src/component/article.js

[Story](https://nidigitalsolutions.jira.com/browse/REPLAT-7461)
For more information you can check the related [Spike](https://nidigitalsolutions.jira.com/browse/REPLAT-9647) comments section.
Before: 
After:

feat: section colouring of components from tiles

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/src/head.web.js

- according to https://developers.google.com/search/docs/data-types/article Publisher logo url needs to updated to correct format.

fix: amend format of structured data

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/src/head.web.js

- change `author` to be an object of type `Person`
- https://developers.google.com/search/docs/data-types/article

fix: update author structured data

---

packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap

Fix broken snapshot from previous PR

fix: snapshots

---

packages/ssr/src/component/article.js
packages/ssr/src/lib/section-from-tiles.js

- We needed to add additional checks for getting section name from tiles arrays

fix: tighten up section name from tiles validation

---

packages/related-articles/__tests__/shared-util.web.js
packages/related-articles/__tests__/web/__snapshots__/la2-1article.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-1article.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-1article.web.test.js.snap
packages/related-articles/src/related-article-item.web.js

Related articles on click event. Tests are added
Tested locally

fix: related articles on click analytics

---

packages/edition-slices/__tests__/android/__snapshots__/tile-s.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-s.test.js.snap
packages/edition-slices/src/tiles/tile-s/markup.js

fix: REPLAT-10301 fix bold in daily universal register

---

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/typeset/src/LayoutManager.ts

Looking at the code from the performance work I found a bug in the new loop that can cause it to break when there is still some work left. Small fix.

fix: loop condition error in refactor from REPLAT-10300

---

packages/responsive-image/package.json

fix: the watch command

---

packages/provider-queries/src/draft-article.js
packages/provider-queries/src/draft_article.graphql
packages/provider-queries/src/provider-queries.js
packages/provider/src/draft-article.js
packages/provider/src/provider.js
packages/ssr/src/client/article.js
packages/ssr/src/component/article.js
packages/ssr/src/server/article.js

[Story.](https://nidigitalsolutions.jira.com/browse/REPLAT-10475)
Draft article query created.
Draft article provider created.
isPreview boolean consumed in ssr.

feat: REPLAT-10475 draft article query and provider created

---

packages/save-and-share-bar/package.json
packages/save-and-share-bar/save-and-share-bar.showcase.web.js

chore: knobs added to save and share bar

---

packages/related-articles/__tests__/shared-no-style.web.js
packages/related-articles/__tests__/web/__snapshots__/la2-1article.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/la2-2articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/la2-3articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/la2-no-short-headline.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/la2-with-style.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-1article.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-2articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-3articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-no-short-headline.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/oa2-with-style.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-1article.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-2articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-3articles.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-has-video.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-no-short-headline.web.test.js.snap
packages/related-articles/__tests__/web/__snapshots__/std-with-style.web.test.js.snap
packages/related-articles/src/related-article-item.web.js

- Need more ui hooks in order to do Cypress e2e tests in render.

chore: add test ids to related articles

---

packages/article-skeleton/src/article-body/article-body-row.js
packages/responsive-image/package.json
packages/typeset/package.json

There were some missing nodes on the article body row object.

fix: (REPAT-11005) crashing article

---

package.json
packages/context/package.json
packages/mocks/package.json
packages/responsive-image/__tests__/__snapshots__/image.test.tsx.snap
packages/responsive-image/package.json
packages/responsive-image/src/index.tsx
packages/watermark/package.json

Fixes an article crash and an issue with offline mode

fix: (REPLAT-10970) minor fixes for a crash and offline images

---

packages/context/package.json
packages/mocks/package.json
packages/responsive-image/package.json
packages/watermark/package.json

- something not right.
- having to fix deps again.

fix: deps again

---

packages/utils/package.json

syncing version of dependencies.

chore: deps fixed

---

packages/context/package.json
packages/mocks/package.json
packages/responsive-image/package.json
packages/watermark/package.json

chore: fix dep versions

---

packages/utils/package.json

chore: dependencies sync

---

packages/context/package.json
packages/mocks/package.json
packages/responsive-image/package.json
packages/watermark/package.json

Sync dependencies with deps:fix.
If a package is out of sync again after this try, I'll do manual bump.

chore: deps fix again

---

packages/ad/package.json
packages/article-flag/package.json
packages/article-in-depth/package.json
packages/article-label/package.json
packages/article-lead-asset/package.json
packages/article-list/package.json
packages/article-magazine-comment/package.json
packages/article-magazine-standard/package.json
packages/article-main-comment/package.json
packages/article-main-standard/package.json
packages/article-skeleton/package.json
packages/author-profile/package.json
packages/brightcove-video/package.json
packages/button/package.json
packages/edition-slices/package.json
packages/icons/package.json
packages/image/package.json
packages/responsive/package.json
packages/save-and-share-bar/package.json
packages/save-star-web/package.json
packages/topic/package.json
packages/user-state/package.json
packages/utils/package.json

Manual bump of utils package.
Hopefully this will end the cycle of deps fixes.

chore: increment utils version

---

packages/article-extras/__tests__/web/__snapshots__/article-extras.web.test.js.snap
packages/article-extras/src/article-extras.web.js

- Wrap sponsored article div to fix issue with commenting

fix(REPLAT-11036): Wrap sponsored article div to fix issue with commenting

---

packages/edition-slices/__tests__/android/__snapshots__/tile-b.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-d.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-e.test.js.snap
packages/edition-slices/__tests__/android/__snapshots__/tile-g.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-b.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-d.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-e.test.js.snap
packages/edition-slices/__tests__/ios/__snapshots__/tile-g.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-b.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-d.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-e.test.js.snap
packages/edition-slices/__tests__/web/__snapshots__/tile-g.test.js.snap
packages/edition-slices/src/tiles/tile-b/styles/index.js
packages/edition-slices/src/tiles/tile-d/styles/index.js
packages/edition-slices/src/tiles/tile-e/styles/index.js
packages/edition-slices/src/tiles/tile-g/styles/index.js

Some tiles had wrong tile label spacing.

fix: label-spacing

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/email-share.js
packages/save-and-share-bar/src/save-and-share-bar.js
packages/save-star-web/__tests__/web/__snapshots__/save-star-web.test.js.snap
packages/save-star-web/src/save-star-with-tracking.js

- Email share, copy to clipboard and save button were not focusable

fix(REPLAT-10511): tabbing issue in share and save bar

---

packages/article-extras/__tests__/web/__snapshots__/article-extras.web.test.js.snap
packages/article-extras/src/article-extras.web.js

- Fix layout issue with inline image and the content in `article-extra`.
- https://nidigitalsolutions.jira.com/browse/REPLAT-11035
- If anyone has a "nicer" solution please shout!

fix(REPLAT-11035): fix layout issue with inline image and article-extra

---

.circleci/config.yml
lib/publish.sh
lib/publish_storybook.sh
package.json

Migrate master pipeline to circle ci
This will improve publishing from 60mins to 12mins 
TODO:
~~add artifactory api key in circle ci environment variables~~
added 
What is tested:

feat: migrate master pipeline to circleci

---

.circleci/config.yml

Fix android SDK issue with circle ci

fix: android sdk issue

---

packages/article-skeleton/__tests__/web/dropcap-util.test.js
packages/article-skeleton/src/dropcap-util-common.js

Capitalising the first two characters if the first one is:
Before:
After:

feat: REPLAT-11397 drop cap starting with quote for web

---

android-app/package.json
ios-app/package.json

Bump apps packages to fix CI issue

fix: bump apps packages

---

android-app/package.json
ios-app/package.json
packages/pages/package.json

fix: pages package version

---

lib/publish-ios-assets.sh

fix: ios publish of artifactories

---

.circleci/config.yml
lib/publish-ios-assets.sh

fix: ios git user

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/styles/responsive.web.js
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/src/styles/responsive.web.js
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/src/styles/responsive.web.js
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/src/styles/responsive.web.js

Reverts newsuk/times-components#2449

chore: Revert "fix(REPLAT-11399): fix bylines that were breaking out of container"

---

packages/image/package.json
packages/responsive-image/package.json

There is an issue with responsive-image package, this should fix it

fix: responsive image

---

packages/image/package.json
packages/responsive-image/src/index.tsx

Fix responsive image package version with a dummy change

fix: responsive image package version

---

packages/responsive-image/package.json
packages/typeset/package.json
yarn.lock

Remove unnecessary version scripts from typeset and responsive-image

fix: remove unnecessary version scripts

---

lib/publish-ios-assets.sh

We should copy the package json across so that the IOS app can display the version of times-components.

feat: copy package.json to ios pod

---

packages/interactive-wrapper/src/interactive-wrapper.js

Some interactive are failing to load intermittently, the interactive component did not have any error handling so this adds some and attempts reload a limited amount of times.

fix: REPLAT-11684 handle bad messages and attempt reload on interactives

---

packages/ad/src/utils/sizes.js

Second MPU size added to slot size matrix

feat: super-mpu ad size added to custom slot

---

packages/message-bar/__tests__/android/__snapshots__/message-bar.test.js.snap
packages/message-bar/__tests__/ios/__snapshots__/message-bar.test.js.snap
packages/message-bar/src/message-bar.js

Add data-testid to message bar

chore: add data-testid to message bar

---

packages/interactive-wrapper/src/interactive-wrapper.js

fix: REPLAT-11942 fix missing prop crash

---

packages/context/package.json
packages/interactive-wrapper/src/interactive-wrapper.js
packages/mocks/package.json
packages/responsive-image/package.json
packages/watermark/package.json

fix: (REPLAT-12060) handle interactives sending wrong height values

---

packages/context/package.json
packages/mocks/package.json
packages/responsive-image/package.json

- dep versions have gone out again.

chore: bump deps

---

packages/image/__tests__/android/__snapshots__/modal-image.android.test.js.snap
packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
packages/image/src/modal-image/modal-image.js
yarn.lock

fix: (REPLAT-12076) modal lead asset images blocking on network

---

android-app/build.gradle
android-app/package.json
android-app/settings.gradle
android-app/xnative/build.gradle
android-app/xnative/src/main/java/uk/co/thetimes/xnative/XNative.java
ios-app/package.json
package.json
packages/ad/package.json
packages/ad/src/ad.web.js
packages/jest-configurator/setup-jest.js
yarn.lock

https://nidigitalsolutions.jira.com/browse/REPLAT-11368
We should not load ads if the user is offline.
Desired behaviour:
* If the user is offline, don't load ads
* If the user becomes online, load ads in the current article and others
* If a user is swiping online, show ads
* If the user is online and goes offline, don't hide ads already loaded

fix: (REPLAT-11368) make ads network-aware

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-isPreview.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/video/__tests__/web/__snapshots__/video-with-provider.web.test.js.snap
packages/video/__tests__/web/__snapshots__/video.web.test.js.snap
packages/video/package.json
packages/video/src/inline-video-player.web.js
yarn.lock

[Jira](https://nidigitalsolutions.jira.com/browse/TNLT-26)
Before:
After:

feat: add resize param poster video image

---

packages/article-magazine-comment/__tests__/android/__snapshots__/article-tablet.android.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-magazine-comment/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-tablet.ios.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-magazine-comment/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-magazine-comment/src/article-header/article-header.js
packages/article-magazine-comment/src/styles/native.js
packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/src/article-body/drop-cap.js

fix: article-magazine-comment was messed up

---

packages/edition-slices/src/edition-slices.js
packages/responsive/src/responsive.js

This value may be undefined, so just checking if it is not the string small is not correct :|

fix: bad conditional for breakpoint check

---

packages/article-skeleton/src/article-body/article-body.web.js
packages/article-skeleton/src/article-skeleton.web.js

In this PR we are improving the quality of the inline images on retina screens, indepth article template. 
**Before:** 
**After:**

feat: improve inline images retina indepth article

---

packages/topic/src/topic-head.web.js

fix: (TNLT-617) topics crash

---

packages/typeset/__tests__/AttributedString.test.ts
packages/typeset/src/AttributedString.ts

Fixes a crash on empty paragraphs.

fix: (TNLT-634) fix handling of empty paragraphs

---

packages/image/__tests__/ios/__snapshots__/modal-image-with-style.ios.test.js.snap
packages/image/__tests__/ios/__snapshots__/modal-image.ios.test.js.snap
packages/image/src/modal-image/modal-image.js
packages/image/src/styles/index.ios.js

fix: (TNLT-652) use safe area view for modals

---

doc/running-ios-dev.md

feat: add guide to running ios app for development

---

packages/ssr/src/standalone-renderer/app.js
packages/ssr/webpack.config.js

Reverts newsuk/times-components#2563

Revert "feat: (TNLT-697) vendors.js bundle extracted from common.js"

---

packages/pages/src/section/section.js
packages/section/__tests__/android/__snapshots__/section-tracking.test.js.snap
packages/section/__tests__/ios/__snapshots__/section-tracking.test.js.snap
packages/section/src/section-tracking-context.js

Fix publication name in analytics for section pages (apps)

fix: publication name in section pages

---

packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/__tests__/shared.native.js
packages/article-skeleton/fixtures/full-article.js
packages/typeset/src/AttributedString.ts

[TNLT-869](https://nidigitalsolutions.jira.com/browse/TNLT-869)
[TNLT-678](https://nidigitalsolutions.jira.com/browse/TNLT-678)
Before:
After:

fix: (TNLT-869, TNLT-678) last italic word and links wrapping in first paragraph with dropcap

---

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/__tests__/shared.base.js
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/fixtures/headings-article-content.js
packages/article-skeleton/src/article-body/article-body-row.js
packages/article-skeleton/src/styles/article-body/shared.js
packages/styleguide/src/fonts/font-sizes-base.js
packages/styleguide/src/fonts/font-sizes.web.js
packages/styleguide/src/line-heights/mapping-base.js

[TNLT-1156](https://nidigitalsolutions.jira.com/browse/TNLT-1156)
Before:
After:

fix: (TNLT-1156) native heading tags styling

---

packages/lazy-load/package.json
packages/provider/package.json
packages/tracking/package.json
storybook-native/package.json

Times components deps are out of sync

fix: deps fix

---

packages/interactive-wrapper/src/interactive-wrapper.js

[Jira](https://nidigitalsolutions.jira.com/browse/TNLT-1654)

feat: fix deck quizzes not displaying

---

ios-app/package.json

chore: bump of ios-app to fix failed publish

---

packages/article-skeleton/__tests__/android/__snapshots__/article-with-style.android.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/article.android.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article-with-style.ios.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/article.ios.test.js.snap
packages/article-skeleton/__tests__/shared.base.js
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-body/article-body-row.js
packages/interactive-wrapper/src/interactive-wrapper.js
yarn.lock

Reverts newsuk/times-components#2615

Revert "fix: error boundaries interactives error"

---

packages/interactive-wrapper/src/interactive-wrapper.js

https://github.com/newsuk/times-components/pull/2615

feat: handle async code error boundary

---

packages/ssr/src/client/article.js
packages/ssr/src/client/topic.js
packages/ssr/src/server/topic.js

https://nidigitalsolutions.jira.com/browse/TNLT-193
Need to provide TM2 in Times Components header for render.

feat(TNLT-193): add tm2 headers

---

packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-button.test.js.snap
packages/article-skeleton/__tests__/android/__snapshots__/newsletter-puff-link.test.js.snap
packages/article-skeleton/__tests__/inline-newsletter-puff.base.js
packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-button.test.js.snap
packages/article-skeleton/__tests__/ios/__snapshots__/newsletter-puff-link.test.js.snap
packages/article-skeleton/__tests__/newsletter-puff-button.base.js
packages/article-skeleton/__tests__/newsletter-puff-link.base.js
packages/article-skeleton/__tests__/web/__snapshots__/newsletter-puff-button.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/newsletter-puff-link.test.js.snap
packages/article-skeleton/src/article-body/inline-newsletter-puff.js
packages/article-skeleton/src/article-body/newsletter-puff-button.js
packages/article-skeleton/src/article-body/newsletter-puff-link.js
packages/provider-queries/src/get_newsletter.graphql

In this PR we update the tracking for NewsletterPuff. You can find the specs [here](https://docs.google.com/spreadsheets/d/1NVWE4VxOB0hUkUBgmOmOoC_G0qoAQr0T/edit#gid=152412066) in the columns BO12, BP12 and BQ12
[TNLT-4872](https://nidigitalsolutions.jira.com/browse/TNLT-4872)
PR [#155](https://github.com/newsuk/times-components-native/pull/155) in `times-components-native`

fix(TNLT-4872): Update NewsletterPuff tracking

---

packages/article-topics/__tests__/android/__snapshots__/article-topics-with-style.android.test.js.snap
packages/article-topics/__tests__/ios/__snapshots__/article-topics-with-style.ios.test.js.snap
packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
packages/article-topics/src/styles/shared.js

added a width to the topic tags to spot text overflowing from them
https://nidigitalsolutions.jira.com/browse/TNLT-5628

feat(TNLT-5628): added a width to avoid string coming out of the topic button

---

packages/article-comments/__tests__/web/__snapshots__/tracking.web.test.js.snap
packages/article-comments/src/comments.web.js
packages/article-comments/src/tracking/with-track-events.js

Added a new solution to get share and filter comment tracking events to work
[JIRA-Link-6001](https://nidigitalsolutions.jira.com/browse/TNLT-6001)

feat(TNLT-6001): new solution to dynamically fire comment tracking

---

packages/article-skeleton/src/article-skeleton.web.js

This Pr removes the function that adds the Native ad to the article body

fix(TNLT-000): remove native ad placement

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/__tests__/web/native-ad.web.test.js
packages/article-skeleton/fixtures/native-ad.js
packages/article-skeleton/src/native-ad.web.js

Add native ads 2nd paragraph for unsubscribed users

fix(SCB-667):  add native ads for unsubscribed users after 2nd para

---

packages/article-extras/__tests__/shared.web.js
packages/article-extras/src/article-extras.web.js
packages/user-state/src/matchers.js
packages/user-state/src/user-state.js

Reverts newsuk/times-components#2662

fix(TNLT-2359): revert "fix: add new user state check for comments readOnly state"

---

packages/article-in-depth/src/article-in-depth.web.js
packages/article-magazine-comment/src/article-magazine-comment.web.js
packages/article-magazine-standard/src/article-magazine-standard.web.js
packages/article-main-comment/src/article-main-comment.web.js
packages/article-main-standard/src/article-main-standard.web.js
packages/article-skeleton/__tests__/web/__snapshots__/auto-place-newsletter-puff.web.test.js.snap
packages/article-skeleton/__tests__/web/auto-place-newsletter-puff.web.test.js
packages/article-skeleton/fixtures/newsletter.js
packages/article-skeleton/src/article-body/article-body.web.js
packages/article-skeleton/src/article-skeleton.web.js
packages/article-skeleton/src/newsletter-puff.web.js
packages/ssr/src/client/article.js
packages/ssr/src/component/article.js
packages/ssr/src/server/article.js

Automatically insert `NewsletterPuff` in article pages. [TNLT-6841](https://nidigitalsolutions.jira.com/browse/TNLT-6841?atlOrigin=eyJpIjoiMWIzMDllNDY3YjhmNGVhMWE2NjFlZWJkNDQ5YjlmNjIiLCJwIjoiaiJ9)
Pass `newsletterPuffFlag` prop to conditionally render `NewsletterPuff` from Render

feat(TNLT-6841): insert newsletter in article pages

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
packages/article-list/src/article-list.web.js
packages/article-list/src/styles/index.web.js
packages/article-list/src/styles/responsive.web.js
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-body/article-body.web.js
packages/article-skeleton/src/styles/article-body/responsive.web.js
packages/article-skeleton/src/styles/responsive.web.js

This PR adds set height to the article, topic and profile adverts.

fix(TNLT-6962): Add set heights to ads times components

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-images-with-style.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-skeleton/src/styles/responsive.web.js

This pr adds the correct alignment to the ad header

fix(tnlt-000): slight tweaks to ad styles

---

packages/article-comments/__tests__/android/__snapshots__/shared-with-style.android.test.js.snap
packages/article-comments/__tests__/android/__snapshots__/shared.android.test.js.snap
packages/article-comments/__tests__/ios/__snapshots__/shared-with-style.ios.test.js.snap
packages/article-comments/__tests__/ios/__snapshots__/shared.ios.test.js.snap
packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/article-comments.js
packages/article-comments/src/comments.js
packages/article-comments/src/comments.web.js

Removing community guidelines because this will be controlled via the new open web upgrade

feat (TNLT-7317): remove community guidelines

---

packages/article-skeleton/src/article-body/view-count-wrapper.js
yarn.lock

Simplified the content cookie check as well as adding a guard to check that window exists for ssr.

feat(TE-35): add auto newsletter puff - fixed cookie check for ssr

---

packages/ssr/README.md

feat: update readme

---

packages/article-skeleton/__tests__/web/view-count-wrapper.test.js
packages/article-skeleton/src/article-body/auto-newsletter-puff.js
packages/article-skeleton/src/article-body/auto-newsletter-puff.showcase.js
packages/article-skeleton/src/article-body/view-count-wrapper.js
packages/ssr/README.md

TE-35: Update the auto newsletter puff to fix session storage for ssr

fix(TNLT-000): session storage window issue

---

packages/article-skeleton/__tests__/web/__snapshots__/auto-place-newsletter-puff.web.test.js.snap
packages/article-skeleton/src/article-body/auto-newsletter-puff.js

hide auto newsletter puff by default

feat: hide auto newsletter puff by default

---

packages/article-skeleton/__tests__/web/auto-place-newsletter-puff.web.test.js
packages/article-skeleton/src/article-skeleton.web.js

This PR disables the auto-NewsletterPuff (comment out placement and tests).

fix: disable auto-NewsletterPuff

---

CODEOWNERS
packages/context/package.json
packages/mocks/package.json
packages/styleguide/CHANGELOG.md
yarn.lock

- Remove Chris, Aron and Adam
- Add Vin and Bibi

chore: Update codeowners

---

packages/ad/src/ad-container.web.js

This adds an ID to the ad container.

feat(TD-35): add-id-to-ad-container

---

packages/ts-components/src/components/opta/utils/config.ts

fix: OPTA football widgets loading insecure css

---

packages/article-skeleton/src/article-body/article-body.web.js

Remove football components that should not be used.

fix: OPTA football widgets

---

packages/article-skeleton/src/article-body/article-body.web.js
packages/ts-components/src/components/opta/football/fixtures/OptaFootballFixtures.stories.tsx
packages/ts-components/src/components/opta/football/fixtures/styles.ts
packages/ts-components/src/components/opta/football/match-stats/OptaFootballMatchStats.stories.tsx
packages/ts-components/src/components/opta/football/match-stats/OptaFootballMatchStats.tsx
packages/ts-components/src/components/opta/football/match-stats/styles.ts
packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.stories.tsx
packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.tsx
packages/ts-components/src/components/opta/football/standings/styles.ts
packages/ts-components/src/index.ts

* Add MatchStats component
* Allow single table component
* Tweak styles

feat: OPTA Football - Match Stats

---

packages/ts-components/src/components/carousel/Card.tsx
packages/ts-components/src/components/carousel/GalleryCarousel.stories.tsx
packages/ts-components/src/components/carousel/GalleryCarousel.tsx
packages/ts-components/src/components/carousel/__tests__/GalleryCarousel.test.tsx
packages/ts-components/src/components/carousel/__tests__/__snapshots__/GalleryCarousel.test.tsx.snap
packages/ts-components/src/components/carousel/styles.ts
packages/ts-components/src/components/in-article-puff/__tests__/__snapshots__/InArticlePuff.test.tsx.snap

https://nidigitalsolutions.jira.com/browse/TE-54

Feat:(TE-54) in article galleries analytics

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/ts-components/src/components/related-article-slice/RelatedArticleSlice.tsx
packages/ts-components/src/components/related-article-slice/__tests__/RelatedArticleSlice.test.tsx
packages/ts-components/src/components/related-article-slice/__tests__/__snapshots__/RelatedArticleSlice.test.tsx.snap

Needed to add a null check which caused exception in `render`

feat(TE-120): Null checks on related article slice

---

packages/ts-components/package.json
packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.stories.tsx
packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx

feat:Olympics Medal Table

---

packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.stories.tsx
packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx

feat:Olympics Medal Table - changing to allow for staging endpoint

---

packages/depend/package.json
packages/ts-components/jest.config.js
packages/ts-components/package.json
packages/ts-components/src/components/olympics/__tests__/OlympicsMedalTable.test.tsx
packages/ts-components/src/components/olympics/__tests__/OlympicsSchedule.test.tsx
packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsMedalTable.test.tsx.snap
packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsSchedule.test.tsx.snap
packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx
packages/ts-components/src/components/olympics/medal-table/styles.ts
packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.stories.tsx
packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.tsx
packages/ts-components/src/components/olympics/schedule/styles.ts
packages/ts-components/src/components/olympics/types.ts
packages/ts-components/src/index.ts
packages/ts-components/src/types/externs.d.ts

feat:Olympics - added tests and further styling

---

.storybook/public/static/schedule.js
packages/ts-components/src/components/olympics/__tests__/OlympicsMedalTable.test.tsx
packages/ts-components/src/components/olympics/__tests__/OlympicsSchedule.test.tsx
packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsMedalTable.test.tsx.snap
packages/ts-components/src/components/olympics/__tests__/__snapshots__/OlympicsSchedule.test.tsx.snap
packages/ts-components/src/components/olympics/medal-table/OlympicsMedalTable.tsx
packages/ts-components/src/components/olympics/schedule/OlympicsSchedule.tsx

feat:Olympics - added ability to add helmet provider for channel pages

---

packages/ts-components/jest.config.js
packages/ts-components/package.json
packages/ts-components/src/components/in-article-info-card/InfoCard.tsx
packages/ts-components/src/components/in-article-puff/InArticlePuff.tsx
packages/ts-components/src/helpers/fetch/FetchProvider.tsx
packages/ts-components/src/helpers/fetch/__tests__/FetchProvider.test.tsx
packages/ts-components/src/helpers/fetch/__tests__/__snapshots__/FetchProvider.test.tsx.snap
packages/ts-components/src/helpers/fetch/types.ts
yarn.lock

chore: Update fetch to use generics and unit tests

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/head.web.test.js.snap
packages/article-skeleton/__tests__/web/head.web.test.js
packages/article-skeleton/src/head.web.js

When there isn't an author name present, using the organization name as an author.

fix(TSEO-26):added default author

---

packages/ts-components/package.json
packages/ts-components/src/helpers/text-formatting/SanitiseCopy.ts
packages/ts-components/src/helpers/text-formatting/__tests__/SanitiseCopy.test.tsx
yarn.lock

revert the previous commit and add tests

revert: remove sanitize html

---

packages/ts-components/src/components/in-article-big-numbers/BigNumbers.stories.tsx
packages/ts-components/src/components/in-article-big-numbers/BigNumbers.tsx
packages/ts-components/src/components/in-article-big-numbers/__tests__/BigNumbers.test.tsx
packages/ts-components/src/components/in-article-big-numbers/__tests__/__snapshots__/BigNumbers.test.tsx.snap

Please review and suggest if we need to do any changes. Thank you.

Feat/TDP-121 Inarticle Bignumbers Analytics

---

packages/article-comments/src/comments.js

feat: commenting update

---

packages/ts-components/src/components/article-flag/__tests__/__snapshots__/LiveArticleFlag.test.tsx.snap
packages/ts-components/src/components/article-flag/styles.ts
packages/ts-components/src/helpers/fetch/__tests__/__snapshots__/FetchProvider.test.tsx.snap

This PR centres the bullet in the LIVE article flag.

feat(TDP-478): Centre bullet in LIVE article flag

---

lib/publish_storybook.sh

chore - disables the storybook branch from CI

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/comments.js

TDP-1024 - reverted changes as bug resolved by openweb.

---

packages/article-list/__tests__/web/__snapshots__/article-list-error-with-styles.web.test.js.snap
packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-render-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-reverse-style.test.js.snap
packages/image/__tests__/web/__snapshots__/image-with-style.web.test.js.snap
packages/image/src/image.js
packages/image/src/styles/index.js
packages/ts-components/src/components/latest-from-section/__tests__/__snapshots__/LatestFromSection.test.tsx.snap
packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/InlineNewsletterPuff.test.tsx.snap
packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/PreviewNewsletterPuff.test.tsx.snap

TDP-1109 - Big space between images and captions on article pages

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/__tests__/web/shared.web.test.js
packages/article-comments/article-comments.showcase.js
packages/article-comments/src/article-comments.js
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article/showcase-helper.js
packages/ts-components/src/components/inline-message/__tests__/__snapshots__/InlineMessage.test.tsx.snap
packages/ts-components/src/components/inline-message/styles.ts

TDP-803 - Real name commenting banner

---

packages/article-skeleton/src/contentModifiers/inline-related-article.js

Add check for empty `relatedArticleSlice` object and `relatedArticleSlice.items` array

fix(TDP-000): InlineRelatedArticles

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/article-comments.js

TDP-803 - Added hiddendiv to the comment banner

---

packages/key-facts/src/styles.js
packages/lazy-load/package.json
packages/tracking/package.json
yarn.lock

- Design wanted to add a hover colour state to the links in the key moments component

chore(TDP-759): Add hover and active state to links in key moments component

---

packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/src/styles/responsive.js

Bug fix for article key lines at 1024px
[JIRA-1351](https://nidigitalsolutions.jira.com/jira/software/c/projects/TDP/boards/1491?modal=detail&selectedIssue=TDP-1351)

feat(TDP-1351): fix article keylines responsive bug

---

packages/key-facts/__tests__/web/key-facts.web.test.js
packages/key-facts/showcase-helper.js
packages/key-facts/src/key-facts-text.js
packages/key-facts/src/key-facts.js

Tracking not making it to tealium layer: https://github.com/newsuk/times-components/pull/2862

feat(TDP-1139): key moments analytics fix

---

packages/article-skeleton/src/article-body/article-body.js
packages/article-skeleton/src/article-skeleton.js
packages/key-facts/__tests__/web/key-facts.web.test.js
packages/key-facts/src/key-facts-text-prop-types.js
packages/key-facts/src/key-facts-text.js
packages/key-facts/src/key-facts.js

update key moment analytics

---

packages/key-facts/__tests__/web/key-facts.web.test.js
packages/key-facts/fixtures/key-facts-test.json
packages/key-facts/src/key-facts-text.js

feat(TDP-1139): fixing article name value

---

packages/ts-components/src/components/article-flag/__tests__/__snapshots__/LiveArticleFlag.test.tsx.snap
packages/ts-components/src/components/article-flag/styles.ts
packages/ts-components/src/components/article-header/__tests__/__snapshots__/ArticleHeader.test.tsx.snap

Flashing animation for bulletin

feat(TDP-756): live flag animation

---

packages/key-facts/__tests__/web/key-facts.web.test.js
packages/key-facts/src/key-facts-text.js
packages/key-facts/src/key-facts.js

Request to swap around key names

feat(TDP-1139):key moments analytics amendment

---

packages/article-skeleton/src/article-body/article-body.js
packages/ts-components/src/index.ts

feat(TDP-000) Sport widget update

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-paragraph/__tests__/web/__snapshots__/article-paragraph-with-style.web.test.js.snap
packages/article-paragraph/__tests__/web/__snapshots__/themes-with-style.web.test.js.snap
packages/article-paragraph/src/styles/responsive.js
packages/article-skeleton/__tests__/web/__snapshots__/article-with-style.web.test.js.snap

This PR removes redundant code that was merged into master from the anchor link feature branch.
[TDP-1577](https://nidigitalsolutions.jira.com/browse/TDP-1577)

feat(TDP-000): Anchor link update

---

packages/key-facts/src/key-facts-text.js

fix(TDP-1577): key facts anchor links

---

packages/key-facts/src/key-facts-text.js

feat(TDP-1577): key moments anchor points

---

packages/article-image/__tests__/shared-with-style.js
packages/article-image/__tests__/shared.js
packages/article-image/__tests__/web/__snapshots__/article-image-with-style.web.test.js.snap
packages/article-image/__tests__/web/__snapshots__/article-image.web.test.js.snap
packages/article-image/package.json
packages/article-image/src/article-image.base.js
packages/article-image/src/styles/index.js
packages/article-image/src/styles/responsive.js
packages/context/package.json

Removed react native code from article-image [TDP-1689](https://nidigitalsolutions.jira.com/browse/TDP-1689)

feat(TDP-1689): removed react-native

---

packages/context/package.json

test(TDP-000): Circle pipeline

---

packages/article-list/__tests__/shared-error-with-styles.js
packages/article-list/__tests__/shared-states.js
packages/article-list/__tests__/shared-with-styles.js
packages/article-list/__tests__/web/__snapshots__/article-list-error-with-styles.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list-error.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list-states.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list.web.test.js.snap
packages/article-list/article-list.showcase.js
packages/article-list/package.json
packages/article-list/src/article-list-empty-state.js
packages/article-list/src/article-list-error.js
packages/article-list/src/article-list-item-separator.js
packages/article-list/src/article-list-pagination.js
packages/article-list/src/article-list.js
packages/article-list/src/styles/index.js
packages/article-list/src/styles/responsive.js
packages/context/package.json
packages/ssr/__tests__/cypress/plugins/index.js
packages/ssr/__tests__/cypress/support/index.js
packages/ssr/__tests__/helpers/author-profile-helper.js

removed react native from the article-list component.
[TDP-1693](https://nidigitalsolutions.jira.com/browse/TDP-1693)

feat(TDP-1693): removed react native from article list

---

packages/context/package.json
packages/ts-components/src/index.ts

Missed out the named export so adding this in.

feat(TDP-1714): export named breakpoint from ts styleguide

---

packages/article-topics/__tests__/web/__snapshots__/article-topics-with-style.web.test.js.snap
packages/context/package.json
packages/link/__tests__/web/__snapshots__/link.web.test.js.snap
packages/link/src/link.js
packages/pagination/__tests__/web/__snapshots__/pagination-with-styles.web.test.js.snap
packages/ts-components/src/components/latest-from-section/__tests__/__snapshots__/LatestFromSection.test.tsx.snap
packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/InlineNewsletterPuff.test.tsx.snap
packages/ts-components/src/components/newsletter-puff/__tests__/__snapshots__/NewsletterPuffLink.test.tsx.snap
yarn.lock

fixed issue where links were appearing with underlines 
and now they don't

feat(TDP-1705): fixed css issue from recent change

---

packages/ts-components/src/components/recommended-articles/RecommendedArticles.tsx
packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedArticles.test.tsx.snap

feat(TDP-1935): Recommended Articles

---

packages/article-magazine-standard/__tests__/shared-with-style.js
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/package.json
packages/article-magazine-standard/src/article-header/article-header.js
packages/article-magazine-standard/src/article-label/article-label.js
packages/article-magazine-standard/src/article-meta/article-meta.js
packages/article-magazine-standard/src/article-standfirst/article-standfirst.js
packages/article-magazine-standard/src/styles/index.js
packages/article-magazine-standard/src/styles/responsive.js
packages/article-magazine-standard/src/styles/shared.js

removed react native from article-magazine-standard
[TDP-1697](https://nidigitalsolutions.jira.com/browse/TDP-1697)

feat(TDP-1697): removed reactNative from articleMagazineStandard

---

packages/article-extras/__tests__/web/__snapshots__/article-extras.test.js.snap
packages/article-extras/src/article-extras.js

fix(TDP-1942): Recommended article - no feature flag

---

packages/article-extras/__tests__/web/__snapshots__/article-extras.test.js.snap
packages/article-extras/src/article-extras.js
packages/ts-components/src/components/recommended-articles/__tests__/RecommendedFetch.test.tsx
packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedFetch.test.tsx.snap

fix(TDP-1942): Recommended article - feature flag

---

packages/article-list/__tests__/web/__snapshots__/article-list-error-with-styles.web.test.js.snap
packages/pagination/__tests__/shared.base.js
packages/pagination/__tests__/shared.js
packages/pagination/__tests__/web/__snapshots__/pagination-with-styles.web.test.js.snap
packages/pagination/__tests__/web/__snapshots__/pagination-wrapper.web.test.js.snap
packages/pagination/__tests__/web/__snapshots__/pagination.web.test.js.snap
packages/pagination/__tests__/web/pagination-wrapper.web.test.js
packages/pagination/__tests__/web/pagination.web.test.js
packages/pagination/package.json
packages/pagination/src/page-label.js
packages/pagination/src/pagination-border.js
packages/pagination/src/pagination-container.js
packages/pagination/src/pagination-icons.js
packages/pagination/src/pagination.js
packages/pagination/src/results-message.js
packages/pagination/src/results.js
packages/pagination/src/styles/responsive.js

removed react native from the pagination component
[TDP-1706](https://nidigitalsolutions.jira.com/browse/TDP-1706)

feat(TDP-1706): removed react native from pagination

---

packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-render-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card-reverse-style.test.js.snap
packages/card/src/card-content.js
packages/card/src/styles/index.js

fix(1710): RNR card images

---

packages/ts-components/src/components/recommended-articles/RecommendedFetch.tsx

feat(TDP-1967): Recommended articles - experiment id

---

packages/article-extras/src/article-extras.js
packages/ts-components/src/components/recommended-articles/RecommendedArticles.stories.tsx
packages/ts-components/src/components/recommended-articles/RecommendedArticles.tsx
packages/ts-components/src/components/recommended-articles/RecommendedFetch.tsx
packages/ts-components/src/components/recommended-articles/__tests__/RecommendedArticles.test.tsx
packages/ts-components/src/components/recommended-articles/__tests__/RecommendedFetch.test.tsx

fix(TDP-1967): recommended articles analytics

---

.gitignore
packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/article-comments.js

TDP-2230: Update copy

---

packages/ts-components/src/components/recommended-articles/RecommendedArticles.tsx
packages/ts-components/src/components/recommended-articles/RecommendedFetch.tsx
packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedArticles.test.tsx.snap

revert(TDP-1967): Recommended articles - remove feature flag

---

packages/save-and-share-bar/__tests__/mocks.js
packages/save-and-share-bar/__tests__/shared-tracking.js
packages/save-and-share-bar/__tests__/shared.base.js
packages/save-and-share-bar/__tests__/shared.js
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/__tests__/web/__snapshots__/save-share-bar-tracking.test.js.snap
packages/save-and-share-bar/package.json
packages/save-and-share-bar/src/bar-item.js
packages/save-and-share-bar/src/email-share.js
packages/save-and-share-bar/src/save-and-share-bar.js
packages/save-and-share-bar/src/styles/index.js

removed react native from save and share bar

feat(TDP-1694): removed react native from save and share bar

---

packages/jest-configurator-web/__tests__/jest-configurator.test.js
packages/jest-configurator-web/src/jest-configurator.js

updated the path in the config to the tests

feat(TDP-1712): update jest web config

---

packages/caption/__tests__/web/jest.config.js
packages/caption/babel.config.js
packages/caption/package.json

Have updated jest/babel config to use the new jest-configurator-web package

feat(TDP-1712): updated package/caption to use the new jest web config

---

packages/jest-configurator-web/src/jest-configurator.js

not sure how many times i need too put the path in correctly, but i'm sure it's ok now

feat(TDP-1712): updated path again

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/__tests__/web/tracking.web.test.js
packages/article-comments/src/article-comments.js
packages/article-comments/src/comments.js
packages/article-extras/__tests__/web/__snapshots__/article-extras.test.js.snap
packages/article-extras/src/article-extras.js

feat(TDP-2202): Commenting update

---

packages/ts-components/src/components/recommended-articles/RecommendedArticles.tsx
packages/ts-components/src/components/recommended-articles/__tests__/RecommendedArticles.test.tsx
packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedArticles.test.tsx.snap
packages/ts-components/src/components/recommended-articles/formatters.ts
packages/ts-components/src/components/recommended-articles/styles.ts
packages/ts-components/src/components/related-article-slice/__tests__/__snapshots__/RelatedArticleSlice.test.tsx.snap
packages/ts-components/src/fixtures/preview-data/recommended-articles.ts
packages/ts-slices/src/components/slices/RelatedArticle1/RelatedArticle1.tsx
packages/ts-slices/src/components/slices/RelatedArticle1/__tests__/__snapshots__/RelatedArticle1.test.tsx.snap
packages/ts-slices/src/components/slices/RelatedArticle2/RelatedArticle2.tsx
packages/ts-slices/src/components/slices/RelatedArticle2/__tests__/RelatedArticle2.test.tsx
packages/ts-slices/src/components/slices/RelatedArticle2/__tests__/__snapshots__/RelatedArticle2.test.tsx.snap
packages/ts-slices/src/components/slices/RelatedArticle2/styles.ts
packages/ts-slices/src/components/slices/RelatedArticle3/RelatedArticle3.tsx
packages/ts-slices/src/components/slices/RelatedArticle3/__tests__/RelatedArticle3.test.tsx
packages/ts-slices/src/components/slices/RelatedArticle3/__tests__/__snapshots__/RelatedArticle3.test.tsx.snap
packages/ts-slices/src/components/slices/RelatedArticle3/styles.ts
packages/ts-slices/src/components/slices/Slice.stories.tsx
packages/ts-slices/src/fixtures/getSlice.ts
packages/ts-slices/src/utils/getSlice.ts

- replace the use of `related-articles` with a slice from `ts-slices`
- update the slice data formatter
- update component tests and snapshots

fix(TDP-2268): Double tracking bug - replace slice

---

packages/ts-components/src/components/recommended-articles/RecommendedArticles.stories.tsx
packages/ts-components/src/components/recommended-articles/RecommendedFetch.tsx
packages/ts-components/src/components/recommended-articles/__tests__/RecommendedArticles.test.tsx

chore(TDP-2268): Recommended article analytics

---

packages/markup-forest/package.json

Remove unused jest configurator dependency from markup-forest

feat(TDP-1712): markup forest

---

packages/ts-slices/README.md
packages/ts-slices/babel.config.js
packages/ts-slices/jest.config.js
packages/ts-slices/package.json
packages/ts-slices/tsconfig.json

and removed any react native remaining

feat(TDP-1712): updated jest config for ts-slices

---

packages/ts-styleguide/babel.config.js
packages/ts-styleguide/jest.config.js
packages/ts-styleguide/package.json

Change babel and jest configs to remove any react-native.

feat(TDP-1712): remove react-native from ts-styleguide

---

packages/ts-components/babel.config.js
packages/ts-components/jest.config.js
packages/ts-components/package.json

Remove react native from ts-components jest config and babel

feat(TDP-1712): Remove react-native from ts-components

---

packages/utils/__tests__/jest.config.js
packages/utils/__tests__/scroll-to-element.test.js
packages/utils/babel.config.js
packages/utils/package.json
packages/utils/src/tc-text.js

updated jest configurator for utils

feat(TDP-1712): TDP-2320 TDP-2328 utils

---

packages/article-comments/__tests__/web/shared.web.test.js
packages/article-comments/src/comment-login.js

Removing feature flag to allow new endpoint to be used in production
https://nidigitalsolutions.jira.com/jira/software/c/projects/TDP/boards/1491?modal=detail&selectedIssue=TDP-2318

feat(TDP-2318): enable sso loginv2 endpoint prod

---

lib/cli/cli.js
lib/cli/templates.js
packages/article-comments/README.md
packages/article-paragraph/README.md

There was still some test files and readme's referencing ios & android that I've removed

feat(TDP-1712): removed old mobile specific references

---

packages/button/babel.config.js
packages/caption/babel.config.js
packages/card/__tests__/web/__snapshots__/card-loading-style.test.js.snap
packages/card/__tests__/web/__snapshots__/card.web.test.js.snap
packages/card/babel.config.js
packages/context/babel.config.js
packages/error-view/babel.config.js
packages/gradient/babel.config.js
packages/icons/babel.config.js
packages/image/babel.config.js
packages/jest-serializer/babel.config.js
packages/key-facts/babel.config.js
packages/link/babel.config.js
packages/markup/babel.config.js
packages/message-bar/babel.config.js
packages/pagination/babel.config.js
packages/pull-quote/babel.config.js
packages/related-articles/babel.config.js
packages/responsive/babel.config.js
packages/save-and-share-bar/babel.config.js
packages/save-star-web/babel.config.js
packages/slice-layout/babel.config.js
packages/storybook/babel.config.js
packages/topic/babel.config.js
packages/tracking/babel.config.js
packages/utils/babel.config.js
packages/video-label/babel.config.js
packages/video/babel.config.js
packages/watermark/babel.config.js

Update babel configs so tests can pass locally

feat(TDP-1712): Update babel configs

---

packages/article-comments/src/comments.js
packages/article-comments/src/utils.js

feat(TDP-000): commenting test

---

packages/article-list/__tests__/shared-error.base.js

simplified declaration of variable consoleSpy

feat(TDP-1712): updated small test

---

packages/image/src/image.js

fix(TDP-000): image without resize

---

packages/article-extras/__tests__/mocks.js
packages/article-extras/__tests__/shared.js
packages/article-extras/article-extras.showcase.js
packages/article-extras/src/article-extras.js
packages/article-in-depth/src/article-in-depth.js
packages/article-magazine-comment/src/article-magazine-comment.js
packages/article-magazine-standard/src/article-magazine-standard.js
packages/article-main-comment/src/article-main-comment.js
packages/article-main-standard/src/article-main-standard.js
packages/article-skeleton/ArticleSkeleton.stories.js
packages/article-skeleton/__tests__/mocks.js
packages/article-skeleton/showcase-helper.js
packages/article-skeleton/src/article-body/article-body.js
packages/article-skeleton/src/article-skeleton.js
packages/article/showcase-helper.js
packages/ssr/src/client/article.js
packages/ssr/src/component/article.js
packages/ssr/src/server/article.js
packages/ts-components/src/index.ts

feat(TDP-000): Remove algolia related articles and various TS imports

---

packages/article-comments/src/comment-login.js

feat(TDP-000): Commenting re-auth testing

---

packages/article-comments/src/comment-login.js

feat(TDP-000): commenting reauth with cpn

---

packages/article-skeleton/__tests__/web/__snapshots__/head.test.js.snap
packages/article-skeleton/__tests__/web/head.test.js

Create a test to output the `Live blog schema`.

test(TDP-2477): Live blog schema test

---

packages/save-and-share-bar/package.json
packages/save-and-share-bar/src/save-and-share-bar.js
packages/tracking/package.json
packages/ts-components/src/components/in-article-link/InArticleLink.tsx
packages/ts-components/src/components/in-article-related-articles/__tests__/__snapshots__/RelatedArticle.test.tsx.snap
packages/ts-components/src/components/save-star/SaveStar.stories.tsx
packages/ts-components/src/components/save-star/SaveStar.tsx
packages/ts-components/src/components/save-star/SaveStarUI.tsx
packages/ts-components/src/components/save-star/__tests__/SaveStar.test.tsx
packages/ts-components/src/components/save-star/__tests__/__snapshots__/SaveStar.test.tsx.snap
packages/ts-components/src/components/save-star/styles.ts
packages/ts-components/src/helpers/fetch/FetchProvider.tsx
packages/ts-components/src/helpers/fetch/__tests__/FetchProvider.test.tsx
packages/ts-components/src/index.ts
packages/ts-components/src/types/externs.d.ts
yarn.lock

feat(TDP-000): Bookmarks migrated to Newskit

---

packages/article-skeleton/__tests__/web/__snapshots__/auto-place-newsletter-puff.web.test.js.snap
packages/ts-components/src/components/save-star/SaveStar.tsx
packages/ts-components/src/components/save-star/SaveStarUI.tsx
packages/ts-components/src/components/save-star/__tests__/SaveStar.test.tsx

feat(TDP-000): Bookmarks to Newskit

---

packages/article-extras/package.json
packages/article-skeleton/package.json

cross your fingers and hope it fixes the issue, or will try something else.

fix(TDP-000): attempting to force CircleCi to fix conflict with tag

---

packages/article-image/src/styles/index.js
packages/article-in-depth/src/styles/shared.js
packages/article-list/src/styles/shared.js
packages/article-magazine-standard/src/newStyles/shared.js
packages/article-main-standard/src/styles/article-body/shared.js
packages/article-skeleton/src/styles/article-body/shared.js
packages/author-profile/__tests__/web/__snapshots__/author-profile-with-style.web.test.js.snap
packages/author-profile/src/styles/shared.js
packages/caption/__tests__/web/__snapshots__/caption.web.test.js.snap
packages/caption/src/centred-caption.js
packages/topic/__tests__/web/__snapshots__/topic-with-style.web.test.js.snap
packages/topic/src/styles/shared.js

We had some React Native styling hanging around, so have replaced then with ordinary css syntax

feat(TDP-2838): change residual react native styles

---

packages/ts-components/src/components/recommended-articles/__tests__/RecommendedFetch.test.tsx
packages/ts-components/src/components/recommended-articles/__tests__/__snapshots__/RecommendedFetch.test.tsx.snap

fix(TDP-2933): add test for Scotland section

---

.storybook/preview-head.html
fonts.js
lib/fetch-fonts.js
packages/ts-newskit/src/theme/times-web-light/styles/fonts.json

Add roboto font to Times component so it can be used for Nav UI only
[JIRA-3186](https://nidigitalsolutions.jira.com/browse/TDP-3186)

feat(TDP-3186): add roboto font

---

packages/ts-newskit/src/components/hamburger-menu/HamburgerMenu.stories.mdx
packages/ts-newskit/src/components/hamburger-menu/NavigationList.tsx
packages/ts-newskit/src/components/hamburger-menu/__tests__/__snapshots__/HamburgerMenu.test.tsx.snap
packages/ts-newskit/src/components/hamburger-menu/__tests__/__snapshots__/NavItems.test.tsx.snap
packages/ts-newskit/src/components/hamburger-menu/styles.ts
packages/ts-newskit/src/theme/times-web-light/style-presets/menu.ts

Revert chevrons to default behaviour on MenuSub items to face down when closed and then up when opened. Small storybook updates

fix(TDP-3102): Styling tweaks from design review and updates to storybook

---

packages/ts-newskit/src/components/utils/TCThemeProvider.tsx
packages/ts-newskit/src/components/utils/__tests__/TCThemeProvider.test.tsx
packages/ts-newskit/src/components/utils/__tests__/__snapshots__/TCThemeProvider.test.tsx.snap
packages/ts-newskit/src/index.ts

Packaging of NewskitProvider component to allow for exporting of this and associated ThemeProvider

feat(TDP-3290): add ThemeProvider wrapper component

---

CODEOWNERS

chore(TDP-000): Update Codeowners

---

packages/ts-newskit/src/index.ts

For testing Nav UI components in render.

chore(TDP-000): Export HamburgerMenuContainer for testing

---

packages/ts-newskit/src/components/global-nav/__tests__/index.test.tsx
packages/ts-newskit/src/components/global-nav/index.tsx
packages/ts-newskit/src/index.ts

Another one to test why GlobalNav not working in render

chore(TDP-000): Export drawer

---

packages/ts-newskit/src/components/global-nav/HamburgerMenuContainer.tsx
packages/ts-newskit/src/components/global-nav/__tests__/HamburgerMenuContainer.test.tsx
packages/ts-newskit/src/components/global-nav/__tests__/index.test.tsx
packages/ts-newskit/src/components/global-nav/index.tsx
packages/ts-newskit/src/components/global-nav/notglobalnav.stories.mdx
packages/ts-newskit/src/index.ts

Still only going to be used for testing purposes but have created a custom Drawer component to see whether this can be used in place of Newskit Drawer as that is breaking when imported to render.

fix(TDP-3223): Create custom drawer component

---

packages/ts-newskit/src/components/global-nav/HamburgerMenuContainer.tsx
packages/ts-newskit/src/components/global-nav/notglobalnav.stories.mdx

Update overlay and drawer component so that it doesn't block the content on the page.

fix(TDP-3223): Fix overlay of navigation drawer

---

packages/article-skeleton/src/static-content.js

Modified logic to make zephr static component SSR

---

packages/ts-newskit/src/components/global-nav/__tests__/index.test.tsx
packages/ts-newskit/src/components/global-nav/index.tsx
packages/ts-newskit/src/index.ts

Export NewsKit Drawer so we can test in render

chore(TDP-000): Export NewsKit Drawer component for testing

---

packages/ts-newskit/src/components/secondary-menu/__tests__/__snapshots__/create-menu.test.tsx.snap
packages/ts-newskit/src/components/secondary-menu/styles.ts

fix(TDP-3295): add z index

---

packages/ts-newskit/src/components/slices/lead-story/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/lead-story/index.tsx
packages/ts-newskit/src/components/slices/lead-story/styles.ts
packages/ts-newskit/src/components/slices/slice-header/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/slice-header/index.tsx
packages/ts-newskit/src/components/slices/slice-header/styles.ts

fix padding issue on mobile
[JIRA-3230](https://nidigitalsolutions.jira.com/browse/TDP-3230)

fix(TDP-3230): fix padding issue on mobile

---

README.md
packages/article-skeleton/src/static-content.js

chore: retry publish

---

packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-skeleton.js

chore: remove whitespace from zephr test div

---

packages/ad/package.json
packages/article-byline/package.json
packages/article-extras/package.json
packages/article-image/package.json
packages/article-label/package.json
packages/article-lead-asset/package.json
packages/article-topics/package.json
packages/author-profile/package.json
packages/caption/package.json
packages/context/package.json
packages/date-publication/package.json
packages/image/package.json
packages/interactive-wrapper/package.json
packages/key-facts/package.json
packages/link/package.json
packages/markup/package.json
packages/message-bar/package.json
packages/provider/package.json
packages/pull-quote/package.json
packages/responsive/package.json
packages/save-and-share-bar/package.json
packages/sticky/package.json
packages/topic/package.json
packages/tracking/package.json
packages/ts-components/package.json
packages/ts-styleguide/package.json
packages/user-state/package.json
packages/utils/package.json
packages/video-label/package.json
packages/video/package.json

Need to re-release the broken packages.

chore: bump the broken packages

---

packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-skeleton.js

chore: more zephr divs

---

packages/ts-newskit/src/components/puzzles/archive/Archive.stories.mdx
packages/ts-newskit/src/components/puzzles/archive/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/archive/index.tsx
packages/ts-newskit/src/components/puzzles/archive/styles.ts
packages/ts-newskit/src/components/puzzles/date-card/DateCard.stories.mdx
packages/ts-newskit/src/components/puzzles/date-card/fixtures/data.json
packages/ts-newskit/src/components/puzzles/date-card/index.tsx
packages/ts-newskit/src/components/puzzles/date-card/types.ts
packages/ts-newskit/src/components/puzzles/flag/Flag.stories.mdx
packages/ts-newskit/src/components/puzzles/flag/index.tsx
packages/ts-newskit/src/index.ts

[TMST-619](https://nidigitalsolutions.jira.com/browse/TMST-619)
**Description**
- merged Flag, DateCard, and Archive components
- adjustments after merging components
- added controls on Scroll inside Accordion's panel
- snapshots updates
[TMST-619]: https://nidigitalsolutions.jira.com/browse/TMST-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMST-619): create puzzles archive component

---

packages/ts-newskit/src/components/misc/accordion/accordion-group.stories.mdx
packages/ts-newskit/src/components/misc/accordion/accordion-group.tsx
packages/ts-newskit/src/index.ts
packages/ts-newskit/src/theme/times-web-light/style-presets/accordion.ts

feat(TDP-000): Accordion

---

README.md
packages/ts-newskit/src/components/misc/accordion/__tests__/__snapshots__/accordion-group.test.tsx.snap
packages/ts-newskit/src/components/misc/accordion/__tests__/accordion-group.test.tsx
packages/ts-newskit/src/components/misc/accordion/accordion-group.stories.mdx
packages/ts-newskit/src/components/misc/toast/__tests__/__snapshots__/toast.test.tsx.snap
packages/ts-newskit/src/components/misc/toast/__tests__/toast.test.tsx
packages/ts-newskit/src/components/misc/toast/toast.stories.mdx
packages/ts-newskit/src/components/misc/toast/toast.tsx

feat(TDP-000): toast component

---

packages/ts-newskit/src/components/article-audio/audio/index.tsx

TMRX-1198
Update to logic for closing sticky player for audio component. Will now reappear, if closed, when clicking the play/pause button.

feat(TMRX-1198): update logic for close button

---

.storybook/preview-head.html
packages/ts-newskit/src/components/slices/articleList/__tests__/index.test.tsx
packages/ts-newskit/src/components/slices/articleList/fixtures/data.json
packages/ts-newskit/src/components/slices/articleList/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-1/__tests__/index.test.tsx
packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-2/__tests__/index.test.tsx
packages/ts-newskit/src/slices/content-bucket-2/index.tsx
packages/ts-newskit/src/slices/fixtures/data.json
packages/ts-newskit/src/theme/times-web-light/style-presets/slices.ts

Update Content Buck 2 with new theme presets and ArticleList component
Update fonts from new theme

feat(TMRX-1240): update content bucket 2

---

packages/ts-newskit/src/components/slices/lead-story/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/lead-story/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap

This PR is ti fix color mismatch of timetoread props of lead story 
[TMRX-1257](https://nidigitalsolutions.jira.com/browse/TMRX-1257)
[TMRX-1257]: https://nidigitalsolutions.jira.com/browse/TMRX-1257?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1257): fix color mismatch

---

packages/ts-newskit/src/index.ts

Added export for puzzle theme.

fix(TMST-theme-export): exported puzzles theme

---

packages/author-profile/__tests__/web/__snapshots__/author-profile-loading.web.test.js.snap
packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
packages/author-profile/package.json
packages/author-profile/src/author-profile-head-base.js
packages/author-profile/src/author-profile-head-jobtitle.js
packages/author-profile/src/author-profile-head.js
packages/author-profile/src/author-profile.js
packages/ts-newskit/src/components/misc/job-title/__tests__/index.test.tsx
packages/ts-newskit/src/components/misc/job-title/job-title.stories.mdx
packages/ts-newskit/src/components/misc/job-title/job-title.tsx

The useBreakpointKey hook wasn't working in the article, this is because it seems to take into account the component size rather than the window.. So in situ was always returning xs. 
https://nidigitalsolutions.jira.com/browse/TMRX-499
This fixes that so should now be responsive within the author profile page.

fix(TRMX-499) fix job title breakpoint key usage

---

packages/ts-newskit/src/components/slices/articleList/ArticleList.stories.mdx
packages/ts-newskit/src/components/slices/articleList/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/articleList/__tests__/index.test.tsx
packages/ts-newskit/src/components/slices/articleList/fixtures/data.json
packages/ts-newskit/src/components/slices/articleList/index.tsx
packages/ts-newskit/src/components/slices/lead-story/LeadStory.stories.mdx
packages/ts-newskit/src/components/slices/lead-story/__tests__/index.test.tsx
packages/ts-newskit/src/components/slices/lead-story/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/fixtures/data.json

Allow for content to be left or right justified with image 
[TMRX-1226](https://nidigitalsolutions.jira.com/browse/TMRX-1226)
[TMRX-1226]: https://nidigitalsolutions.jira.com/browse/TMRX-1226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1226): update articleList component to accommodate slice

---

packages/ts-newskit/src/components/puzzles/archive/fixtures/boardAndCardArchive.json
packages/ts-newskit/src/components/puzzles/archive/fixtures/corsswordsArchive.json
packages/ts-newskit/src/components/puzzles/archive/fixtures/numbersAndLogicArchive.json
packages/ts-newskit/src/components/puzzles/archive/fixtures/quizzesAndTeasersArchive.json
packages/ts-newskit/src/components/puzzles/archive/fixtures/sudokuArchive.json
packages/ts-newskit/src/components/puzzles/archive/fixtures/wordPuzzlesArchive.json
packages/ts-newskit/src/components/puzzles/archive/types.ts
packages/ts-newskit/src/components/puzzles/breakout-section/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/breakout-section/index.tsx
packages/ts-newskit/src/components/puzzles/breakout-section/styles.ts
packages/ts-newskit/src/components/puzzles/cards-container/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/cards-container/fixtures/puzzleGame.json
packages/ts-newskit/src/components/puzzles/cards-container/index.tsx
packages/ts-newskit/src/components/puzzles/cards-container/styles.ts
packages/ts-newskit/src/components/puzzles/personal-stats/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/personal-stats/index.tsx
packages/ts-newskit/src/components/puzzles/puzzle-card/PuzzleCard.stories.mdx
packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/PuzzleCard.test.tsx
packages/ts-newskit/src/components/puzzles/puzzle-card/__tests__/__snapshots__/PuzzleCard.test.tsx.snap
packages/ts-newskit/src/components/puzzles/puzzle-card/fixtures/data.json
packages/ts-newskit/src/components/puzzles/puzzle-card/index.tsx
packages/ts-newskit/src/components/puzzles/puzzle-card/types.ts

[TMST-673](https://nidigitalsolutions.jira.com/browse/TMST-673)
**Description**
- updated CardsContainer component props and types to work with data from TPA
[TMST-673]: https://nidigitalsolutions.jira.com/browse/TMST-673?atlOrigin=eyJpIjoiNWI4Yjc1YjY3MDkzNDYyY2EzZDFjYWE5NzlmZWFmMGMiLCJwIjoiaiJ9

fix(TMST-673): CardsContainer and PuzzleCard fixes

---

packages/article-skeleton/__tests__/web/__snapshots__/head.test.js.snap
packages/article-skeleton/src/head.js

feat(TMR-1147): revert head product id

---

packages/ts-newskit/package.json
packages/ts-newskit/src/assets/EastArrow.tsx
packages/ts-newskit/src/assets/SeeAllLeft.tsx
packages/ts-newskit/src/assets/SeeAllRight.tsx
packages/ts-newskit/src/assets/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/assets/index.tsx
packages/ts-newskit/src/components/puzzles/archive/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/cards-container/__tests__/__snapshots__/index.test.tsx.snap
yarn.lock

Added svg icons

---

packages/ssr/src/client/article.js
packages/ssr/src/lib/run-client.js
packages/ssr/src/lib/run-server.js

feat: TPA get requests

---

packages/ts-newskit/src/slices/stacked-module-1/stacked-module-1.stories.mdx

add gridOverlay
[TMRX-1093](https://nidigitalsolutions.jira.com/browse/TMRX-1093)
[TMRX-1093]: https://nidigitalsolutions.jira.com/browse/TMRX-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1093): add gridOverlay

---

packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.stories.tsx
packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.tsx
packages/ts-components/src/components/opta/cricket/scorecard/__tests__/__snapshots__/OptaCricketScorecard.test.tsx.snap
packages/ts-components/src/components/opta/cricket/scorecard/styles.ts

feat: cricket widget

---

packages/ts-newskit/src/slices/section-bucket/__tests__/index.test.tsx

Branch created to test to see if it will fix  CI/CD pipeline issue.

fix(TMRX-0000): fix pipeline issue

---

packages/article/__tests__/web/ad-mock.js

The pipeline failed on Master during the publish npm step, can't re run it because it's already created the version so this is just to push through another pipeline build.

fix(TMRX-000): Add a small space to trigger another pipeline build

---

packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/index.tsx

Apply design feedback
[TMRX-1099](https://nidigitalsolutions.jira.com/browse/TMRX-1099)
[TMRX-1099]: https://nidigitalsolutions.jira.com/browse/TMRX-1099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1099): apply design feedback

---

packages/ts-newskit/src/components/navigation/breadcrumb/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/theme/times-web-light/style-presets/breadcrumb.ts

removed error from invalid reference

fix(TMRX-0000): fixed invalid colour reference

---

packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-1/article-stack.tsx
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/shared-styles/index.ts
packages/ts-newskit/src/slices/shared/article-stacks.tsx

Resolve vertical 'bounce' from native behaviour on Safari/iPhone

fix(TMRX-1348): vertical scroll bounce

---

packages/ts-newskit/src/components/puzzles/breakout-section/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/breakout-section/fixtures/breakoutItems.json
packages/ts-newskit/src/components/puzzles/breakout-section/index.tsx

Updated BreakoutSection url values.

Removed puzzlePage=true from urls in BreakoutSection

---

packages/article-in-depth/src/article-in-depth.js
packages/article-main-standard/src/article-main-standard.js

Add hasUpdate to indepth template type.

feat(TMRX-1250) live news update

---

packages/ts-newskit/src/components/puzzles/cards-container/CardsContainer.stories.mdx
packages/ts-newskit/src/components/puzzles/cards-container/index.tsx

Added isImageCropped prop to CardsContainer component.

fix: Added isImageCropped to CardsContainer component.

---

packages/ts-newskit/src/index.ts

EXPORT LeadStory1 ,LeadStory2, LeadStory3, SectionBucket, StackModule1

fix(TMRX-0000): export slices

---

packages/article-skeleton/src/article-skeleton.js
packages/ts-newskit/src/components/misc/delayed-component/__tests__/delayed-component.test.tsx
packages/ts-newskit/src/components/misc/delayed-component/delayed-component.tsx
packages/ts-newskit/src/components/misc/update-button/update-button-with-delay.tsx

Description
Minor updates to reset state after delay has passed so that it should catch the next update and render the button again. 
Having a problem with caching so have passed true into reload() to hopefully break that.

feat(TMRX-1250): Updates to update button

---

packages/ts-newskit/src/components/misc/delayed-component/__tests__/delayed-component.test.tsx
packages/ts-newskit/src/components/misc/delayed-component/delayed-component.tsx
packages/ts-newskit/src/components/misc/update-button/update-button-with-delay.tsx

Revert state reset as it would then show the update button on polling every time. 
Point to new data point publishedTime.

fix(TMRX-1250): Revert state reset and point to publishedTime

---

packages/article-in-depth/src/article-in-depth.js
packages/article-main-standard/src/article-main-standard.js
packages/article-skeleton/src/article-skeleton.js
packages/article/showcase-helper.js
packages/ssr/src/client/article.js
packages/ssr/src/component/article.js
packages/ssr/src/server/article.js
packages/ts-newskit/src/components/misc/update-button/update-button-with-delay.tsx

Remove feature flag `showUpdate` and increase the poll time for fetching data to 2 minutes.

feat(TMRX-1250): remove update button feature flag

---

packages/ts-newskit/src/slices/lead-story-2/article-stacks.tsx
packages/ts-newskit/src/slices/lead-story-2/index.tsx
packages/ts-newskit/src/slices/shared/article-stacks.tsx
packages/ts-newskit/src/slices/shared/composed-article-stack.tsx

Trying to see whether this would fix the issue we have with the breakpoint Key initialisation - Storybook doesn't show the same breakpoint key issue as when the components are in render. So if this doesn't help will revert.

fix(TMRX-1314): Try to fix breakpoint key issue

---

packages/ts-newskit/src/components/slices/article/index.tsx
packages/ts-newskit/src/components/slices/lead-article/index.tsx
packages/ts-newskit/src/slices/fixtures/lead-story.json
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/index.tsx
packages/ts-newskit/src/slices/lead-story-2/article-stacks.tsx
packages/ts-newskit/src/slices/lead-story-3/article-stack.tsx

Remove external link icon
[TMRX-1314](https://nidigitalsolutions.jira.com/browse/TMRX-1314)
[TMRX-1314]: https://nidigitalsolutions.jira.com/browse/TMRX-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1314): remove external link icon

---

packages/ts-newskit/src/components/slices/lead-article/index.tsx
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/index.tsx

Description 
filter image with aspect ratio provided by lead story 3 and change the logic also add same width to lead story 3 as lead story 1 and 2 have to align lead story 3 with the others 
[TMRX-1314](https://nidigitalsolutions.jira.com/browse/TMRX-1314)
[TMRX-1314]: https://nidigitalsolutions.jira.com/browse/TMRX-1314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1314): try to fix image flashing

---

packages/ts-newskit/src/slices/content-bucket-1/index.tsx
packages/ts-newskit/src/slices/content-bucket-2/index.tsx
packages/ts-newskit/src/slices/lead-story-1/index.tsx
packages/ts-newskit/src/slices/lead-story-3/index.tsx
packages/ts-newskit/src/slices/section-bucket/index.tsx
packages/ts-newskit/src/slices/stacked-module-1/index.tsx

So turns out the change to lead1 did actually work I was just looking at the wrong slice.... oops. 
Added that change to all the other slices!

fix(TMRX-1313): Fix breakpoint key on slices

---

packages/article-skeleton/src/article-skeleton.js
packages/ts-components/src/components/welcome-banner/WelcomeBanner.stories.tsx
packages/ts-components/src/components/welcome-banner/WelcomeBanner.tsx
packages/ts-components/src/components/welcome-banner/__tests__/WelcomeBanner.test.tsx
packages/ts-components/src/components/welcome-banner/styles.ts
packages/ts-components/src/index.ts
packages/ts-styleguide/src/styleguide/colours/functional.tsx

This PR creates a welcome banner for users new to The Times once they have registered.

feat(TMG-773): Create welcome banner

---

.github/PULL_REQUEST_TEMPLATE.md

As part of our development process, we need to enhance the Times component by adding a Pull Request (PR) template. The PR template will help improve the clarity and consistency of our pull requests, making it easier for reviewers to understand the changes being made.
[JIRA-1379](https://nidigitalsolutions.jira.com/browse/TMRX-1379)

feat(TMRX-1379): Created PR Template

---

packages/ts-components/README.md

chore(TM-000): Force ts-components update

---

packages/ts-newskit/src/components/slices/lead-article/LeadArticle.stories.mdx
packages/ts-newskit/src/components/slices/lead-article/__tests__/index.test.tsx
packages/ts-newskit/src/components/slices/lead-article/index.tsx
packages/ts-newskit/src/components/slices/shared/GroupedArticle.stories.mdx
packages/ts-newskit/src/slices/fixtures/data.json
packages/ts-newskit/src/slices/fixtures/lead-story.json
packages/ts-newskit/src/slices/fixtures/lead-story3.json

So turns out existing slices also take standfirst as a prop. Changing our new slice summary prop to shortSummary. 

fix(TMRX-1314): Change standfirst prop

---

packages/ts-newskit/src/components/slices/comment-card/__tests__/comment-card.test.tsx
packages/ts-newskit/src/components/slices/comment-card/comment-card.stories.mdx
packages/ts-newskit/src/components/slices/comment-card/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-1/comment-stack.tsx
packages/ts-newskit/src/slices/content-bucket-1/content-bucket-1.stories.mdx
packages/ts-newskit/src/slices/fixtures/data.json

All articles want to have the flag so have added them to the comment cards.

feat(TMRX-1314): Add flag to comment cards

---

packages/ts-components/src/components/welcome-banner/WelcomeBanner.tsx
packages/ts-components/src/components/welcome-banner/styles.ts

This PR fixes the styling of the Welcome banner.
[TMG-773](https://nidigitalsolutions.jira.com/browse/TMG-773)
[TMG-773]: https://nidigitalsolutions.jira.com/browse/TMG-773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMG-773): Fix Welcome Banner styling

---

packages/ts-newskit/src/components/slices/comment-card/__tests__/__snapshots__/comment-card.test.tsx.snap
packages/ts-newskit/src/components/slices/comment-card/__tests__/comment-card.test.tsx
packages/ts-newskit/src/components/slices/comment-card/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/fixtures/data.json

change href to url
[JIRA-1314](https://nidigitalsolutions.jira.com/browse/TMRX-1314)

fix(TMRX-1314): change href to url

---

packages/ts-newskit/src/index.ts
packages/ts-newskit/src/utils/index.tsx

This method allows us to update a newskit theme typography, exporting will allow us to do this easier in render.
[TMRX-1152](https://nidigitalsolutions.jira.com/browse/TMRX-1152)
[TMRX-1152]: https://nidigitalsolutions.jira.com/browse/TMRX-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1152): allowing render to update custom themes

---

packages/ts-newskit/src/index.ts
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-1/content-bucket-1.stories.mdx
packages/ts-newskit/src/slices/content-bucket-1/index.tsx
packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-2/__tests__/index.test.tsx
packages/ts-newskit/src/slices/content-bucket-2/content-bucket-2.stories.mdx
packages/ts-newskit/src/slices/content-bucket-2/index.tsx
packages/ts-newskit/src/slices/fixtures/data.json

remove slice header from slices and export separately
[JIRA-1402](https://nidigitalsolutions.jira.com/browse/TMRX-1402)

feat(TMRX-1402): remove slice header from slices and export it

---

.circleci/config.yml
lerna.json
lib/publish.sh
lib/run_jobs.sh

**Summary:**
This pull request proposes a change from NPX to npm and Yarn for executing packages in our CircleCI pipeline. NPX, while convenient, introduces an extra layer of execution that may lead to errors and slower performance. By using npm and Yarn directly, we can avoid these issues and achieve faster pipeline execution.
**Proposed Changes:**
This PR includes the following changes:
1. Replacing NPX with npm and Yarn: We will replace NPX commands with npm and Yarn equivalents for package execution in the CircleCI configuration.
2. Updating Documentation: The project's documentation will be updated to reflect the new approach using npm and Yarn for package execution.
**Pros of Using NPX:**
1. Convenience: NPX allows for easy execution of packages directly from the registry without …

chore(TMP-323): Remove npx and use directly lerna, yarn and npm.

---

packages/user-state/__tests__/matchers.test.js
packages/user-state/src/matchers.js

chore(TMG-867): Update user state for Registered users

---

packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/index.tsx
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/index.tsx

revert font size of leadStory2 and leadStory3
[JIRA-0000](https://nidigitalsolutions.jira.com/browse/JIRA-0000)

fix(TMRX-0000): revert font size of leadStory2 and leadStory3

---

packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/index.tsx
packages/ts-newskit/src/theme/times-web-light/styles/typography-presets.ts

remove customEditorialHeadline030 and use editorialHeadline020 instead
[JIRA-0000](https://nidigitalsolutions.jira.com/browse/JIRA-0000)

fix(TMRX-0000): change typographyPreset to editorialHeadline020

---

packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/index.tsx

fix image layout issue
[JIRA-1442](https://nidigitalsolutions.jira.com/browse/TMRX-1442)
before
after

fix(TMRX-1442): fix image layout issue

---

packages/ts-newskit/src/components/slices/article/index.tsx

add null check to expirableFlags
[JIRA-1442](https://nidigitalsolutions.jira.com/browse/TMRX-1442)

fix(TMRX-1442): add null check to expirableFlags

---

packages/ts-newskit/src/index.ts

fix: Exported components from index.ts file.

---

packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/index.tsx
packages/ts-newskit/src/slices/shared/layouts.tsx
packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap

Update of `marginBlock` to `marginBlockEnd`
[TMRX-1477](https://nidigitalsolutions.jira.com/browse/TMRX-1477)
[TMRX-1477]: https://nidigitalsolutions.jira.com/browse/TMRX-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1477): sports channel feedback

---

packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/create-menu.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-mobile.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-desktop.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-mobile.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-navigation.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/desktop/create-menu.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/mobile/navItems.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/mobile/navigator.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/styles.ts
packages/ts-newskit/src/theme/times-web-light/style-presets/secondary-nav.ts
packages/ts-newskit/src/theme/times-web-light/styles/typography-presets.ts

Refactor of SecondaryNav component, with style updates. A few style/typography presets to be updated remain, and have been noted (as below). These updates will be included in other secondary nav tickets (such as [TMRX-1494](https://nidigitalsolutions.jira.com/browse/TMRX-1494)) once received.
https://docs.google.com/document/d/1LN9am3WrbCzLgJ75qwrjvKQb7_n0uNvWgngdu3bgjGE/edit
https://docs.google.com/document/d/1WPgWxWsQetl_6d_PVlzFuOHdwaYzza4q6OQLh7SjOIg/edit
[TMRX-1404): update tokens](https://nidigitalsolutions.jira.com/browse/TMRX-1404): update tokens)
[TMRX-1494]: https://nidigitalsolutions.jira.com/browse/TMRX-1494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1404): update tokens

---

packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/lead-article/index.tsx
packages/ts-newskit/src/components/slices/shared-styles/index.ts
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap

change typographyPreset from `editorialCaption020` to `editorialCaption010`
[JIRA-0000](https://nidigitalsolutions.jira.com/browse/JIRA-0000)

fix(TMRX-0000): update typographyPreset

---

packages/ts-newskit/src/components/navigation/global-nav/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/navigation/global-nav/__tests__/search.test.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/HamburgerMenu.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/__tests__/HamburgerMenu.test.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/__tests__/__snapshots__/HamburgerMenu.test.tsx.snap
packages/ts-newskit/src/components/navigation/global-nav/search/handleSearchSubmit.ts
packages/ts-newskit/src/components/navigation/global-nav/search/search.tsx
packages/ts-newskit/src/components/navigation/global-nav/topnav/__tests__/topnav.test.tsx
packages/ts-newskit/src/components/navigation/global-nav/topnav/topnav.tsx
packages/ts-newskit/src/components/navigation/global-nav/wrapped-components/WrappedComponents.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/fixtures/data.json

Update GlobalNav component to add search function that triggers `onSubmit` from search fields in Global Nav. This includes both the TopNav and HamburgerMenu, where we auto focus on the search field when mounted and pass `search term` and `source` onto `/search` upon submission.
[TMRX-1256](https://nidigitalsolutions.jira.com/browse/TMRX-1256)
[TMRX-1256]: https://nidigitalsolutions.jira.com/browse/TMRX-1256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1256): integrate search function in globalnav

---

packages/article-skeleton/src/contentModifiers/newsletter-puff.js

Add newsletter puff items for `ireland` and `irish-sport` sections 
[TMRX-1463](https://nidigitalsolutions.jira.com/browse/TMRX-1463)
[TMRX-1463]: https://nidigitalsolutions.jira.com/browse/TMRX-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1463): add newsletter objects for ireland

---

packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/index.tsx
packages/ts-newskit/src/slices/lead-story-1/styles.ts

remove StyleDivider and replace it with normal Divider
[JIRA-0000](https://nidigitalsolutions.jira.com/browse/JIRA-0000)

fix(TMRX-0000): change divider color

---

.circleci/config.yml
lib/publish.sh

fix(TMP-00): Remove npm whoami from circleci and add it to publish.sh.

---

lib/publish.sh

Fix/tmp 00/improve/lerna/commands

---

packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/create-menu.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/create-more-menu.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/navitems.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/secondary-desktop.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/secondary-mobile.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/secondary-nav-desktop.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/secondary-nav-mobile.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/secondary-navigation.test.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/desktop/create-menu.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/desktop/create-more-menu.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/desktop/index.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/desktop/navItems.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/index.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/mobile/index.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/mobile/navItems.tsx
packages/ts-newskit/src/components/navigation/secondary-menu/secondary-navigation.stories.mdx

A function will be passed down from render to enable tracking on the Secondary Navigation
[TMRX-1547](https://nidigitalsolutions.jira.com/browse/TMRX-1547)
[TMRX-1547]: https://nidigitalsolutions.jira.com/browse/TMRX-1547?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1547): Add tracking to secondary navigation

---

packages/ts-newskit/package.json
packages/ts-newskit/src/components/puzzles/breakout-section/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/breakout-section/styles.ts
packages/ts-newskit/src/components/puzzles/categoryCard/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/categoryCard/styles.ts
packages/ts-newskit/src/components/puzzles/free-trial/__tests__/__snapshots__/FreeTrial.test.tsx.snap
packages/ts-newskit/src/components/puzzles/free-trial/styles.ts
packages/ts-newskit/src/components/puzzles/hero-banner/__tests__/__snapshots__/HeroBanner.test.tsx.snap
packages/ts-newskit/src/components/puzzles/hero-banner/styles.ts
packages/ts-newskit/src/components/puzzles/personal-stats/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/personal-stats/styles.ts
packages/ts-newskit/src/components/puzzles/puzzle-card/styles.ts
packages/ts-newskit/src/components/puzzles/teaserCards-container/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/index.tsx
packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/stacked-module-1/index.tsx
yarn.lock

Update of newskit theme to add `sectionBrand` tokens to the different themes. This allows for theme specific colour values.
[TMRX-0000](https://nidigitalsolutions.jira.com/browse/TMRX-0000)

chore(TMRX-0000): update newskit theme

---

packages/ts-newskit/src/components/coloured-text/__tests__/coloured-text.test.tsx
packages/ts-newskit/src/components/coloured-text/index.tsx
packages/ts-newskit/src/index.ts

addition of exportable `ColouredText` component to allow us to modify colours on TextBlock through `$color` prop
[TMRX-1513](https://nidigitalsolutions.jira.com/browse/TMRX-1513)
[TMRX-1513]: https://nidigitalsolutions.jira.com/browse/TMRX-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1513): add component for handling coloured text

---

packages/ts-newskit/src/components/slices/shared/ArticleTileInfo.stories.mdx
packages/ts-newskit/src/slices/content-bucket-1/content-bucket-1.stories.mdx
packages/ts-newskit/src/slices/content-bucket-2/content-bucket-2.stories.mdx
packages/ts-newskit/src/slices/content-bucket-3/content-bucket-3.stories.mdx
packages/ts-newskit/src/slices/section-bucket/section-bucket.stories.mdx
packages/ts-newskit/src/slices/stacked-module-1/stacked-module-1.stories.mdx

Update `themes` import in stories to point to `TimesWebThemes`
[TMRX-0000](https://nidigitalsolutions.jira.com/browse/TMRX-0000)

chore(TMRX-0000): update theme import

---

packages/ts-newskit/src/components/slices/comment-card/__tests__/__snapshots__/comment-card.test.tsx.snap
packages/ts-newskit/src/components/slices/comment-card/index.tsx
packages/ts-newskit/src/components/slices/shared-styles/index.ts
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap

Comment, name and headline styling are using updated token
Design spec - https://drive.google.com/file/d/1iYHd5kBO2dDwudNUY7QwzK7KNa6CYQwe/view?usp=drive_link 
Description
Token update: Comment, name and headline styling
Design spec - https://drive.google.com/file/d/1iYHd5kBO2dDwudNUY7QwzK7KNa6CYQwe/view?usp=drive_link  
[JIRA-1519](https://nidigitalsolutions.jira.com/browse/TMRX-1519)

feat(TMRX-1519): token update comment name and headline

---

packages/ts-newskit/package.json
packages/ts-newskit/src/components/slices/comment-card/__tests__/__snapshots__/comment-card.test.tsx.snap
packages/ts-newskit/src/components/slices/comment-card/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
yarn.lock

Comment, name and headline styling are using updated token
Design spec - https://drive.google.com/file/d/1iYHd5kBO2dDwudNUY7QwzK7KNa6CYQwe/view?usp=drive_link 
Description
Token update: Comment, name and headline styling
Design spec - https://drive.google.com/file/d/1iYHd5kBO2dDwudNUY7QwzK7KNa6CYQwe/view?usp=drive_link  
[JIRA-1519](https://nidigitalsolutions.jira.com/browse/TMRX-1519)
before
after

feat(TMRX-1519): update token

---

packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-mobile.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-desktop.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-nav-mobile.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/__tests__/__snapshots__/secondary-navigation.test.tsx.snap
packages/ts-newskit/src/components/navigation/secondary-menu/mobile/navigator.tsx

fix(TMRX-000): Fix typo

---

packages/jest-serializer/package.json
packages/ts-newskit/src/index.ts
yarn.lock

Added exports for signup page components to use them on the render.

feat(TMPZ-000) : Exported Signup components

---

packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/ts-newskit/src/components/article-audio/__tests__/__snapshots__/in-article-audio.test.tsx.snap
packages/ts-newskit/src/components/article-audio/__tests__/__snapshots__/stickyplayer.test.tsx.snap
packages/ts-newskit/src/components/article-audio/in-article-audio.stories.mdx
packages/ts-newskit/src/components/article-audio/index.tsx

update `MQ` values to size audio player button and icon with sizing tokens

fix(TMRX-0000): update article audio icon

---

packages/ts-newskit/src/components/slices/comment-card/__tests__/__snapshots__/comment-card.test.tsx.snap
packages/ts-newskit/src/components/slices/comment-card/index.tsx
packages/ts-newskit/src/components/slices/slice-header/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/slice-header/index.tsx
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap

tabindex added into `SliceHeader` and `CommentCard` 
[TMRX-1629](https://nidigitalsolutions.jira.com/browse/TMRX-1629)
[TMRX-1629]: https://nidigitalsolutions.jira.com/browse/TMRX-1629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1629): tabindex added

---

packages/ts-newskit/src/components/slices/comment-card/index.tsx

Change headline color in comment card from sectionBrand070 to sectionBrand080 in CB1 CB3 CS1
Headline color in comment card is sectionBrand080
[JIRA-1642](https://nidigitalsolutions.jira.com/browse/TMRX-1642)

feat(TMRX-1642): change headline color in comment card

---

packages/ts-newskit/src/index.ts

feat(TMRX-0000): export comment bucket 1

---

packages/ts-newskit/src/index.ts
packages/ts-newskit/src/theme/index.ts
packages/ts-newskit/src/theme/times-web-light-travel/index.ts

- added TimesWebLightTravel theme

Added TimesWebLightTravel theme

---

packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-4/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-4/article-stack.tsx
packages/ts-newskit/src/slices/shared-styles/index.ts

implement design feedback: remove white space below tag/flag
[JIRA-1234](https://nidigitalsolutions.jira.com/browse/TMRX-1472)
before
after

feat(TMRX-1472): implement design feedback

---

packages/ts-newskit/src/components/slices/lead-article/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/slices/shared-styles/index.ts
packages/ts-newskit/src/slices/content-bucket-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/content-bucket-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/article-stack.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-1/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/article-stacks.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-2/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-3/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/lead-story-4/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/section-bucket/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/stacked-module-1/__tests__/__snapshots__/index.test.tsx.snap

Fixed alignment when wrapped 
[TMRX-1578](https://nidigitalsolutions.jira.com/browse/TMRX-1578)
After: 
Before: 
[TMRX-1578]: https://nidigitalsolutions.jira.com/browse/TMRX-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1578): line height added

---

packages/ts-newskit/src/components/puzzles/daily-quiz/hint-button/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/daily-quiz/hint-button/index.tsx
packages/ts-newskit/src/components/puzzles/daily-quiz/hint-container/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/daily-quiz/hints/index.tsx
packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts

Updated styling for daily quiz components.
[TMPZ-258](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMPZ/boards/1656?selectedIssue=TMPZ-258)
[TMPZ-258]: https://nidigitalsolutions.jira.com/browse/TMPZ-258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMPZ-258): adjusted quiz components styling

---

packages/ts-newskit/src/components/puzzles/article-sidebar/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/article-sidebar/index.tsx

Updated max width for image in puzzle sidebar component to fix the style issues in render.

feat(TMPZ-000) : Changes to Article Sidebar component

---

packages/ts-newskit/src/theme/index.ts
packages/ts-newskit/src/theme/times-web-light-business/index.tsx

Importing and exporting the Business design sub-theme for the Business and Money channel page
[TMRX-1770](https://nidigitalsolutions.jira.com/browse/TMRX-1770)
[TMRX-1770]: https://nidigitalsolutions.jira.com/browse/TMRX-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1770): Create theme for Business and Money channel

---

packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/desktop.test.tsx.snap
packages/ts-newskit/src/slices/list-view-slice/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/slices/list-view-slice/pagination.tsx

removal of `window` reference in pagination to circumvent error in SSR
[TMRX-1446](https://nidigitalsolutions.jira.com/browse/TMRX-1446)
[TMRX-1446]: https://nidigitalsolutions.jira.com/browse/TMRX-1446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRX-1446): remove window reference

---

packages/article-skeleton/src/article-skeleton.js
packages/user-state/__tests__/matchers.test.js
packages/user-state/src/matchers.js
packages/user-state/src/mock-user-state.js
packages/user-state/src/user-state.js

This PR creates an entitlement for the live update feature (users need to be logged in).
- create `showLiveUpdateButton` entitlement
- wrap `UpdateButtonWithDelay` component in `UserState` with above entitlement

fix(TMRX-000): Limit live update to logged in users

---

packages/ts-newskit/src/slices/list-view-slice/pagination.tsx

Update pagination props to impose boundaries to active page siblings
[TMRX-1826](https://nidigitalsolutions.jira.com/browse/TMRX-1826)
[TMRX-1826]: https://nidigitalsolutions.jira.com/browse/TMRX-1826?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRX-1826): update pagination props

---

packages/ssr/package.json

feat(TMRX-000): Update article path

---

packages/article-skeleton/__tests__/web/__snapshots__/article-images.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-isPreview.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article-with-user-state.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/__tests__/web/__snapshots__/auto-place-newsletter-puff.web.test.js.snap
packages/article-skeleton/__tests__/web/head.test.js
packages/article-skeleton/src/article-skeleton.js
packages/article-skeleton/src/head.js
packages/responsive/package.json
packages/ts-newskit/package.json
packages/utils/package.json

This PR uses data exposed via Render to create a canonical url:
```js
articleDataFromRender: {
hostName: string,
canonicalUrl: string,
},
```

feat(TMRX-000): Article canonical url

---

packages/responsive/package.json
packages/ts-newskit/package.json
packages/ts-newskit/src/components/navigation/global-nav/HamburgerMenuContainer.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/HamburgerMenu.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/LoggedInMenuItem.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/NavButtons.tsx
packages/ts-newskit/src/components/navigation/global-nav/hamburger-menu/NavigationList.tsx
packages/ts-newskit/src/components/navigation/global-nav/index.tsx
packages/ts-newskit/src/components/navigation/global-nav/search/handleSearchSubmit.ts
packages/ts-newskit/src/components/navigation/global-nav/search/search.tsx
packages/ts-newskit/src/components/navigation/global-nav/styles.ts
packages/ts-newskit/src/components/navigation/global-nav/topnav/createMenus.tsx
packages/ts-newskit/src/components/navigation/global-nav/topnav/loggedOutButtons.tsx
packages/ts-newskit/src/components/navigation/global-nav/topnav/topnav.tsx
packages/ts-newskit/src/components/navigation/global-nav/types.ts
packages/utils/package.json
yarn.lock

This PR is to add comments to the codebase indicating that certain components are in the process of being moved to the main repository. The comments serve to notify other developers to avoid making changes to these components until the move is complete
[JIRA-1843](https://nidigitalsolutions.jira.com/browse/TMRX-1843)

feat(TMRX-1843): add note to files that are being moved to render

---

packages/ts-newskit/src/components/puzzles/daily-quiz/final-screen/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-newskit/src/components/puzzles/daily-quiz/final-screen/index.tsx
packages/ts-newskit/src/components/puzzles/daily-quiz/how-to-play/index.tsx
packages/ts-newskit/src/theme/puzzles-web-light/style-presets.ts

Adjusted styling for daily quiz.
[TMPZ-346](https://nidigitalsolutions.jira.com/jira/software/c/projects/TMPZ/boards/1656?selectedIssue=TMPZ-346)
[TMPZ-346]: https://nidigitalsolutions.jira.com/browse/TMPZ-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMPZ-346): adjuted daily quiz styling

---

packages/ts-newskit/src/components/navigation/masthead/index.tsx
packages/ts-newskit/src/components/navigation/masthead/styles.ts

This PR is to add comments to the codebase indicating that certain components are in the process of being moved to the main repository. The comments serve to notify other developers to avoid making changes to these components until the move is complete
[JIRA-1954](https://nidigitalsolutions.jira.com/browse/TMRX-1954)

feat(TMRX-1954): add note to files which are being moved to render

---

packages/article-skeleton/__tests__/web/inline-ad.test.js
packages/article-skeleton/fixtures/inline-ad.js
packages/article-skeleton/src/contentModifiers/inline-ad.js
packages/article-skeleton/src/contentModifiers/native-ad.js

Reverts newsuk/times-components#3775

Revert "feat(TMRX-1962): Update ad placement in articles"

---

packages/video/src/inline-video-player.js

Reverts newsuk/times-components#3784

Revert "fix(TMRX-1734): video play button bugs"

---

packages/ssr/src/lib/graphql-logging-link.js

https://nidigitalsolutions.jira.com/browse/TMP-993

chore(tmp-993): Enrich graphql query logs

---

.circleci/config.yml

chore(TMP-00): Temp remove verdaccio.

---

.circleci/config.yml

Enable previously disable verdaccio_test stage.

chore(TMP-1076): Revert verdaccio_test disable - enable it again

---

packages/ts-newskit/package.json
yarn.lock

update themes
[JIRA-131](https://nidigitalsolutions.jira.com/browse/TMD-131)

feat(TMD-131): implement updated themes

---

packages/article-in-depth/__tests__/shared.base.js
packages/article-in-depth/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-comment/__tests__/shared.base.js
packages/article-magazine-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-magazine-standard/__tests__/shared.base.js
packages/article-magazine-standard/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-comment/__tests__/shared.base.js
packages/article-main-comment/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-skeleton/src/article-skeleton.js
packages/save-and-share-bar/__tests__/shared.base.js
packages/save-and-share-bar/save-and-share-bar.showcase.js
packages/save-and-share-bar/src/components/email-share.js
packages/save-and-share-bar/src/save-and-share-bar.js

Added getDomainSpecificUrl to be sent within articleDataFromRender because we need it in order to get valid article url inside times-component
[TMRS-173](https://nidigitalsolutions.jira.com/browse/TMRS-173)
[TMRS-173]: https://nidigitalsolutions.jira.com/browse/TMRS-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-173): Made fix for sharing email

---

packages/responsive/package.json
packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts
packages/ts-components/src/index.ts
packages/utils/package.json

export component from package
[TMRS-170](https://nidigitalsolutions.jira.com/browse/TMRS-170)
[TMRS-170]: https://nidigitalsolutions.jira.com/browse/TMRS-170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(TMRS-170): export opta fixtures component

---

packages/responsive/package.json
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-tournament/OptaFootballFixturesTournament.tsx
packages/ts-components/src/components/opta/football/fixtures-tournament/__tests__/__snapshots__/OptaFootballFixturesTournament.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-tournament/styles.ts
packages/ts-components/src/components/opta/football/fixtures/__tests__/__snapshots__/OptaFootballFixtures.test.tsx.snap
packages/ts-components/src/components/opta/football/match-stats/__tests__/__snapshots__/OptaFootballMatchStats.test.tsx.snap
packages/ts-components/src/components/opta/football/player-stats/OptaFootballPlayerStats.tsx
packages/ts-components/src/components/opta/football/player-stats/__tests__/__snapshots__/OptaFootballPlayerStats.test.tsx.snap
packages/ts-components/src/components/opta/football/shared-styles.ts
packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.tsx
packages/ts-components/src/components/opta/football/standings/__tests__/__snapshots__/OptaFootballStandings.test.tsx.snap
packages/ts-components/src/components/opta/football/summary/__tests__/__snapshots__/OptaFootballSummary.test.tsx.snap
packages/ts-components/src/components/opta/utils/replaceNationalTeamDetails.ts
packages/ts-newskit/package.json
packages/utils/package.json

- Addition of transformation to test, e.g. `Quarter Finalist` to `QF`
- Addition of prop to allow us to add classes to widget components 
[TMRS-226](https://nidigitalsolutions.jira.com/browse/TMRS-226)
[TMRS-226]: https://nidigitalsolutions.jira.com/browse/TMRS-226?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-226): transform text on euro widgets and add dynamic classes

---

packages/responsive/package.json
packages/ts-components/src/components/newsletter-puff/InlineNewsletterPuff.tsx
packages/ts-components/src/components/newsletter-puff/newsletter/Newsletter.tsx
packages/utils/package.json
yarn.lock

feat(TMW-000): Add error message to newsletter puff

---

packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts

- add width value for dynamic resize calculations
- remove fade on mobile
- 
[TMRS-243](https://nidigitalsolutions.jira.com/browse/TMRS-243)
[TMRS-243]: https://nidigitalsolutions.jira.com/browse/TMRS-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-243): add width value and remove fade

---

packages/responsive/package.json
packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts
packages/utils/package.json

- update starting position of live/next match
- update scroll calculations
- remove button for mobile app
[TMRS-243)](https://nidigitalsolutions.jira.com/browse/TMRS-243)

feat(TMRS-243): euro ticker widget updates

---

packages/responsive/package.json
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts
packages/utils/package.json

update styling for scrolling in App
[TMRS-247](https://nidigitalsolutions.jira.com/browse/TMRS-247)
[TMRS-247]: https://nidigitalsolutions.jira.com/browse/TMRS-247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-247): update app styling

---

packages/responsive/package.json
packages/ts-components/src/components/opta/cricket/scorecard/__tests__/__snapshots__/OptaCricketScorecard.test.tsx.snap
packages/ts-components/src/components/opta/cricket/shared-styles.ts
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts
packages/utils/package.json

- add/review styling to set height for `.Opta-Room` element that was affecting computed height of component
- add/review styling to set `background-color` override
[TMRS-272](https://nidigitalsolutions.jira.com/browse/TMRS-272)
[TMRS-272]: https://nidigitalsolutions.jira.com/browse/TMRS-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-272): review styling

---

packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.stories.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts

Addition of `showButtons` prop to fixtures ticker widget, to enable buttons to be displayed on mobile
[TMRS-277](https://nidigitalsolutions.jira.com/browse/TMRS-277)
[TMRS-277]: https://nidigitalsolutions.jira.com/browse/TMRS-277?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-277): addition of buttons prop

---

.circleci/config.yml

To optimize circleci jobs resource classes based on the current usage

optimize circleci jobs resource class

---

packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/package.json
packages/save-and-share-bar/src/assets/bookmark-fill-icon.js
packages/save-and-share-bar/src/assets/bookmark-icon.js
packages/save-and-share-bar/src/assets/share-icon.js
packages/save-and-share-bar/src/components/save-button.js
packages/save-and-share-bar/src/save-and-share-bar.js
yarn.lock

removed dependency and copied icons into codebase instead.
[TMD-477](https://nidigitalsolutions.jira.com/browse/TMD-477)
[TMD-477]: https://nidigitalsolutions.jira.com/browse/TMD-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMD-477): remove emotion icons

---

.circleci/config.yml

Revert to using default executor
https://nidigitalsolutions.jira.com/browse/TMP-1445

chore(TMP-1445): Revert "chore(TMP-1445): set 2xlarge on running cypress tests (#3899)"

---

packages/ssr/__tests__/helpers/article-helper.js
packages/ssr/__tests__/helpers/topic-helper.js

https://nidigitalsolutions.jira.com/browse/TMP-1445

feat(TMP-1445): Enable a11y debug output on failure

---

packages/ts-components/src/components/save-star/SaveStar.tsx

fix(TMP-1437): Call /is-bookmarked only for logged in users

---

packages/provider-queries/src/get_tokenised_article_url.graphql
packages/save-and-share-bar/src/components/email-share.js

Added category path to email share.
[TMRS-329](https://nidigitalsolutions.jira.com/browse/TMRS-329)
[TMRS-329]: https://nidigitalsolutions.jira.com/browse/TMRS-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-329): Category path added to email share

---

packages/provider-queries/src/get_tokenised_article_url.graphql
packages/save-and-share-bar/src/components/email-share.js

Reverts newsuk/times-components#3923

Revert "feat(TMRS-329): Category path added to email share"

---

packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/styled.js

Article share bar padding and gap update
[TMD-465](https://nidigitalsolutions.jira.com/browse/TMD-465)
[TMD-465]: https://nidigitalsolutions.jira.com/browse/TMD-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMD-465): Article share bar padding and mobile scroll

---

packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/styled.js

It updates the save and share buttons to be left aligned as requested in Jira from Himes.
https://nidigitalsolutions.jira.com/browse/TMD-465?focusedCommentId=671544
[TMD-465](https://nidigitalsolutions.jira.com/browse/TMD-465)
[TMD-465]: https://nidigitalsolutions.jira.com/browse/TMD-465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMD-465): Article share bar padding and mobile scroll update

---

packages/article/__tests__/web/article.test.js
packages/article/src/article.js

fix(TMRS-000): extend logic to ignore preview articles

---

packages/article/__tests__/web/article.test.js
packages/article/src/article.js
packages/ssr/src/component/article.js

reverts/removes 410 error logic

fix(TMRS-000) remove 410 error logic

---

packages/article/__tests__/web/article.test.js
packages/article/src/article.js
packages/ssr/src/component/article.js

add `isPreview` to article object to enable preview articles to be ignored in 410 error logic 

fix(TMRS-000): add isPreview to article object

---

packages/article-list/src/styles/responsive.js
packages/article-skeleton/src/styles/article-body/responsive.js
packages/article-skeleton/src/styles/responsive.js

chore(TMW-000): Ad height mapping

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-list/__tests__/web/__snapshots__/article-list-with-styles.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap

chore(TMW-000): Ad height mapping tests

---

packages/ts-components/src/components/article-header/ArticleHeader.stories.tsx
packages/ts-components/src/components/article-header/ArticleHeader.tsx
packages/ts-components/src/components/updated-timestamp/UpdatedTimestamp.tsx
packages/ts-components/tslint.json
packages/ts-slices/src/utils/getDate.ts
packages/ts-slices/src/utils/getTimeSince.ts
packages/ts-slices/tslint.json

Update imports from date-fns to import submodules

chore(TMD-000): Update date-fns imports

---

packages/ts-components/src/components/article-sidebar/ArticleSidebar.stories.tsx
packages/ts-components/src/components/article-sidebar/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-components/src/components/article-sidebar/__tests__/index.test.tsx

feat(TMPZ-112): Implement tracking of clicks on puzzles in sidebar component

---

packages/ts-components/src/components/opta/football/fixtures-ticker/OptaFootballFixturesTicker.stories.tsx
packages/ts-components/src/components/opta/football/fixtures-ticker/__tests__/__snapshots__/OptaFootballFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures-ticker/styles.ts

scope dark mode styling, so it is nly available when using the `isApp` parameter
[TMRS-514](https://nidigitalsolutions.jira.com/browse/TMRS-514)
[TMRS-514]: https://nidigitalsolutions.jira.com/browse/TMRS-514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-514): ticker styling app

---

packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.tsx

update `player_naming` from `last_name` to `full` for the cricket scorecard
[TMRS-491](https://nidigitalsolutions.jira.com/browse/TMRS-491)
[TMRS-491]: https://nidigitalsolutions.jira.com/browse/TMRS-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-491): update player_naming on cricket

---

packages/video/src/inline-video-player.js

trigger publish of video package

feat(TMRS-000): remove comment

---

packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/src/styles/responsive.js
packages/article-main-comment/src/styles/shared.js

feat(TMW-000): ArticleHeader - MainComment

---

packages/article-main-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-comment/src/styles/responsive.js

chore(TMW-000): MainComment - header layout

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/styles/responsive.js
packages/article-in-depth/src/styles/shared.js

Header style update for `in-depth` template

feat(TMW-000): Header in-depth update

---

packages/article-in-depth/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-in-depth/src/styles/responsive.js

feat(TMW-000): Header indepth update

---

packages/article-magazine-comment/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-comment/src/styles/responsive.js
packages/article-magazine-comment/src/styles/shared.js
packages/article-magazine-standard/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-magazine-standard/src/styles/shared.js

feat(TMW-000): Header magazine update

---

packages/ts-components/src/components/features-carousel/__tests__/__snapshots__/index.test.tsx.snap
packages/ts-components/src/components/features-carousel/styles.ts

update Benefits Rail styles
[TMRS-584](https://nidigitalsolutions.jira.com/browse/TMRS-584)
[TMRS-584]: https://nidigitalsolutions.jira.com/browse/TMRS-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-584): update benefits rail style

---

README.md

this pr is just to fix the pipeline issue

fix(TMD-000): this pr is just to fix the pipeline issue

---

packages/article-skeleton/fixtures/full-article-content.js
packages/article-skeleton/src/article-body/article-body.js

[TMC-262](https://nidigitalsolutions.jira.com/browse/TMC-262)
[TMC-262]: https://nidigitalsolutions.jira.com/browse/TMC-262?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMC-262): Fix the logic for detecting iframe blocks

---

packages/article-skeleton/src/article-body/article-body.js

update script source value for embed
[TMRS-575](https://nidigitalsolutions.jira.com/browse/TMRS-575)
[TMRS-575]: https://nidigitalsolutions.jira.com/browse/TMRS-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-575): parse id for embed

---

packages/article-skeleton/src/article-body/article-body.js

Revert updates for Formstack JS embed
[TMRS-575](https://nidigitalsolutions.jira.com/browse/TMRS-575)
[TMRS-575]: https://nidigitalsolutions.jira.com/browse/TMRS-575?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMRS-575): revert updates

---

lib/publish_canary.sh

In order to reduce errors of duplication canary release version we need to add branch name to lerna command. 
[Lerna preid command](https://github.com/lerna/lerna/tree/main/libs/commands/publish#--preid)
[TMP-1718](https://nidigitalsolutions.jira.com/browse/TMP-1718)
> Successfully published:
>  - @times-components/article-comments@0.44.24-165ddd20e1b5c8ad0781fea37d851b2c.5+41c2102561
>  - @times-components/article-extras@0.32.25-165ddd20e1b5c8ad0781fea37d851b2c.5+41c2102561
>  - @times-components/article-in-depth@3.92.5-165ddd20e1b5c8ad0781fea37d851b2c.5+41c2102561
>  - @times-components/article-list@9.19.26-165ddd20e1b5c8ad0781fea37d851b2c.5+41c2102561
>  - @times-components/article-magazine-comment@3.87.5-165ddd20e1b5c8ad0781fea37d851b2c.5+41c2102561
>  - …

feat(TMP-1718): Add prefix id to each canary release equal to the branch name.

---

packages/ts-components/src/components/cta-button/CtaButton.tsx
packages/ts-components/src/components/cta-button/__tests__/CtaButton.test.tsx
packages/ts-components/src/helpers/tracking/TrackingHandler.tsx
packages/ts-components/src/helpers/tracking/__tests__/TrackingHandler.test.tsx

Add tealium tracking on cta buttons.
[TMC-313](https://nidigitalsolutions.jira.com/browse/TMC-313)
[TMC-313]: https://nidigitalsolutions.jira.com/browse/TMC-313?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMC-3113): Add tracking for cta buttons

---

packages/ts-components/src/components/cta-button/CtaButton.tsx
packages/ts-components/src/components/cta-button/__tests__/CtaButton.test.tsx
packages/ts-components/src/helpers/tracking/TrackingHandler.tsx
packages/ts-components/src/helpers/tracking/__tests__/TrackingHandler.test.tsx

Changed tracking info based on new specification.
[TMC-330](https://nidigitalsolutions.jira.com/browse/TMC-330)
[TMC-330]: https://nidigitalsolutions.jira.com/browse/TMC-330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tmc-330): Change tracking info for cta button

---

README.md
packages/ssr/src/server/article.js

chore(TMW-000): Test NPM deployment

---

packages/article-extras/package.json
packages/article-skeleton/package.json

chore(TMW-000): Update package versions

---

.circleci/config.yml
packages/article-extras/src/article-extras.js
packages/article-skeleton/src/article-skeleton.js

feat(TMW-000): Remove user state wrapper for share

---

.circleci/config.yml

chore(TMW-000): Add failing web tests

---

.prettierignore
packages/save-and-share-bar/__tests__/shared.base.js
packages/save-and-share-bar/__tests__/web/__snapshots__/save-and-share-bar.test.js.snap
packages/save-and-share-bar/src/save-and-share-bar.js
packages/save-and-share-bar/src/styled.js
packages/utils/__tests__/check-for-symphony-experiment.test.js
packages/utils/__tests__/get-base64-cookie-value.test.js
packages/utils/__tests__/get-cookie-value.test.js
packages/utils/src/check-for-symphony-experiment.js
packages/utils/src/get-base64-cookie-value.js
packages/utils/src/get-cookie-value.js
packages/utils/src/index.js

Re-implement this previous removed commit https://github.com/newsuk/times-components/pull/4079

feat(TMG-3003): Share button highlight

---

packages/article-skeleton/src/article-body/article-body.js

remove `fullwidth` prop from `InteractiveContainer` used to wrap social embed
[TMRS-487](https://nidigitalsolutions.jira.com/browse/TMRS-487)
[TMRS-487]: https://nidigitalsolutions.jira.com/browse/TMRS-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRS-487): remove fullwidth

---

packages/article-main-video/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-video/article-main-video.showcase.js
packages/article-main-video/src/article-main-video.js
packages/article-main-video/src/styles/responsive.js
packages/provider-test-tools/fixtures/article-video.json
packages/user-state/src/storybook-helper.js

Update video article story to allow viewer to customise various article parameters
[TMRA-123](https://nidigitalsolutions.jira.com/browse/TMRA-123)
[TMRA-123]: https://nidigitalsolutions.jira.com/browse/TMRA-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-123): update video article story

---

packages/author-profile/__tests__/web/__snapshots__/author-profile.web.test.js.snap
packages/author-profile/src/author-profile-head-image.js

Implement WebP images on author page
https://nidigitalsolutions.jira.com/browse/JIRA-1234)](https://nidigitalsolutions.jira.com/browse/TMPR-137

feat(TMPR-130): Enable webp on author page

---

packages/article-main-video/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-video/article-main-video.showcase.js
packages/article-main-video/package.json
packages/article-main-video/src/article-main-video.js
packages/article-main-video/src/styles/responsive.js
packages/article-skeleton/__tests__/web/__snapshots__/head.test.js.snap
packages/article-skeleton/src/article-skeleton.js
packages/article-skeleton/src/contentModifiers/newsletter-puff.js
packages/article/src/article.js
packages/fixture-generator/src/types.ts
packages/provider-queries/src/article_page_props.graphql
packages/provider-queries/src/article_web.graphql
packages/provider-queries/src/draft_article.graphql
packages/provider-test-tools/fixtures/article-video.json
packages/provider/__tests__/__snapshots__/article-provider.test.js.snap

[TMRA-152](https://nidigitalsolutions.jira.com/browse/TMRA-152)
[TMRA-152]: https://nidigitalsolutions.jira.com/browse/TMRA-152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-152): add query fields

---

packages/article-extras/src/article-extras.js
packages/article-skeleton/src/article-body/article-body.js
packages/article-skeleton/src/article-skeleton.js
packages/utils/__tests__/excluded-paths.test.js
packages/utils/src/excluded-paths.js
packages/utils/src/index.js

- Removed ads from all obituaries articles
[TMC-355](https://nidigitalsolutions.jira.com/browse/TMC-355)
Before and after:
[TMC-355]: https://nidigitalsolutions.jira.com/browse/TMC-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(TMC-355): Removed ads from obituaries articles

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/__tests__/web/article-comments.web.test.js
packages/article-comments/src/article-comments.js
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap

feat(TMG-2570): Removed commenting entitlement ff

---

packages/article-skeleton/fixtures/full-article-content.js
packages/article-skeleton/src/article-body/article-body.js
packages/ts-components/package.json
packages/ts-components/src/components/palin-polls/PalinPolls.tsx
packages/ts-components/src/components/palin-polls/__tests__/PalinPolls.test.tsx
packages/ts-components/src/index.ts

- fixed issue with the Palin Polls component
- web component moved to TC
[TMC-500](https://nidigitalsolutions.jira.com/browse/TMC-500)
[TMC-500]: https://nidigitalsolutions.jira.com/browse/TMC-500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(TMC-500): Implement & fix Palin Polls component

---

packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.stories.tsx
packages/ts-components/src/components/opta/cricket/scorecard/OptaCricketScorecard.tsx
packages/ts-components/src/components/opta/cricket/scorecard/__tests__/__snapshots__/OptaCricketScorecard.test.tsx.snap
packages/ts-components/src/components/opta/cricket/shared-styles.ts
packages/ts-components/src/components/opta/football/fixtures-tournament/OptaFootballFixturesTournament.tsx
packages/ts-components/src/components/opta/football/fixtures-tournament/__tests__/__snapshots__/OptaFootballFixturesTournament.test.tsx.snap
packages/ts-components/src/components/opta/football/fixtures/OptaFootballFixtures.tsx
packages/ts-components/src/components/opta/football/fixtures/__tests__/__snapshots__/OptaFootballFixtures.test.tsx.snap
packages/ts-components/src/components/opta/football/match-stats/OptaFootballMatchStats.tsx
packages/ts-components/src/components/opta/football/match-stats/__tests__/__snapshots__/OptaFootballMatchStats.test.tsx.snap
packages/ts-components/src/components/opta/football/player-stats/OptaFootballPlayerStats.tsx
packages/ts-components/src/components/opta/football/player-stats/__tests__/__snapshots__/OptaFootballPlayerStats.test.tsx.snap
packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.stories.tsx
packages/ts-components/src/components/opta/football/standings/OptaFootballStandings.tsx
packages/ts-components/src/components/opta/football/standings/__tests__/__snapshots__/OptaFootballStandings.test.tsx.snap
packages/ts-components/src/components/opta/football/summary/OptaFootballSummary.tsx
packages/ts-components/src/components/opta/football/summary/__tests__/__snapshots__/OptaFootballSummary.test.tsx.snap
packages/ts-components/src/components/opta/rugby/fixtures/OptaRugbyFixtures.tsx
packages/ts-components/src/components/opta/rugby/fixtures/__tests__/__snapshots__/OptaRugbyFixtures.test.tsx.snap
packages/ts-components/src/components/opta/rugby/match-stats/OptaRugbyMatchStats.tsx
packages/ts-components/src/components/opta/rugby/match-stats/__tests__/__snapshots__/OptaRugbyMatchStats.test.tsx.snap
packages/ts-components/src/components/opta/rugby/shared-styles.ts
packages/ts-components/src/components/opta/rugby/standings/OptaRugbyStandings.tsx
packages/ts-components/src/components/opta/rugby/standings/__tests__/__snapshots__/OptaRugbyStandings.test.tsx.snap
packages/ts-components/src/components/opta/rugby/summary/OptaRugbySummary.tsx
packages/ts-components/src/components/opta/rugby/summary/__tests__/__snapshots__/OptaRugbySummary.test.tsx.snap
packages/ts-components/src/components/opta/shared/fixtures-ticker/OptaFixturesTicker.tsx
packages/ts-components/src/components/opta/shared/fixtures-ticker/__tests__/__snapshots__/OptaFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/shared/fixtures-ticker/styles.ts
packages/ts-components/src/components/opta/shared/shared-styles.ts

Update OPTA components to use breakpoint specific height values, when passed.
[TMRA-309](https://nidigitalsolutions.jira.com/browse/TMRA-309)
[TMRA-309]: https://nidigitalsolutions.jira.com/browse/TMRA-309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-309): update height parameters

---

packages/article-in-depth/src/article-in-depth.js
packages/article-magazine-comment/src/article-magazine-comment.js
packages/article-magazine-standard/src/article-magazine-standard.js
packages/article-main-comment/src/article-main-comment.js
packages/article-main-standard/src/article-main-standard.js
packages/article-main-video/src/article-main-video.js

chore(TMW-000): Remove teaser article content

---

packages/article-in-depth/src/article-in-depth.js
packages/article-magazine-comment/src/article-magazine-comment.js
packages/article-magazine-standard/src/article-magazine-standard.js
packages/article-main-standard/src/article-main-standard.js

If the `removeTeaserContent` feature flag is active - remove all content from the teaser article page.

chore(TMW-000): Remove teaser article header elements

---

packages/article-skeleton/src/article-skeleton.js
packages/article-skeleton/src/styles/responsive.js

chore(TMW-000): Add teaser article padding

---

packages/article-skeleton/__tests__/web/article-sidebar.web.test.js
packages/article-skeleton/src/article-sidebar.js
packages/article-skeleton/src/article-skeleton.js

Using the puzzle config data, we determined what gets displayed, in what order, and what difficulty preferences are by updating and changing the sidebar data from the config.
[TMPZ-973](https://nidigitalsolutions.jira.com/browse/TMPZ-973)
[TMPZ-973]: https://nidigitalsolutions.jira.com/browse/TMPZ-973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMPZ-973): Use json config file for to organise Puzzles Article Sidebar

---

packages/ts-components/src/components/opta/shared/fixtures-ticker/OptaFixturesTicker.stories.tsx
packages/ts-components/src/components/opta/shared/fixtures-ticker/__tests__/__snapshots__/OptaFixturesTicker.test.tsx.snap
packages/ts-components/src/components/opta/shared/fixtures-ticker/styles.ts

Update styling for `OPTAFixturesTicker` widget. This will align with design spec for both light and dark mode states.
[TMRA-284](https://nidigitalsolutions.jira.com/browse/TMRA-284)
[TMRA-284]: https://nidigitalsolutions.jira.com/browse/TMRA-284?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-284): update ticker styling

---

packages/ad/src/ad-container.js
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/article-main-video.showcase.js
packages/article-main-video/src/article-main-video.js

Update ad slot names for video article template
[TMRA-206](https://nidigitalsolutions.jira.com/browse/TMRA-206)
[TMRA-206]: https://nidigitalsolutions.jira.com/browse/TMRA-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-206): video article comments

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/disabled-comments.js
packages/article-main-video/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/ts-styleguide/src/styleguide/fonts/font-sizes.tsx

Update text and styling for disabled comment headline.
[TMRA-344](https://nidigitalsolutions.jira.com/browse/TMRA-344)
[TMRA-344]: https://nidigitalsolutions.jira.com/browse/TMRA-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-344): update disabled comment

---

packages/article-main-video/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/src/article-main-video.js

update styling for comments section
[TMRA-342](https://nidigitalsolutions.jira.com/browse/TMRA-342)
[TMRA-342]: https://nidigitalsolutions.jira.com/browse/TMRA-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-342): update comments styling

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/src/disabled-comments.js
packages/article-main-video/__tests__/web/__snapshots__/article-with-style.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/article.web.test.js.snap
packages/article-main-video/__tests__/web/__snapshots__/semantic.web.test.js.snap

another text update
[TMRA-344](https://nidigitalsolutions.jira.com/browse/TMRA-344)
[TMRA-344]: https://nidigitalsolutions.jira.com/browse/TMRA-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-344): update comment

---

packages/article-comments/__tests__/web/__snapshots__/shared.web.test.js.snap
packages/article-comments/__tests__/web/article-comments.web.test.js
packages/article-comments/src/article-comments.js
packages/article-in-depth/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-magazine-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-comment/__tests__/web/__snapshots__/semantic.web.test.js.snap
packages/article-main-standard/__tests__/web/__snapshots__/semantic.web.test.js.snap

Removing commenting entitlement feature flag.
Ticket: https://nidigitalsolutions.jira.com/browse/TMG-2570

feat(TMG-2570) commenting feature ff removal

---

packages/article-extras/src/styles/index.js

Adding min-height to improve CLS issues.
[TMC-474](https://nidigitalsolutions.jira.com/browse/TMC-474)
[TMC-474]: https://nidigitalsolutions.jira.com/browse/TMC-474?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(tmc-474): Promoted Content - CLS shift 

---

packages/article-skeleton/fixtures/full-article-content.js
packages/article-skeleton/src/article-body/article-body.js

- removing all travel offers from articles
- 2 tasks are done in this one branch
[TMC-452](https://nidigitalsolutions.jira.com/browse/TMC-452)
[TMC-453](https://nidigitalsolutions.jira.com/browse/TMC-453)
[TMC-452]: https://nidigitalsolutions.jira.com/browse/TMC-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TMC-453]: https://nidigitalsolutions.jira.com/browse/TMC-453?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(TMC-452 & TMC-453): Travel offers removal

---

packages/article-extras/__tests__/shared.js
packages/article-extras/__tests__/web/__snapshots__/article-extras.test.js.snap
packages/article-extras/src/article-extras.js
packages/article-paragraph/article-paragraph.showcase.js
packages/article-paragraph/package.json

add `commentsSortOrder` prop to `ArticleExtras`
[TMRA-652](https://nidigitalsolutions.jira.com/browse/TMRA-652)
[TMRA-652]: https://nidigitalsolutions.jira.com/browse/TMRA-652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(TMRA-652): add commentsSortOrder prop
